import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L16-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 20, BATCH);

export function lesson20Patterns(byId) {
  return [
    P(
      byId,
      "l20-g01",
      {
        meaning: "Khi (làm) xong thì… / vừa… thì kết quả là…",
        structures: ["Vた ＋ ところ"],
        explanation:
          "Nêu kết quả thực tế ngay sau khi thử/làm A: vừa làm A thì phát hiện/được B.",
        usage: "Báo cáo kết quả thử, gọi điện, hỏi thăm: làm thử thì thấy…",
        cautions: [
          "Khác ところだ (đúng lúc đang…); たところ nhấn kết quả sau hành động hoàn thành.",
          "Thường kèm kết quả bất ngờ hoặc thông tin mới nhận được.",
        ],
        contrast:
          "たところ ≈ vừa làm thì kết quả là. Khác たら (giả định/điều kiện) và ところだった (suýt).",
        examples: [
          ex(
            "問い合わせたところ在庫がないと言われた。",
            "といあわせたところざいこがないといわれた。",
            "Hỏi thử thì được bảo là hết hàng.",
            [
              ["問", "と"],
              ["い"],
              ["合", "あ"],
              ["わせたところ"],
              ["在庫", "ざいこ"],
              ["がないと"],
              ["言", "い"],
              ["われた。"],
            ],
          ),
          ex(
            "窓を開けたところ涼しい風が入ってきた。",
            "まどをあけたところすずしいかぜがはいってきた。",
            "Vừa mở cửa sổ thì gió mát tràn vào.",
            [
              ["窓", "まど"],
              ["を"],
              ["開", "あ"],
              ["けたところ"],
              ["涼", "すず"],
              ["しい"],
              ["風", "かぜ"],
              ["が"],
              ["入", "はい"],
              ["ってきた。"],
            ],
          ),
          ex(
            "先生に相談したところ賛成してくれた。",
            "せんせいにそうだんしたところさんせいしてくれた。",
            "Vừa bàn với thầy thì thầy tán thành.",
            [
              ["先生", "せんせい"],
              ["に"],
              ["相談", "そうだん"],
              ["したところ"],
              ["賛成", "さんせい"],
              ["してくれた。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜たところ",
        "Câu kết quả: Vた＋ところ — vừa/làm xong A thì kết quả là B.",
        [
          ["Gọi thử thì máy bận.", "電話したところ話し中だった。"],
          ["Đọc kỹ thì thấy lỗi đánh máy.", "よく読んだところ誤字を見つけた。"],
          ["Mở hộp thì có thư bên trong.", "箱を開けたところ手紙が入っていた。"],
          ["Hỏi cửa hàng thì còn chỗ trống.", "店に聞いたところ空きがあると言われた。"],
          ["Thử mặc thì hơi chật.", "着てみたところ少し小さかった。"],
          ["Kiểm tra lại thì số liệu khớp.", "再確認したところ数字が一致した。"],
          ["Gửi mail thì nhận được trả lời ngay.", "メールしたところすぐに返事が来た。"],
          ["Tìm trên mạng thì có thông tin cũ.", "検索したところ古い情報が出た。"],
          ["Gặp trực tiếp thì anh ấy xin lỗi.", "直接会ったところ彼は謝った。"],
          ["Đo nhiệt độ thì sốt cao.", "熱を測ったところ高熱だった。"],
        ],
        [
          ["申請したところ許可が下りた。", "Nộp đơn thì được cấp phép."],
          ["冷蔵庫を開けたところ牛乳が切れていた。", "Mở tủ lạnh thì hết sữa."],
          ["調べたところ原因は配線だった。", "Điều tra thì nguyên nhân là dây điện."],
          ["近所に聞いたところ彼は出張中だ。", "Hỏi hàng xóm thì anh ấy đang công tác."],
          ["試食したところ思ったより辛かった。", "Nếm thử thì cay hơn tưởng."],
          ["予約を確認したところ翌日だった。", "Xác nhận đặt chỗ thì là ngày hôm sau."],
          ["書類を見直したところ署名が抜けていた。", "Xem lại giấy tờ thì thiếu chữ ký."],
          ["駅員に尋ねたところ次の電車は満席だ。", "Hỏi nhân viên ga thì tàu sau hết chỗ."],
          ["録音を聞いたところ雑音が多かった。", "Nghe bản ghi thì nhiễu nhiều."],
          ["図書館で探したところ貸出中だった。", "Tìm ở thư viện thì đang được mượn."],
        ],
        [
          ["Hỏi kho thì hết hàng.", ["在庫を聞いたところ", "品切れだと", "知らされた", "。"], 0],
          ["Mở cửa có gió lạnh.", ["ドアを開けたところ", "冷たい風が", "入ってきた", "。"], 0],
          ["Bàn với sếp được đồng ý.", ["上司に相談したところ", "了承して", "もらえた", "。"], 0],
          ["Gọi thì máy bận.", ["電話したところ", "話し中だと", "分かった", "。"], 0],
          ["Đọc kỹ thấy lỗi.", ["よく読んだところ", "誤字が", "見つかった", "。"], 0],
          ["Mở hộp có thư.", ["箱を開けたところ", "手紙が", "出てきた", "。"], 0],
          ["Nộp đơn được phép.", ["申請したところ", "許可が", "出た", "。"], 0],
          ["Mở tủ hết sữa.", ["冷蔵庫を開けたところ", "牛乳が", "なかった", "。"], 0],
          ["Điều tra ra dây điện.", ["調べたところ", "原因は", "配線だった", "。"], 0],
          ["Xác nhận là ngày sau.", ["予約を確認したところ", "翌日だと", "分かった", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l20-g02",
      {
        meaning: "Từ đó (không…) / chỉ… mãi",
        structures: ["Vた ＋ きり（っきり）", "N ＋ きり"],
        explanation:
          "たきり: sau hành động đó tình trạng không đổi (thường tiêu cực). Nきり: chỉ có N / chỉ đến mức đó.",
        usage: "Kể chuyện: đi rồi không về; nói một câu rồi im; chỉ một lần.",
        cautions: [
          "っきり là biến thể khẩu ngữ của きり.",
          "Phân biệt nghĩa 'từ đó không…' với nghĩa 'chỉ…' tùy ngữ cảnh.",
        ],
        contrast:
          "たきり ≈ từ đó không… nữa. Khác たまま (giữ nguyên trạng thái) và だけ (chỉ).",
        examples: [
          ex(
            "彼は出かけたきり戻ってこない。",
            "かれはでかけたきりもどってこない。",
            "Anh ấy đi ra ngoài rồi không về.",
            [
              ["彼", "かれ"],
              ["は"],
              ["出", "で"],
              ["かけたきり"],
              ["戻", "もど"],
              ["ってこない。"],
            ],
          ),
          ex(
            "一言挨拶したきり黙っている。",
            "ひとことあいさつしたきりだまっている。",
            "Chỉ chào một câu rồi im.",
            [
              ["一言", "ひとこと"],
              ["挨拶", "あいさつ"],
              ["したきり"],
              ["黙", "だま"],
              ["っている。"],
            ],
          ),
          ex(
            "二人きりで話したい。",
            "ふたりきりではなしたい。",
            "Muốn nói chuyện chỉ hai người.",
            [
              ["二人", "ふたり"],
              ["きりで"],
              ["話", "はな"],
              ["したい。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜きり",
        "Câu きり／っきり: từ đó không… hoặc chỉ (N).",
        [
          ["Cô ấy về quê rồi không liên lạc.", "彼女は帰省したきり連絡がない。"],
          ["Đọc thư xong rồi không trả lời.", "手紙を読んだきり返事を出さない。"],
          ["Nằm xuống rồi không dậy nữa.", "横になったきり起き上がらない。"],
          ["Gặp lần đó rồi không gặp lại.", "あの時会ったきり再会していない。"],
          ["Chỉ còn một tuần nữa.", "あと一週間きりだ。"],
          ["Nói xong rồi bỏ đi luôn.", "言い終わったきり出て行った。"],
          ["Mượn sách rồi không trả.", "本を借りたきり返していない。"],
          ["Chỉ mình tôi ở văn phòng.", "オフィスは私きりだ。"],
          ["Uống thuốc rồi ngủ luôn.", "薬を飲んだきり眠ってしまった。"],
          ["Gửi mail rồi im thin thít.", "メールを送ったきり音沙汰がない。"],
        ],
        [
          ["子供は学校へ行ったきり帰ってこない。", "Đứa trẻ đi học rồi không về."],
          ["彼は就職したきり地元に戻らない。", "Anh ấy đi làm rồi không về quê."],
          ["一口食べたきり箸を置いた。", "Chỉ ăn một miếng rồi đặt đũa xuống."],
          ["約束したきり守らない。", "Hứa rồi không giữ lời."],
          ["三人きりで旅行する。", "Đi du lịch chỉ ba người."],
          ["窓を開けたきり閉め忘れた。", "Mở cửa sổ rồi quên đóng."],
          ["一度失敗したきり挑戦しない。", "Thất bại một lần rồi không thử nữa."],
          ["現金は千円きりしかない。", "Tiền mặt chỉ còn đúng nghìn yên."],
          ["彼女は泣いたきり何も言わない。", "Cô ấy khóc rồi không nói gì."],
          ["荷物を預けたきり受け取っていない。", "Gửi hành lý rồi chưa nhận lại."],
        ],
        [
          ["Ra phố rồi không về nhà.", ["街へ出たきり", "家に", "帰らない", "。"], 0],
          ["Nói một câu rồi im lặng.", ["一言言ったきり", "黙り込んで", "しまった", "。"], 0],
          ["Muốn bàn chỉ hai người.", ["二人きりで", "相談したいと", "思う", "。"], 0],
          ["Về quê rồi mất liên lạc.", ["帰省したきり", "連絡が", "途絶えた", "。"], 0],
          ["Đọc thư không trả lời.", ["手紙を読んだきり", "返事を", "書かない", "。"], 0],
          ["Nằm rồi không dậy.", ["横になったきり", "起きようと", "しない", "。"], 0],
          ["Đi học rồi không về.", ["学校へ行ったきり", "戻って", "こない", "。"], 0],
          ["Ăn một miếng đặt đũa.", ["一口食べたきり", "箸を", "置いた", "。"], 0],
          ["Đi làm không về quê.", ["就職したきり", "地元に", "戻らない", "。"], 0],
          ["Gửi mail rồi im.", ["メールを送ったきり", "返事が", "ない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l20-g03",
      {
        meaning: "Sau cùng (sau thời gian dài) thì… (thường kết quả xấu)",
        structures: ["Vた ＋ あげく（に）", "Nの ＋ あげく（に）"],
        explanation:
          "Sau quá trình dài mệt mỏi/lo lắng, cuối cùng dẫn đến kết quả thường không mong muốn.",
        usage: "Phàn nàn, kể hậu quả: tranh cãi mãi rồi…; suy nghĩ mãi rồi…",
        cautions: [
          "Kết quả sau あげく thường tiêu cực hoặc bất tiện.",
          "あげくに nhấn mạnh hơn một chút; cả hai đều phổ biến.",
        ],
        contrast:
          "あげく ≈ cuối cùng (sau khổ sở) thì…. Gần 末に nhưng あげく thiên kết quả xấu hơn.",
        examples: [
          ex(
            "議論したあげく結論が出なかった。",
            "ぎろんしたあげくけつろんがでなかった。",
            "Bàn luận mãi cuối cùng không ra kết luận.",
            [
              ["議論", "ぎろん"],
              ["したあげく"],
              ["結論", "けつろん"],
              ["が"],
              ["出", "で"],
              ["なかった。"],
            ],
          ),
          ex(
            "迷いのあげく申し込みをやめた。",
            "まよいのあげくもうしこみをやめた。",
            "Do dự mãi cuối cùng thôi đăng ký.",
            [
              ["迷", "まよ"],
              ["いのあげく"],
              ["申", "もう"],
              ["し"],
              ["込", "こ"],
              ["みを"],
              ["やめた。"],
            ],
          ),
          ex(
            "待たされたあげく受付はもう閉まっていた。",
            "またされたあげくうけつけはもうしまっていた。",
            "Bị bắt đợi mãi cuối cùng quầy đã đóng.",
            [
              ["待", "ま"],
              ["たされたあげく"],
              ["受付", "うけつけ"],
              ["は"],
              ["もう"],
              ["閉", "し"],
              ["まっていた。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜あげく",
        "Câu あげく（に）: sau quá trình dài, cuối cùng (thường xấu) thì B.",
        [
          ["Cãi nhau mãi cuối cùng chia tay.", "喧嘩したあげく別れた。"],
          ["Tìm mãi cuối cùng bỏ cuộc.", "探したあげく諦めた。"],
          ["Suy nghĩ mãi cuối cùng từ chối.", "考えたあげく断った。"],
          ["Chờ lâu cuối cùng bị hủy.", "長い待ちのあげく中止になった。"],
          ["Mua sắm mãi cuối cùng hết tiền.", "買い物したあげく金がなくなった。"],
          ["Giải thích mãi cuối cùng bị hiểu nhầm.", "説明したあげく誤解された。"],
          ["Đàm phán mãi cuối cùng đổ vỡ.", "交渉したあげく決裂した。"],
          ["Lo lắng mãi cuối cùng mất ngủ.", "心配したあげく眠れなかった。"],
          ["Làm thêm mãi cuối cùng bệnh.", "残業したあげく病気になった。"],
          ["So sánh mãi cuối cùng không mua.", "比較したあげく買わなかった。"],
        ],
        [
          ["文句を言ったあげく何も変わらない。", "Phàn nàn mãi cuối cùng chẳng đổi gì."],
          ["行列に並んだあげく売り切れた。", "Xếp hàng mãi cuối cùng hết hàng."],
          ["何度も確認したあげくミスがあった。", "Kiểm nhiều lần cuối cùng vẫn có lỗi."],
          ["借金のあげく家を失った。", "Nợ nần cuối cùng mất nhà."],
          ["残業続きのあげく辞表を出した。", "Làm thêm liên tục cuối cùng nộp đơn nghỉ."],
          ["迷ったあげくどちらも選ばなかった。", "Do dự mãi cuối cùng không chọn bên nào."],
          ["抗議したあげく無視された。", "Phản đối mãi cuối cùng bị bỏ qua."],
          ["修理したあげくまた壊れた。", "Sửa mãi cuối cùng lại hỏng."],
          ["相談したあげく自分で決めた。", "Bàn mãi cuối cùng tự quyết."],
          ["遅刻したあげく試験を受けられなかった。", "Đến muộn cuối cùng không thi được."],
        ],
        [
          ["Họp mãi không quyết được.", ["会議したあげく", "決められず", "終わった", "。"], 0],
          ["Do dự rồi thôi dự thi.", ["迷いのあげく", "受験を", "取りやめた", "。"], 0],
          ["Đợi lâu cửa đã đóng.", ["長く待ったあげく", "窓口は", "閉まっていた", "。"], 0],
          ["Cãi rồi đường ai nấy đi.", ["喧嘩したあげく", "縁を", "切った", "。"], 0],
          ["Tìm mãi rồi bỏ cuộc.", ["探しまわったあげく", "諦めるしか", "なかった", "。"], 0],
          ["Suy nghĩ rồi từ chối lời mời.", ["考えたあげく", "誘いを", "断った", "。"], 0],
          ["Xếp hàng rồi hết sạch.", ["並んだあげく", "完売だと", "知った", "。"], 0],
          ["Nợ nần mất nhà.", ["借金のあげく", "家まで", "失った", "。"], 0],
          ["Phàn nàn chẳng đổi.", ["文句を言ったあげく", "状況は", "変わらない", "。"], 0],
          ["Đàm phán rồi đổ vỡ.", ["交渉したあげく", "話が", "決裂した", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l20-g04",
      {
        meaning: "Cuối cùng sau khi… / sau nhiều… thì…",
        structures: ["Nの ＋ 末（に）", "Vた ＋ 末（に）"],
        explanation:
          "Sau quá trình dài suy nghĩ/cố gắng/thảo luận, đi đến kết quả cuối cùng (trung lập hoặc tích cực hơn あげく).",
        usage: "Quyết định trang trọng: sau cân nhắc; sau đàm phán; sau cố gắng.",
        cautions: [
          "末に thường trang trọng hơn hội thoại thân mật.",
          "Kết quả có thể tốt hoặc xấu; không thiên tiêu cực như あげく.",
        ],
        contrast:
          "末に ≈ sau cùng (sau quá trình). あげく nghiêng kết quả xấu; 末に trung lập hơn.",
        examples: [
          ex(
            "検討の末に方針を変更した。",
            "けんとうのすえにほうしんをへんこうした。",
            "Sau khi xem xét, cuối cùng đổi phương châm.",
            [
              ["検討", "けんとう"],
              ["の"],
              ["末", "すえ"],
              ["に"],
              ["方針", "ほうしん"],
              ["を"],
              ["変更", "へんこう"],
              ["した。"],
            ],
          ),
          ex(
            "苦労した末に合格できた。",
            "くろうしたすえにごうかくできた。",
            "Sau bao vất vả cuối cùng đậu.",
            [
              ["苦労", "くろう"],
              ["した"],
              ["末", "すえ"],
              ["に"],
              ["合格", "ごうかく"],
              ["できた。"],
            ],
          ),
          ex(
            "話し合いの末合意に達した。",
            "はなしあいのすえごういにたっした。",
            "Sau thảo luận cuối cùng đạt thỏa thuận.",
            [
              ["話", "はな"],
              ["し"],
              ["合", "あ"],
              ["いの"],
              ["末", "すえ"],
              ["合意", "ごうい"],
              ["に"],
              ["達", "たっ"],
              ["した。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜末（に）",
        "Câu 末（に）: sau quá trình dài, cuối cùng đạt kết quả B.",
        [
          ["Sau cân nhắc quyết định nghỉ việc.", "熟考の末に退職を決めた。"],
          ["Sau cố gắng hoàn thành báo cáo.", "努力の末に報告書を仕上げた。"],
          ["Sau đàm phán ký hợp đồng.", "交渉の末に契約を結んだ。"],
          ["Sau chờ đợi nhận được thư.", "長い待ちの末に手紙が届いた。"],
          ["Sau nghiên cứu công bố kết quả.", "研究の末に成果を発表した。"],
          ["Sau suy nghĩ chọn ngành này.", "悩んだ末にこの道を選んだ。"],
          ["Sau tranh luận thống nhất ý kiến.", "議論の末に意見がまとまった。"],
          ["Sau thử nghiệm tìm ra nguyên nhân.", "実験の末に原因が分かった。"],
          ["Sau điều trị khỏi bệnh.", "治療の末に病気が治った。"],
          ["Sau tìm kiếm gặp lại bạn cũ.", "捜索の末に旧友と再会した。"],
        ],
        [
          ["審査の末に採用が決まった。", "Sau thẩm định cuối cùng được tuyển."],
          ["失敗を重ねた末に成功した。", "Sau nhiều thất bại cuối cùng thành công."],
          ["相談の末に延期することにした。", "Sau bàn bạc quyết định hoãn."],
          ["旅の末に目的地へ着いた。", "Sau chuyến đi cuối cùng tới đích."],
          ["計算の末に答えが出た。", "Sau tính toán ra được đáp án."],
          ["投票の末に案が可決された。", "Sau bỏ phiếu đề án được thông qua."],
          ["練習の末に完璧に弾けた。", "Sau luyện tập chơi được hoàn hảo."],
          ["調査の末に真相が明らかになった。", "Sau điều tra sự thật sáng tỏ."],
          ["選択の末に留学を選んだ。", "Sau lựa chọn quyết định du học."],
          ["忍耐の末に報われた。", "Sau kiên nhẫn cuối cùng được đền đáp."],
        ],
        [
          ["Xem xét rồi đổi kế hoạch.", ["検討の末に", "計画を", "見直した", "。"], 0],
          ["Vất vả rồi đạt mục tiêu.", ["苦労した末に", "目標を", "達成した", "。"], 0],
          ["Thảo luận rồi thống nhất.", ["話し合いの末に", "意見が", "一致した", "。"], 0],
          ["Cân nhắc kỹ rồi xin nghỉ.", ["熟考の末に", "退職願を", "出した", "。"], 0],
          ["Cố gắng rồi hoàn tất báo cáo.", ["努力の末に", "レポートを", "完成させた", "。"], 0],
          ["Đàm phán rồi ký kết.", ["交渉の末に", "契約書に", "サインした", "。"], 0],
          ["Thẩm định rồi được tuyển.", ["審査の末に", "採用が", "決まった", "。"], 0],
          ["Thất bại nhiều rồi thành công.", ["失敗を重ねた末に", "成果を", "得た", "。"], 0],
          ["Bàn rồi quyết định hoãn.", ["相談の末に", "延期する", "ことにした", "。"], 0],
          ["Điều tra rồi ra sự thật.", ["調査の末に", "真相が", "明らかになった", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l20-g05",
      {
        meaning: "Suýt nữa thì…",
        structures: ["Vる／Vそうになる ＋ ところだった"],
        explanation:
          "Diễn đạt suýt xảy ra điều gì (thường xấu) nhưng cuối cùng tránh được.",
        usage: "Kể lại may mắn: suýt muộn; suýt quên; suýt gặp tai nạn.",
        cautions: [
          "Thường dùng quá khứ ところだった vì sự việc đã không xảy ra.",
          "Hay kèm もう少しで／危うく để nhấn 'suýt'.",
        ],
        contrast:
          "ところだった ≈ suýt nữa thì. Khác たところ (kết quả thực) và ところだ (đúng lúc).",
        examples: [
          ex(
            "もう少しで電車に乗り遅れるところだった。",
            "もうすこしででんしゃにのりおくれるところだった。",
            "Suýt nữa thì lỡ tàu.",
            [
              ["もう少しで"],
              ["電車", "でんしゃ"],
              ["に"],
              ["乗", "の"],
              ["り"],
              ["遅", "おく"],
              ["れるところだった。"],
            ],
          ),
          ex(
            "危うく秘密を話すところだった。",
            "あやうくひみつをはなすところだった。",
            "Suýt nữa thì nói lộ bí mật.",
            [
              ["危", "あや"],
              ["うく"],
              ["秘密", "ひみつ"],
              ["を"],
              ["話", "はな"],
              ["すところだった。"],
            ],
          ),
          ex(
            "財布を忘れるところだった。",
            "さいふをわすれるところだった。",
            "Suýt nữa thì quên ví.",
            [
              ["財布", "さいふ"],
              ["を"],
              ["忘", "わす"],
              ["れるところだった。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ところだった",
        "Câu ところだった: suýt xảy ra A nhưng không.",
        [
          ["Suýt nữa thì ngã cầu thang.", "階段から落ちるところだった。"],
          ["Suýt nữa thì gửi nhầm mail.", "メールを間違えて送るところだった。"],
          ["Suýt nữa thì gọi nhầm tên.", "名前を呼び間違えるところだった。"],
          ["Suýt nữa thì va xe đạp.", "自転車とぶつかるところだった。"],
          ["Suýt nữa thì quên khóa cửa.", "鍵をかけ忘れるところだった。"],
          ["Suýt nữa thì nói thừa.", "余計なことを言うところだった。"],
          ["Suýt nữa thì bỏ lỡ deadline.", "締め切りに間に合わないところだった。"],
          ["Suýt nữa thì làm đổ cà phê.", "コーヒーをこぼすところだった。"],
          ["Suýt nữa thì chọn sai đường.", "道を間違えるところだった。"],
          ["Suýt nữa thì khóc trước mọi người.", "人前で泣くところだった。"],
        ],
        [
          ["危うく大事な書類を捨てるところだった。", "Suýt nữa thì vứt giấy tờ quan trọng."],
          ["もう少しで約束をすっぽかすところだった。", "Suýt nữa thì bỏ bê cuộc hẹn."],
          ["事故に遭うところだった。", "Suýt nữa thì gặp tai nạn."],
          ["面接に遅れるところだった。", "Suýt nữa thì muộn phỏng vấn."],
          ["火を消し忘れるところだった。", "Suýt nữa thì quên tắt bếp."],
          ["値段を見誤るところだった。", "Suýt nữa thì nhìn nhầm giá."],
          ["本音を漏らすところだった。", "Suýt nữa thì lộ ý thật."],
          ["階段を踏み外すところだった。", "Suýt nữa thì hụt bậc thang."],
          ["友人を怒らせるところだった。", "Suýt nữa thì làm bạn giận."],
          ["データを消すところだった。", "Suýt nữa thì xóa dữ liệu."],
        ],
        [
          ["Suýt lỡ chuyến bus.", ["バスに", "乗り遅れる", "ところだった", "。"], 0],
          ["Suýt nói lộ bí mật.", ["うっかり秘密を", "口にする", "ところだった", "。"], 0],
          ["Suýt bỏ quên ví.", ["財布を", "置き忘れる", "ところだった", "。"], 0],
          ["Suýt ngã cầu thang.", ["階段から", "転落する", "ところだった", "。"], 0],
          ["Suýt gửi nhầm mail.", ["宛先を", "間違える", "ところだった", "。"], 0],
          ["Suýt va xe đạp.", ["自転車と", "接触する", "ところだった", "。"], 0],
          ["Suýt vứt giấy tờ.", ["重要書類を", "捨てる", "ところだった", "。"], 0],
          ["Suýt muộn phỏng vấn.", ["面接に", "遅れる", "ところだった", "。"], 0],
          ["Suýt quên tắt bếp.", ["ガスを", "消し忘れる", "ところだった", "。"], 0],
          ["Suýt xóa dữ liệu.", ["データを", "消去する", "ところだった", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l20-g06",
      {
        meaning: "Cuối cùng không (làm được)… / đành không…",
        structures: ["Vず ＋ じまいだ"],
        explanation:
          "Dự định làm nhưng vì lý do nào đó cuối cùng không làm được; mang tiếc nuối.",
        usage: "Kể lại việc bỏ lỡ: không kịp gặp; không kịp nói; không kịp đọc.",
        cautions: [
          "ず là thể phủ định cổ: 行かずじまい ← 行かない.",
          "Thường kết thúc bằng だ／だった; thể hiện kết cục đã định.",
        ],
        contrast:
          "ずじまいだ ≈ cuối cùng không làm được. Khác ないまま (vẫn chưa) và 損ねる (suýt lỡ).",
        examples: [
          ex(
            "結局彼には会えずじまいだった。",
            "けっきょくかれにはあえずじまいだった。",
            "Cuối cùng đành không gặp được anh ấy.",
            [
              ["結局", "けっきょく"],
              ["彼", "かれ"],
              ["には"],
              ["会", "あ"],
              ["えずじまいだった。"],
            ],
          ),
          ex(
            "忙しくて本が読めずじまいだ。",
            "いそがしくてほんがよめずじまいだ。",
            "Bận quá cuối cùng không đọc được sách.",
            [
              ["忙", "いそが"],
              ["しくて"],
              ["本", "ほん"],
              ["が"],
              ["読", "よ"],
              ["めずじまいだ。"],
            ],
          ),
          ex(
            "お礼を言わずじまいで帰ってしまった。",
            "おれいをいわずじまいでかえってしまった。",
            "Về luôn mà đành không kịp cảm ơn.",
            [
              ["お"],
              ["礼", "れい"],
              ["を"],
              ["言", "い"],
              ["わずじまいで"],
              ["帰", "かえ"],
              ["ってしまった。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ずじまいだ",
        "Câu ずじまいだ: định làm nhưng cuối cùng không làm được.",
        [
          ["Cuối cùng không kịp hỏi.", "結局聞けずじまいだった。"],
          ["Không kịp gửi quà.", "贈り物を渡せずじまいだ。"],
          ["Không kịp xem triển lãm.", "展覧会を見ずじまいだった。"],
          ["Không kịp báo cáo với sếp.", "上司に報告せずじまいだ。"],
          ["Không kịp trả tiền vay.", "借金を返せずじまいだった。"],
          ["Không kịp thử món đó.", "その料理を食べずじまいだ。"],
          ["Không kịp chào tạm biệt.", "別れの挨拶をせずじまいだった。"],
          ["Không kịp sửa lỗi.", "ミスを直せずじまいだ。"],
          ["Không kịp gọi điện cho mẹ.", "母に電話せずじまいだった。"],
          ["Không kịp viết nhật ký.", "日記を書かずじまいだ。"],
        ],
        [
          ["旅行中に写真を撮らずじまいだった。", "Trong chuyến đi đành không chụp ảnh."],
          ["質問したかったが聞けずじまいだ。", "Muốn hỏi nhưng cuối cùng không hỏi được."],
          ["約束の時間に間に合わずじまいだった。", "Đành không kịp giờ hẹn."],
          ["欲しかった本を買わずじまいだ。", "Cuối cùng không mua được sách muốn."],
          ["彼の話を最後まで聞かずじまいだった。", "Đành không nghe hết lời anh ấy."],
          ["掃除をせずじまいで出かけた。", "Ra ngoài mà đành chưa dọn."],
          ["説明書を読まずじまいで組み立てた。", "Lắp mà đành không đọc hướng dẫn."],
          ["感謝を伝えずじまいだった。", "Cuối cùng không kịp bày tỏ biết ơn."],
          ["資料に目を通さずじまいだ。", "Đành không kịp xem tài liệu."],
          ["会場に寄らずじまいで帰った。", "Về luôn mà đành không ghé hội trường."],
        ],
        [
          ["Đành không gặp được cô ấy.", ["彼女には", "会えずじまい", "だった", "。"], 0],
          ["Bận quá không đọc hết sách.", ["忙しくて本を", "読み終えずじまい", "だ", "。"], 0],
          ["Không kịp cảm ơn đã về.", ["お礼を言わずじまいで", "その場を", "去った", "。"], 0],
          ["Rốt cuộc không kịp hỏi.", ["大事なことを", "聞けずじまい", "だった", "。"], 0],
          ["Đành không trao được quà.", ["贈り物さえ", "渡せずじまい", "だった", "。"], 0],
          ["Đành bỏ lỡ triển lãm.", ["展覧会へ", "行けずじまい", "だった", "。"], 0],
          ["Trong chuyến đi không kịp chụp.", ["旅先で写真を", "撮らずじまい", "だった", "。"], 0],
          ["Đành trễ giờ hẹn.", ["約束の時間に", "間に合わずじまい", "だった", "。"], 0],
          ["Đành không mua nổi sách.", ["欲しい本を", "買わずじまい", "だ", "。"], 0],
          ["Đành không kịp cảm ơn.", ["感謝の気持ちを", "伝えずじまい", "だった", "。"], 0],
        ],
      ),
    ),
  ];
}
