import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L06-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 10, BATCH);

export function lesson10Patterns(byId) {
  return [
    P(
      byId,
      "l10-g01",
      {
        meaning: "Nào là… nào là… (liệt kê lung tung, thường bất ổn)",
        structures: ["N／いA／V ＋ やら ＋ N／いA／V ＋ やら"],
        explanation:
          "Liệt kê vài thứ đại diện, gợi cảm giác lộn xộn hoặc dồn dập.",
        usage: "Kể chuyện, phàn nàn nhẹ: nào A nào B…",
        cautions: [
          "Thường mang sắc thái chủ quan, không liệt kê trang trọng.",
          "Khác や (liệt kê trung lập).",
        ],
        contrast: "やらやら ≈ nào… nào…. Khác といった (ví dụ như…) và とか.",
        examples: [
          ex(
            "荷物やら書類やらで机がいっぱいだ。",
            "にもつやらしょるいやらでつくえがいっぱいだ。",
            "Nào đồ đạc nào giấy tờ, bàn đầy ắp.",
            [
              ["荷物", "にもつ"],
              ["やら"],
              ["書類", "しょるい"],
              ["やらで"],
              ["机", "つくえ"],
              ["が"],
              ["いっぱいだ。"],
            ],
          ),
          ex(
            "嬉しいやら悲しいやら複雑な気分だ。",
            "うれしいやらかなしいやらふくざつなきぶんだ。",
            "Nào vui nào buồn, tâm trạng phức tạp.",
            [
              ["嬉", "うれ"],
              ["しいやら"],
              ["悲", "かな"],
              ["しいやら"],
              ["複雑", "ふくざつ"],
              ["な"],
              ["気分", "きぶん"],
              ["だ。"],
            ],
          ),
          ex(
            "来るやら来ないやらはっきりしない。",
            "くるやらこないやらはっきりしない。",
            "Nào đến nào không, chẳng rõ.",
            [["来るやら"], ["来ないやら"], ["はっきりしない。"]],
          ),
        ],
      },
      packFrom(
        "〜やら〜やら",
        "Câu dùng やらやら để liệt kê lung tung hoặc tâm trạng lẫn lộn.",
        [
          ["Nào mưa nào gió, trận đấu bị hủy.", "雨やら風やらで試合が中止になった。"],
          ["Nào họp nào báo cáo, cả ngày bận.", "会議やら報告やらで一日中忙しい。"],
          ["Nào vui nào lo, không ngủ được.", "楽しいやら心配やらで眠れない。"],
          ["Nào sách nào tạp chí, phòng đầy.", "本やら雑誌やらで部屋がいっぱいだ。"],
          ["Nào trẻ khóc nào điện thoại reo, hỗn loạn.", "子供の泣き声やら電話の音やらで騒がしい。"],
          ["Nào đói nào mệt, không muốn đi.", "空腹やら疲労やらで行きたくない。"],
          ["Nào lỗi máy nào mất mạng, công việc dừng.", "故障やら通信障害やらで作業が止まった。"],
          ["Nào khen nào chê, anh ấy bối rối.", "褒め言葉やら批判やらで彼は困惑した。"],
          ["Nào vali nào quà, hành lý nặng.", "スーツケースやら土産やらで荷物が重い。"],
          ["Nào nhớ nào tiếc, không quên được.", "懐かしいやら寂しいやらで忘れられない。"],
        ],
        [
          ["宿題やら試験やらで余裕がない。", "Nào bài tập nào thi, chẳng còn dư sức."],
          ["嬉しいやら恥ずかしいやら顔が赤い。", "Nào vui nào ngại, mặt đỏ."],
          ["荷物やらゴミやらが廊下に置いてある。", "Nào đồ nào rác để ở hành lang."],
          ["来るやらどうやら連絡がない。", "Nào đến thế nào chẳng liên lạc."],
          ["文句やら言い訳やらばかり言う。", "Chỉ nào phàn nàn nào biện hộ."],
          ["寒いやら暑いやら体調が変だ。", "Nào lạnh nào nóng, sức khỏe lạ."],
          ["書類やらデータやら確認が必要だ。", "Cần kiểm tra nào giấy tờ nào dữ liệu."],
          ["歌やら踊りやらで会場が盛り上がった。", "Nào hát nào nhảy, hội trường sôi động."],
          ["不安やら期待やらで胸が騒ぐ。", "Nào lo nào kỳ vọng, ngực thổn thức."],
          ["道具やら材料やらが足りない。", "Thiếu nào dụng cụ nào nguyên liệu."],
        ],
        [
          ["Nào đồ nào giấy tờ bàn đầy.", ["荷物やら", "書類やらで", "机が", "いっぱいだ。"], 1],
          ["Nào vui nào buồn tâm trạng phức tạp.", ["嬉しいやら", "悲しいやら", "気分が", "複雑だ。"], 1],
          ["Nào đến nào không chẳng rõ.", ["来るやら", "来ないやら", "態度が", "不明だ。"], 1],
          ["Nào mưa nào gió trận hủy.", ["雨やら", "風やらで", "試合が", "中止だ。"], 1],
          ["Nào họp nào báo cáo bận.", ["会議やら", "報告やらで", "一日が", "終わる。"], 1],
          ["Nào sách nào tạp chí đầy phòng.", ["本やら", "雑誌やらで", "部屋が", "狭い。"], 1],
          ["Nào đói nào mệt không muốn đi.", ["空腹やら", "疲労やらで", "外出を", "やめた。"], 1],
          ["Nào lỗi nào mất mạng dừng việc.", ["故障やら", "障害やらで", "作業が", "止まった。"], 1],
          ["Nào bài tập nào thi hết sức.", ["宿題やら", "試験やらで", "余裕が", "ない。"], 1],
          ["Nào hát nào nhảy sôi động.", ["歌やら", "踊りやらで", "会場が", "熱い。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l10-g02",
      {
        meaning: "Vừa như… vừa như… / nói là… cũng được",
        structures: ["〜というか〜というか"],
        explanation:
          "Liệt kê cách diễn đạt cảm xúc/ấn tượng chưa chắc chắn; chọn từ chưa quyết.",
        usage: "Nói cảm nghĩ mơ hồ: nói là vui cũng được, nói là lo cũng được.",
        cautions: [
          "Thường dùng khi khó chọn một từ duy nhất.",
          "Khác というより (đúng hơn là…).",
        ],
        contrast: "というか ≈ nói là A cũng được, B cũng được. Khác やらやら (liệt kê sự việc).",
        examples: [
          ex(
            "嬉しいというか安心したというか複雑な気持ちだ。",
            "うれしいというかあんしんしたというかふくざつなきもちだ。",
            "Nói vui cũng được, nói yên tâm cũng được, cảm xúc phức tạp.",
            [
              ["嬉", "うれ"],
              ["しいというか"],
              ["安心", "あんしん"],
              ["したというか"],
              ["複雑", "ふくざつ"],
              ["な"],
              ["気持", "きも"],
              ["ちだ。"],
            ],
          ),
          ex(
            "彼は厳しいというか真面目というか不思議な人だ。",
            "かれはきびしいというかまじめというかふしぎなひとだ。",
            "Anh ấy nói nghiêm cũng được, nói nghiêm túc cũng được, người lạ.",
            [
              ["彼", "かれ"],
              ["は"],
              ["厳", "きび"],
              ["しいというか"],
              ["真面目", "まじめ"],
              ["というか"],
              ["不思議", "ふしぎ"],
              ["な"],
              ["人", "ひと"],
              ["だ。"],
            ],
          ),
          ex(
            "残念というか悔しいというか言葉にできない。",
            "ざんねんというかくやしいというかことばにできない。",
            "Nói tiếc cũng được, nói tức cũng được, không nói nên lời.",
            [
              ["残念", "ざんねん"],
              ["というか"],
              ["悔", "くや"],
              ["しいというか"],
              ["言葉", "ことば"],
              ["にできない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜というか〜というか",
        "Câu dùng というか…というか khi chưa chọn được một cách diễn đạt duy nhất.",
        [
          ["Nói vui cũng được nói ngạc nhiên cũng được.", "嬉しいというか驚いたというかだ。"],
          ["Nói khó cũng được nói thú vị cũng được.", "難しいというか面白いというか課題だ。"],
          ["Nói lạnh cũng được nói dễ chịu cũng được.", "寒いというか爽やかというか天気だ。"],
          ["Nói giận cũng được nói buồn cũng được.", "怒っているというか悲しいというか顔だ。"],
          ["Nói giản dị cũng được nói thô cũng được.", "素朴というか粗いというかデザインだ。"],
          ["Nói tự tin cũng được nói kiêu cũng được.", "自信があるというか生意気というか態度だ。"],
          ["Nói mệt cũng được nói thỏa mãn cũng được.", "疲れたというか充実したというか一日だ。"],
          ["Nói dễ cũng được nói nhàm cũng được.", "簡単というか単調というか作業だ。"],
          ["Nói thân thiện cũng được nói suồng sã cũng được.", "親しみやすいというかくだけすぎというか話し方だ。"],
          ["Nói tiếc cũng được nói nhẹ nhõm cũng được.", "残念というかほっとしたというか結果だ。"],
        ],
        [
          ["嬉しいというか恥ずかしいというか返事に困った。", "Nói vui cũng được nói ngại cũng được, khó đáp."],
          ["厳しいというか公正というか評価だった。", "Nói nghiêm cũng được nói công bằng cũng được."],
          ["速いというか雑というか仕事ぶりだ。", "Nói nhanh cũng được nói ẩu cũng được."],
          ["静かというか寂しいというか街だ。", "Nói yên cũng được nói vắng cũng được."],
          ["賢いというか狡猾というか人だと感じた。", "Cảm giác nói thông minh cũng được nói láu cũng được."],
          ["嬉しいというか不安というか発表の前だ。", "Trước công bố, nói vui cũng được nói lo cũng được."],
          ["安いというか不安な品質というか商品だ。", "Nói rẻ cũng được nói chất lượng đáng ngờ cũng được."],
          ["面白いというか分かりにくいというか説明だ。", "Nói hay cũng được nói khó hiểu cũng được."],
          ["優しいというか甘いというか対応だ。", "Nói dịu dàng cũng được nói nuông chiều cũng được."],
          ["新しいというか未熟というか企画だと指摘された。", "Bị chỉ: nói mới cũng được nói chưa chín cũng được."],
        ],
        [
          ["Nói vui cũng được nói yên tâm cũng được.", ["嬉しいというか", "安心というか", "気持ちが", "複雑だ。"], 1],
          ["Nói nghiêm cũng được nói nghiêm túc cũng được.", ["厳しいというか", "真面目というか", "人柄が", "独特だ。"], 1],
          ["Nói tiếc cũng được nói tức cũng được.", ["残念というか", "悔しいというか", "言葉が", "出ない。"], 1],
          ["Thành ra vừa khó vừa thú vị.", ["難しいというか", "面白いというか", "課題に", "なった。"], 1],
          ["Vẻ mặt cứng: vừa giận vừa buồn.", ["怒りというか", "悲しみというか", "表情が", "固い。"], 1],
          ["Một ngày vừa mệt vừa thỏa mãn.", ["疲労というか", "充実というか", "一日が", "終わった。"], 1],
          ["Nói nhanh cũng được nói ẩu cũng được.", ["速いというか", "雑というか", "仕上がりに", "なった。"], 1],
          ["Nói yên cũng được nói vắng cũng được.", ["静かというか", "寂しいというか", "街に", "感じる。"], 1],
          ["Nói rẻ cũng được nói đáng ngờ cũng được.", ["安いというか", "不安というか", "品質が", "気になる。"], 1],
          ["Nói hay cũng được nói khó hiểu cũng được.", ["面白いというか", "難解というか", "説明に", "なった。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l10-g03",
      {
        meaning: "Dù là… hay… thì… (liệt kê nhượng bộ)",
        structures: [
          "〜にしても〜にしても",
          "〜にしろ〜にしろ",
          "〜にせよ〜にせよ",
        ],
        explanation:
          "Nêu vài khả năng/đối tượng rồi kết luận chung vẫn đúng với mọi trường hợp.",
        usage: "Lập luận: dù A hay B thì vẫn…",
        cautions: [
          "にしろ／にせよ sắc thái viết mạnh hơn にしても.",
          "Cũng dùng một vế にしても (dù là…).",
        ],
        contrast: "にしても／にしろ／にせよ ≈ dù… hay…. Khác やらやら (liệt kê lung tung).",
        examples: [
          ex(
            "行くにしても行かないにしても連絡してほしい。",
            "いくにしてもいかないにしてもれんらくしてほしい。",
            "Dù đi hay không cũng muốn được liên lạc.",
            [
              ["行", "い"],
              ["くにしても"],
              ["行", "い"],
              ["かないにしても"],
              ["連絡", "れんらく"],
              ["してほしい。"],
            ],
          ),
          ex(
            "勝つにしろ負けるにしろ全力を尽くせ。",
            "かつにしろまけるにしろぜんりょくをつくせ。",
            "Dù thắng hay thua hãy hết sức.",
            [
              ["勝", "か"],
              ["つにしろ"],
              ["負", "ま"],
              ["けるにしろ"],
              ["全力", "ぜんりょく"],
              ["を"],
              ["尽", "つ"],
              ["くせ。"],
            ],
          ),
          ex(
            "高いにせよ安いにせよ品質が大事だ。",
            "たかいにせよやすいにせよひんしつがだいじだ。",
            "Dù đắt hay rẻ chất lượng mới quan trọng.",
            [
              ["高", "たか"],
              ["いにせよ"],
              ["安", "やす"],
              ["いにせよ"],
              ["品質", "ひんしつ"],
              ["が"],
              ["大事", "だいじ"],
              ["だ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜にしても／にしろ／にせよ",
        "Câu dùng にしても／にしろ／にせよ: dù A hay B thì kết luận vẫn đúng.",
        [
          ["Dù mưa hay nắng trận đấu vẫn tổ chức.", "雨にしても晴れにしても試合は行う。"],
          ["Dù đồng ý hay không hãy trả lời sớm.", "賛成にしても反対にしても早く返事してほしい。"],
          ["Dù thắng hay thua hãy bắt tay.", "勝つにしろ負けるにしろ握手しよう。"],
          ["Dù đắt hay rẻ hãy so sánh kỹ.", "高いにせよ安いにせよよく比較せよ。"],
          ["Dù đi làm hay ở nhà hãy giữ sức khỏe.", "出勤にしても在宅にしても健康を守れ。"],
          ["Dù thích hay không phải hoàn thành.", "好きにしろ嫌いにしろ仕上げなければならない。"],
          ["Dù sớm hay muộn phải báo cáo.", "早いにせよ遅いにせよ報告は必要だ。"],
          ["Dù anh ấy hay cô ấy đều có trách nhiệm.", "彼にしても彼女にしても責任がある。"],
          ["Dù thành công hay thất bại hãy học hỏi.", "成功にしろ失敗にしろ学べ。"],
          ["Dù đông hay vắng phục vụ phải tốt.", "混むにせよ空くにせよ接客は丁寧に。"],
        ],
        [
          ["来るにしても来ないにしても席は確保する。", "Dù đến hay không vẫn giữ chỗ."],
          ["買うにしろ買わないにしろ説明を聞け。", "Dù mua hay không hãy nghe giải thích."],
          ["賛成にせよ反対にせよ理由を述べよ。", "Dù tán thành hay phản đối hãy nêu lý do."],
          ["平日にしても休日にしても予約が要る。", "Dù ngày thường hay ngày nghỉ đều cần đặt chỗ."],
          ["上手にしろ下手にしろ挑戦する価値がある。", "Dù giỏi hay kém vẫn đáng thử."],
          ["高いにしても品質が伴わなければ意味がない。", "Dù đắt nếu chất lượng không theo thì vô nghĩa."],
          ["彼にしても無理は続かない。", "Dù là anh ấy cũng không thể cố mãi."],
          ["勝つにせよ負けるにせよ応援する。", "Dù thắng hay thua tôi vẫn cổ vũ."],
          ["行くにしろ残るにしろ決断が必要だ。", "Dù đi hay ở lại đều cần quyết định."],
          ["子どもにしても大人にしてもルールは同じだ。", "Dù trẻ hay người lớn quy tắc như nhau."],
        ],
        [
          ["Dù đi hay không hãy liên lạc.", ["行くにしても", "行かないにしても", "連絡を", "くれ。"], 1],
          ["Dù thắng hay thua hãy hết sức.", ["勝つにしろ", "負けるにしろ", "全力を", "出せ。"], 1],
          ["Dù đắt hay rẻ chất lượng quan trọng.", ["高いにせよ", "安いにせよ", "品質が", "大事だ。"], 1],
          ["Dù mưa hay nắng vẫn tổ chức.", ["雨にしても", "晴れにしても", "開催は", "する。"], 1],
          ["Dù đồng ý hay không trả lời sớm.", ["賛成にしても", "反対にしても", "返事を", "急げ。"], 1],
          ["Dù thích hay không phải xong.", ["好きにしろ", "嫌いにしろ", "完成が", "必要だ。"], 1],
          ["Dù đến hay không giữ chỗ.", ["来るにしても", "来ないにしても", "席は", "残す。"], 1],
          ["Dù mua hay không nghe giải thích.", ["買うにしろ", "買わないにしろ", "説明を", "聞け。"], 1],
          ["Dù tán thành hay phản đối nêu lý do.", ["賛成にせよ", "反対にせよ", "理由を", "言え。"], 1],
          ["Dù trẻ hay lớn quy tắc như nhau.", ["子供にしても", "大人にしても", "規則は", "同じだ。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l10-g04",
      {
        meaning: "Những thứ như… / ví dụ như…",
        structures: ["N や N ＋ といった ＋ N", "N ＋ といった ＋ N"],
        explanation:
          "Đưa ví dụ đại diện rồi khái quát loại/nhóm; thường theo sau danh từ chỉ loại.",
        usage: "Giới thiệu ví dụ: những môn như…, những vấn đề như…",
        cautions: [
          "Không nhầm với といったら (nói đến… thì).",
          "Thường kết hợp や／とか trước といった.",
        ],
        contrast: "といった ≈ những thứ như. Khác やらやら (liệt kê cảm tính).",
        examples: [
          ex(
            "東京や大阪といった大都市に人が集まる。",
            "とうきょうやおおさかといっただいとしにひとがあつまる。",
            "Người tập trung ở các thành phố lớn như Tokyo, Osaka.",
            [
              ["東京", "とうきょう"],
              ["や"],
              ["大阪", "おおさか"],
              ["といった"],
              ["大都市", "だいとし"],
              ["に"],
              ["人", "ひと"],
              ["が"],
              ["集", "あつ"],
              ["まる。"],
            ],
          ),
          ex(
            "風邪やインフルエンザといった病気に注意したい。",
            "かぜやいんふるえんざといったびょうきにちゅういしたい。",
            "Muốn chú ý các bệnh như cảm, cúm.",
            [
              ["風邪", "かぜ"],
              ["や"],
              ["インフルエンザ"],
              ["といった"],
              ["病気", "びょうき"],
              ["に"],
              ["注意", "ちゅうい"],
              ["したい。"],
            ],
          ),
          ex(
            "彼は野球やサッカーといったスポーツが得意だ。",
            "かれはやきゅうやさっかーといったすぽーつがとくいだ。",
            "Anh ấy giỏi các môn như bóng chày, bóng đá.",
            [
              ["彼", "かれ"],
              ["は"],
              ["野球", "やきゅう"],
              ["や"],
              ["サッカー"],
              ["といった"],
              ["スポーツが"],
              ["得意", "とくい"],
              ["だ。"],
            ],
          ),
        ],
      },
      packFrom(
        "N や N ＋ といった ＋ N",
        "Câu dùng といった để nêu ví dụ đại diện rồi khái quát loại.",
        [
          ["Các môn như toán, lý cần luyện nhiều.", "数学や物理といった科目は練習が必要だ。"],
          ["Các nước như Nhật, Hàn phát triển công nghệ.", "日本や韓国といった国は技術が進んでいる。"],
          ["Các vấn đề như môi trường, năng lượng quan trọng.", "環境やエネルギーといった問題が重要だ。"],
          ["Các nghề như bác sĩ, luật sư được tôn trọng.", "医師や弁護士といった職業は尊敬される。"],
          ["Các lễ như Tết, Obon đông người về quê.", "正月やお盆といった時期は帰省が多い。"],
          ["Các app như bản đồ, dịch thuật tiện lợi.", "地図や翻訳といったアプリが便利だ。"],
          ["Các chi phí như tiền thuê, điện nước tăng.", "家賃や光熱費といった支出が増えた。"],
          ["Các môn thể thao như tennis, bơi phổ biến.", "テニスや水泳といったスポーツが人気だ。"],
          ["Các kỹ năng như giao tiếp, thuyết trình cần thiết.", "会話や発表といったスキルが求められる。"],
          ["Các hiện tượng như động đất, bão hay xảy ra.", "地震や台風といった災害に備えたい。"],
        ],
        [
          ["紅茶やコーヒーといった飲み物が好きだ。", "Tôi thích đồ uống như trà, cà phê."],
          ["小説や詩といった文学作品を読む。", "Đọc tác phẩm văn học như tiểu thuyết, thơ."],
          ["駅や空港といった交通拠点が混む。", "Các điểm giao thông như ga, sân bay đông."],
          ["英語や中国語といった言語を学ぶ学生が増えた。", "Sinh viên học ngôn ngữ như Anh, Trung tăng."],
          ["スマホやパソコンといった機器が必需品だ。", "Thiết bị như điện thoại, máy tính là cần thiết."],
          ["美術館や博物館といった施設を巡った。", "Đi quanh các cơ sở như bảo tàng mỹ thuật, bảo tàng."],
          ["会議や研修といった予定で埋まっている。", "Lịch kín các việc như họp, tập huấn."],
          ["野菜や果物といった食材を安く買える。", "Mua rẻ thực phẩm như rau, trái cây."],
          ["規則やマナーといった基本を守れ。", "Hãy giữ những điều cơ bản như quy tắc, phép lịch sự."],
          ["映画やドラマといった娯楽が欠かせない。", "Giải trí như phim, drama không thể thiếu."],
        ],
        [
          ["Thành phố lớn như Tokyo, Osaka.", ["東京や大阪", "といった", "大都市に", "集まる。"], 1],
          ["Bệnh như cảm, cúm.", ["風邪や流感", "といった", "病気に", "注意する。"], 1],
          ["Thể thao như bóng chày, bóng đá.", ["野球や蹴球", "といった", "競技が", "得意だ。"], 1],
          ["Môn như toán, lý.", ["数学や物理", "といった", "科目を", "学ぶ。"], 1],
          ["Nước như Nhật, Hàn.", ["日本や韓国", "といった", "国が", "進んでいる。"], 1],
          ["Vấn đề như môi trường, năng lượng.", ["環境やエネルギー", "といった", "課題が", "大きい。"], 1],
          ["Nghề như bác sĩ, luật sư.", ["医師や弁護士", "といった", "職業が", "ある。"], 1],
          ["Đồ uống như trà, cà phê.", ["紅茶やコーヒー", "といった", "飲み物が", "好きだ。"], 1],
          ["Thiết bị như điện thoại, máy tính.", ["端末やPC", "といった", "機器が", "要る。"], 1],
          ["Thảm họa như động đất, bão.", ["地震や台風", "といった", "災害に", "備える。"], 1],
        ],
      ),
    ),
  ];
}
