import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L16-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 19, BATCH);

export function lesson19Patterns(byId) {
  return [
    P(
      byId,
      "l19-g01",
      {
        meaning: "So với… thì… / dù… nhưng (không tương xứng)",
        structures: [
          "N／普通形 ＋ わりに（は）",
          "いAい ＋ わりに（は）",
          "なAな／である ＋ わりに（は）",
        ],
        explanation:
          "わりに（は）: đánh giá kết quả không tương xứng với mức độ/điều kiện đã nêu — thường tốt hơn hoặc kém hơn kỳ vọng.",
        usage: "Nhận xét: giá rẻ mà chất lượng tốt; trẻ mà chín chắn.",
        cautions: [
          "Thường kèm đánh giá chủ quan sau わりに.",
          "わりには nhấn mạnh hơn một chút so với わりに.",
        ],
        contrast: "わりに ≈ so với… thì…. Gần にしては nhưng thiên 'mức độ ↔ kết quả'.",
        examples: [
          ex(
            "値段のわりに味がいい。",
            "ねだんのわりにあじがいい。",
            "So với giá thì vị khá ngon.",
            [
              ["値段", "ねだん"],
              ["のわりに"],
              ["味", "あじ"],
              ["が"],
              ["いい。"],
            ],
          ),
          ex(
            "若いわりには落ち着いている。",
            "わかいわりにはおちついている。",
            "Dù còn trẻ mà khá điềm đạm.",
            [
              ["若", "わか"],
              ["いわりには"],
              ["落", "お"],
              ["ち着いている。"],
            ],
          ),
          ex(
            "努力したわりに成果が出ない。",
            "どりょくしたわりにせいかがでない。",
            "Đã cố gắng mà kết quả chẳng ra.",
            [
              ["努力", "どりょく"],
              ["したわりに"],
              ["成果", "せいか"],
              ["が"],
              ["出", "で"],
              ["ない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜わりに（は）",
        "Câu dùng わりに／わりには: so với… thì… (không tương xứng).",
        [
          ["So với tuổi thì trông trẻ.", "年齢のわりに若く見える。"],
          ["So với lương thì công việc nặng.", "給料のわりに仕事がきつい。"],
          ["Học ít mà điểm cao.", "勉強時間が短いわりに成績がいい。"],
          ["Nhỏ mà chứa nhiều.", "サイズが小さいわりに容量が多い。"],
          ["Đắt mà chất lượng kém.", "高いわりに品質が低い。"],
          ["Kinh nghiệm ít mà xử lý tốt.", "経験が少ないわりにうまく対応する。"],
          ["Quảng cáo hay mà thực tế tầm thường.", "宣伝が派手なわりに中身は普通だ。"],
          ["Mệt mà vẫn vui vẻ.", "疲れているわりに明るく振る舞う。"],
          ["Rẻ mà bền.", "安いわりに長持ちする。"],
          ["Cố nhiều mà tiến bộ chậm.", "頑張ったわりに上達が遅い。"],
        ],
        [
          ["この店は安いわりに美味しい。", "Quán này rẻ mà ngon."],
          ["彼は忙しいわりに連絡をくれる。", "Anh ấy bận mà vẫn liên lạc."],
          ["部屋は狭いわりに使いやすい。", "Phòng hẹp mà dễ dùng."],
          ["練習不足のわりに上手だ。", "Thiếu luyện tập mà vẫn giỏi."],
          ["この本は難しいわりに面白い。", "Sách này khó mà thú vị."],
          ["彼女は新人のわりに仕事が速い。", "Cô ấy mới mà làm việc nhanh."],
          ["雨のわりに客が多かった。", "Dù mưa mà khách vẫn đông."],
          ["説明が短いわりに分かりやすい。", "Giải thích ngắn mà dễ hiểu."],
          ["この服は高いわりにすぐ破れる。", "Áo này đắt mà mau rách."],
          ["準備不足のわりに成功した。", "Thiếu chuẩn bị mà vẫn thành công."],
        ],
        [
          ["So với giá thì khá ngon.", ["値段のわりに", "味は", "悪くない", "。"], 0],
          ["Trẻ mà khá điềm đạm.", ["若いわりには", "とても", "落ち着いている", "。"], 0],
          ["Cố mà kết quả kém.", ["努力したわりに", "成果が", "少ない", "。"], 0],
          ["So với tuổi trông trẻ.", ["年齢のわりに", "若く", "見える", "。"], 0],
          ["Lương thấp việc nặng.", ["給料のわりに", "仕事が", "きつい", "。"], 0],
          ["Rẻ mà dùng lâu được.", ["安いわりに", "長持ち", "する", "。"], 0],
          ["Đắt mà chất kém.", ["高いわりに", "品質が", "低い", "。"], 0],
          ["Hẹp mà dễ dùng.", ["部屋は狭いわりに", "使い", "やすい", "。"], 0],
          ["Bận mà vẫn liên lạc.", ["忙しいわりに", "連絡を", "くれる", "。"], 0],
          ["Rẻ mà vẫn ngon.", ["この店は安いわりに", "美味", "しい", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l19-g02",
      {
        meaning: "Xét về tư cách/điều kiện… thì… (khác kỳ vọng)",
        structures: ["N ＋ にしては"],
        explanation:
          "にしては: lấy N làm chuẩn đánh giá; kết quả khác với mức người ta thường kỳ vọng từ N đó.",
        usage: "Nhận xét: với tư cách người mới thì giỏi; với giá này thì ổn.",
        cautions: [
          "Thường sau danh từ (hoặc cụm danh từ hóa).",
          "Gần わりに nhưng nhấn mạnh 'xét theo tư cách/điều kiện đã nêu'.",
        ],
        contrast: "にしては ≈ xét về… thì…. Khác としては (với tư cách… làm).",
        examples: [
          ex(
            "初心者にしては上手だ。",
            "しょしんしゃにしてはじょうずだ。",
            "Với tư cách người mới thì khá giỏi.",
            [
              ["初心者", "しょしんしゃ"],
              ["にしては"],
              ["上手", "じょうず"],
              ["だ。"],
            ],
          ),
          ex(
            "この値段にしては品質が良い。",
            "このねだんにしてはひんしつがよい。",
            "Với mức giá này thì chất lượng tốt.",
            [
              ["この"],
              ["値段", "ねだん"],
              ["にしては"],
              ["品質", "ひんしつ"],
              ["が"],
              ["良", "よ"],
              ["い。"],
            ],
          ),
          ex(
            "冬にしては暖かい日だ。",
            "ふゆにしてはあたたかいひだ。",
            "Xét là mùa đông thì hôm nay ấm.",
            [
              ["冬", "ふゆ"],
              ["にしては"],
              ["暖", "あたた"],
              ["かい"],
              ["日", "ひ"],
              ["だ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜にしては",
        "Câu dùng にしては: xét về tư cách/điều kiện… thì…",
        [
          ["Với người mới thì nói khá trôi.", "新人にしては話し方がうまい。"],
          ["Với trẻ em thì suy nghĩ chín.", "子供にしては考えが深い。"],
          ["Với số tiền ấy thì mua được nhiều.", "その金額にしてはたくさん買える。"],
          ["Với bài thi khó thì điểm cao.", "難しい試験にしては点が高い。"],
          ["Với lần đầu thì ít lỗi.", "初めてにしてはミスが少ない。"],
          ["Với nhà cũ thì sạch sẽ.", "古い家にしてはきれいだ。"],
          ["Với mùa hè thì mát.", "夏にしては涼しい。"],
          ["Với quy mô nhỏ thì lợi nhuận tốt.", "小規模にしては利益が大きい。"],
          ["Với tự học thì trình độ cao.", "独学にしてはレベルが高い。"],
          ["Với lời đồn thì bình thường.", "噂にしては普通だった。"],
        ],
        [
          ["彼はアマチュアにしては上手い。", "Anh ấy nghiệp dư mà khá giỏi."],
          ["この店は駅前にしては安い。", "Quán này ở trước ga mà rẻ."],
          ["彼女は忙しい人にしては丁寧だ。", "Cô ấy là người bận mà vẫn chu đáo."],
          ["この車は中古にしては状態がいい。", "Xe này cũ mà tình trạng tốt."],
          ["今日は月曜日にしては混んでいる。", "Hôm nay là thứ Hai mà đông."],
          ["この問題は入門にしては難しい。", "Bài này là nhập môn mà khó."],
          ["彼は大学生にしては社会経験が豊富だ。", "Anh ấy là sinh viên mà nhiều kinh nghiệm xã hội."],
          ["この荷物は航空便にしては安い。", "Hàng này gửi máy bay mà rẻ."],
          ["その説明は専門家にしては分かりにくい。", "Lời giải thích ấy của chuyên gia mà khó hiểu."],
          ["この部屋はホテルにしては狭い。", "Phòng này của khách sạn mà hẹp."],
        ],
        [
          ["Người mới mà khá khéo.", ["初心者にしては", "かなり", "上手だ", "。"], 0],
          ["Giá này chất lượng ổn.", ["この値段にしては", "品質が", "悪くない", "。"], 0],
          ["Mùa đông mà khá ấm.", ["冬にしては", "温かい", "一日だ", "。"], 0],
          ["Trẻ em mà suy nghĩ chín.", ["子供にしては", "考えが", "深い", "。"], 0],
          ["Lần đầu mà ít lỗi.", ["初めてにしては", "ミスが", "少ない", "。"], 0],
          ["Mùa hè mà mát.", ["夏にしては", "涼", "しい", "。"], 0],
          ["Nhà cũ mà sạch.", ["古い家にしては", "きれい", "だ", "。"], 0],
          ["Tự học mà trình độ cao.", ["独学にしては", "レベルが", "高い", "。"], 0],
          ["Trước ga mà rẻ.", ["駅前にしては", "安", "い", "。"], 0],
          ["Xe cũ mà tình trạng tốt.", ["中古にしては", "状態が", "いい", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l19-g03",
      {
        meaning: "Đúng là… nên… / quả xứng với…",
        structures: [
          "普通形 ＋ だけあって",
          "普通形 ＋ だけある",
          "普通形 ＋ だけのことはある",
        ],
        explanation:
          "だけあって／だけある／だけのことはある: kết quả xứng với danh tiếng, nỗ lực, tư cách đã nêu — thường khen.",
        usage: "Khen ngợi: học nhiều nên giỏi; danh tiếng nên đáng giá.",
        cautions: [
          "だけあって thường nối sang vế kết quả; だけのことはある hay đứng cuối câu khen.",
          "Không dùng cho kết quả tiêu cực trái kỳ vọng (khi đó dùng わりに／にしては).",
        ],
        contrast: "だけあって ≈ đúng là… nên…. Khác わりに (không tương xứng).",
        examples: [
          ex(
            "プロだけあって速い。",
            "ぷろだけあってはやい。",
            "Đúng là chuyên nghiệp nên nhanh.",
            [
              ["プロ", "ぷろ"],
              ["だけあって"],
              ["速", "はや"],
              ["い。"],
            ],
          ),
          ex(
            "高いだけのことはある。",
            "たかいだけのことはある。",
            "Đắt thì cũng xứng đáng.",
            [
              ["高", "たか"],
              ["いだけのことはある。"],
            ],
          ),
          ex(
            "練習しただけあって上手になった。",
            "れんしゅうしただけあってじょうずになった。",
            "Đúng là đã luyện nên đã giỏi hơn.",
            [
              ["練習", "れんしゅう"],
              ["しただけあって"],
              ["上手", "じょうず"],
              ["に"],
              ["なった。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜だけ（のことは）ある",
        "Câu dùng だけあって／だけある／だけのことはある: quả xứng với…",
        [
          ["Đúng là chuyên gia nên giải thích rõ.", "専門家だけあって説明が分かりやすい。"],
          ["Học lâu nên từ vựng phong phú.", "長く勉強しただけあって語彙が豊富だ。"],
          ["Giá cao thì cũng xứng.", "値段が高いだけのことはある。"],
          ["Đúng là quán nổi tiếng nên đông.", "有名店だけあっていつも混んでいる。"],
          ["Tập chăm nên thể lực tốt.", "よく鍛えただけあって体力がある。"],
          ["Đúng là hàng Nhật nên bền.", "日本製品だけあって丈夫だ。"],
          ["Kinh nghiệm nhiều nên xử lý nhanh.", "経験が多いだけあって対応が早い。"],
          ["Thầy giỏi thì cũng xứng danh.", "良い先生だけのことはある。"],
          ["Đúng là mùa lễ hội nên vui.", "祭りの時期だけあって賑やかだ。"],
          ["Chuẩn bị kỹ nên ít lỗi.", "念入りに準備しただけあってミスが少ない。"],
        ],
        [
          ["彼は元選手だけあって動きが軽い。", "Anh ấy đúng là cựu vận động viên nên động tác nhẹ."],
          ["この包丁は高いだけのことはある。", "Dao này đắt thì cũng xứng."],
          ["彼女は留学しただけあって発音がきれいだ。", "Cô ấy đúng là đã du học nên phát âm đẹp."],
          ["老舗だけあって味が安定している。", "Đúng là quán lâu đời nên vị ổn định."],
          ["努力しただけのことはある結果だ。", "Kết quả xứng với công sức đã bỏ."],
          ["一流ホテルだけあってサービスが丁寧だ。", "Đúng là khách sạn hạng nhất nên dịch vụ chu đáo."],
          ["彼は教師だけあって教え方が上手い。", "Anh ấy đúng là giáo viên nên dạy khéo."],
          ["この地図は詳しいだけのことはある。", "Bản đồ này chi tiết thì cũng xứng."],
          ["優勝しただけあって実力がある。", "Đúng là vô địch nên có thực lực."],
          ["高級ブランドだけあってデザインが洗練されている。", "Đúng là thương hiệu cao cấp nên thiết kế tinh tế."],
        ],
        [
          ["Chuyên nghiệp nên rất nhanh.", ["プロだけあって", "スピードが", "速い", "。"], 0],
          ["Đắt thì quả cũng xứng.", ["値段が高い", "だけのことは", "ある", "。"], 0],
          ["Luyện nên tiến bộ rõ.", ["練習しただけあって", "上達", "した", "。"], 0],
          ["Chuyên gia nên dễ hiểu.", ["専門家だけあって", "説明が", "分かりやすい", "。"], 0],
          ["Quán nổi tiếng nên đông.", ["有名店だけあって", "いつも", "混んでいる", "。"], 0],
          ["Hàng Nhật nên bền.", ["日本製品だけあって", "丈夫", "だ", "。"], 0],
          ["Tập chăm nên khỏe.", ["よく鍛えただけあって", "体力が", "ある", "。"], 0],
          ["Kinh nghiệm nên xử lý nhanh.", ["経験が多いだけあって", "対応が", "早い", "。"], 0],
          ["Khách sạn hạng nhất chu đáo.", ["一流ホテルだけあって", "サービスが", "丁寧だ", "。"], 0],
          ["Vô địch nên có thực lực.", ["優勝しただけあって", "実力が", "ある", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l19-g04",
      {
        meaning: "Với tư cách… / trong vai trò…",
        structures: [
          "N ＋ として",
          "N ＋ としての ＋ N",
        ],
        explanation:
          "として diễn đạt tư cách, vai trò, vị thế. としての bổ nghĩa danh từ sau: trách nhiệm với tư cách…",
        usage: "Giới thiệu vai trò: 代表として話す; 学生としての自覚.",
        cautions: [
          "Không nhầm với として～ない (ngay cả một… cũng không) ở bài khác.",
          "としての luôn theo sau bởi danh từ.",
        ],
        contrast: "として ≈ với tư cách…. Khác にとって (đối với…).",
        examples: [
          ex(
            "私は代表として発言した。",
            "わたしはだいひょうとしてはつげんした。",
            "Tôi phát biểu với tư cách đại diện.",
            [
              ["私", "わたし"],
              ["は"],
              ["代表", "だいひょう"],
              ["として"],
              ["発言", "はつげん"],
              ["した。"],
            ],
          ),
          ex(
            "彼は医者としての責任を果たした。",
            "かれはいしゃとしてのせきにんをはたした。",
            "Anh ấy đã làm tròn trách nhiệm với tư cách bác sĩ.",
            [
              ["彼", "かれ"],
              ["は"],
              ["医者", "いしゃ"],
              ["としての"],
              ["責任", "せきにん"],
              ["を"],
              ["果", "は"],
              ["たした。"],
            ],
          ),
          ex(
            "贈り物として花を選んだ。",
            "おくりものとしてはなをえらんだ。",
            "Tôi chọn hoa làm quà tặng.",
            [
              ["贈", "おく"],
              ["り物として"],
              ["花", "はな"],
              ["を"],
              ["選", "えら"],
              ["んだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜として",
        "Câu dùng として／としての: với tư cách / trong vai trò…",
        [
          ["Tôi tham dự với tư cách quan sát viên.", "オブザーバーとして参加する。"],
          ["Cô ấy làm việc với tư cách biên dịch.", "彼女は翻訳者として働いている。"],
          ["Anh ấy có nghĩa vụ với tư cách lãnh đạo.", "彼にはリーダーとしての義務がある。"],
          ["Tôi gửi thư với tư cách khách hàng.", "顧客として手紙を送った。"],
          ["Đây là vấn đề với tư cách xã hội.", "これは社会としての課題だ。"],
          ["Anh ấy nổi tiếng với tư cách nhạc sĩ.", "彼は音楽家として有名だ。"],
          ["Tôi ký với tư cách người bảo lãnh.", "保証人として署名した。"],
          ["Cô ấy phát biểu với tư cách mẹ.", "母親として意見を述べた。"],
          ["Đây là kinh nghiệm với tư cách sinh viên.", "学生としての経験だ。"],
          ["Họ hợp tác với tư cách đối tác.", "彼らはパートナーとして協力している。"],
        ],
        [
          ["彼は教師として尊敬されている。", "Anh ấy được kính trọng với tư cách giáo viên."],
          ["私は個人として反対する。", "Tôi phản đối với tư cách cá nhân."],
          ["この件は会社としての方針だ。", "Việc này là phương châm của công ty."],
          ["彼女は友人として相談に乗った。", "Cô ấy tư vấn với tư cách bạn."],
          ["彼は専門家として助言した。", "Anh ấy góp ý với tư cách chuyên gia."],
          ["私は親としての責任を感じる。", "Tôi cảm nhận trách nhiệm với tư cách cha mẹ."],
          ["この賞は激励として贈られる。", "Giải thưởng này được tặng như sự khích lệ."],
          ["彼は証人として出廷した。", "Anh ấy hầu tòa với tư cách nhân chứng."],
          ["これは記念としての写真だ。", "Đây là tấm ảnh mang tính kỷ niệm."],
          ["彼女は志願者として登録した。", "Cô ấy đăng ký với tư cách tình nguyện viên."],
        ],
        [
          ["Phát biểu với tư cách đại diện.", ["代表として", "発言", "した", "。"], 0],
          ["Trách nhiệm với tư cách bác sĩ.", ["医者としての", "責任を", "果たした", "。"], 0],
          ["Chọn hoa làm quà tặng.", ["プレゼントとして", "花を", "選んだ", "。"], 0],
          ["Tham dự với tư cách quan sát.", ["オブザーバーとして", "参加", "する", "。"], 0],
          ["Làm việc với tư cách biên dịch.", ["翻訳者として", "働いて", "いる", "。"], 0],
          ["Nổi tiếng với tư cách nhạc sĩ.", ["音楽家として", "有名", "だ", "。"], 0],
          ["Ký với tư cách bảo lãnh.", ["保証人として", "署名", "した", "。"], 0],
          ["Phát biểu với tư cách mẹ.", ["母親として", "意見を", "述べた", "。"], 0],
          ["Phản đối với tư cách cá nhân.", ["個人として", "反対", "する", "。"], 0],
          ["Tư vấn với tư cách bạn.", ["友人として", "相談に", "乗った", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l19-g05",
      {
        meaning: "Đối với… / với… thì…",
        structures: [
          "N ＋ にとって",
          "N ＋ にとっては",
        ],
        explanation:
          "にとって đánh giá từ góc nhìn của đối tượng N: quan trọng/khó/có ích đối với ai đó.",
        usage: "Nêu giá trị chủ quan: 私にとって大切だ; 子供にとっては難しい.",
        cautions: [
          "Không dùng cho hành động chủ thể 'làm với tư cách' — khi đó dùng として.",
          "にとっては nhấn mạnh phạm vi đánh giá của N.",
        ],
        contrast: "にとって ≈ đối với…. Khác として (tư cách) và にすれば (nếu đứng ở vị trí…).",
        examples: [
          ex(
            "家族は私にとって大切だ。",
            "かぞくはわたしにとってたいせつだ。",
            "Gia đình đối với tôi rất quan trọng.",
            [
              ["家族", "かぞく"],
              ["は"],
              ["私", "わたし"],
              ["にとって"],
              ["大切", "たいせつ"],
              ["だ。"],
            ],
          ),
          ex(
            "この問題は初心者にとっては難しい。",
            "このもんだいはしょしんしゃにとってはむずかしい。",
            "Bài này đối với người mới thì khó.",
            [
              ["この"],
              ["問題", "もんだい"],
              ["は"],
              ["初心者", "しょしんしゃ"],
              ["にとっては"],
              ["難", "むずか"],
              ["しい。"],
            ],
          ),
          ex(
            "お金より時間が彼にとって重要だ。",
            "おかねよりじかんがかれにとってじゅうようだ。",
            "Thời gian đối với anh ấy quan trọng hơn tiền.",
            [
              ["お金", "おかね"],
              ["より"],
              ["時間", "じかん"],
              ["が"],
              ["彼", "かれ"],
              ["にとって"],
              ["重要", "じゅうよう"],
              ["だ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜にとって",
        "Câu dùng にとって／にとっては: đối với… thì…",
        [
          ["Sức khỏe đối với ai cũng quý.", "健康は誰にとっても大切だ。"],
          ["Thất bại đối với tôi là bài học.", "失敗は私にとって教訓だ。"],
          ["Tiếng Nhật đối với cô ấy là công cụ.", "日本語は彼女にとって道具だ。"],
          ["Sự im lặng đối với anh ấy là câu trả lời.", "沈黙は彼にとっては答えだ。"],
          ["Công việc này đối với người mới nặng.", "この仕事は新人にとっては負担だ。"],
          ["Tự do đối với thanh niên rất quý.", "自由は若者にとって貴重だ。"],
          ["Máy tính đối với tôi không thể thiếu.", "パソコンは私にとって不可欠だ。"],
          ["Luật này đối với doanh nghiệp khắt khe.", "この規制は企業にとっては厳しい。"],
          ["Kỷ niệm đối với bà ấy quý giá.", "思い出は彼女にとって宝物だ。"],
          ["Áp lực đối với trẻ nhỏ có hại.", "プレッシャーは子供にとっては有害だ。"],
        ],
        [
          ["この経験は私にとって貴重だ。", "Kinh nghiệm này đối với tôi rất quý."],
          ["安全は乗客にとって最優先だ。", "An toàn đối với hành khách là ưu tiên hàng đầu."],
          ["この町は観光客にとっては便利だ。", "Thị trấn này đối với khách du lịch thì tiện."],
          ["彼の助言は私たちにとって助かる。", "Lời khuyên của anh ấy đối với chúng tôi rất hữu ích."],
          ["騒音は住民にとっては深刻な問題だ。", "Tiếng ồn đối với cư dân là vấn đề nghiêm trọng."],
          ["この薬は患者にとって必要だ。", "Thuốc này đối với bệnh nhân là cần thiết."],
          ["勝敗は選手にとって全てではない。", "Thắng thua đối với vận động viên không phải tất cả."],
          ["プライバシーは現代人にとって重要だ。", "Quyền riêng tư đối với người hiện đại rất quan trọng."],
          ["この規則は外国人にとっては分かりにくい。", "Quy tắc này đối với người nước ngoài khó hiểu."],
          ["自然は子供にとって最高の教室だ。", "Thiên nhiên đối với trẻ em là lớp học tuyệt vời."],
        ],
        [
          ["Gia đình đối với tôi rất quý.", ["家族は", "私にとって", "とても大切", "だ。"], 0],
          ["Bài này với người mới khá khó.", ["この問題は", "初心者にとっては", "難しすぎる", "。"], 0],
          ["Thời gian với anh ấy quan trọng.", ["時間が", "彼にとって", "重要", "だ。"], 0],
          ["Thất bại với tôi là bài học.", ["失敗は", "私にとって", "教訓", "だ。"], 0],
          ["Máy tính với tôi không thiếu.", ["パソコンは", "私にとって", "不可欠", "だ。"], 0],
          ["Việc này với người mới nặng.", ["この仕事は", "新人にとっては", "負担", "だ。"], 0],
          ["Kỷ niệm với cô ấy quý.", ["思い出は", "彼女にとって", "宝物", "だ。"], 0],
          ["An toàn với hành khách ưu tiên.", ["安全は", "乗客にとって", "最優先", "だ。"], 0],
          ["Thuốc này với bệnh nhân cần.", ["この薬は", "患者にとって", "必要", "だ。"], 0],
          ["Quyền riêng tư rất quan trọng.", ["プライバシーは", "現代人にとって", "重要", "だ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l19-g06",
      {
        meaning: "Nếu đứng ở vị trí… / xét từ phía… / ngay cả với…",
        structures: [
          "N ＋ にしたら／にすれば／にしてみれば",
          "N ＋ にしても",
        ],
        explanation:
          "にしたら・にすれば・にしてみれば: đánh giá từ lập trường của N. にしても: ngay cả xét từ phía N / dù là N thì cũng…",
        usage: "Thấu hiểu góc nhìn: 親にしたら心配だ; 彼にしても無理はない.",
        cautions: [
          "にしたら／にすれば／にしてみれば gần nghĩa; chọn theo thói quen.",
          "にしても cũng có nghĩa 'dù… đi nữa' ở bài khác — ở đây chủ yếu góc nhìn/đánh giá.",
        ],
        contrast:
          "にしたら ≈ nếu đứng ở vị trí…. にしても ≈ ngay cả với…. Khác にとって (đối với, ít 'đứng vào vị trí').",
        examples: [
          ex(
            "親にしたら心配な話だ。",
            "おやにしたらしんぱいなはなしだ。",
            "Nếu đứng ở vị trí bố mẹ thì đây là chuyện đáng lo.",
            [
              ["親", "おや"],
              ["にしたら"],
              ["心配", "しんぱい"],
              ["な"],
              ["話", "はなし"],
              ["だ。"],
            ],
          ),
          ex(
            "彼にしてみれば当然の要求だ。",
            "かれにしてみればとうぜんのようきゅうだ。",
            "Xét từ phía anh ấy thì đây là yêu cầu đương nhiên.",
            [
              ["彼", "かれ"],
              ["にしてみれば"],
              ["当然", "とうぜん"],
              ["の"],
              ["要求", "ようきゅう"],
              ["だ。"],
            ],
          ),
          ex(
            "私にしても納得できない。",
            "わたしにしてもなっとくできない。",
            "Ngay cả với tôi cũng không thể tâm phục.",
            [
              ["私", "わたし"],
              ["にしても"],
              ["納得", "なっとく"],
              ["できない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜にしたら／にしても",
        "Câu dùng にしたら／にすれば／にしてみれば／にしても: từ góc nhìn / ngay cả với…",
        [
          ["Nếu đứng ở vị trí học sinh thì bài khó.", "生徒にしたら難しい問題だ。"],
          ["Xét từ phía khách thì giá cao.", "客にすれば値段が高い。"],
          ["Từ phía nhân viên thì giờ làm dài.", "社員にしてみれば勤務時間が長い。"],
          ["Ngay cả với chuyên gia cũng khó.", "専門家にしても難しい。"],
          ["Nếu đứng ở vị trí nạn nhân thì tức.", "被害者にしたら腹立たしい。"],
          ["Xét từ phía công ty thì hợp lý.", "会社にすれば妥当な判断だ。"],
          ["Từ phía trẻ em thì quy tắc khó.", "子供にしてみればルールが厳しい。"],
          ["Ngay cả với tôi cũng bất ngờ.", "私にしても意外だった。"],
          ["Nếu đứng ở vị trí hàng xóm thì ồn.", "近所の人にしたらうるさい。"],
          ["Xét từ phía người mua thì rủi ro.", "買い手にすればリスクがある。"],
        ],
        [
          ["初心者にしたら説明が足りない。", "Nếu đứng ở vị trí người mới thì giải thích còn thiếu."],
          ["利用者にすれば手続きが複雑だ。", "Xét từ phía người dùng thì thủ tục phức tạp."],
          ["選手にしてみれば厳しい日程だ。", "Từ phía vận động viên thì lịch trình khắc nghiệt."],
          ["親にしても賛成しかねる。", "Ngay cả bố mẹ cũng khó lòng tán thành."],
          ["店員にしたら理不尽な客だ。", "Nếu đứng ở vị trí nhân viên thì khách vô lý."],
          ["市民にすれば透明性が必要だ。", "Xét từ phía người dân thì cần minh bạch."],
          ["患者にしてみれば待ち時間が長い。", "Từ phía bệnh nhân thì thời gian chờ dài."],
          ["彼にしても断りにくかっただろう。", "Ngay cả với anh ấy chắc cũng khó từ chối."],
          ["外国人にしたら案内が不足だ。", "Nếu đứng ở vị trí người nước ngoài thì hướng dẫn thiếu."],
          ["投資家にすれば魅力的な案件だ。", "Xét từ phía nhà đầu tư thì vụ này hấp dẫn."],
        ],
        [
          ["Bố mẹ thì rất đáng lo.", ["親にしたら", "大いに", "心配だ", "。"], 0],
          ["Từ phía anh ấy cũng hợp lý.", ["彼にしてみれば", "妥当な", "要求だ", "。"], 0],
          ["Ngay cả tôi cũng khó phục.", ["私にしても", "納得し", "にくい", "。"], 0],
          ["Học sinh thì bài khó.", ["生徒にしたら", "難しい", "問題だ", "。"], 0],
          ["Khách thì giá cao.", ["客にすれば", "値段が", "高い", "。"], 0],
          ["Nhân viên thì giờ dài.", ["社員にしてみれば", "勤務時間が", "長い", "。"], 0],
          ["Chuyên gia cũng khó.", ["専門家にしても", "難し", "い", "。"], 0],
          ["Công ty thì hợp lý.", ["会社にすれば", "妥当な", "判断だ", "。"], 0],
          ["Tôi cũng bất ngờ.", ["私にしても", "意外", "だった", "。"], 0],
          ["Người mua thì rủi ro.", ["買い手にすれば", "リスクが", "ある", "。"], 0],
        ],
      ),
    ),
  ];
}
