import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L21-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 23, BATCH);

export function lesson23Patterns(byId) {
  return [
    P(
      byId,
      "l23-g01",
      {
        meaning: "Vốn là… / lẽ thường là… / thật là… (cảm thán, bản chất)",
        structures: [
          "普通形 ＋ ものだ／もんだ",
          "いAい ＋ ものだ",
          "なAな ＋ ものだ",
        ],
        explanation:
          "ものだ nêu bản chất/lẽ thường của sự việc, hoặc cảm thán mạnh (ngạc nhiên, xúc động) trước sự thật; khẩu ngữ thường thành もんだ.",
        usage: "Nhận định chung: người ta vốn…; cảm thán: thời gian trôi thật nhanh.",
        cautions: [
          "Khác nghĩa khuyên bảo ものだ／ものではない ở bài 24 (nên/không nên).",
          "もんだ thân mật hơn; văn viết thường giữ ものだ.",
        ],
        contrast:
          "ものだ (bài 23) ≈ vốn/lẽ thường/cảm thán. Khác というものだ (định nghĩa ‘đúng là…’) và べきだ (nghĩa vụ).",
        examples: [
          ex(
            "人の心は変わりやすいものだ。",
            "ひとのこころはかわりやすいものだ。",
            "Lòng người vốn dễ thay đổi.",
            [
              ["人", "ひと"],
              ["の"],
              ["心", "こころ"],
              ["は"],
              ["変", "か"],
              ["わりやすいものだ。"],
            ],
          ),
          ex(
            "子供の成長は早いものだ。",
            "こどものせいちょうははやいものだ。",
            "Trẻ con lớn lên thật nhanh.",
            [
              ["子供", "こども"],
              ["の"],
              ["成長", "せいちょう"],
              ["は"],
              ["早", "はや"],
              ["いものだ。"],
            ],
          ),
          ex(
            "若い頃はよく徹夜したものだ。",
            "わかいころはよくてつやしたものだ。",
            "Hồi trẻ tôi từng thức trắng đêm nhiều.",
            [
              ["若", "わか"],
              ["い"],
              ["頃", "ころ"],
              ["はよく"],
              ["徹夜", "てつや"],
              ["したものだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ものだ",
        "Câu nhận định/cảm thán: 普通形＋ものだ — vốn là / thật là…",
        [
          ["Tiền bạc vốn dễ hết.", "お金はすぐになくなるものだ。"],
          ["Thời gian trôi thật nhanh.", "時間が経つのは早いものだ。"],
          ["Người ta dễ quên ơn cũ.", "人は恩を忘れやすいものだ。"],
          ["Càng lớn càng nhớ quê.", "年を取るほど故郷が恋しいものだ。"],
          ["Công việc mới vốn mệt.", "新しい仕事は疲れるものだ。"],
          ["Hồi học hay đọc sách đêm.", "学生の頃は夜遅くまで本を読んだものだ。"],
          ["Mưa mùa này vốn bất ngờ.", "この季節の雨は突然降るものだ。"],
          ["Trẻ con vốn thích hỏi.", "子供は何でも聞きたがるものだ。"],
          ["Thất bại vốn dạy người ta.", "失敗は人を成長させるものだ。"],
          ["Nghe nhạc cũ thấy xúc động.", "昔の曲を聞くと懐かしいものだ。"],
        ],
        [
          ["習慣は簡単には変わらないものだ。", "Thói quen vốn không dễ đổi."],
          ["約束は守るべきものだと分かる。", "Tôi hiểu lời hứa vốn phải giữ."],
          ["一人暮らしは寂しいものだ。", "Sống một mình vốn cô đơn."],
          ["成功の裏には努力があるものだ。", "Sau thành công vốn có nỗ lực."],
          ["言葉は時に人を傷つけるものだ。", "Lời nói đôi khi vốn làm tổn thương."],
          ["若い頃は無茶をしたものだ。", "Hồi trẻ từng làm liều."],
          ["季節の変わり目は体調を崩しやすいものだ。", "Giao mùa vốn dễ ốm."],
          ["親の気持ちは後から分かるものだ。", "Lòng cha mẹ vốn hiểu muộn."],
          ["初めての挑戦は不安なものだ。", "Thử lần đầu vốn bất an."],
          ["美しい景色は心を穏やかにするものだ。", "Cảnh đẹp vốn làm lòng dịu lại."],
        ],
        [
          ["Lòng người vốn dễ đổi.", ["人の心は", "変わりやすい", "もの", "だ。"], 0],
          ["Trẻ lớn lên thật nhanh.", ["子供の成長は", "早い", "もの", "だ。"], 0],
          ["Hồi trẻ hay thức trắng.", ["若い頃はよく", "徹夜した", "もの", "だ。"], 0],
          ["Tiền vốn mau hết.", ["お金はすぐに", "なくなる", "もの", "だ。"], 0],
          ["Thời gian trôi nhanh.", ["時間が経つのは", "早い", "もの", "だ。"], 0],
          ["Người dễ quên ơn.", ["人は恩を", "忘れやすい", "もの", "だ。"], 0],
          ["Thất bại dạy người.", ["失敗は人を", "成長させる", "もの", "だ。"], 0],
          ["Sống một mình cô đơn.", ["一人暮らしは", "寂しい", "もの", "だ。"], 0],
          ["Giao mùa dễ ốm.", ["季節の変わり目は", "体調を崩しやすい", "もの", "だ。"], 0],
          ["Thử lần đầu bất an.", ["初めての挑戦は", "不安な", "もの", "だ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l23-g02",
      {
        meaning: "Đúng là… / thế mới gọi là… / thật sự là…",
        structures: ["普通形 ＋ というものだ", "N ＋ というものだ"],
        explanation:
          "というものだ khẳng định đánh giá: đó mới đúng là bản chất/định nghĩa của việc đó, thường mang sắc thái khen hoặc nhấn mạnh.",
        usage: "Kết luận nhận định: giúp người khác mới đúng là bạn; đó mới gọi là trách nhiệm.",
        cautions: [
          "Khác ものだ cảm thán chung; というものだ nhấn ‘định nghĩa/đúng nghĩa là…’.",
          "Thường ở cuối câu nhận định chắc chắn, ít dùng hỏi.",
        ],
        contrast:
          "というものだ ≈ đúng là / thế mới gọi là. Khác にほかならない (chính là, không gì khác) và にすぎない (chỉ là).",
        examples: [
          ex(
            "困った時こそ助け合うというのが友情というものだ。",
            "こまったときこそたすけあうというのがゆうじょうというものだ。",
            "Lúc khó khăn mới giúp nhau — đó mới gọi là tình bạn.",
            [
              ["困", "こま"],
              ["った"],
              ["時", "とき"],
              ["こそ"],
              ["助", "たす"],
              ["け合うというのが"],
              ["友情", "ゆうじょう"],
              ["というものだ。"],
            ],
          ),
          ex(
            "約束を守るというのが社会人というものだ。",
            "やくそくをまもるというのがしゃかいじんというものだ。",
            "Giữ lời hứa — đó mới đúng là người đi làm.",
            [
              ["約束", "やくそく"],
              ["を"],
              ["守", "まも"],
              ["るというのが"],
              ["社会人", "しゃかいじん"],
              ["というものだ。"],
            ],
          ),
          ex(
            "努力が報われるというのは喜びというものだ。",
            "どりょくがむくわれるというのはよろこびというものだ。",
            "Nỗ lực được đền đáp — đó mới là niềm vui.",
            [
              ["努力", "どりょく"],
              ["が"],
              ["報", "むく"],
              ["われるというのは"],
              ["喜", "よろこ"],
              ["びというものだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜というものだ",
        "Câu khẳng định định nghĩa: 〜というものだ — đúng là / thế mới gọi là…",
        [
          ["Biết xin lỗi mới đúng là trưởng thành.", "過ちを認めるというのが大人というものだ。"],
          ["Chia sẻ khó khăn mới là đồng đội.", "苦楽を共にするというのが仲間というものだ。"],
          ["Giữ bí mật mới đúng là tin cậy.", "秘密を守るというのが信頼というものだ。"],
          ["Lắng nghe ý kiến mới là lãnh đạo.", "部下の声を聞くというのが上司というものだ。"],
          ["Hoàn thành đúng hạn mới là trách nhiệm.", "期限を守るというのが責任というものだ。"],
          ["Giúp người yếu mới là lòng tốt.", "弱い人を助けるというのが優しさというものだ。"],
          ["Học từ thất bại mới là tiến bộ.", "失敗から学ぶというのが成長というものだ。"],
          ["Nói thật dù khó mới là thành thật.", "言いづらいことも話すというのが正直というものだ。"],
          ["Tôn trọng khác biệt mới là khoan dung.", "違いを認めるというのが寛容というものだ。"],
          ["Chuẩn bị kỹ mới là chuyên nghiệp.", "準備を怠らないというのがプロというものだ。"],
        ],
        [
          ["感謝を伝えるというのが礼儀というものだ。", "Bày tỏ biết ơn — đó mới là lễ độ."],
          ["相手の立場で考えるというのが思いやりというものだ。", "Nghĩ theo phía đối phương — đó mới là quan tâm."],
          ["約束の時間に来るというのが常識というものだ。", "Đến đúng giờ hẹn — đó mới là lẽ thường."],
          ["最後まで諦めないというのが根性というものだ。", "Không bỏ cuộc đến cùng — đó mới là bản lĩnh."],
          ["公平に扱うというのが正義というものだ。", "Đối xử công bằng — đó mới là công lý."],
          ["自分の言葉に責任を持つというのが誠実というものだ。", "Chịu trách nhiệm lời mình — đó mới là chân thành."],
          ["困っている人に手を貸すというのが親切というものだ。", "Đưa tay giúp người khó — đó mới là tốt bụng."],
          ["事実に基づいて話すというのが誠実さというものだ。", "Nói dựa trên sự thật — đó mới là thành thật."],
          ["チームのために動くというのが協力というものだ。", "Hành động vì đội — đó mới là hợp tác."],
          ["小さな改善を重ねるというのが工夫というものだ。", "Gom cải tiến nhỏ — đó mới là sáng tạo."],
        ],
        [
          ["Giúp nhau lúc khó mới là bạn.", ["助け合うというのが", "友情", "というもの", "だ。"], 0],
          ["Giữ lời mới là người đi làm.", ["約束を守るというのが", "社会人", "というもの", "だ。"], 0],
          ["Nỗ lực được đền là vui.", ["努力が報われるというのは", "喜び", "というもの", "だ。"], 0],
          ["Xin lỗi mới là trưởng thành.", ["過ちを認めるというのが", "大人", "というもの", "だ。"], 0],
          ["Giữ bí mật mới là tin cậy.", ["秘密を守るというのが", "信頼", "というもの", "だ。"], 0],
          ["Đúng hạn mới là trách nhiệm.", ["期限を守るというのが", "責任", "というもの", "だ。"], 0],
          ["Học từ sai mới là tiến bộ.", ["失敗から学ぶというのが", "成長", "というもの", "だ。"], 0],
          ["Bày tỏ ơn mới là lễ độ.", ["感謝を伝えるというのが", "礼儀", "というもの", "だ。"], 0],
          ["Đến đúng giờ mới là lẽ thường.", ["約束の時間に来るというのが", "常識", "というもの", "だ。"], 0],
          ["Không bỏ cuộc mới là bản lĩnh.", ["最後まで諦めないというのが", "根性", "というもの", "だ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l23-g03",
      {
        meaning: "Chỉ là… / chẳng qua là… (không hơn thế)",
        structures: [
          "N ＋ にすぎない",
          "普通形 ＋ にすぎない",
          "N ＋ に過ぎない",
        ],
        explanation:
          "にすぎない／に過ぎない hạ thấp mức độ: chỉ là A thôi, không đáng kể hoặc không phải điều lớn lao hơn.",
        usage: "Khiêm tốn hoặc phủ định phóng đại: đó chỉ là ý kiến cá nhân; chỉ là sơ suất nhỏ.",
        cautions: [
          "すぎない và 過ぎない cùng nghĩa; kanji 過ぎ thường trong văn viết.",
          "Khác だけ (chỉ) ở chỗ nhấn ‘không hơn mức đó / đánh giá thấp’.",
        ],
        contrast:
          "にすぎない ≈ chỉ là / chẳng qua. Đối lập にほかならない (chính là, không gì khác).",
        examples: [
          ex(
            "これは私の個人的な意見にすぎない。",
            "これはわたしのこじんてきないけんにすぎない。",
            "Đây chỉ là ý kiến cá nhân của tôi.",
            [
              ["これは"],
              ["私", "わたし"],
              ["の"],
              ["個人的", "こじんてき"],
              ["な"],
              ["意見", "いけん"],
              ["にすぎない。"],
            ],
          ),
          ex(
            "彼はまだ新人にすぎない。",
            "かれはまだしんじんにすぎない。",
            "Anh ấy vẫn chỉ là người mới.",
            [
              ["彼", "かれ"],
              ["はまだ"],
              ["新人", "しんじん"],
              ["にすぎない。"],
            ],
          ),
          ex(
            "今回のミスは不注意にすぎない。",
            "こんかいのみすはふちゅういにすぎない。",
            "Lỗi lần này chẳng qua là bất cẩn.",
            [
              ["今回", "こんかい"],
              ["のミスは"],
              ["不注意", "ふちゅうい"],
              ["にすぎない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜にすぎない",
        "Câu hạ thấp mức độ: N／普通形＋にすぎない — chỉ là / chẳng qua…",
        [
          ["Đó chỉ là tin đồn thôi.", "それは噂にすぎない。"],
          ["Tôi chỉ là sinh viên thôi.", "私は学生にすぎない。"],
          ["Số tiền đó chỉ là tạm ứng.", "その金額は前払いにすぎない。"],
          ["Đây chỉ là bản nháp.", "これは下書きにすぎない。"],
          ["Anh ấy chỉ là khách mời.", "彼は来賓にすぎない。"],
          ["Đó chỉ là hiểu nhầm nhỏ.", "それは小さな誤解にすぎない。"],
          ["Tôi chỉ biết sơ thôi.", "私は少し知っているにすぎない。"],
          ["Thành công đó chỉ là may mắn.", "その成功は幸運にすぎない。"],
          ["Đây chỉ là bước đầu.", "これは第一歩にすぎない。"],
          ["Lời khen đó chỉ là xã giao.", "その褒め言葉は社交辞令にすぎない。"],
        ],
        [
          ["彼の説明は言い訳にすぎない。", "Lời giải thích của anh chỉ là biện hộ."],
          ["今回の結果は偶然にすぎない。", "Kết quả lần này chẳng qua là tình cờ."],
          ["私にできるのは手伝うことにすぎない。", "Tôi chỉ có thể giúp một chút thôi."],
          ["その計画は机上の空論にすぎない。", "Kế hoạch đó chỉ là lý thuyết suông."],
          ["彼は形式上の責任者にすぎない。", "Anh ấy chỉ là người chịu trách nhiệm trên danh nghĩa."],
          ["この症状は風邪の初期にすぎない。", "Triệu chứng này chỉ là giai đoạn đầu của cảm."],
          ["私の役割は連絡係にすぎない。", "Vai trò của tôi chỉ là người liên lạc."],
          ["その差は誤差にすぎない。", "Chênh lệch đó chỉ là sai số."],
          ["彼の反対は感情的なものにすぎない。", "Phản đối của anh chỉ là cảm tính."],
          ["今の蓄えはわずかなお金にすぎない。", "Tiền tiết kiệm hiện chỉ là số nhỏ."],
        ],
        [
          ["Đây chỉ là ý kiến cá nhân.", ["これは私の", "個人的な意見に", "すぎない", "。"], 0],
          ["Anh ấy vẫn chỉ là người mới.", ["彼はまだ", "新人に", "すぎない", "。"], 0],
          ["Lỗi lần này chỉ bất cẩn.", ["今回のミスは", "不注意に", "すぎない", "。"], 0],
          ["Đó chỉ là tin đồn.", ["それは", "噂に", "すぎない", "。"], 0],
          ["Tôi chỉ là sinh viên.", ["私は", "学生に", "すぎない", "。"], 0],
          ["Đây chỉ là bản thảo thôi.", ["これは", "下書きに", "すぎない", "。"], 0],
          ["Thành công chỉ là may.", ["その成功は", "幸運に", "すぎない", "。"], 0],
          ["Đây mới chỉ là khởi đầu.", ["これは", "第一歩に", "すぎない", "。"], 0],
          ["Kết quả chỉ tình cờ.", ["今回の結果は", "偶然に", "すぎない", "。"], 0],
          ["Chênh lệch chỉ sai số.", ["その差は", "誤差に", "すぎない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l23-g04",
      {
        meaning: "Chính là… / không gì khác ngoài…",
        structures: ["N ＋ にほかならない", "普通形の名詞化 ＋ にほかならない"],
        explanation:
          "にほかならない khẳng định chắc chắn: A chính là B, không phải thứ gì khác — thường kết luận nguyên nhân hoặc bản chất.",
        usage: "Kết luận mạnh: thành công chính là nhờ nỗ lực; đó chính là sự thật.",
        cautions: [
          "Giọng trang trọng/khẳng định; ít dùng khẩu ngữ thân mật.",
          "Đối lập rõ với にすぎない (hạ thấp).",
        ],
        contrast:
          "にほかならない ≈ chính là / không gì khác. Khác というものだ (định nghĩa đánh giá) và にすぎない.",
        examples: [
          ex(
            "彼の成功は日々の努力の結果にほかならない。",
            "かれのせいこうはひびのどりょくのけっかにほかならない。",
            "Thành công của anh ấy chính là kết quả nỗ lực hằng ngày.",
            [
              ["彼", "かれ"],
              ["の"],
              ["成功", "せいこう"],
              ["は"],
              ["日々", "ひび"],
              ["の"],
              ["努力", "どりょく"],
              ["の"],
              ["結果", "けっか"],
              ["にほかならない。"],
            ],
          ),
          ex(
            "今回の事故は不注意にほかならない。",
            "こんかいのじこはふちゅういにほかならない。",
            "Tai nạn lần này chính là do bất cẩn.",
            [
              ["今回", "こんかい"],
              ["の"],
              ["事故", "じこ"],
              ["は"],
              ["不注意", "ふちゅうい"],
              ["にほかならない。"],
            ],
          ),
          ex(
            "それは愛の表現にほかならない。",
            "それはあいのひょうげんにほかならない。",
            "Đó chính là cách thể hiện tình yêu.",
            [
              ["それは"],
              ["愛", "あい"],
              ["の"],
              ["表現", "ひょうげん"],
              ["にほかならない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜にほかならない",
        "Câu khẳng định bản chất: N＋にほかならない — chính là / không gì khác…",
        [
          ["Thất bại đó chính là bài học.", "その失敗は貴重な教訓にほかならない。"],
          ["Lời cảm ơn chính là phép lịch sự.", "お礼の言葉は基本的な礼儀にほかならない。"],
          ["Sự chậm trễ chính là thiếu chuẩn bị.", "その遅れは準備不足にほかならない。"],
          ["Niềm vui này chính là nhờ mọi người.", "この喜びは皆の支えにほかならない。"],
          ["Phản ứng đó chính là sợ hãi.", "その反応は恐怖にほかならない。"],
          ["Quyết định đó chính là trách nhiệm.", "その決断は責任の表れにほかならない。"],
          ["Im lặng đó chính là đồng ý.", "その沈黙は同意にほかならない。"],
          ["Sự khác biệt chính là điểm mạnh.", "その違いは強みにほかならない。"],
          ["Kết quả xấu chính do chủ quan.", "悪い結果は慢心にほかならない。"],
          ["Giúp đỡ đó chính là tình bạn.", "その援助は友情の証にほかならない。"],
        ],
        [
          ["彼の発言は警告にほかならない。", "Lời anh ấy chính là lời cảnh báo."],
          ["今回の勝利はチームワークにほかならない。", "Chiến thắng lần này chính là nhờ tinh thần đồng đội."],
          ["その笑顔は安心の印にほかならない。", "Nụ cười đó chính là dấu hiệu yên tâm."],
          ["この制度は公平性の確保にほかならない。", "Chế độ này chính là để đảm bảo công bằng."],
          ["彼の怒りは失望にほかならない。", "Cơn giận của anh chính là thất vọng."],
          ["その提案は妥協案にほかならない。", "Đề xuất đó chính là phương án thỏa hiệp."],
          ["今回の改善は地道な点検にほかならない。", "Cải thiện lần này chính nhờ kiểm tra kiên trì."],
          ["その涙は感謝にほかならない。", "Nước mắt đó chính là lòng biết ơn."],
          ["彼の態度は拒絶にほかならない。", "Thái độ anh ấy chính là từ chối."],
          ["この結果は長年の研究にほかならない。", "Kết quả này chính là nhờ nghiên cứu lâu năm."],
        ],
        [
          ["Thành công chính nhờ nỗ lực.", ["彼の成功は", "日々の努力の結果に", "ほかならない", "。"], 0],
          ["Tai nạn chính do bất cẩn.", ["今回の事故は", "不注意に", "ほかならない", "。"], 0],
          ["Đó chính là thể hiện tình yêu.", ["それは愛の", "表現に", "ほかならない", "。"], 0],
          ["Thất bại chính là bài học.", ["その失敗は", "貴重な教訓に", "ほかならない", "。"], 0],
          ["Chậm trễ chính thiếu chuẩn bị.", ["その遅れは", "準備不足に", "ほかならない", "。"], 0],
          ["Im lặng chính là đồng ý.", ["その沈黙は", "同意に", "ほかならない", "。"], 0],
          ["Lời anh chính là cảnh báo.", ["彼の発言は", "警告に", "ほかならない", "。"], 0],
          ["Thắng nhờ tinh thần đồng đội.", ["今回の勝利は", "チームワークに", "ほかならない", "。"], 0],
          ["Nước mắt chính là biết ơn.", ["その涙は", "感謝に", "ほかならない", "。"], 0],
          ["Kết quả nhờ nghiên cứu lâu.", ["この結果は", "長年の研究に", "ほかならない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l23-g05",
      {
        meaning: "Không gì hơn… / tốt nhất là… (càng… càng tốt)",
        structures: [
          "N ＋ に越したことはない",
          "普通形 ＋ に越したことはない",
        ],
        explanation:
          "に越したことはない nói rằng nếu được A thì không gì tốt hơn — khuyến khích mức lý tưởng dù không bắt buộc tuyệt đối.",
        usage: "Lời khuyên mềm: có bảo hiểm thì tốt nhất; chuẩn bị sớm không gì hơn.",
        cautions: [
          "Không khẳng định ‘phải làm’; chỉ nói ‘tốt hơn nếu…’.",
          "Thường kèm điều kiện mong muốn (sức khỏe, an toàn, chuẩn bị).",
        ],
        contrast:
          "に越したことはない ≈ không gì hơn / tốt nhất là. Khác べきだ (nên/phải) và しかない (chỉ còn cách).",
        examples: [
          ex(
            "健康に越したことはない。",
            "けんこうにこしたことはない。",
            "Không gì hơn được sức khỏe.",
            [
              ["健康", "けんこう"],
              ["に越したことはない。"],
            ],
          ),
          ex(
            "早めに準備するに越したことはない。",
            "はやめにじゅんびするにこしたことはない。",
            "Chuẩn bị sớm thì không gì hơn.",
            [
              ["早", "はや"],
              ["めに"],
              ["準備", "じゅんび"],
              ["するに越したことはない。"],
            ],
          ),
          ex(
            "バックアップは多いに越したことはない。",
            "ばっくあっぷはおおいにこしたことはない。",
            "Bản sao lưu thì càng nhiều càng tốt.",
            [
              ["バックアップは"],
              ["多", "おお"],
              ["いに越したことはない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜に越したことはない",
        "Câu khuyên mức lý tưởng: 〜に越したことはない — không gì hơn / tốt nhất…",
        [
          ["Có kinh nghiệm thì tốt nhất.", "経験があるに越したことはない。"],
          ["Mang ô thì không gì hơn.", "傘を持っていくに越したことはない。"],
          ["Xác nhận lại thì tốt hơn.", "再確認するに越したことはない。"],
          ["Ngủ đủ giấc không gì hơn.", "十分な睡眠に越したことはない。"],
          ["Có dư thời gian thì tốt.", "時間に余裕があるに越したことはない。"],
          ["Ghi chú rõ ràng thì tốt nhất.", "メモを詳しく残すに越したことはない。"],
          ["Biết ngoại ngữ thì càng tốt.", "外国語ができるに越したことはない。"],
          ["Đường đi an toàn không gì hơn.", "安全な道を選ぶに越したことはない。"],
          ["Hỏi trước thì tốt hơn.", "事前に尋ねるに越したことはない。"],
          ["Giữ liên lạc thường xuyên thì tốt.", "こまめに連絡するに越したことはない。"],
        ],
        [
          ["保険に入っておくに越したことはない。", "Mua bảo hiểm sẵn thì không gì hơn."],
          ["証拠を残すに越したことはない。", "Giữ bằng chứng thì tốt nhất."],
          ["余裕を持って出発するに越したことはない。", "Xuất phát dư thời gian thì không gì hơn."],
          ["専門家に相談するに越したことはない。", "Hỏi chuyên gia thì tốt hơn."],
          ["定期的に点検するに越したことはない。", "Kiểm tra định kỳ thì không gì hơn."],
          ["パスワードは複雑なものに越したことはない。", "Mật khẩu phức tạp thì tốt nhất."],
          ["説明は丁寧であるに越したことはない。", "Giải thích lịch sự thì không gì hơn."],
          ["予備の電池を持つに越したことはない。", "Mang pin dự phòng thì tốt hơn."],
          ["契約書はよく読むに越したことはない。", "Đọc kỹ hợp đồng thì không gì hơn."],
          ["体調管理はしっかりするに越したことはない。", "Quản lý sức khỏe kỹ thì tốt nhất."],
        ],
        [
          ["Sức khỏe không gì hơn.", ["健康に", "越したことは", "ない", "。"], 0],
          ["Chuẩn bị sớm thì tốt nhất.", ["早めに準備するに", "越したことは", "ない", "。"], 0],
          ["Sao lưu càng nhiều càng tốt.", ["バックアップは多いに", "越したことは", "ない", "。"], 0],
          ["Có kinh nghiệm thì tốt.", ["経験があるに", "越したことは", "ない", "。"], 0],
          ["Mang ô thì tốt hơn.", ["傘を持っていくに", "越したことは", "ない", "。"], 0],
          ["Xác nhận lại thì tốt.", ["再確認するに", "越したことは", "ない", "。"], 0],
          ["Ngủ đủ không gì hơn.", ["十分な睡眠に", "越したことは", "ない", "。"], 0],
          ["Mua bảo hiểm sẵn thì tốt.", ["保険に入っておくに", "越したことは", "ない", "。"], 0],
          ["Hỏi chuyên gia thì tốt.", ["専門家に相談するに", "越したことは", "ない", "。"], 0],
          ["Đọc kỹ hợp đồng thì tốt.", ["契約書はよく読むに", "越したことは", "ない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l23-g06",
      {
        meaning: "Chỉ còn cách… / không còn cách nào khác ngoài…",
        structures: [
          "Vる ＋ しかない",
          "Vる ＋ よりほかない",
          "Vる ＋ ほかない",
        ],
        explanation:
          "しかない・よりほかない・ほかない đều nói không còn lựa chọn nào khác ngoài hành động đó; よりほかない hơi trang trọng hơn しかない.",
        usage: "Tình thế buộc phải: hết tiền thì chỉ còn về nhà; không còn cách nào khác ngoài xin lỗi.",
        cautions: [
          "partial-match: TNĐG chủ yếu phủ họ ほかない; vẫn học đủ しかない trong inventory.",
          "Khác だけ (chỉ) — ở đây nhấn ‘bất đắc dĩ / không còn lựa chọn’.",
        ],
        contrast:
          "しかない／よりほかない ≈ chỉ còn cách…. Khác に越したことはない (tốt nhất nếu…) và べきだ (nên).",
        examples: [
          ex(
            "電車が止まったので歩くしかない。",
            "でんしゃがとまったのであるくしかない。",
            "Tàu dừng nên chỉ còn cách đi bộ.",
            [
              ["電車", "でんしゃ"],
              ["が"],
              ["止", "と"],
              ["まったので"],
              ["歩", "ある"],
              ["くしかない。"],
            ],
          ),
          ex(
            "謝るよりほかない。",
            "あやまるよりほかない。",
            "Không còn cách nào khác ngoài xin lỗi.",
            [
              ["謝", "あやま"],
              ["るよりほかない。"],
            ],
          ),
          ex(
            "今は待つほかない。",
            "いまはまつほかない。",
            "Giờ chỉ còn cách chờ.",
            [
              ["今", "いま"],
              ["は"],
              ["待", "ま"],
              ["つほかない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜しかない・〜よりほかない",
        "Câu bất đắc dĩ: Vる＋しかない／よりほかない／ほかない — chỉ còn cách…",
        [
          ["Hết chỗ ngồi nên chỉ còn đứng.", "席がないので立つしかない。"],
          ["Mưa to nên chỉ còn ở nhà.", "大雨なので家にいるしかない。"],
          ["Không còn cách nào ngoài nộp lại.", "出し直すよりほかない。"],
          ["Hỏng máy nên chỉ còn sửa.", "故障したので修理するしかない。"],
          ["Muộn rồi nên chỉ còn chạy.", "遅いので走るしかない。"],
          ["Không hiểu thì chỉ còn hỏi.", "分からないなら尋ねるほかない。"],
          ["Hết tiền mặt nên chỉ còn thẻ.", "現金がないのでカードで払うしかない。"],
          ["Bị từ chối nên chỉ còn thôi.", "断られたので諦めるよりほかない。"],
          ["Tài liệu thiếu nên chỉ còn bổ sung.", "資料が足りないので追加するしかない。"],
          ["Đường tắc nên chỉ còn đợi.", "渋滞なので待つほかない。"],
        ],
        [
          ["証拠がない以上、信じるしかない。", "Đã không có bằng chứng thì chỉ còn tin."],
          ["期限が近いので急ぐよりほかない。", "Sát hạn nên không còn cách nào ngoài gấp."],
          ["助けが来ないので自分でやるしかない。", "Không có ai giúp nên chỉ còn tự làm."],
          ["雨が止まないので延期するほかない。", "Mưa không tạnh nên chỉ còn hoãn."],
          ["予算が足りないので縮小するしかない。", "Thiếu ngân sách nên chỉ còn thu hẹp."],
          ["相手が謝らないなら訴えるよりほかない。", "Đối phương không xin lỗi thì chỉ còn kiện."],
          ["鍵を忘れたので戻るしかない。", "Quên chìa nên chỉ còn quay lại."],
          ["説明しても無駄なので黙るほかない。", "Giải thích cũng vô ích nên chỉ còn im."],
          ["在庫が切れたので別店へ行くしかない。", "Hết hàng nên chỉ còn sang quán khác."],
          ["体調が悪いので休むよりほかない。", "Sức khỏe kém nên không còn cách nào ngoài nghỉ."],
        ],
        [
          ["Tàu dừng chỉ còn đi bộ.", ["電車が止まったので", "歩く", "しかない", "。"], 0],
          ["Chỉ còn cách xin lỗi.", ["謝る", "よりほか", "ない", "。"], 0],
          ["Giờ chỉ còn chờ thôi.", ["今は", "待つ", "ほかない", "。"], 0],
          ["Hết chỗ chỉ còn đứng.", ["席がないので", "立つ", "しかない", "。"], 0],
          ["Mưa to chỉ còn ở nhà.", ["大雨なので", "家にいる", "しかない", "。"], 0],
          ["Chỉ còn nộp lại.", ["出し直す", "よりほか", "ない", "。"], 0],
          ["Hỏng máy chỉ còn sửa.", ["故障したので", "修理する", "しかない", "。"], 0],
          ["Sát hạn chỉ còn gấp.", ["期限が近いので", "急ぐ", "よりほかない", "。"], 0],
          ["Quên chìa chỉ còn quay.", ["鍵を忘れたので", "戻る", "しかない", "。"], 0],
          ["Ốm thì chỉ còn nghỉ.", ["体調が悪いので", "休む", "よりほかない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l23-g07",
      {
        meaning: "Nên… / không nên… (nghĩa vụ, đánh giá đúng sai)",
        structures: [
          "Vる ＋ べきだ",
          "Vる ＋ べきではない",
          "する → すべきだ／するべきだ",
        ],
        explanation:
          "べきだ nêu việc nên làm theo lẽ phải/nghĩa vụ; べきではない phủ định — không nên làm. Với する thường gặp すべきだ.",
        usage: "Khuyên bảo hoặc nhận định đạo đức/xã hội: nên nói thật; không nên nói dối.",
        cautions: [
          "Mạnh hơn たほうがいい; mang sắc ‘đúng/sai’ rõ.",
          "Khác ものだ／ことだ khuyên theo tập quán (bài 24).",
        ],
        contrast:
          "べきだ ≈ nên/phải (lẽ phải). Khác しかない (bất đắc dĩ) và に越したことはない (tốt nhất nếu).",
        examples: [
          ex(
            "約束は守るべきだ。",
            "やくそくはまもるべきだ。",
            "Lời hứa thì nên giữ.",
            [
              ["約束", "やくそく"],
              ["は"],
              ["守", "まも"],
              ["るべきだ。"],
            ],
          ),
          ex(
            "他人のプライバシーを侵害すべきではない。",
            "たにんのぷらいばしーをしんがいすべきではない。",
            "Không nên xâm phạm quyền riêng tư của người khác.",
            [
              ["他人", "たにん"],
              ["のプライバシーを"],
              ["侵害", "しんがい"],
              ["すべきではない。"],
            ],
          ),
          ex(
            "困っている人を助けるべきだ。",
            "こまっているひとをたすけるべきだ。",
            "Nên giúp người đang gặp khó.",
            [
              ["困", "こま"],
              ["っている"],
              ["人", "ひと"],
              ["を"],
              ["助", "たす"],
              ["けるべきだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜べきだ／〜べきではない",
        "Câu nghĩa vụ: Vる＋べきだ／べきではない — nên / không nên…",
        [
          ["Nên đọc kỹ hợp đồng.", "契約書はよく読むべきだ。"],
          ["Không nên nói dối khách hàng.", "顧客に嘘をつくべきではない。"],
          ["Nên cảm ơn người đã giúp.", "助けてくれた人に礼を言うべきだ。"],
          ["Không nên bỏ mặc đồng đội.", "仲間を見捨てるべきではない。"],
          ["Nên nộp báo cáo đúng hạn.", "報告書は期限内に提出すべきだ。"],
          ["Không nên cười nhạo lỗi người khác.", "他人の失敗を笑うべきではない。"],
          ["Nên xin phép trước khi dùng.", "使う前に許可を取るべきだ。"],
          ["Không nên chia sẻ mật khẩu.", "パスワードを共有すべきではない。"],
          ["Nên lắng nghe ý kiến phản biện.", "反対意見にも耳を傾けるべきだ。"],
          ["Không nên đánh giá vội vàng.", "慌てて判断すべきではない。"],
        ],
        [
          ["事実は正直に伝えるべきだ。", "Sự thật thì nên nói thẳng."],
          ["公共の場で大声を出すべきではない。", "Không nên nói lớn ở nơi công cộng."],
          ["困ったときは相談すべきだ。", "Khi khó khăn thì nên bàn bạc."],
          ["約束の時間に遅れるべきではない。", "Không nên đến muộn giờ hẹn."],
          ["環境に配慮した行動を取るべきだ。", "Nên hành động quan tâm môi trường."],
          ["個人情報を勝手に公開すべきではない。", "Không nên tự ý công khai thông tin cá nhân."],
          ["ミスはすぐに報告すべきだ。", "Lỗi thì nên báo cáo ngay."],
          ["根拠のない噂を広めるべきではない。", "Không nên loan tin đồn vô căn cứ."],
          ["後輩には丁寧に教えるべきだ。", "Nên dạy hậu bối một cách lịch sự."],
          ["感情だけで決定すべきではない。", "Không nên quyết chỉ vì cảm xúc."],
        ],
        [
          ["Lời hứa thì nên giữ.", ["約束は", "守る", "べき", "だ。"], 0],
          ["Không nên xâm phạm riêng tư.", ["プライバシーを", "侵害すべき", "ではない", "。"], 0],
          ["Nên giúp người gặp khó.", ["困っている人を", "助ける", "べき", "だ。"], 0],
          ["Hợp đồng thì phải đọc kỹ.", ["契約書はよく", "読む", "べき", "だ。"], 0],
          ["Không nên nói dối khách.", ["顧客に嘘を", "つくべき", "ではない", "。"], 0],
          ["Nên cảm ơn người giúp.", ["助けてくれた人に", "礼を言う", "べき", "だ。"], 0],
          ["Báo cáo phải nộp đúng hạn.", ["報告書は", "期限内に", "提出す", "べきだ。"], 0],
          ["Mật khẩu không được chia sẻ.", ["パスワードを", "共有すべき", "ではない", "。"], 0],
          ["Sự thật nên nói thẳng.", ["事実は正直に", "伝える", "べき", "だ。"], 0],
          ["Lỗi thì nên báo ngay.", ["ミスは", "すぐに", "報告す", "べきだ。"], 0],
        ],
      ),
    ),
  ];
}
