import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L16-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 17, BATCH);

export function lesson17Patterns(byId) {
  return [
    P(
      byId,
      "l17-g01",
      {
        meaning: "Vả lại… / vì (đã)… nên… (thêm lý do để quyết định)",
        structures: ["普通形 ＋ ことだし"],
        explanation:
          "ことだし nêu một lý do (thường thêm vào các lý do khác) để dẫn đến đề xuất hoặc quyết định tự nhiên.",
        usage: "Đề xuất hành động: trời lạnh, vả lại muộn rồi nên về đi…",
        cautions: [
          "Thường kèm kết luận kiểu đề xuất/khuyên (〜たらどう／〜しよう).",
          "Không dùng như から đơn thuần cho mọi lý do trang trọng.",
        ],
        contrast:
          "ことだし ≈ vả lại/vì thế nên…. Khác し (liệt kê) ở chỗ nghiêng về lý do quyết định.",
        examples: [
          ex(
            "疲れたことだし、今日は早く寝よう。",
            "つかれたことだし、きょうははやくねよう。",
            "Vả lại mệt rồi, hôm nay ngủ sớm thôi.",
            [
              ["疲", "つか"],
              ["れたことだし、"],
              ["今日", "きょう"],
              ["は"],
              ["早", "はや"],
              ["く"],
              ["寝", "ね"],
              ["よう。"],
            ],
          ),
          ex(
            "雨も降ってきたことだし、帰ろうか。",
            "あめもふってきたことだし、かえろうか。",
            "Vả lại mưa cũng bắt đầu rồi, về thôi nhé?",
            [
              ["雨", "あめ"],
              ["も"],
              ["降", "ふ"],
              ["ってきたことだし、"],
              ["帰", "かえ"],
              ["ろうか。"],
            ],
          ),
          ex(
            "明日は休みのことだし、夜更かししてもいい。",
            "あしたはやすみのことだし、よふかししてもいい。",
            "Mai đã nghỉ rồi, thức khuya cũng được.",
            [
              ["明日", "あした"],
              ["は"],
              ["休", "やす"],
              ["みのことだし、"],
              ["夜更かし", "よふかし"],
              ["してもいい。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ことだし",
        "Câu thêm lý do để quyết định/đề xuất: ことだし.",
        [
          ["Vả lại lạnh rồi, vào quán đi.", "寒いことだし、店に入ろう。"],
          ["Vả lại hết việc rồi, về sớm được.", "仕事が終わったことだし、早退していい。"],
          ["Vả lại cuối tuần rồi, đi chơi thôi.", "週末のことだし、遊びに行こう。"],
          ["Vả lại tối rồi, mai bàn tiếp.", "遅いことだし、続きは明日にしよう。"],
          ["Vả lại anh ấy bận, nhờ người khác.", "彼が忙しいことだし、別の人に頼もう。"],
          ["Vả lại điểm tốt rồi, nghỉ ngơi đi.", "成績が良いことだし、少し休もう。"],
          ["Vả lại trời quang, phơi đồ đi.", "晴れたことだし、洗濯ものを干そう。"],
          ["Vả lại còn thời gian, kiểm tra lại.", "時間があることだし、もう一度確認しよう。"],
          ["Vả lại đông quá, đổi chỗ đi.", "混んでいることだし、別の店にしよう。"],
          ["Vả lại mệt rồi, taxi về thôi.", "疲れたことだし、タクシーで帰ろう。"],
        ],
        [
          ["静かになったことだし、勉強を始めよう。", "Vả lại yên rồi, bắt đầu học thôi."],
          ["お金が貯まったことだし、旅行しよう。", "Vả lại có tiền rồi, đi du lịch thôi."],
          ["準備も整ったことだし、出発しよう。", "Vả lại chuẩn bị xong, xuất phát thôi."],
          ["子どもも寝たことだし、映画を見よう。", "Vả lại con ngủ rồi, xem phim thôi."],
          ["期限も近いことだし、急ごう。", "Vả lại sát hạn rồi, nhanh lên."],
          ["天気も悪いことだし、外出はやめよう。", "Vả lại thời tiết xấu, thôi đừng ra ngoài."],
          ["約束の時間のことだし、もう行こう。", "Vả lại đến giờ hẹn rồi, đi thôi."],
          ["資料も揃ったことだし、提出しよう。", "Vả lại tài liệu đủ rồi, nộp thôi."],
          ["お腹も空いたことだし、食事にしよう。", "Vả lại đói rồi, ăn thôi."],
          ["試験も終わったことだし、祝おう。", "Vả lại thi xong rồi, ăn mừng thôi."],
        ],
        [
          ["Mệt rồi ngủ sớm thôi.", ["疲れたことだし", "今日は", "早く", "寝よう。"], 0],
          ["Mưa rồi về thôi nhé.", ["雨も降ってきたことだし", "もう", "帰ろう", "か。"], 0],
          ["Mai nghỉ thức khuya được.", ["休みのことだし", "夜更かしして", "も", "いい。"], 0],
          ["Lạnh rồi vào quán đi.", ["寒いことだし", "店に", "入ろう", "よ。"], 0],
          ["Hết việc về sớm được.", ["仕事が終わったことだし", "早退して", "も", "いい。"], 0],
          ["Cuối tuần đi chơi thôi.", ["週末のことだし", "遊びに", "行こう", "よ。"], 0],
          ["Tối rồi mai bàn tiếp.", ["遅いことだし", "続きは", "明日に", "しよう。"], 0],
          ["Còn thời gian kiểm lại.", ["時間があることだし", "もう一度", "確認", "しよう。"], 0],
          ["Đông quá đổi chỗ đi.", ["混んでいることだし", "別の店に", "しよう", "か。"], 0],
          ["Yên rồi bắt đầu học.", ["静かになったことだし", "勉強を", "始めよう", "よ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l17-g02",
      {
        meaning: "Vì là (tính cách/thói quen của)… nên chắc…",
        structures: ["N ＋ のことだから"],
        explanation:
          "のことだから dựa trên hiểu biết về tính cách/thói quen của ai đó để suy đoán hành động hoặc kết quả tự nhiên.",
        usage: "Đoán: anh ấy vốn cẩn thận nên chắc không quên…",
        cautions: [
          "N thường là người (hoặc nhóm người) đã biết rõ.",
          "Khác ことだから thông thường; cần の trước こと.",
        ],
        contrast:
          "のことだから ≈ vì là kiểu người đó nên…. Khác ものだから (biện hộ bản thân).",
        examples: [
          ex(
            "慎重な彼のことだから、よく調べたはずだ。",
            "しんちょうなかれのことだから、よくしらべたはずだ。",
            "Vì anh ấy vốn thận trọng nên chắc đã tra kỹ.",
            [
              ["慎重", "しんちょう"],
              ["な"],
              ["彼", "かれ"],
              ["のことだから、"],
              ["よく"],
              ["調", "しら"],
              ["べたはずだ。"],
            ],
          ),
          ex(
            "優しい彼女のことだから、手伝ってくれるだろう。",
            "やさしいかのじょのことだから、てつだってくれるだろう。",
            "Vì cô ấy vốn tốt bụng nên sẽ giúp thôi.",
            [
              ["優", "やさ"],
              ["しい"],
              ["彼女", "かのじょ"],
              ["のことだから、"],
              ["手伝", "てつだ"],
              ["ってくれるだろう。"],
            ],
          ),
          ex(
            "時間に厳しい部長のことだから、遅れは許さない。",
            "じかんにきびしいぶちょうのことだから、おくれはゆるさない。",
            "Vì trưởng phòng vốn khắt khe giờ giấc nên không tha muộn.",
            [
              ["時間", "じかん"],
              ["に"],
              ["厳", "きび"],
              ["しい"],
              ["部長", "ぶちょう"],
              ["のことだから、"],
              ["遅", "おく"],
              ["れは"],
              ["許", "ゆる"],
              ["さない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜のことだから",
        "Câu suy đoán theo tính cách: Nのことだから.",
        [
          ["Vì anh ấy chăm chỉ nên sẽ luyện thêm.", "勤勉な彼のことだから、さらに練習するだろう。"],
          ["Vì cô ấy đãng trí nên hay quên chìa khóa.", "忘れっぽい彼女のことだから、鍵を忘れがちだ。"],
          ["Vì sếp nóng tính nên đừng làm trễ.", "短気な上司のことだから、遅らせるな。"],
          ["Vì bạn trung thực nên sẽ nói thẳng.", "正直な友のことだから、はっきり言うはずだ。"],
          ["Vì mẹ lo xa nên đã chuẩn bị sẵn.", "用心深い母のことだから、もう準備済みだ。"],
          ["Vì thầy nghiêm nên không bỏ qua lỗi.", "厳しい先生のことだから、ミスは見逃さない。"],
          ["Vì em hay ngủ nướng nên gọi sớm.", "朝に弱い弟のことだから、早めに起こそう。"],
          ["Vì đồng nghiệp tỉ mỉ nên báo cáo đẹp.", "几帳面な同僚のことだから、報告はきれいだ。"],
          ["Vì anh ấy keo nên không mời ăn.", "けちな彼のことだから、奢ってはくれない。"],
          ["Vì cô ấy lạc quan nên sớm đứng dậy.", "前向きな彼女のことだから、すぐに立ち直る。"],
        ],
        [
          ["元気な子どものことだから、すぐ外で遊びたがる。", "Vì trẻ vốn khỏe nên muốn ra ngoài chơi ngay."],
          ["慎重な田中さんのことだから、契約はよく読むはずだ。", "Vì anh Tanaka thận trọng nên chắc đọc kỹ hợp đồng."],
          ["世話好きな隣のことだから、助けに来るだろう。", "Vì hàng xóm thích giúp nên sẽ tới giúp."],
          ["負けず嫌いな彼のことだから、再挑戦する。", "Vì anh ấy không chịu thua nên sẽ thử lại."],
          ["心配性の母のことだから、何度も電話する。", "Vì mẹ hay lo nên gọi nhiều lần."],
          ["経験豊富な彼のことだから、うまく対応するだろう。", "Vì anh ấy giàu kinh nghiệm nên xử lý tốt."],
          ["口が堅い彼女のことだから、秘密は守る。", "Vì cô ấy kín miệng nên giữ bí mật."],
          ["完璧主義の上司のことだから、修正が多い。", "Vì sếp cầu toàn nên sửa nhiều."],
          ["スポーツ好きな弟のことだから、週末は練習だ。", "Vì em thích thể thao nên cuối tuần tập."],
          ["面倒見の良い先輩のことだから、相談に乗ってくれる。", "Vì senpai tốt bụng nên sẽ lắng nghe."],
        ],
        [
          ["Anh thận trọng chắc đã tra kỹ.", ["慎重な彼のことだから", "よく調べた", "はず", "だ。"], 0],
          ["Cô tốt bụng sẽ giúp thôi.", ["優しい彼女のことだから", "手伝って", "くれる", "だろう。"], 0],
          ["Trưởng phòng khắt khe không tha muộn.", ["厳しい部長のことだから", "遅れは", "許さ", "ない。"], 0],
          ["Anh chăm sẽ luyện thêm.", ["勤勉な彼のことだから", "さらに", "練習する", "だろう。"], 0],
          ["Cô đãng trí hay quên chìa.", ["忘れっぽい彼女のことだから", "鍵を", "忘れ", "がちだ。"], 0],
          ["Bạn trung thực nói thẳng.", ["正直な友のことだから", "はっきり", "言う", "はずだ。"], 0],
          ["Mẹ lo xa đã chuẩn bị sẵn.", ["用心深い母のことだから", "もう", "準備済み", "だ。"], 0],
          ["Thầy nghiêm không bỏ qua lỗi.", ["厳しい先生のことだから", "ミスは", "見逃さ", "ない。"], 0],
          ["Đồng nghiệp tỉ mỉ báo cáo đẹp.", ["几帳面な同僚のことだから", "報告は", "きれい", "だ。"], 0],
          ["Cô lạc quan sớm đứng dậy.", ["前向きな彼女のことだから", "すぐに", "立ち直る", "だろう。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l17-g03",
      {
        meaning: "Chính vì… nên… (kết quả tương xứng / càng…)",
        structures: ["N／普通形 ＋ だけに"],
        explanation:
          "だけに nhấn mạnh vì đúng là A nên kết quả B hợp lý hoặc cảm xúc mạnh hơn (vui hơn, thất vọng hơn…).",
        usage: "Nhấn mạnh tương quan nguyên nhân–kết quả: kỳ vọng cao nên vui/thất vọng lớn.",
        cautions: [
          "Kết quả thường tương xứng với mức độ của lý do.",
          "Khác だけあって (đáng với danh tiếng) — gần nhưng sắc thái hơi khác.",
        ],
        contrast:
          "だけに ≈ chính vì…. Gần だけあって; khác ばかりに (thường kết quả xấu).",
        examples: [
          ex(
            "期待していただけに、がっかりした。",
            "きたいしていただけに、がっかりした。",
            "Chính vì đã kỳ vọng nên thất vọng.",
            [
              ["期待", "きたい"],
              ["していただけに、"],
              ["がっかりした。"],
            ],
          ),
          ex(
            "初めての海外だけに緊張する。",
            "はじめてのかいがいだけにきんちょうする。",
            "Chính vì lần đầu ra nước ngoài nên căng thẳng.",
            [
              ["初", "はじ"],
              ["めての"],
              ["海外", "かいがい"],
              ["だけに"],
              ["緊張", "きんちょう"],
              ["する。"],
            ],
          ),
          ex(
            "努力しただけに合格が嬉しい。",
            "どりょくしただけにごうかくがうれしい。",
            "Chính vì đã cố gắng nên việc đậu càng vui.",
            [
              ["努力", "どりょく"],
              ["しただけに"],
              ["合格", "ごうかく"],
              ["が"],
              ["嬉", "うれ"],
              ["しい。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜だけに",
        "Câu chính vì… nên…: だけに.",
        [
          ["Chính vì giá cao nên chất lượng tốt.", "値段が高いだけに品質が良い。"],
          ["Chính vì khó nên khi xong càng thấy vui.", "難しいだけに解けて嬉しい。"],
          ["Chính vì tin tưởng nên bị phản bội càng đau.", "信頼していただけに裏切られて辛い。"],
          ["Chính vì trẻ nên học nhanh.", "若いだけに吸収が早い。"],
          ["Chính vì kinh nghiệm ít nên lo.", "経験が少ないだけに不安だ。"],
          ["Chính vì chuẩn bị kỹ nên tự tin.", "準備が万全なだけに自信がある。"],
          ["Chính vì xa nên càng nhớ nhà.", "遠いだけに故郷が恋しい。"],
          ["Chính vì nổi tiếng nên bị soi nhiều.", "有名なだけに注目されやすい。"],
          ["Chính vì trách nhiệm nặng nên áp lực lớn.", "責任が重いだけにプレッシャーが大きい。"],
          ["Chính vì chờ lâu nên càng xúc động.", "長く待っただけに感動も大きい。"],
        ],
        [
          ["練習しただけに試合で力を出せた。", "Chính vì đã luyện nên thi đấu phát huy được."],
          ["高価なだけに壊れてショックだ。", "Chính vì đắt nên hỏng càng sốc."],
          ["親しいだけに本音が言える。", "Chính vì thân nên nói thật được."],
          ["初めてだけに勝って嬉しい。", "Chính vì lần đầu nên thắng càng vui."],
          ["忙しいだけに休みが貴重だ。", "Chính vì bận nên ngày nghỉ quý."],
          ["期待が大きいだけに結果が気になる。", "Chính vì kỳ vọng lớn nên quan tâm kết quả."],
          ["専門だけに説明が詳しい。", "Chính vì chuyên môn nên giải thích kỹ."],
          ["狭いだけに家賃は安い。", "Chính vì hẹp nên tiền thuê rẻ."],
          ["真剣なだけに失敗が悔しい。", "Chính vì nghiêm túc nên thất bại càng tiếc."],
          ["経験者だけに判断が速い。", "Chính vì người có kinh nghiệm nên phán đoán nhanh."],
        ],
        [
          ["Kỳ vọng nên thất vọng.", ["期待していただけに", "がっかり", "して", "しまった。"], 0],
          ["Lần đầu ra ngoài nên căng.", ["初めての海外だけに", "緊張", "して", "いる。"], 0],
          ["Cố gắng nên đậu càng vui.", ["努力しただけに", "合格が", "嬉しい", "のだ。"], 0],
          ["Giá cao nên chất lượng tốt.", ["高いだけに", "品質が", "良い", "らしい。"], 0],
          ["Khó nên giải được càng vui.", ["難しいだけに", "解けて", "嬉しい", "そうだ。"], 0],
          ["Trẻ nên học nhanh.", ["若いだけに", "吸収が", "早い", "ものだ。"], 0],
          ["Ít kinh nghiệm nên lo.", ["経験が少ないだけに", "不安", "な", "のだ。"], 0],
          ["Xa nên càng nhớ nhà.", ["遠いだけに", "故郷が", "恋しい", "らしい。"], 0],
          ["Nổi tiếng nên bị soi nhiều.", ["有名なだけに", "注目され", "やすい", "ようだ。"], 0],
          ["Chờ lâu nên càng xúc động.", ["長く待っただけに", "感動も", "大きい", "だろう。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l17-g04",
      {
        meaning: "Chỉ vì… / chính vì… (thường dẫn đến kết quả xấu)",
        structures: ["普通形 ＋ ばかりに"],
        explanation:
          "ばかりに diễn đạt chính vì một việc nhỏ/một lý do mà dẫn đến hậu quả đáng tiếc.",
        usage: "Than thở, giải thích nguyên nhân gây ra kết quả xấu ngoài ý muốn.",
        cautions: [
          "Hậu quả hầu như tiêu cực; ít dùng cho kết quả tốt.",
          "Khác ばかりでなく (không chỉ…) — cấu trúc khác hẳn.",
        ],
        contrast:
          "ばかりに ≈ chỉ vì… (xấu). Khác だけに (có thể tốt/xấu tương xứng).",
        examples: [
          ex(
            "一言言ったばかりに嫌われた。",
            "ひとこといったばかりにきらわれた。",
            "Chỉ vì nói một câu mà bị ghét.",
            [
              ["一言", "ひとこと"],
              ["言", "い"],
              ["ったばかりに"],
              ["嫌", "きら"],
              ["われた。"],
            ],
          ),
          ex(
            "油断したばかりに失敗した。",
            "ゆだんしたばかりにしっぱいした。",
            "Chỉ vì chủ quan mà thất bại.",
            [
              ["油断", "ゆだん"],
              ["したばかりに"],
              ["失敗", "しっぱい"],
              ["した。"],
            ],
          ),
          ex(
            "正直に話したばかりに損をした。",
            "しょうじきにはなしたばかりにそんをした。",
            "Chính vì nói thẳng mà bị thiệt.",
            [
              ["正直", "しょうじき"],
              ["に"],
              ["話", "はな"],
              ["したばかりに"],
              ["損", "そん"],
              ["をした。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ばかりに",
        "Câu chỉ vì… nên kết quả xấu: ばかりに.",
        [
          ["Chỉ vì tin lời đồn mà lo lắng.", "噂を信じたばかりに不安になった。"],
          ["Chỉ vì quên dù mà bị ướt.", "傘を忘れたばかりに濡れてしまった。"],
          ["Chỉ vì vội mà làm sai.", "急いだばかりにミスをした。"],
          ["Chính vì giúp đỡ mà bị lợi dụng.", "親切にしたばかりに利用された。"],
          ["Chỉ vì mở miệng mà lộ bí mật.", "口を滑らせたばかりに秘密が漏れた。"],
          ["Chỉ vì ngủ quên mà lỡ tàu.", "寝坊したばかりに電車に乗り遅れた。"],
          ["Chính vì tham rẻ mà mua phải hàng kém.", "安さに釣られたばかりに粗悪品を買った。"],
          ["Chỉ vì không hỏi mà hiểu nhầm.", "確認しなかったばかりに誤解した。"],
          ["Chính vì khoe khoang mà bị ghét.", "自慢したばかりに嫌われた。"],
          ["Chỉ vì đường tắt mà lạc.", "近道をしたばかりに迷ってしまった。"],
        ],
        [
          ["嘘をついたばかりに信用を失った。", "Chỉ vì nói dối mà mất uy tín."],
          ["無理をしたばかりに体調を崩した。", "Chỉ vì cố quá mà đổ bệnh."],
          ["値段だけ見たばかりに失敗した。", "Chỉ vì chỉ nhìn giá mà thất bại."],
          ["連絡を怠ったばかりに怒られた。", "Chỉ vì lười liên lạc mà bị mắng."],
          ["小さな油断をしたばかりに事故になった。", "Chỉ vì chủ quan nhỏ mà thành tai nạn."],
          ["欲張ったばかりに両方失った。", "Chỉ vì tham mà mất cả hai."],
          ["約束を破ったばかりに信頼を損ねた。", "Chỉ vì phá hẹn mà tổn hại lòng tin."],
          ["笑ったばかりに怒らせてしまった。", "Chỉ vì cười mà làm người ta giận."],
          ["安請け合いしたばかりに苦労した。", "Chỉ vì nhận bừa mà khổ sở."],
          ["夜更かししたばかりに朝起きれない。", "Chỉ vì thức khuya mà sáng không dậy nổi."],
        ],
        [
          ["Chỉ vì một câu bị ghét.", ["一言言ったばかりに", "嫌われて", "しまった", "らしい。"], 0],
          ["Chỉ vì chủ quan thất bại.", ["油断したばかりに", "失敗", "して", "しまった。"], 0],
          ["Nói thẳng nên bị thiệt.", ["正直に話したばかりに", "損を", "して", "しまった。"], 0],
          ["Tin đồn nên lo lắng.", ["噂を信じたばかりに", "不安に", "なった", "そうだ。"], 0],
          ["Quên dù nên bị ướt.", ["傘を忘れたばかりに", "濡れて", "しまった", "らしい。"], 0],
          ["Vội nên làm sai.", ["急いだばかりに", "ミスを", "した", "ようだ。"], 0],
          ["Giúp đỡ nên bị lợi dụng.", ["親切にしたばかりに", "利用", "された", "そうだ。"], 0],
          ["Ngủ quên nên lỡ tàu.", ["寝坊したばかりに", "電車に", "乗り遅れた", "らしい。"], 0],
          ["Không hỏi nên hiểu nhầm.", ["確認しなかったばかりに", "誤解", "して", "しまった。"], 0],
          ["Đường tắt nên lạc.", ["近道をしたばかりに", "迷って", "しまった", "ようだ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l17-g05",
      {
        meaning: "Đã… thì phải… / một khi đã… thì nhất định…",
        structures: [
          "Vた／普通形 ＋ からには",
          "Vた／普通形 ＋ 以上（は）",
          "Vた／普通形 ＋ 上は",
        ],
        explanation:
          "からには・以上（は）・上は diễn đạt một khi đã chọn/đã ở vị thế đó thì phải làm cho trọn hoặc chịu trách nhiệm.",
        usage: "Quyết tâm, trách nhiệm: đã nhận thì làm đến cùng; đã biết thì phải nói.",
        cautions: [
          "Kết luận thường là nghĩa vụ, quyết tâm hoặc điều tất yếu.",
          "上は hơi văn viết; からには／以上は phổ biến hơn.",
        ],
        contrast:
          "からには／以上は／上は ≈ đã… thì phải…. Khác から (lý do thường).",
        examples: [
          ex(
            "引き受けたからには最後までやる。",
            "ひきうけたからにはさいごまでやる。",
            "Đã nhận thì làm đến cùng.",
            [
              ["引", "ひ"],
              ["き"],
              ["受", "う"],
              ["けたからには"],
              ["最後", "さいご"],
              ["までやる。"],
            ],
          ),
          ex(
            "学生である以上、勉強すべきだ。",
            "がくせいであるいじょう、べんきょうすべきだ。",
            "Đã là sinh viên thì phải học.",
            [
              ["学生", "がくせい"],
              ["である以上、"],
              ["勉強", "べんきょう"],
              ["すべきだ。"],
            ],
          ),
          ex(
            "約束した上は守らなければならない。",
            "やくそくしたうえはまもらなければならない。",
            "Đã hứa thì phải giữ lời.",
            [
              ["約束", "やくそく"],
              ["した上は"],
              ["守", "まも"],
              ["らなければならない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜からには／以上は／上は",
        "Câu đã… thì phải…: からには／以上（は）／上は.",
        [
          ["Đã bắt đầu thì đừng bỏ giữa chừng.", "始めたからには途中でやめない。"],
          ["Đã biết sự thật thì phải nói.", "事実を知った以上は言うべきだ。"],
          ["Đã vào đội thì tuân thủ luật.", "チームに入った上はルールを守れ。"],
          ["Đã thi thì nhằm điểm cao.", "受験するからには高得点を目指す。"],
          ["Đã là lãnh đạo thì chịu trách nhiệm.", "リーダーである以上は責任を取れ。"],
          ["Đã ký thì thực hiện hợp đồng.", "署名した上は契約を履行せよ。"],
          ["Đã đến đây thì cố hết sức.", "ここまで来たからには全力を尽くす。"],
          ["Đã chọn nghề này thì chịu cực.", "この道を選んだ以上は苦労を覚悟しろ。"],
          ["Đã nghe thì đừng làm ngơ.", "聞いた上は無視するな。"],
          ["Đã tuyên bố thì làm cho được.", "宣言したからには成し遂げろ。"],
        ],
        [
          ["日本に来たからには日本語を学ぶ。", "Đã sang Nhật thì học tiếng Nhật."],
          ["プロである以上は妥協しない。", "Đã là chuyên nghiệp thì không thỏa hiệp."],
          ["始めた上は完成させる。", "Đã bắt đầu thì hoàn thành."],
          ["参加したからには最後まで残る。", "Đã tham gia thì ở đến cuối."],
          ["親である以上は子どもを守る。", "Đã là cha mẹ thì bảo vệ con."],
          ["決めた上は迷わず進む。", "Đã quyết thì tiến không do dự."],
          ["挑戦するからには成功を狙う。", "Đã thử thách thì nhắm thành công."],
          ["公務員である以上は公正であれ。", "Đã là công chức thì phải công bằng."],
          ["引き受けた上は逃げられない。", "Đã nhận thì không trốn được."],
          ["発言したからには責任を持つ。", "Đã phát ngôn thì chịu trách nhiệm."],
        ],
        [
          ["Đã nhận làm đến cùng.", ["引き受けたからには", "最後まで", "やる", "つもりだ。"], 0],
          ["Đã là sinh viên phải học.", ["学生である以上", "勉強", "すべき", "だ。"], 0],
          ["Đã hứa phải giữ lời.", ["約束した上は", "守らなければ", "なら", "ない。"], 0],
          ["Đã bắt đầu đừng bỏ dở.", ["始めたからには", "途中で", "やめ", "ない。"], 0],
          ["Đã biết thì phải nói.", ["知った以上は", "言う", "べき", "だ。"], 0],
          ["Đã vào đội tuân luật.", ["入った上は", "ルールを", "守れ", "よ。"], 0],
          ["Đã thi nhắm điểm cao.", ["受験するからには", "高得点を", "目指す", "つもりだ。"], 0],
          ["Đã là lãnh đạo chịu trách nhiệm.", ["リーダーである以上は", "責任を", "取れ", "よ。"], 0],
          ["Đã đến đây cố hết sức.", ["ここまで来たからには", "全力を", "尽くす", "つもりだ。"], 0],
          ["Đã tuyên bố làm cho được.", ["宣言したからには", "成し遂げ", "ろ", "よ。"], 0],
        ],
      ),
    ),
  ];
}
