import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L11-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 12, BATCH);

export function lesson12Patterns(byId) {
  return [
    P(
      byId,
      "l12-g01",
      {
        meaning: "Không đời nào… / chẳng lẽ… được",
        structures: ["V／いA／なA／N の ＋ わけがない", "V／いA／なA／N の ＋ わけはない"],
        explanation:
          "Phủ định mạnh: không có lý do/cơ sở để A đúng; khẳng định A là không thể.",
        usage: "Phản bác, tự tin phủ nhận: không đời nào anh ấy nói dối…",
        cautions: [
          "わけがない mạnh hơn はずがない đôi khi mang cảm xúc phản đối.",
          "Khác わけではない (không hẳn là… — phủ định một phần).",
        ],
        contrast: "わけがない ≈ không đời nào. Khác わけではない (không phải là…).",
        examples: [
          ex(
            "彼が嘘をつくわけがない。",
            "かれがうそをつくわけがない。",
            "Không đời nào anh ấy nói dối.",
            [
              ["彼", "かれ"],
              ["が"],
              ["嘘", "うそ"],
              ["をつくわけがない。"],
            ],
          ),
          ex(
            "この値段で買えるわけがない。",
            "このねだんでかえるわけがない。",
            "Không đời nào mua được với giá này.",
            [
              ["この"],
              ["値段", "ねだん"],
              ["で"],
              ["買", "か"],
              ["えるわけがない。"],
            ],
          ),
          ex(
            "初心者に解けるわけがない。",
            "しょしんしゃにとけるわけがない。",
            "Không đời nào người mới giải được.",
            [
              ["初心者", "しょしんしゃ"],
              ["に"],
              ["解", "と"],
              ["けるわけがない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜わけがない",
        "Câu dùng わけがない để phủ định mạnh: không có lý do để A đúng.",
        [
          ["Không đời nào cô ấy quên hẹn.", "彼女が約束を忘れるわけがない。"],
          ["Không đời nào bài này dễ vậy.", "この問題が簡単なわけがない。"],
          ["Không đời nào anh ấy bỏ cuộc.", "彼が諦めるわけがない。"],
          ["Không đời nào miễn phí hoàn toàn.", "完全に無料なわけがない。"],
          ["Không đời nào một ngày xong.", "一日で終わるわけがない。"],
          ["Không đời nào trẻ hiểu hết.", "子供に全部分かるわけがない。"],
          ["Không đời nào máy hỏng vô cớ.", "機械が理由なく壊れるわけがない。"],
          ["Không đời nào điểm tuyệt đối dễ vậy.", "満点が簡単に取れるわけがない。"],
          ["Không đời nào trời lạnh giữa hè.", "真夏に寒いわけがない。"],
          ["Không đời nào bí mật lộ ra dễ vậy.", "秘密が簡単に漏れるわけがない。"],
        ],
        [
          ["彼が裏切るわけがない。", "Không đời nào anh ấy phản bội."],
          ["今から間に合うわけがない。", "Không đời nào kịp từ giờ."],
          ["そんな都合のいい話があるわけがない。", "Không đời nào có chuyện thuận tiện thế."],
          ["経験ゼロで成功するわけがない。", "Không đời nào thành công với zero kinh nghiệm."],
          ["この布陣で勝つわけがない。", "Không đời nào thắng với đội hình này."],
          ["誰も知らないわけがない。", "Không đời nào chẳng ai biết."],
          ["努力なしで上達するわけがない。", "Không đời nào tiến bộ mà không nỗ lực."],
          ["この量を一人で運ぶわけがない。", "Không đời nào một người bê hết lượng này."],
          ["急に態度が変わるわけがない。", "Không đời nào thái độ đổi đột ngột vô cớ."],
          ["無料で高級品が手に入るわけがない。", "Không đời nào có đồ cao cấp miễn phí."],
        ],
        [
          ["Anh ấy không đời nào nói dối được.", ["彼が", "嘘を言う", "わけが", "ない。"], 2],
          ["Không đời nào mua nổi với giá đó.", ["その値段では", "買える", "わけが", "ない。"], 2],
          ["Người mới thì không đời nào giải nổi.", ["初心者には", "解ける", "わけが", "ない。"], 2],
          ["Không đời nào cô ấy quên hẹn.", ["彼女が", "忘れる", "わけが", "ない。"], 2],
          ["Không đời nào anh ấy bỏ cuộc.", ["彼が", "諦める", "わけが", "ない。"], 2],
          ["Không đời nào một ngày xong.", ["一日で", "終わる", "わけが", "ない。"], 2],
          ["Không đời nào kịp từ giờ.", ["今から", "間に合う", "わけが", "ない。"], 2],
          ["Không đời nào phản bội.", ["彼が", "裏切る", "わけが", "ない。"], 2],
          ["Không đời nào tiến bộ không nỗ lực.", ["努力なしで", "上達する", "わけが", "ない。"], 2],
          ["Không đời nào chẳng ai biết.", ["誰も", "知らない", "わけが", "ない。"], 2],
        ],
      ),
    ),

    P(
      byId,
      "l12-g02",
      {
        meaning: "Đâu phải lúc… / chứ đừng nói đến…",
        structures: [
          "N／Vる ＋ どころではない",
          "N／Vる ＋ どころか",
        ],
        explanation:
          "どころではない: hoàn toàn không phải tình trạng để làm A. どころか: không chỉ không A mà thậm chí ngược lại/B nặng hơn.",
        usage: "Từ chối/nhấn mạnh mức độ: bận đến mức đâu phải đi chơi; chứ đừng nói đến giúp, còn làm phiền…",
        cautions: [
          "どころではない ≠ ところだ (đúng lúc).",
          "どころか thường theo sau kết quả bất ngờ hoặc mức độ mạnh hơn.",
        ],
        contrast: "どころではない ≈ đâu phải lúc. どころか ≈ chứ đừng nói; khác わけがない.",
        examples: [
          ex(
            "忙しくて旅行どころではない。",
            "いそがしくてりょこうどころではない。",
            "Bận đến mức đâu phải lúc đi du lịch.",
            [
              ["忙", "いそが"],
              ["しくて"],
              ["旅行", "りょこう"],
              ["どころではない。"],
            ],
          ),
          ex(
            "助かるどころか迷惑をかけた。",
            "たすかるどころかめいわくをかけた。",
            "Chứ đừng nói giúp được, còn gây phiền.",
            [
              ["助", "たす"],
              ["かるどころか"],
              ["迷惑", "めいわく"],
              ["をかけた。"],
            ],
          ),
          ex(
            "休みどころか残業続きだ。",
            "やすみどころかざんぎょうつづきだ。",
            "Chứ đừng nói nghỉ, toàn làm thêm.",
            [
              ["休", "やす"],
              ["みどころか"],
              ["残業", "ざんぎょう"],
              ["続きだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜どころではない・〜どころか",
        "Câu dùng どころではない (đâu phải lúc) hoặc どころか (chứ đừng nói…).",
        [
          ["Đâu phải lúc xem phim, đang ôn thi.", "試験勉強中で映画どころではない。"],
          ["Đâu phải lúc ăn ngoài, túi hết tiền.", "お金がなく外食どころではない。"],
          ["Chứ đừng nói khen, còn bị mắng.", "褒めるどころか叱られた。"],
          ["Chứ đừng nói tiến bộ, còn kém hơn.", "上達どころか下手になった。"],
          ["Đâu phải lúc vui chơi, có việc gấp.", "急ぎの用事で遊びどころではない。"],
          ["Chứ đừng nói cảm ơn, còn giận.", "感謝どころか怒っている。"],
          ["Đâu phải lúc ngủ muộn, mai họp sớm.", "朝早い会議で夜更かしどころではない。"],
          ["Chứ đừng nói dư, còn thiếu.", "余裕どころか足りない。"],
          ["Đâu phải lúc mua sắm, đang tiết kiệm.", "節約中で買い物どころではない。"],
          ["Chứ đừng nói sạch, còn bẩn hơn.", "きれいどころか汚くなった。"],
        ],
        [
          ["風邪で外出どころではない。", "Cảm nên đâu phải lúc ra ngoài."],
          ["手伝うどころか邪魔をした。", "Chứ đừng nói giúp, còn làm vướng."],
          ["笑うどころか泣き出した。", "Chứ đừng nói cười, còn khóc òa."],
          ["貯金どころではない出費だ。", "Khoản chi đâu phải lúc để dành."],
          ["楽になるどころか忙しくなった。", "Chứ đừng nói nhàn, còn bận hơn."],
          ["説明どころではない騒ぎだ。", "Ồn ào đến mức đâu phải lúc giải thích."],
          ["優勝どころか予選落ちだ。", "Chứ đừng nói vô địch, còn trượt vòng loại."],
          ["読書どころではない疲れ方だ。", "Mệt đến mức đâu phải lúc đọc sách."],
          ["解決どころか悪化した。", "Chứ đừng nói giải quyết, còn tệ hơn."],
          ["観光どころではない日程だ。", "Lịch trình đâu phải lúc tham quan."],
        ],
        [
          ["Đâu phải lúc đi du lịch vì bận.", ["忙しくて", "観光", "どころでは", "ない。"], 2],
          ["Chứ đừng nói giúp còn gây phiền.", ["役立つ", "どころか", "迷惑に", "なった。"], 1],
          ["Chứ đừng nói nghỉ toàn làm thêm.", ["休み", "どころか", "残業が", "続く。"], 1],
          ["Đâu phải lúc xem phim vì ôn thi.", ["勉強中で", "映画", "どころでは", "ない。"], 2],
          ["Chứ đừng nói khen còn bị mắng.", ["褒める", "どころか", "叱られ", "た。"], 1],
          ["Đâu phải lúc chơi vì việc gấp.", ["用事で", "遊び", "どころでは", "ない。"], 2],
          ["Chứ đừng nói dư còn thiếu.", ["余裕", "どころか", "不足が", "目立つ。"], 1],
          ["Đâu phải lúc ra ngoài vì cảm.", ["風邪で", "外出", "どころでは", "ない。"], 2],
          ["Chứ đừng nói cười còn khóc.", ["笑う", "どころか", "泣き出", "した。"], 1],
          ["Chứ đừng nói giải quyết còn tệ hơn.", ["解決", "どころか", "悪化", "した。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l12-g03",
      {
        meaning: "Làm gì có… / sao lại… chứ",
        structures: ["Vる／いA／なA語幹 ＋ ものか／もんか"],
        explanation:
          "Phủ định cảm xúc mạnh, phản kháng: tuyệt đối không làm/không chấp nhận A.",
        usage: "Phản đối gay gắt, lời thề phủ định: làm gì có chịu thua; sao lại xin lỗi chứ.",
        cautions: [
          "もんか thân mật hơn ものか; sắc thái mạnh, dễ nghe khiếm nhã.",
          "Khác わけがない (lý luận 'không có lý'); ものか thiên cảm xúc phản kháng.",
        ],
        contrast: "ものか ≈ làm gì có/sao lại. Gần わけがない; khác わけではない.",
        examples: [
          ex(
            "二度と行くものか。",
            "にどといくものか。",
            "Làm gì có đi lại lần nữa.",
            [
              ["二度", "にど"],
              ["と"],
              ["行", "い"],
              ["くものか。"],
            ],
          ),
          ex(
            "負けるものか。",
            "まけるものか。",
            "Làm gì có chịu thua.",
            [
              ["負", "ま"],
              ["けるものか。"],
            ],
          ),
          ex(
            "そんなことに賛成できるものか。",
            "そんなことにさんせいできるものか。",
            "Sao lại tán thành chuyện đó chứ.",
            [
              ["そんなことに"],
              ["賛成", "さんせい"],
              ["できるものか。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ものか",
        "Câu dùng ものか／もんか để phủ định cảm xúc mạnh, phản kháng.",
        [
          ["Làm gì có chịu xin lỗi.", "謝るものか。"],
          ["Làm gì có tin lời đó.", "そんな話を信じるものか。"],
          ["Sao lại bỏ cuộc giữa chừng chứ.", "途中でやめるものか。"],
          ["Làm gì có nói với kẻ đó.", "あいつに話すものか。"],
          ["Sao lại sợ chuyện nhỏ chứ.", "こんなことで怖がるものか。"],
          ["Làm gì có để người khác quyết.", "他人に決めさせるものか。"],
          ["Sao lại ăn đồ đó chứ.", "あんなものを食べるものか。"],
          ["Làm gì có quên ơn.", "恩を忘れるものか。"],
          ["Sao lại im lặng chịu đựng chứ.", "黙って耐えるものか。"],
          ["Làm gì có đi cùng lần nữa.", "もう一緒に行くものか。"],
        ],
        [
          ["二度と頼むものか。", "Làm gì có nhờ lần nữa."],
          ["負けるもんか。", "Làm gì có thua (thân mật)."],
          ["彼の言うことを聞くものか。", "Sao lại nghe lời anh ấy chứ."],
          ["安いから買うものか。", "Rẻ thì đã sao, làm gì có mua."],
          ["そんな条件を飲むものか。", "Sao lại chấp nhận điều kiện đó chứ."],
          ["泣いて見せるものか。", "Làm gì có khóc cho xem."],
          ["今更謝られても許すものか。", "Giờ có xin lỗi cũng làm gì có tha."],
          ["一人で全部やるものか。", "Sao lại một mình làm hết chứ."],
          ["秘密を漏らすものか。", "Làm gì có lộ bí mật."],
          ["そんな場所に住むものか。", "Sao lại ở chỗ như vậy chứ."],
        ],
        [
          ["Đời nào đi lại lần nữa.", ["二度と", "戻る", "ものか", "。"], 2],
          ["Đời nào chịu thua.", ["絶対に", "負ける", "ものか", "。"], 2],
          ["Sao mà tán thành chuyện đó được.", ["その案に", "賛成できる", "ものか", "。"], 2],
          ["Làm gì có chịu xin lỗi.", ["決して", "謝る", "ものか", "。"], 2],
          ["Làm gì có tin lời đó.", ["そんな話を", "信じる", "ものか", "。"], 2],
          ["Sao lại bỏ cuộc giữa chừng.", ["途中で", "やめる", "ものか", "。"], 2],
          ["Làm gì có nhờ lần nữa.", ["二度と", "頼む", "ものか", "。"], 2],
          ["Sao lại nghe lời anh ấy.", ["彼の言うことを", "聞く", "ものか", "。"], 2],
          ["Làm gì có lộ bí mật.", ["秘密を", "漏らす", "ものか", "。"], 2],
          ["Sao lại chấp nhận điều kiện đó.", ["そんな条件を", "飲む", "ものか", "。"], 2],
        ],
      ),
    ),

    P(
      byId,
      "l12-g04",
      {
        meaning: "Không phải là… / không hẳn là…",
        structures: [
          "V／いA／なA／N の ＋ わけではない",
          "〜というわけではない",
        ],
        explanation:
          "Phủ định một phần hoặc làm mềm khẳng định: không hoàn toàn đúng rằng A; tránh hiểu nhầm tuyệt đối.",
        usage: "Giải thích, đính chính: không phải là ghét; không hẳn là không thích…",
        cautions: [
          "Khác わけがない (phủ định mạnh tuyệt đối).",
          "というわけではない thường đính chính suy luận của đối phương.",
        ],
        contrast: "わけではない ≈ không phải/không hẳn. Khác わけがない; gần というものではない.",
        examples: [
          ex(
            "行きたくないわけではない。",
            "いきたくないわけではない。",
            "Không phải là không muốn đi.",
            [
              ["行", "い"],
              ["きたくないわけではない。"],
            ],
          ),
          ex(
            "高いというわけではない。",
            "たかいというわけではない。",
            "Không hẳn là đắt.",
            [
              ["高", "たか"],
              ["いというわけではない。"],
            ],
          ),
          ex(
            "彼が悪いわけではない。",
            "かれがわるいわけではない。",
            "Không phải anh ấy sai.",
            [
              ["彼", "かれ"],
              ["が"],
              ["悪", "わる"],
              ["いわけではない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜わけではない・〜というわけではない",
        "Câu dùng わけではない／というわけではない: phủ định một phần, làm mềm ý.",
        [
          ["Không phải là ghét công việc.", "仕事が嫌いなわけではない。"],
          ["Không hẳn là không quan tâm.", "関心がないというわけではない。"],
          ["Không phải lúc nào cũng đúng.", "いつも正しいわけではない。"],
          ["Không hẳn là từ chối lời mời.", "招待を断るというわけではない。"],
          ["Không phải không hiểu.", "分からないわけではない。"],
          ["Không hẳn là phản đối kế hoạch.", "計画に反対だというわけではない。"],
          ["Không phải chỉ vì tiền.", "お金だけのわけではない。"],
          ["Không hẳn là hết hy vọng.", "絶望したというわけではない。"],
          ["Không phải mọi người đều đồng ý.", "全員が賛成なわけではない。"],
          ["Không hẳn là bỏ cuộc.", "諦めたというわけではない。"],
        ],
        [
          ["忙しいわけではないが余裕もない。", "Không phải bận nhưng cũng chẳng dư sức."],
          ["嫌いなわけではないが得意でもない。", "Không phải ghét nhưng cũng chẳng giỏi."],
          ["無理だというわけではない。", "Không hẳn là không làm nổi."],
          ["嘘をついたわけではない。", "Không phải đã nói dối."],
          ["簡単だというわけではない。", "Không hẳn là dễ."],
          ["無視したわけではない。", "Không phải cố tình bỏ qua."],
          ["満足したというわけではない。", "Không hẳn là đã thỏa mãn."],
          ["責任がないわけではない。", "Không phải là không có trách nhiệm."],
          ["急ぐというわけではない。", "Không hẳn là đang vội."],
          ["彼だけが悪いわけではない。", "Không phải chỉ mỗi anh ấy sai."],
        ],
        [
          ["Chẳng phải là không muốn đi.", ["行きたくない", "わけでは", "ないが", "都合が悪い。"], 1],
          ["Chẳng hẳn là đắt đâu.", ["高い", "というわけでは", "ないが", "安いとも言えない。"], 1],
          ["Chẳng phải anh ấy có lỗi.", ["彼が悪い", "わけでは", "ないと思う", "。"], 1],
          ["Không phải ghét công việc.", ["仕事が嫌いな", "わけでは", "ない", "。"], 1],
          ["Không hẳn là không quan tâm.", ["関心がない", "というわけでは", "ない", "。"], 1],
          ["Không phải không hiểu.", ["分からない", "わけでは", "ない", "。"], 1],
          ["Không phải chỉ vì tiền.", ["お金だけの", "わけでは", "ない", "。"], 1],
          ["Không hẳn là bỏ cuộc.", ["諦めた", "というわけでは", "ない", "。"], 1],
          ["Không phải đã nói dối.", ["嘘をついた", "わけでは", "ない", "。"], 1],
          ["Không phải chỉ mỗi anh ấy sai.", ["彼だけが悪い", "わけでは", "ない", "。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l12-g05",
      {
        meaning: "Không phải cứ… là… / cũng chẳng phải là…",
        structures: [
          "〜というものではない",
          "〜というものでもない",
        ],
        explanation:
          "Phủ định cách hiểu tuyệt đối/công thức hóa: không thể nói cứ A thì luôn đúng; というものでもない làm mềm hơn.",
        usage: "Nhận xét, khuyên: tiền nhiều không phải cứ hạnh phúc; cũng chẳng phải là không cần…",
        cautions: [
          "というものではない phủ định quy tắc chung; khác phủ định một sự việc cụ thể.",
          "というものでもない thường 'cũng chẳng đến mức… / cũng không hẳn…'.",
        ],
        contrast: "というものではない ≈ không phải cứ. Gần わけではない; khác わけがない.",
        examples: [
          ex(
            "お金があれば幸せというものではない。",
            "おかねがあればしあわせというものではない。",
            "Không phải cứ có tiền là hạnh phúc.",
            [
              ["お金", "おかね"],
              ["があれば"],
              ["幸", "しあわ"],
              ["せというものではない。"],
            ],
          ),
          ex(
            "練習すれば必ず上達するというものでもない。",
            "れんしゅうすればかならずじょうたつするというものでもない。",
            "Cũng chẳng phải cứ luyện là chắc tiến bộ.",
            [
              ["練習", "れんしゅう"],
              ["すれば"],
              ["必", "かなら"],
              ["ず"],
              ["上達", "じょうたつ"],
              ["するというものでもない。"],
            ],
          ),
          ex(
            "若いから無理がないというものではない。",
            "わかいからむりがないというものではない。",
            "Không phải cứ trẻ là không quá sức.",
            [
              ["若", "わか"],
              ["いから"],
              ["無理", "むり"],
              ["がないというものではない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜というものではない・〜というものでもない",
        "Câu dùng というものではない／でもない: phủ định cách hiểu tuyệt đối 'cứ A thì B'.",
        [
          ["Không phải cứ đắt là chất lượng tốt.", "高ければ品質がいいというものではない。"],
          ["Cũng chẳng phải cứ im là đồng ý.", "黙っていれば賛成というものでもない。"],
          ["Không phải cứ nhiều bạn là vui.", "友人が多ければ楽しいというものではない。"],
          ["Cũng chẳng phải cứ điểm cao là giỏi.", "点数が高いから優秀というものでもない。"],
          ["Không phải cứ nhanh là tốt.", "速ければいいというものではない。"],
          ["Cũng chẳng phải cứ thất bại là hết.", "失敗したら終わりというものでもない。"],
          ["Không phải cứ tuổi cao là khôn.", "年齢が高ければ賢いというものではない。"],
          ["Cũng chẳng phải cứ miễn phí là lợi.", "無料なら得だというものでもない。"],
          ["Không phải cứ nói thẳng là đúng.", "率直なら正しいというものではない。"],
          ["Cũng chẳng phải cứ nghỉ là hết mệt.", "休めば疲れが取れるというものでもない。"],
        ],
        [
          ["努力すれば報われるというものではない。", "Không phải cứ nỗ lực là được đền đáp."],
          ["便利なら使いやすいというものでもない。", "Cũng chẳng phải cứ tiện là dễ dùng."],
          ["経験があれば成功するというものではない。", "Không phải cứ có kinh nghiệm là thành công."],
          ["安いから悪いというものでもない。", "Cũng chẳng phải cứ rẻ là kém."],
          ["忙しいほど偉いというものではない。", "Không phải cứ càng bận càng giỏi/đáng nể."],
          ["笑っていれば平気というものでもない。", "Cũng chẳng phải cứ cười là không sao."],
          ["規則を守れば十分というものではない。", "Không phải cứ giữ quy tắc là đủ."],
          ["有名なら信頼できるというものでもない。", "Cũng chẳng phải cứ nổi tiếng là đáng tin."],
          ["時間が解決するというものではない。", "Không phải cứ thời gian sẽ giải quyết."],
          ["反対が多ければ誤りというものでもない。", "Cũng chẳng phải cứ nhiều người phản đối là sai."],
        ],
        [
          ["Cứ có tiền chưa chắc đã hạnh phúc.", ["金があれば", "幸せ", "というものでは", "ない。"], 2],
          ["Cứ luyện chưa chắc đã tiến bộ.", ["練習すれば", "上達する", "というものでも", "ない。"], 2],
          ["Cứ trẻ chưa chắc là không quá sức.", ["若いからと", "無理がない", "というものでは", "ない。"], 2],
          ["Không phải cứ đắt là chất lượng tốt.", ["高ければ", "品質がいい", "というものでは", "ない。"], 2],
          ["Cũng chẳng phải cứ im là đồng ý.", ["黙っていれば", "賛成", "というものでも", "ない。"], 2],
          ["Không phải cứ nhanh là tốt.", ["速ければ", "いい", "というものでは", "ない。"], 2],
          ["Không phải cứ nỗ lực là được đền đáp.", ["努力すれば", "報われる", "というものでは", "ない。"], 2],
          ["Cũng chẳng phải cứ rẻ là kém.", ["安いから", "悪い", "というものでも", "ない。"], 2],
          ["Không phải cứ thời gian sẽ giải quyết.", ["時間が", "解決する", "というものでは", "ない。"], 2],
          ["Cũng chẳng phải cứ nổi tiếng là đáng tin.", ["有名なら", "信頼できる", "というものでも", "ない。"], 2],
        ],
      ),
    ),
  ];
}
