import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L21-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 21, BATCH);

export function lesson21Patterns(byId) {
  return [
    P(
      byId,
      "l21-g01",
      {
        meaning: "Đến mức… / khoảng… / ít ra cũng…",
        structures: ["N／普通形 ＋ くらい（ぐらい）", "Vる ＋ くらい（ぐらい）"],
        explanation:
          "くらい／ぐらい nêu mức độ ước lượng, so sánh mức, hoặc nhấn 'ít ra cũng đến mức A'.",
        usage: "Ước lượng số lượng/thời gian; nhấn mức độ đáng kể hoặc tối thiểu.",
        cautions: [
          "くらい và ぐらい gần như thay thế được; ぐらい hơi khẩu ngữ hơn.",
          "Khác ほど khi chỉ so sánh mức độ thuần; くらい còn dùng ước lượng số.",
        ],
        contrast:
          "くらい ≈ đến mức / khoảng. Gần ほど (mức độ) nhưng くらい cũng dùng ước lượng.",
        examples: [
          ex(
            "泣きたいくらい悔しかった。",
            "なきたいくらいくやしかった。",
            "Đau khổ đến mức muốn khóc.",
            [
              ["泣", "な"],
              ["きたいくらい"],
              ["悔", "くや"],
              ["しかった。"],
            ],
          ),
          ex(
            "駅まで歩いて十分ぐらいかかる。",
            "えきまであるいてじゅっぷんぐらいかかる。",
            "Đi bộ đến ga mất khoảng mười phút.",
            [
              ["駅", "えき"],
              ["まで"],
              ["歩", "ある"],
              ["いて"],
              ["十分", "じゅっぷん"],
              ["ぐらいかかる。"],
            ],
          ),
          ex(
            "自分の名前ぐらいは書ける。",
            "じぶんのなまえぐらいはかける。",
            "Ít ra cũng viết được tên mình.",
            [
              ["自分", "じぶん"],
              ["の"],
              ["名前", "なまえ"],
              ["ぐらいは"],
              ["書", "か"],
              ["ける。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜くらい／ぐらい",
        "Câu くらい／ぐらい: mức độ, ước lượng, hoặc 'ít ra cũng…'.",
        [
          ["Mệt đến mức đứng không nổi.", "立っていられないくらい疲れた。"],
          ["Còn khoảng năm phút nữa.", "あと五分ぐらいだ。"],
          ["Ít ra cũng biết chào hỏi.", "挨拶ぐらいはできる。"],
          ["Vui đến mức nhảy lên.", "飛び上がるくらい嬉しかった。"],
          ["Đến mức không ngủ được.", "眠れないくらい心配だ。"],
          ["Cách đây khoảng hai kilômét.", "ここから二キロぐらいだ。"],
          ["Ít ra cũng đọc được hiragana.", "ひらがなぐらいは読める。"],
          ["Đau đến mức muốn kêu.", "叫び声が出るくらい痛かった。"],
          ["Khoảng ba người sẽ đến.", "三人ぐらいは来るだろう。"],
          ["Ít ra cũng mang theo tiền mặt.", "現金ぐらいは持っていく。"],
        ],
        [
          ["見えなくなるくらい遠かった。", "Xa đến mức gần như không thấy."],
          ["一時間ぐらい待てますか。", "Có thể đợi khoảng một tiếng không?"],
          ["自分の住所ぐらいは覚えている。", "Ít ra cũng nhớ địa chỉ mình."],
          ["倒れそうなくらい眠い。", "Buồn ngủ đến mức suýt ngã."],
          ["五百円ぐらいしかない。", "Chỉ còn khoảng năm trăm yên."],
          ["謝るくらいの余裕はある。", "Ít ra cũng còn đủ sức xin lỗi."],
          ["忘れられないくらい印象的だった。", "Ấn tượng đến mức không quên được."],
          ["十分ぐらい休憩しよう。", "Nghỉ khoảng mười phút thôi."],
          ["自分の番ぐらいは分かる。", "Ít ra cũng biết đến lượt mình."],
          ["泣けてくるくらい感動した。", "Cảm động đến mức muốn khóc."],
        ],
        [
          ["Mệt đứng không nổi nữa.", ["立っていられないくらい", "疲れ果てて", "しまった", "。"], 0],
          ["Còn năm phút nữa thôi.", ["あと五分ぐらいで", "始まる予定", "だ", "。"], 0],
          ["Ít ra biết chào hỏi.", ["挨拶ぐらいは", "きちんと", "できる", "。"], 0],
          ["Vui muốn nhảy lên.", ["飛び上がるくらい", "嬉しくて", "たまらない", "。"], 0],
          ["Lo đến mức mất ngủ.", ["眠れないくらい", "不安に", "なっている", "。"], 0],
          ["Cách đây khoảng hai km.", ["ここから二キロぐらい", "離れていると", "思う", "。"], 0],
          ["Ít ra đọc được kana.", ["ひらがなぐらいは", "読めるように", "なった", "。"], 0],
          ["Đau muốn kêu lên.", ["叫ぶくらい", "痛みが", "強かった", "。"], 0],
          ["Khoảng ba người tới.", ["三人ぐらいは", "会場に", "来る", "。"], 0],
          ["Ít ra mang tiền mặt.", ["現金ぐらいは", "用意して", "おく", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l21-g02",
      {
        meaning: "Những thứ như… / (khinh thường) cái kiểu…",
        structures: [
          "N ＋ など／なんか／なんて",
          "普通形 ＋ なんて",
        ],
        explanation:
          "など liệt kê/ví dụ nhẹ; なんか／なんて khẩu ngữ, thường hạ thấp hoặc kinh ngạc trước đối tượng.",
        usage: "Nói nhẹ 'v.v.'; phủ định/khinh thường; ngạc nhiên trước sự việc.",
        cautions: [
          "なんか／なんて khẩu ngữ; tránh trong văn bản trang trọng (dùng など／などという).",
          "なんて sau mệnh đề thường kèm đánh giá mạnh (thật không ngờ / chẳng ra gì).",
        ],
        contrast:
          "など ≈ và những thứ như…. なんか／なんて thiên hạ thấp hoặc cảm thán hơn など.",
        examples: [
          ex(
            "お菓子など持っていきます。",
            "おかしなどもっていきます。",
            "Tôi sẽ mang theo bánh kẹo gì đó.",
            [
              ["お菓子", "おかし"],
              ["など"],
              ["持", "も"],
              ["っていきます。"],
            ],
          ),
          ex(
            "お金なんかいらない。",
            "おかねなんかいらない。",
            "Tiền bạc gì đó chẳng cần.",
            [
              ["お金", "おかね"],
              ["なんかいらない。"],
            ],
          ),
          ex(
            "彼が合格するなんて信じられない。",
            "かれがごうかくするなんてしんじられない。",
            "Anh ấy đỗ thì thật không tin nổi.",
            [
              ["彼", "かれ"],
              ["が"],
              ["合格", "ごうかく"],
              ["するなんて"],
              ["信", "しん"],
              ["じられない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜など／なんか／なんて",
        "Câu など／なんか／なんて: liệt kê nhẹ hoặc hạ thấp / cảm thán.",
        [
          ["Mang theo nước uống gì đó.", "飲み物などを持参する。"],
          ["Tôi chẳng cần lời khen gì.", "褒め言葉なんかいらない。"],
          ["Cô ấy nghỉ việc thì không tin.", "彼女が辞めるなんて信じられない。"],
          ["Đồ chơi gì đó để trên bàn.", "おもちゃなどが机の上にある。"],
          ["Lời xin lỗi kiểu đó vô nghĩa.", "そんな謝罪なんかに意味はない。"],
          ["Tôi thắng giải thì thật lạ.", "私が受賞するなんて奇妙だ。"],
          ["Sách báo gì đó xếp góc phòng.", "本や雑誌などを隅に置く。"],
          ["Anh ấy chẳng biết lễ nghi gì.", "彼は礼儀なんかわからない。"],
          ["Đến muộn thì không chấp nhận.", "遅刻するなんて許されない。"],
          ["Quà vặt gì đó cũng được.", "手土産などがあれば十分だ。"],
        ],
        [
          ["書類などを机に置いてください。", "Hãy để giấy tờ gì đó lên bàn."],
          ["言い訳なんかを聞きたくない。", "Chẳng muốn nghe lời bao biện gì."],
          ["彼が嘘をつくなんて思わなかった。", "Không ngờ anh ấy lại nói dối."],
          ["果物などを買って帰ろう。", "Mua hoa quả gì đó rồi về thôi."],
          ["趣味なんかより仕事が大事だ。", "Việc quan trọng hơn thú vui tầm phào."],
          ["失敗するなんてあり得ない。", "Thất bại thì không thể nào."],
          ["名刺などを忘れないでください。", "Đừng quên danh thiếp gì đó."],
          ["泣き言なんかを言うな。", "Đừng có than vãn kiểu đó."],
          ["彼女が怒るなんて珍しい。", "Cô ấy giận thì thật hiếm."],
          ["掃除道具などを片付ける。", "Dọn cất dụng cụ vệ sinh gì đó."],
        ],
        [
          ["Mang theo đồ uống nữa.", ["飲み物などを", "忘れずに", "持参する", "。"], 0],
          ["Chẳng cần lời khen.", ["褒め言葉なんか", "全く", "いらない", "。"], 0],
          ["Cô ấy nghỉ thật không tin.", ["彼女が辞めるなんて", "到底", "信じられない", "。"], 0],
          ["Đồ chơi để trên bàn.", ["おもちゃなどが", "机の上に", "並んでいる", "。"], 0],
          ["Xin lỗi kiểu đó vô nghĩa.", ["そんな謝罪なんかに", "価値は", "ない", "。"], 0],
          ["Tôi đoạt giải thật lạ.", ["私が受賞するなんて", "不思議で", "ならない", "。"], 0],
          ["Sách báo xếp góc phòng.", ["本や雑誌などを", "部屋の隅に", "置く", "。"], 0],
          ["Anh chẳng biết lễ nghi.", ["礼儀なんかを", "心得て", "いない", "。"], 0],
          ["Đến muộn không chấp nhận.", ["遅刻するなんて", "絶対に", "許されない", "。"], 0],
          ["Quà vặt cũng đủ rồi.", ["手土産などがあれば", "それで", "十分だ", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l21-g03",
      {
        meaning: "Đến mức… / thậm chí làm… / đến nỗi phải…",
        structures: [
          "N ＋ まで（して）",
          "Vて ＋ まで",
        ],
        explanation:
          "まで／までして／てまで nhấn cực điểm: thậm chí đến mức A (thường quá đáng hoặc hy sinh lớn).",
        usage: "Phê phán/ngạc nhiên vì mức độ cực đoan; nêu quyết tâm bất chấp.",
        cautions: [
          "てまで thường kèm đánh giá tiêu cực hoặc nghi vấn 'có đáng không'.",
          "Khác まで thời gian/không gian ('cho đến'); ngữ cảnh nhấn mạnh mức độ.",
        ],
        contrast:
          "までして／てまで ≈ thậm chí đến mức…. Khác さえ (cũng/thậm chí) thiên liệt kê cực điểm nhẹ hơn.",
        examples: [
          ex(
            "借金までして車を買った。",
            "しゃっきんまでしてくるまをかった。",
            "Thậm chí vay nợ để mua xe.",
            [
              ["借金", "しゃっきん"],
              ["までして"],
              ["車", "くるま"],
              ["を"],
              ["買", "か"],
              ["った。"],
            ],
          ),
          ex(
            "嘘をついてまで合格したいのか。",
            "うそをついてまでごうかくしたいのか。",
            "Đến mức nói dối chỉ để đỗ sao?",
            [
              ["嘘", "うそ"],
              ["を"],
              ["ついてまで"],
              ["合格", "ごうかく"],
              ["したいのか。"],
            ],
          ),
          ex(
            "夜中まで働いて疲れ果てた。",
            "よなかまではたらいてつかれはてた。",
            "Làm đến tận nửa đêm rồi kiệt sức.",
            [
              ["夜中", "よなか"],
              ["まで"],
              ["働", "はたら"],
              ["いて"],
              ["疲", "つか"],
              ["れ"],
              ["果", "は"],
              ["てた。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜まで／までして／てまで",
        "Câu まで／までして／てまで: nhấn cực điểm 'thậm chí đến mức…'.",
        [
          ["Thậm chí bỏ việc để đi du lịch.", "仕事を辞めてまで旅行した。"],
          ["Đến mức khóc mới xin lỗi.", "泣くまで謝った。"],
          ["Vay tiền để tổ chức tiệc.", "借金までして宴会を開いた。"],
          ["Đến mức gian lận chỉ để thắng?", "不正をしてまで勝ちたいのか。"],
          ["Làm đến tận sáng mới xong.", "朝まで作業して終わらせた。"],
          ["Hy sinh sức khỏe để kiếm tiền.", "健康を犠牲にしてまで稼いだ。"],
          ["Đến mức quỳ xuống van xin.", "土下座までして頼んだ。"],
          ["Nói dối để giữ thể diện?", "嘘をついてまで体面を保つのか。"],
          ["Học đến đêm khuya mới ngủ.", "深夜まで勉強してから寝た。"],
          ["Bán nhà để trả nợ.", "家を売ってまで借金を返した。"],
        ],
        [
          ["徹夜してまで資料を仕上げた。", "Thức trắng để hoàn thành tài liệu."],
          ["親に嘘までついた。", "Thậm chí nói dối cả bố mẹ."],
          ["命を危険にさらしてまで救助した。", "Đến mức liều mạng để cứu người."],
          ["借金をしてまでブランド品を買うな。", "Đừng vay nợ chỉ để mua hàng hiệu."],
          ["夜中まで議論が続いた。", "Tranh luận kéo dài đến nửa đêm."],
          ["泣いてまで反対する必要はない。", "Không cần phản đối đến mức khóc."],
          ["退職してまで独立した。", "Thậm chí nghỉ việc để độc lập."],
          ["規則を破ってまで参加したいのか。", "Đến mức phá luật chỉ để tham gia sao?"],
          ["朝まで練習を続けた。", "Luyện tập liên tục đến sáng."],
          ["貯金を崩してまで援助した。", "Thậm chí phá tiết kiệm để hỗ trợ."],
        ],
        [
          ["Nghỉ việc để đi du lịch.", ["仕事を辞めてまで", "海外旅行に", "行った", "。"], 0],
          ["Khóc mới chịu xin lỗi.", ["泣くまで", "何度も", "謝った", "。"], 0],
          ["Vay nợ để mở tiệc.", ["借金までして", "盛大な宴会を", "開いた", "。"], 0],
          ["Gian lận chỉ để thắng?", ["不正をしてまで", "勝利を", "求めるのか", "。"], 0],
          ["Làm đến sáng mới xong.", ["朝まで作業して", "ようやく", "終わらせた", "。"], 0],
          ["Hy sinh sức khỏe kiếm tiền.", ["健康を犠牲にしてまで", "お金を", "稼いだ", "。"], 0],
          ["Quỳ xuống để van xin.", ["土下座までして", "許しを", "頼んだ", "。"], 0],
          ["Nói dối giữ thể diện?", ["嘘をついてまで", "体面を", "守るのか", "。"], 0],
          ["Học đến khuya rồi ngủ.", ["深夜まで勉強して", "やっと", "眠った", "。"], 0],
          ["Bán nhà mới trả hết nợ.", ["家を売ってまで", "借金を", "返済した", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l21-g04",
      {
        meaning: "Không một ai / không một… nào (làm)…",
        structures: [
          "一人として〜ない",
          "一日として〜ない",
          "N ＋ として ＋ 否定",
        ],
        explanation:
          "として〜ない nhấn phủ định toàn bộ: không một N nào (làm/có)… — thường với 一人／一日／一度…",
        usage: "Nhấn mạnh sự vắng bóng hoàn toàn: không ai đồng ý; không ngày nào yên.",
        cautions: [
          "Luôn đi với phủ định; không dùng khẳng định sau として theo nghĩa này.",
          "Khác として nghĩa 'với tư cách là…'.",
        ],
        contrast:
          "として〜ない ≈ không một… nào. Gần も〜ない nhưng trang trọng/nhấn mạnh hơn.",
        examples: [
          ex(
            "一人として反対しなかった。",
            "ひとりとしてはんたいしなかった。",
            "Không một ai phản đối.",
            [
              ["一人", "ひとり"],
              ["として"],
              ["反対", "はんたい"],
              ["しなかった。"],
            ],
          ),
          ex(
            "一日として安心できない。",
            "いちにちとしてあんしんできない。",
            "Không một ngày nào yên tâm được.",
            [
              ["一日", "いちにち"],
              ["として"],
              ["安心", "あんしん"],
              ["できない。"],
            ],
          ),
          ex(
            "一度として約束を破ったことがない。",
            "いちどとしてやくそくをやぶったことがない。",
            "Chưa từng một lần thất hứa.",
            [
              ["一度", "いちど"],
              ["として"],
              ["約束", "やくそく"],
              ["を"],
              ["破", "やぶ"],
              ["ったことがない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜として〜ない",
        "Câu として＋否定: không một (người/ngày/lần) nào….",
        [
          ["Không một ai cười.", "一人として笑わなかった。"],
          ["Không ngày nào quên luyện tập.", "一日として練習を怠らない。"],
          ["Chưa một lần bỏ cuộc.", "一度として諦めなかった。"],
          ["Không ai hiểu ý tôi.", "一人として私の意図を理解しない。"],
          ["Không đêm nào ngủ ngon.", "一夜として熟睡できない。"],
          ["Chưa lần nào đến muộn.", "一度として遅刻したことがない。"],
          ["Không ai chịu giúp.", "一人として手伝おうとしない。"],
          ["Không ngày nào hết lo.", "一日として心配事が絶えない。"],
          ["Chưa lần nào nói dối.", "一度として嘘をついたことがない。"],
          ["Không ai biết câu trả lời.", "一人として答えを知らない。"],
        ],
        [
          ["一人として賛成しなかった。", "Không một ai tán thành."],
          ["一日として暇な日がない。", "Không một ngày nào rảnh."],
          ["一度として文句を言わない。", "Chưa từng một lần phàn nàn."],
          ["一人として逃げなかった。", "Không ai bỏ chạy."],
          ["一夜として静かではなかった。", "Không đêm nào yên tĩnh."],
          ["一度として嘘はつかない。", "Không bao giờ nói dối dù một lần."],
          ["一人として彼を責めない。", "Không ai trách anh ấy."],
          ["一日として連絡を欠かさない。", "Không ngày nào bỏ liên lạc."],
          ["一度として約束を破らない。", "Không lần nào phá lời hứa."],
          ["一人として疑問を持たなかった。", "Không ai có nghi vấn."],
        ],
        [
          ["Không ai cười cả.", ["一人として", "笑おうとも", "しなかった", "。"], 0],
          ["Không ngày nào bỏ luyện.", ["一日として", "練習を", "怠らない", "。"], 0],
          ["Chưa lần nào bỏ cuộc.", ["一度として", "諦めようと", "しなかった", "。"], 0],
          ["Chẳng ai hiểu ý tôi.", ["一人として", "私の意図を", "理解しない", "。"], 0],
          ["Không đêm nào ngủ sâu.", ["一夜として", "ぐっすり", "眠れない", "。"], 0],
          ["Chưa lần nào muộn giờ.", ["一度として", "遅刻など", "していない", "。"], 0],
          ["Không ai chịu giúp đỡ.", ["一人として", "手伝おうと", "しない", "。"], 0],
          ["Lo lắng không ngày nào dứt.", ["一日として", "心配事が", "消えない", "。"], 0],
          ["Chưa từng nói dối lần nào.", ["一度として", "嘘をついた", "覚えがない", "。"], 0],
          ["Không ai biết đáp án.", ["一人として", "正解を", "知らない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l21-g05",
      {
        meaning: "Thậm chí… / ngay cả… cũng…",
        structures: ["N ＋ さえ（も）", "Nでさえ", "Vます ＋ さえすれば"],
        explanation:
          "さえ nhấn cực điểm: ngay cả A (cũng)… — thường kèm phủ định hoặc điều kiện tối thiểu さえすれば.",
        usage: "Nhấn 'ngay cả… cũng không/có'; nêu điều kiện tối thiểu đủ để…",
        cautions: [
          "でさえ nhấn mạnh hơn さえ một chút.",
          "さえすれば = chỉ cần… là đủ; khác さえ phủ định.",
        ],
        contrast:
          "さえ ≈ thậm chí/ngay cả. Gần まで (cực điểm) và も nhưng さえ nhấn 'không ngờ cả A'.",
        examples: [
          ex(
            "子供でさえ分かる問題だ。",
            "こどもでさえわかるもんだいだ。",
            "Ngay cả trẻ con cũng hiểu câu hỏi này.",
            [
              ["子供", "こども"],
              ["でさえ"],
              ["分", "わ"],
              ["かる"],
              ["問題", "もんだい"],
              ["だ。"],
            ],
          ),
          ex(
            "名前さえ思い出せない。",
            "なまえさえおもいだせない。",
            "Đến tên cũng không nhớ ra.",
            [
              ["名前", "なまえ"],
              ["さえ"],
              ["思", "おも"],
              ["い"],
              ["出", "だ"],
              ["せない。"],
            ],
          ),
          ex(
            "休みさえあれば旅行したい。",
            "やすみさえあればりょこうしたい。",
            "Chỉ cần có nghỉ là muốn đi du lịch.",
            [
              ["休", "やす"],
              ["みさえあれば"],
              ["旅行", "りょこう"],
              ["したい。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜さえ",
        "Câu さえ／でさえ: ngay cả… cũng…; さえすれば = chỉ cần….",
        [
          ["Ngay cả giáo viên cũng nhầm.", "先生でさえ間違える。"],
          ["Đến nước cũng không uống nổi.", "水さえ飲めない。"],
          ["Chỉ cần cố là được.", "努力しさえすれば成功する。"],
          ["Ngay cả người lớn cũng sợ.", "大人でさえ怖がる。"],
          ["Đến chào cũng quên.", "挨拶さえ忘れてしまった。"],
          ["Chỉ cần có thời gian là đi.", "時間さえあれば行く。"],
          ["Ngay cả máy cũng hỏng.", "機械でさえ故障した。"],
          ["Đến đứng cũng khó.", "立つことさえ難しい。"],
          ["Chỉ cần đọc kỹ là hiểu.", "よく読みさえすれば分かる。"],
          ["Ngay cả bạn thân cũng không biết.", "親友でさえ知らない。"],
        ],
        [
          ["初心者でさえ操作できる。", "Ngay cả người mới cũng thao tác được."],
          ["声さえ出せなかった。", "Đến tiếng cũng không phát ra được."],
          ["練習しさえすれば上達する。", "Chỉ cần luyện là tiến bộ."],
          ["専門家でさえ判断に迷う。", "Ngay cả chuyên gia cũng do dự."],
          ["一言さえ言えなかった。", "Đến một lời cũng không nói được."],
          ["天気さえ良ければ出発する。", "Chỉ cần thời tiết đẹp là xuất phát."],
          ["子供でさえ知っている事実だ。", "Sự thật ngay cả trẻ con cũng biết."],
          ["呼吸さえ苦しい。", "Đến thở cũng khó khăn."],
          ["連絡しさえすれば助かる。", "Chỉ cần liên lạc là được cứu."],
          ["社長でさえ例外ではない。", "Ngay cả giám đốc cũng không ngoại lệ."],
        ],
        [
          ["Giáo viên cũng nhầm luôn.", ["先生でさえ", "時々", "間違える", "。"], 0],
          ["Nước cũng không uống nổi.", ["水さえ", "喉を", "通らない", "。"], 0],
          ["Chỉ cần cố là thành công.", ["努力しさえすれば", "必ず", "成功する", "。"], 0],
          ["Người lớn cũng thấy sợ.", ["大人でさえ", "恐怖を", "感じる", "。"], 0],
          ["Chào hỏi cũng quên mất.", ["挨拶さえ", "すっかり", "忘れた", "。"], 0],
          ["Có thời gian là sẽ đi.", ["時間さえあれば", "すぐに", "行く", "。"], 0],
          ["Máy móc cũng bị hỏng.", ["機械でさえ", "突然", "故障した", "。"], 0],
          ["Đứng dậy cũng khó khăn.", ["立つことさえ", "容易では", "ない", "。"], 0],
          ["Đọc kỹ là sẽ hiểu.", ["よく読みさえすれば", "内容が", "分かる", "。"], 0],
          ["Bạn thân cũng không biết.", ["親友でさえ", "真相を", "知らない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l21-g06",
      {
        meaning: "Dù phải… cũng (làm)… / cho dù phải…",
        structures: ["Vて ＋ でも"],
        explanation:
          "てでも bày tỏ quyết tâm mạnh: dù phải làm A (bất tiện/cực đoan) cũng muốn đạt B.",
        usage: "Quyết tâm bất chấp phương tiện: dù vay nợ cũng mua; dù nghỉ việc cũng đi.",
        cautions: [
          "Thường kèm ý chí mạnh (たい／つもり／なければならない).",
          "Khác ても (dù… vẫn) trung tính hơn; てでも nhấn 'bằng mọi giá'.",
        ],
        contrast:
          "てでも ≈ dù phải… cũng…. Gần までして nhưng てでも thiên quyết tâm của người nói.",
        examples: [
          ex(
            "借金してでも留学したい。",
            "しゃっきんしてでもりゅうがくしたい。",
            "Dù phải vay nợ cũng muốn du học.",
            [
              ["借金", "しゃっきん"],
              ["してでも"],
              ["留学", "りゅうがく"],
              ["したい。"],
            ],
          ),
          ex(
            "夜を徹してでも仕上げる。",
            "よをてっしてでもしあげる。",
            "Dù phải thức trắng cũng hoàn thành.",
            [
              ["夜", "よ"],
              ["を"],
              ["徹", "てっ"],
              ["してでも"],
              ["仕", "し"],
              ["上げる。"],
            ],
          ),
          ex(
            "辞めてでも自分の道を行く。",
            "やめてでもじぶんのみちをいく。",
            "Dù nghỉ việc cũng đi con đường mình.",
            [
              ["辞", "や"],
              ["めてでも"],
              ["自分", "じぶん"],
              ["の"],
              ["道", "みち"],
              ["を"],
              ["行", "い"],
              ["く。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜てでも",
        "Câu Vて＋でも: dù phải… cũng (quyết tâm đạt mục tiêu).",
        [
          ["Dù phải bán xe cũng trả nợ.", "車を売ってでも借金を返す。"],
          ["Dù phải xếp hàng cũng mua.", "並んででも手に入れる。"],
          ["Dù phải đi bộ cũng đến kịp.", "歩いてでも間に合わせる。"],
          ["Dù phải vay cũng cứu bạn.", "借りてでも友人を助ける。"],
          ["Dù phải thức khuya cũng ôn.", "夜更かししてでも復習する。"],
          ["Dù phải đổi lịch cũng gặp.", "予定を変えてでも会う。"],
          ["Dù phải cắt giảm cũng hoàn thành.", "経費を削ってでもやり遂げる。"],
          ["Dù phải xin lỗi cũng hòa giải.", "頭を下げてでも仲直りする。"],
          ["Dù phải đổi nghề cũng theo đuổi.", "転職してでも夢を追う。"],
          ["Dù phải chờ lâu cũng đăng ký.", "長く待ってでも申し込む。"],
        ],
        [
          ["徹夜してでも論文を書く。", "Dù thức trắng cũng viết luận văn."],
          ["借金してでも家を買う。", "Dù vay nợ cũng mua nhà."],
          ["走ってでも会場に着く。", "Dù phải chạy cũng tới hội trường."],
          ["休職してでも介護する。", "Dù nghỉ việc tạm cũng chăm sóc."],
          ["謝ってでも協力を得る。", "Dù xin lỗi cũng tranh thủ hợp tác."],
          ["遠回りしてでも安全を選ぶ。", "Dù đường vòng cũng chọn an toàn."],
          ["節約してでも留学費用を貯める。", "Dù tiết kiệm cũng tích phí du học."],
          ["無理してでも締め切りに間に合わせる。", "Dù gắng sức cũng kịp hạn."],
          ["対立してでも意見を通す。", "Dù đối đầu cũng giữ ý kiến."],
          ["夜行列車に乗ってでも帰る。", "Dù tàu đêm cũng về nhà."],
        ],
        [
          ["Bán xe cũng trả hết nợ.", ["車を売ってでも", "借金を", "完済する", "。"], 0],
          ["Xếp hàng cũng phải mua.", ["何時間並んででも", "商品を", "入手する", "。"], 0],
          ["Đi bộ cũng đến kịp giờ.", ["歩いてでも", "開始に", "間に合わせる", "。"], 0],
          ["Vay tiền cũng cứu bạn.", ["金を借りてでも", "友人を", "助ける", "。"], 0],
          ["Thức khuya cũng ôn bài.", ["夜更かししてでも", "試験勉強を", "続ける", "。"], 0],
          ["Đổi lịch cũng gặp mặt.", ["予定を変えてでも", "直接", "会う", "。"], 0],
          ["Cắt chi phí cũng hoàn tất.", ["経費を削ってでも", "計画を", "やり遂げる", "。"], 0],
          ["Cúi đầu cũng hòa giải.", ["頭を下げてでも", "関係を", "修復する", "。"], 0],
          ["Đổi nghề cũng theo đuổi.", ["転職してでも", "夢を", "追いかけたい", "。"], 0],
          ["Chờ lâu cũng đăng ký.", ["何時間待ってでも", "手続きを", "済ませる", "。"], 0],
        ],
      ),
    ),
  ];
}
