import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L16-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 18, BATCH);

export function lesson18Patterns(byId) {
  return [
    P(
      byId,
      "l18-g01",
      {
        meaning: "Khó mà… / không dễ… (cảm xúc, đánh giá)",
        structures: ["Vます ＋ がたい"],
        explanation:
          "がたい gắn vào thân ます: khó làm/chấp nhận về mặt tinh thần hoặc đánh giá, không chỉ khó kỹ thuật.",
        usage: "Tin tức, bình luận: khó tin, khó chấp nhận, khó quên.",
        cautions: [
          "Thường với động từ liên quan cảm xúc/đánh giá: 信じがたい、許しがたい、忘れがたい.",
          "Khác にくい (khó vì tính chất/kỹ thuật); がたい mang sắc thái chủ quan mạnh hơn.",
        ],
        contrast: "がたい ≈ khó mà…. Gần にくい nhưng thiên đánh giá/cảm xúc hơn.",
        examples: [
          ex(
            "彼の話は信じがたい。",
            "かれのはなしはしんじがたい。",
            "Chuyện anh ấy nói thật khó tin.",
            [
              ["彼", "かれ"],
              ["の"],
              ["話", "はなし"],
              ["は"],
              ["信", "しん"],
              ["じがたい。"],
            ],
          ),
          ex(
            "あの光景は忘れがたい。",
            "あのこうけいはわすれがたい。",
            "Cảnh tượng ấy thật khó quên.",
            [
              ["あの"],
              ["光景", "こうけい"],
              ["は"],
              ["忘", "わす"],
              ["れがたい。"],
            ],
          ),
          ex(
            "暴力は許しがたい行為だ。",
            "ぼうりょくはゆるしがたいこういだ。",
            "Bạo lực là hành vi khó chấp nhận.",
            [
              ["暴力", "ぼうりょく"],
              ["は"],
              ["許", "ゆる"],
              ["しがたい"],
              ["行為", "こうい"],
              ["だ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜がたい",
        "Câu dùng がたい: khó mà… (đánh giá/cảm xúc).",
        [
          ["Lời giải thích ấy khó chấp nhận.", "その説明は受け入れがたい。"],
          ["Kết quả này khó hiểu.", "この結果は理解しがたい。"],
          ["Thái độ ấy khó tha thứ.", "あの態度は許しがたい。"],
          ["Tin này khó tin nổi.", "このニュースは信じがたい。"],
          ["Kỷ niệm ấy khó quên.", "その思い出は忘れがたい。"],
          ["Yêu cầu này khó thực hiện.", "この要求は応じがたい。"],
          ["Hành động ấy khó bào chữa.", "その行為は弁解しがたい。"],
          ["Sự thật ấy khó thừa nhận.", "その事実は認めがたい。"],
          ["Cách nói ấy khó chịu.", "その言い方は耐えがたい。"],
          ["Quyết định ấy khó ủng hộ.", "その決定は支持しがたい。"],
        ],
        [
          ["彼の主張は理解しがたい。", "Chủ trương của anh ấy khó hiểu."],
          ["裏切りは許しがたい。", "Phản bội thật khó tha thứ."],
          ["その光景は忘れがたい。", "Cảnh ấy thật khó quên."],
          ["この数字は信じがたい。", "Con số này khó tin."],
          ["不正は見逃しがたい。", "Bất chính khó bỏ qua."],
          ["その提案は受け入れがたい。", "Đề xuất ấy khó chấp nhận."],
          ["この結論は納得しがたい。", "Kết luận này khó tâm phục."],
          ["侮辱は耐えがたい。", "Sỉ nhục thật khó chịu."],
          ["その扱い方は認めがたい。", "Cách đối xử ấy khó thừa nhận."],
          ["この条件は応じがたい。", "Điều kiện này khó đáp ứng."],
        ],
        [
          ["Chuyện anh ấy khó tin.", ["彼の話は", "信じ", "がたい", "ものだ。"], 0],
          ["Cảnh tượng khó quên.", ["あの光景は", "忘れ", "がたい", "だろう。"], 0],
          ["Bạo lực thật khó chấp nhận.", ["暴力は", "許しがたい", "行為で", "ある。"], 0],
          ["Kết quả khó hiểu.", ["この結果は", "理解し", "がたい", "。"], 0],
          ["Tin tức khó tin.", ["このニュースは", "信じ", "がたい", "。"], 0],
          ["Thái độ khó tha thứ.", ["あの態度は", "許し", "がたい", "。"], 0],
          ["Kỷ niệm khó quên.", ["その思い出は", "忘れ", "がたい", "。"], 0],
          ["Yêu cầu khó đáp ứng.", ["この要求は", "応じ", "がたい", "。"], 0],
          ["Sự thật khó thừa nhận.", ["その事実は", "認め", "がたい", "。"], 0],
          ["Quyết định khó ủng hộ.", ["その決定は", "支持し", "がたい", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l18-g02",
      {
        meaning: "Không thể… (vì lý do đạo đức/nghĩa vụ) / cũng không thể không…",
        structures: [
          "Vる ＋ わけにはいかない",
          "Vない ＋ わけにはいかない",
          "Vる ＋ わけにもいかない",
        ],
        explanation:
          "わけにはいかない: không thể làm vì quy tắc, trách nhiệm, lương tâm. わけにもいかない: cũng không thể (làm) vì lý do tương tự, thường mềm hơn.",
        usage: "Từ chối lịch sự, tự ràng buộc: không thể bỏ cuộc, không thể nói dối.",
        cautions: [
          "Khác できない (không có khả năng); đây là 'không nên/không được phép về mặt lý'.",
          "Vないわけにはいかない ≈ buộc phải làm (không thể không làm).",
        ],
        contrast:
          "わけにはいかない ≈ không thể…. わけにもいかない ≈ cũng không thể…. Khác てはいけない (cấm trực tiếp).",
        examples: [
          ex(
            "ここで諦めるわけにはいかない。",
            "ここであきらめるわけにはいかない。",
            "Không thể bỏ cuộc ở đây.",
            [
              ["ここで"],
              ["諦", "あきら"],
              ["めるわけにはいかない。"],
            ],
          ),
          ex(
            "嘘をつくわけにはいかない。",
            "うそをつくわけにはいかない。",
            "Không thể nói dối.",
            [
              ["嘘", "うそ"],
              ["を"],
              ["つ"],
              ["くわけにはいかない。"],
            ],
          ),
          ex(
            "何も言わないわけにもいかない。",
            "なにもいわないわけにもいかない。",
            "Cũng không thể không nói gì.",
            [
              ["何", "なに"],
              ["も"],
              ["言", "い"],
              ["わないわけにもいかない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜わけにはいかない",
        "Câu dùng わけにはいかない／わけにもいかない: không thể… vì lý do đạo đức/nghĩa vụ.",
        [
          ["Không thể bỏ mặc đồng nghiệp.", "同僚を放っておくわけにはいかない。"],
          ["Không thể đến muộn họp quan trọng.", "重要な会議に遅れるわけにはいかない。"],
          ["Không thể phá lời hứa.", "約束を破るわけにはいかない。"],
          ["Cũng không thể từ chối lời mời.", "招待を断るわけにもいかない。"],
          ["Không thể im lặng mãi.", "黙っているわけにはいかない。"],
          ["Không thể tiêu tiền lung tung.", "お金を無駄にするわけにはいかない。"],
          ["Cũng không thể không giúp.", "手伝わないわけにもいかない。"],
          ["Không thể bỏ bê sức khỏe.", "健康を疎かにするわけにはいかない。"],
          ["Không thể lộ bí mật.", "秘密を漏らすわけにはいかない。"],
          ["Cũng không thể cười vào lúc ấy.", "その場で笑うわけにもいかない。"],
        ],
        [
          ["今日は休むわけにはいかない。", "Hôm nay không thể nghỉ."],
          ["彼を無視するわけにはいかない。", "Không thể phớt lờ anh ấy."],
          ["規則を破るわけにはいかない。", "Không thể phá quy tắc."],
          ["返事をしないわけにもいかない。", "Cũng không thể không trả lời."],
          ["親に心配をかけるわけにはいかない。", "Không thể làm bố mẹ lo."],
          ["仕事を途中で放り出すわけにはいかない。", "Không thể bỏ dở công việc."],
          ["失礼なことを言うわけにもいかない。", "Cũng không thể nói thiếu lịch sự."],
          ["証拠を隠すわけにはいかない。", "Không thể giấu bằng chứng."],
          ["一人で決めるわけにはいかない。", "Không thể quyết một mình."],
          ["感謝しないわけにもいかない。", "Cũng không thể không cảm ơn."],
        ],
        [
          ["Không thể bỏ cuộc lúc này.", ["今ここで", "諦める", "わけには", "いかない。"], 0],
          ["Không được phép nói dối.", ["うそを", "つく", "わけには", "いかない。"], 0],
          ["Cũng chẳng thể im thin thít.", ["黙っている", "わけにも", "いかない", "。"], 0],
          ["Không thể nuốt lời đã hứa.", ["約束を", "破る", "わけには", "いかない。"], 0],
          ["Không thể đến họp muộn.", ["会議に", "遅れる", "わけには", "いかない。"], 0],
          ["Cũng không thể từ chối.", ["招待を", "断る", "わけにも", "いかない。"], 0],
          ["Không thể để lộ mật.", ["秘密を", "漏らす", "わけには", "いかない。"], 0],
          ["Cũng chẳng thể đứng nhìn.", ["手伝わない", "わけにも", "いかない", "。"], 0],
          ["Không thể xem nhẹ sức khỏe.", ["健康を", "疎かにする", "わけには", "いかない。"], 0],
          ["Không thể tiêu phí tiền.", ["お金を", "無駄にする", "わけには", "いかない。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l18-g03",
      {
        meaning: "Không thể… / khó lòng… (lịch sự, thường từ chối)",
        structures: ["Vます ＋ かねる"],
        explanation:
          "かねる lịch sự: người nói khó/không thể làm (thường từ chối nhẹ). Không nhầm với かねない (có nguy cơ…).",
        usage: "Công sở, dịch vụ: 分かりかねます、お答えしかねます.",
        cautions: [
          "かねる = khó/không thể; かねない = có thể xảy ra (nghĩa gần như ngược).",
          "Sắc thái trang trọng; ít dùng với người thân mật.",
        ],
        contrast:
          "かねる ≈ không thể/khó lòng…. Khác できない; lịch sự hơn. Đối lập かねない (có nguy cơ).",
        examples: [
          ex(
            "その件は分かりかねます。",
            "そのけんはわかりかねます。",
            "Việc đó tôi khó lòng nắm rõ.",
            [
              ["その"],
              ["件", "けん"],
              ["は"],
              ["分", "わ"],
              ["かりかねます。"],
            ],
          ),
          ex(
            "ご要望には応じかねます。",
            "ごようぼうにはおうじかねます。",
            "Chúng tôi khó lòng đáp ứng yêu cầu của quý vị.",
            [
              ["ご"],
              ["要望", "ようぼう"],
              ["には"],
              ["応", "おう"],
              ["じかねます。"],
            ],
          ),
          ex(
            "今すぐお答えしかねます。",
            "いますぐおこたえしかねます。",
            "Tôi khó lòng trả lời ngay.",
            [
              ["今", "いま"],
              ["すぐ"],
              ["お"],
              ["答", "こた"],
              ["えしかねます。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜かねる",
        "Câu dùng かねる: khó lòng/không thể… (lịch sự).",
        [
          ["Tôi khó lòng đồng ý đề xuất ấy.", "その提案には賛成しかねます。"],
          ["Chúng tôi khó lòng thay đổi lịch.", "日程の変更はいたしかねます。"],
          ["Tôi khó lòng tiết lộ thông tin.", "情報をお伝えしかねます。"],
          ["Anh ấy khó lòng chấp nhận điều kiện.", "彼は条件を受け入れかねる。"],
          ["Tôi khó lòng bình luận việc đó.", "その件についてはコメントしかねます。"],
          ["Cửa hàng khó lòng hoàn tiền.", "返金には応じかねます。"],
          ["Tôi khó lòng hứa chắc.", "確約はいたしかねます。"],
          ["Chúng tôi khó lòng giảm giá thêm.", "これ以上の値引きはしかねます。"],
          ["Tôi khó lòng tham dự họp ấy.", "その会議には出席しかねます。"],
          ["Cô ấy khó lòng từ bỏ kế hoạch.", "彼女は計画をあきらめかねる。"],
        ],
        [
          ["詳細は説明しかねます。", "Tôi khó lòng giải thích chi tiết."],
          ["即答はいたしかねます。", "Tôi khó lòng trả lời tức thì."],
          ["ご期待には添えかねます。", "Chúng tôi khó lòng đáp ứng kỳ vọng."],
          ["その判断は下しかねます。", "Tôi khó lòng đưa ra phán đoán ấy."],
          ["個人情報は教えかねます。", "Tôi khó lòng cho biết thông tin cá nhân."],
          ["無理な要求には応じかねる。", "Khó lòng đáp ứng yêu cầu vô lý."],
          ["今の状況では賛成しかねます。", "Trong tình hình này khó lòng tán thành."],
          ["お約束はいたしかねます。", "Tôi khó lòng hứa."],
          ["その案は採用しかねます。", "Chúng tôi khó lòng áp dụng phương án ấy."],
          ["責任は負いかねます。", "Tôi khó lòng chịu trách nhiệm."],
        ],
        [
          ["Việc này khó nắm rõ.", ["この件は", "分かり", "かねます", "。"], 0],
          ["Khó đáp ứng mong muốn.", ["ご希望には", "応じ", "かねます", "。"], 0],
          ["Khó trả lời ngay bây giờ.", ["ただいまは", "お答えし", "かねます", "。"], 0],
          ["Khó đồng ý đề xuất.", ["その提案には", "賛成し", "かねます", "。"], 0],
          ["Khó hoàn tiền.", ["返金には", "応じ", "かねます", "。"], 0],
          ["Khó hứa chắc.", ["確約は", "いたし", "かねます", "。"], 0],
          ["Khó tiết lộ thông tin.", ["情報を", "お伝えし", "かねます", "。"], 0],
          ["Khó tham dự họp.", ["その会議には", "出席し", "かねます", "。"], 0],
          ["Khó giảm giá thêm.", ["値引きは", "し", "かねます", "。"], 0],
          ["Khó chịu trách nhiệm.", ["責任は", "負い", "かねます", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l18-g04",
      {
        meaning: "Không còn cách nào… / không thể làm gì được",
        structures: ["Vます ＋ ようがない／ようもない"],
        explanation:
          "ようがない／ようもない: không có phương pháp/cách để làm; nhấn mạnh bất lực vì thiếu điều kiện.",
        usage: "Khi không có thông tin, công cụ, cơ hội: 連絡のしようがない.",
        cautions: [
          "Thường đi với しよう／直しよう／助けよう… (dạng ます + よう).",
          "ようもない gần nghĩa; sắc thái hơi mạnh/văn viết hơn một chút.",
        ],
        contrast: "ようがない ≈ không còn cách. Khác できない (thiếu khả năng thuần).",
        examples: [
          ex(
            "住所が分からず連絡のしようがない。",
            "じゅうしょがわからずれんらくのしようがない。",
            "Không biết địa chỉ nên không còn cách liên lạc.",
            [
              ["住所", "じゅうしょ"],
              ["が"],
              ["分", "わ"],
              ["からず"],
              ["連絡", "れんらく"],
              ["の"],
              ["しようがない。"],
            ],
          ),
          ex(
            "壊れたら直しようがない。",
            "こわれたらなおしようがない。",
            "Nếu hỏng thì không còn cách sửa.",
            [
              ["壊", "こわ"],
              ["れたら"],
              ["直", "なお"],
              ["しようがない。"],
            ],
          ),
          ex(
            "証拠がなくて反論しようもない。",
            "しょうこがなくてはんろんしようもない。",
            "Không có bằng chứng nên cũng chẳng phản bác được.",
            [
              ["証拠", "しょうこ"],
              ["が"],
              ["なくて"],
              ["反論", "はんろん"],
              ["しようもない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ようがない",
        "Câu dùng ようがない／ようもない: không còn cách nào để…",
        [
          ["Mất chìa thì không còn cách vào.", "鍵がなくて入りようがない。"],
          ["Không biết tên thì chẳng hỏi được.", "名前が分からず聞きようがない。"],
          ["Hết liệu thì không còn cách chữa.", "薬がなくて治しようがない。"],
          ["Không có tiền thì chẳng mua được.", "金がなくて買いようがない。"],
          ["Mất số điện thoại thì không liên lạc được.", "番号がなくて連絡しようがない。"],
          ["Không có dữ liệu thì chẳng phân tích được.", "データがなくて分析しようがない。"],
          ["Xe hỏng nặng thì chẳng sửa nổi.", "車が大破して直しようもない。"],
          ["Không có manh mối thì chẳng tìm được.", "手がかりがなくて探しようがない。"],
          ["Im lặng thì chẳng giải thích nổi.", "黙っていて説明しようもない。"],
          ["Thiếu nhân lực thì chẳng hoàn thành được.", "人手不足で終えようがない。"],
        ],
        [
          ["助けを求めようがない状況だ。", "Tình huống không còn cách cầu cứu."],
          ["この傷は治しようがない。", "Vết thương này không còn cách chữa."],
          ["理由を聞きようがない。", "Không còn cách hỏi lý do."],
          ["誤りを正しようもない。", "Cũng chẳng sửa sai được."],
          ["逃げようがないほど囲まれた。", "Bị bao vây đến mức không còn đường thoát."],
          ["比較しようがないほど違う。", "Khác đến mức chẳng so sánh được."],
          ["弁解しようがない失敗だ。", "Thất bại không còn cách biện hộ."],
          ["情報が足りず判断しようがない。", "Thiếu thông tin nên không còn cách phán đoán."],
          ["修理しようがない状態だ。", "Tình trạng không còn cách sửa chữa."],
          ["慰めようもないほど悲しい。", "Buồn đến mức chẳng an ủi nổi."],
        ],
        [
          ["Không biết chỗ ở khó liên lạc.", ["居場所が分からず", "連絡の", "しようが", "ない。"], 0],
          ["Hỏng hết thì khó sửa.", ["壊れてしまえば", "直し", "ようが", "ない。"], 0],
          ["Không chứng cứ khó phản bác.", ["根拠がなくて", "反論し", "ようも", "ない。"], 0],
          ["Mất chìa khó vào.", ["鍵がなくて", "入り", "ようが", "ない。"], 0],
          ["Hết thuốc khó chữa.", ["薬がなくて", "治し", "ようが", "ない。"], 0],
          ["Không dữ liệu khó phân tích.", ["データがなくて", "分析し", "ようが", "ない。"], 0],
          ["Không manh mối khó tìm.", ["手がかりがなくて", "探し", "ようが", "ない。"], 0],
          ["Xe hỏng nặng khó sửa.", ["車が大破して", "直し", "ようも", "ない。"], 0],
          ["Thiếu người khó xong.", ["人手不足で", "終え", "ようが", "ない。"], 0],
          ["Không tiền khó mua.", ["金がなくて", "買い", "ようが", "ない。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l18-g05",
      {
        meaning: "Đâu phải lúc… / không phải tâm trạng để…",
        structures: [
          "N／Vる ＋ どころではない",
          "N／Vる ＋ どころではなく",
        ],
        explanation:
          "どころではない: hoàn toàn không phải hoàn cảnh/tâm trạng để làm việc đó; thường vì bận, mệt, khủng hoảng.",
        usage: "Từ chối vui chơi khi quá bận: 旅行どころではない.",
        cautions: [
          "Không chỉ 'không phải là…' trung tính; nhấn mạnh 'đâu rảnh/đâu phải lúc'.",
          "どころではなく thường nối sang vế đối lập mạnh hơn.",
        ],
        contrast: "どころではない ≈ đâu phải lúc…. Khác ではない thuần phủ định.",
        examples: [
          ex(
            "忙しくて旅行どころではない。",
            "いそがしくてりょこうどころではない。",
            "Bận đến mức đâu phải lúc đi du lịch.",
            [
              ["忙", "いそが"],
              ["しくて"],
              ["旅行", "りょこう"],
              ["どころではない。"],
            ],
          ),
          ex(
            "試験前で遊ぶどころではない。",
            "しけんまえであそぶどころではない。",
            "Trước kỳ thi đâu phải lúc chơi.",
            [
              ["試験", "しけん"],
              ["前", "まえ"],
              ["で"],
              ["遊", "あそ"],
              ["ぶどころではない。"],
            ],
          ),
          ex(
            "体調が悪くて食事どころではない。",
            "たいちょうがわるくてしょくじどころではない。",
            "Sức khỏe kém đến mức đâu phải lúc ăn.",
            [
              ["体調", "たいちょう"],
              ["が"],
              ["悪", "わる"],
              ["くて"],
              ["食事", "しょくじ"],
              ["どころではない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜どころではない",
        "Câu dùng どころではない: đâu phải lúc/tâm trạng để…",
        [
          ["Đang deadline đâu phải lúc nghỉ.", "締め切り前で休みどころではない。"],
          ["Nhà có việc đâu phải lúc tiệc.", "家に用事があって宴会どころではない。"],
          ["Thất nghiệp đâu phải lúc mua xe.", "失業中で車を買うどころではない。"],
          ["Đau bụng đâu phải lúc cười.", "腹痛で笑っていられるどころではない。"],
          ["Thi cử đâu phải lúc xem phim.", "受験勉強で映画どころではない。"],
          ["Sập mạng đâu phải lúc chơi game.", "システム障害でゲームどころではない。"],
          ["Chạy deadline đâu phải lúc cà phê.", "納期に追われてお茶どころではない。"],
          ["Cãi nhau đâu phải lúc du lịch.", "喧嘩中で旅行どころではない。"],
          ["Ốm nặng đâu phải lúc tập gym.", "大病で運動どころではない。"],
          ["Nợ nần đâu phải lúc mua sắm.", "借金があって買い物どころではない。"],
        ],
        [
          ["今夜は残業で寝るどころではない。", "Tối nay tăng ca đâu phải lúc ngủ."],
          ["準備不足で余裕どころではない。", "Thiếu chuẩn bị đâu còn dư dả."],
          ["火事で悠長な話どころではない。", "Hỏa hoạn đâu phải lúc nói thong thả."],
          ["赤字で投資どころではない。", "Thâm hụt đâu phải lúc đầu tư."],
          ["渋滞でのんびりどころではない。", "Kẹt xe đâu phải lúc thong dong."],
          ["苦情対応で休憩どころではない。", "Xử lý khiếu nại đâu phải lúc nghỉ."],
          ["台風で外出どころではない。", "Bão đâu phải lúc ra ngoài."],
          ["引っ越しで掃除どころではない。", "Đang chuyển nhà đâu phải lúc dọn dẹp thường."],
          ["納品前で冗談どころではない。", "Trước giao hàng đâu phải lúc đùa."],
          ["看病で自分のことはどころではない。", "Chăm bệnh đâu rảnh việc của mình."],
        ],
        [
          ["Bận đâu rảnh đi chơi xa.", ["忙しくて", "観光", "どころでは", "ない。"], 0],
          ["Sát kỳ thi đâu phải lúc chơi.", ["試験直前で", "遊ぶ", "どころでは", "ない。"], 0],
          ["Ốm đâu phải lúc ăn uống.", ["体調不良で", "食事", "どころでは", "ない。"], 0],
          ["Deadline đâu phải lúc nghỉ.", ["締め切り前で", "休み", "どころでは", "ない。"], 0],
          ["Thất nghiệp đâu mua xe.", ["失業中で", "車を買う", "どころでは", "ない。"], 0],
          ["Thi cử đâu xem phim.", ["受験勉強で", "映画", "どころでは", "ない。"], 0],
          ["Bão đâu ra ngoài.", ["台風で", "外出", "どころでは", "ない。"], 0],
          ["Thâm hụt đâu đầu tư.", ["赤字で", "投資", "どころでは", "ない。"], 0],
          ["Tăng ca đâu phải lúc ngủ.", ["残業で", "寝る", "どころでは", "ない。"], 0],
          ["Nợ nần đâu mua sắm.", ["借金があって", "買い物", "どころでは", "ない。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l18-g06",
      {
        meaning: "Có thể xảy ra… / không thể xảy ra…",
        structures: [
          "Vます ＋ 得る（うる／える）",
          "Vます ＋ 得ない（えない）",
        ],
        explanation:
          "得る diễn đạt khả năng khách quan có thể xảy ra; 得ない phủ định khả năng đó. Đọc うる hoặc える tùy ngữ cảnh (うる phổ biến trong văn viết).",
        usage: "Phân tích rủi ro, lập luận: あり得る、起こり得ない.",
        cautions: [
          "Không nhầm với 得る 'kiếm được/thu được' nghĩa từ vựng thường.",
          "あり得る rất hay gặp; phủ định thường あり得ない.",
        ],
        contrast: "得る ≈ có thể xảy ra. 得ない ≈ không thể xảy ra. Khác できる (khả năng chủ thể).",
        examples: [
          ex(
            "そのような事故は起こり得る。",
            "そのようなじこはおこりうる。",
            "Tai nạn như vậy có thể xảy ra.",
            [
              ["そのような"],
              ["事故", "じこ"],
              ["は"],
              ["起", "お"],
              ["こり得る。"],
            ],
          ),
          ex(
            "彼が裏切ることはあり得ない。",
            "かれがうらぎることはありえない。",
            "Anh ấy phản bội là điều không thể xảy ra.",
            [
              ["彼", "かれ"],
              ["が"],
              ["裏切", "うらぎ"],
              ["ることは"],
              ["あり得ない。"],
            ],
          ),
          ex(
            "最悪の場合も想定し得る。",
            "さいあくのばあいもそうていしうる。",
            "Cũng có thể giả định trường hợp xấu nhất.",
            [
              ["最悪", "さいあく"],
              ["の"],
              ["場合", "ばあい"],
              ["も"],
              ["想定", "そうてい"],
              ["し得る。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜得る／〜得ない",
        "Câu dùng 得る／得ない: có thể / không thể xảy ra (khách quan).",
        [
          ["Sai sót kiểu đó hoàn toàn có thể.", "そのようなミスは十分あり得る。"],
          ["Thất bại cũng có thể xảy ra.", "失敗も起こり得る。"],
          ["Kết quả ấy không thể xảy ra.", "その結果はあり得ない。"],
          ["Rủi ro này vẫn dự đoán được.", "このリスクは予測し得る。"],
          ["Anh ấy nói dối khó lòng xảy ra.", "彼が嘘をつくことはあり得ない。"],
          ["Thay đổi chính sách có thể xảy ra.", "方針の変更はあり得る。"],
          ["Thiên tai lớn vẫn có thể xảy ra.", "大災害も起こり得る。"],
          ["Giải pháp ấy không thể chấp nhận.", "その解決策は容認し得ない。"],
          ["Mọi tình huống đều hình dung được.", "あらゆる状況を想像し得る。"],
          ["Sự trùng hợp ấy không thể có.", "その偶然はあり得ない。"],
        ],
        [
          ["事故は誰にでも起こり得る。", "Tai nạn ai cũng có thể gặp."],
          ["この説明では納得し得ない。", "Với lời giải thích này không thể tâm phục."],
          ["誤作動もあり得る。", "Lỗi hoạt động cũng có thể xảy ra."],
          ["彼の勝利は十分あり得る。", "Chiến thắng của anh ấy hoàn toàn có thể."],
          ["そのような要求は認め得ない。", "Yêu cầu như vậy không thể chấp nhận."],
          ["最悪の事態も起こり得る。", "Tình huống xấu nhất cũng có thể xảy ra."],
          ["データ改ざんはあり得ない。", "Giả mạo dữ liệu là điều không thể xảy ra."],
          ["この仮説は検証し得る。", "Giả thuyết này có thể kiểm chứng."],
          ["全面拒否は避け得る選択だ。", "Từ chối toàn bộ là lựa chọn có thể tránh."],
          ["その結論は導き得ない。", "Không thể rút ra kết luận ấy."],
        ],
        [
          ["Tai nạn kiểu này vẫn có thể.", ["こうした事故は", "起こり", "得る", "。"], 0],
          ["Anh ấy phản bội thật khó xảy ra.", ["彼の裏切りは", "あり", "得ない", "。"], 0],
          ["Cũng có thể tính cả kịch bản xấu.", ["最悪の事態も", "想定し", "得る", "。"], 0],
          ["Sai sót kiểu đó có thể.", ["そのようなミスは", "十分", "あり", "得る。"], 0],
          ["Kết quả ấy không thể.", ["その結果は", "あり", "得ない", "。"], 0],
          ["Rủi ro vẫn dự đoán được.", ["このリスクは", "予測し", "得る", "。"], 0],
          ["Đổi chính sách có thể.", ["方針の変更は", "あり", "得る", "。"], 0],
          ["Thiên tai lớn có thể.", ["大災害も", "起こり", "得る", "。"], 0],
          ["Giải pháp không chấp nhận được.", ["その解決策は", "容認し", "得ない", "。"], 0],
          ["Trùng hợp ấy không thể.", ["その偶然は", "あり", "得ない", "。"], 0],
        ],
      ),
    ),
  ];
}
