import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L11-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 14, BATCH);

export function lesson14Patterns(byId) {
  return [
    P(
      byId,
      "l14-g01",
      {
        meaning: "Mặc dù… / dù… nhưng… (nhượng bộ trang trọng)",
        structures: ["N／普通形 ＋ にもかかわらず"],
        explanation:
          "Nhượng bộ rõ ràng: dù có A (thường bất lợi/khác thường) nhưng vẫn B; sắc thái văn viết, tin tức.",
        usage: "Báo cáo, bài luận: dù mưa to vẫn tổ chức; dù khó vẫn tiếp tục.",
        cautions: [
          "Hình thức trang trọng hơn のに; ít dùng hội thoại thân mật.",
          "Sau danh từ thường không cần だ: 雨にもかかわらず.",
        ],
        contrast: "にもかかわらず ≈ mặc dù. Gần のに; trang trọng hơn でも.",
        examples: [
          ex(
            "悪天候にもかかわらず試合は行われた。",
            "あくてんこうにもかかわらずしあいはおこなわれた。",
            "Dù thời tiết xấu, trận đấu vẫn được tổ chức.",
            [
              ["悪天候", "あくてんこう"],
              ["にもかかわらず"],
              ["試合", "しあい"],
              ["は"],
              ["行", "おこな"],
              ["われた。"],
            ],
          ),
          ex(
            "忙しいにもかかわらず彼は手伝ってくれた。",
            "いそがしいにもかかわらずかれはてつだってくれた。",
            "Dù bận, anh ấy vẫn giúp tôi.",
            [
              ["忙", "いそが"],
              ["しいにもかかわらず"],
              ["彼", "かれ"],
              ["は"],
              ["手伝", "てつだ"],
              ["ってくれた。"],
            ],
          ),
          ex(
            "注意したにもかかわらず同じミスを繰り返した。",
            "ちゅういしたにもかかわらずおなじみすをくりかえした。",
            "Dù đã nhắc, vẫn lặp lại lỗi giống.",
            [
              ["注意", "ちゅうい"],
              ["したにもかかわらず"],
              ["同", "おな"],
              ["じミスを"],
              ["繰", "く"],
              ["り"],
              ["返", "かえ"],
              ["した。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜にもかかわらず",
        "Câu dùng にもかかわらず: mặc dù A nhưng vẫn B (trang trọng).",
        [
          ["Dù mưa lớn buổi lễ vẫn diễn ra.", "大雨にもかかわらず式は実施された。"],
          ["Dù mệt cô ấy vẫn tiếp tục làm.", "疲れているにもかかわらず彼女は作業を続けた。"],
          ["Dù giá cao hàng vẫn bán chạy.", "高いにもかかわらず商品はよく売れた。"],
          ["Dù phản đối kế hoạch vẫn được duyệt.", "反対にもかかわらず計画は承認された。"],
          ["Dù ít kinh nghiệm anh ấy được chọn.", "経験が少ないにもかかわらず彼は選ばれた。"],
          ["Dù cảnh báo nguy hiểm vẫn đi.", "危険だと警告されたにもかかわらず出発した。"],
          ["Dù trời lạnh ngoài trời đông người.", "寒いにもかかわらず屋外に人が多い。"],
          ["Dù thất bại anh ấy không bỏ cuộc.", "失敗したにもかかわらず彼は諦めなかった。"],
          ["Dù luật cấm vẫn có người vi phạm.", "禁止されているにもかかわらず違反する人がいる。"],
          ["Dù lời khuyên bác sĩ vẫn hút thuốc.", "医師の忠告にもかかわらず喫煙を続けた。"],
        ],
        [
          ["準備不足にもかかわらず発表は成功した。", "Dù thiếu chuẩn bị, thuyết trình vẫn thành công."],
          ["高齢にもかかわらず彼は現役だ。", "Dù cao tuổi, anh ấy vẫn đang hoạt động."],
          ["費用が高いにもかかわらず参加者が多い。", "Dù phí cao, người tham gia vẫn nhiều."],
          ["説明したにもかかわらず誤解が生じた。", "Dù đã giải thích, vẫn phát sinh hiểu nhầm."],
          ["時間がなかったにもかかわらずレポートを出した。", "Dù không có thời gian, vẫn nộp báo cáo."],
          ["体調不良にもかかわらず出勤した。", "Dù không khỏe vẫn đi làm."],
          ["反対意見があるにもかかわらず決定した。", "Dù có ý kiến phản đối vẫn quyết định."],
          ["雨が降っているにもかかわらず試合は続行した。", "Dù mưa vẫn tiếp tục trận đấu."],
          ["経験豊富にもかかわらず慎重だった。", "Dù giàu kinh nghiệm vẫn thận trọng."],
          ["努力したにもかかわらず結果は出なかった。", "Dù nỗ lực, kết quả vẫn không ra."],
        ],
        [
          ["Dù thời tiết xấu trận vẫn tổ chức.", ["悪天候", "にもかかわらず", "試合は", "行われた。"], 1],
          ["Dù bận anh vẫn giúp.", ["忙しい", "にもかかわらず", "彼は", "手伝った。"], 1],
          ["Dù nhắc vẫn lặp lỗi.", ["注意した", "にもかかわらず", "ミスを", "繰り返した。"], 1],
          ["Dù mưa lớn lễ vẫn diễn ra.", ["大雨", "にもかかわらず", "式は", "実施された。"], 1],
          ["Dù mệt vẫn tiếp tục.", ["疲れている", "にもかかわらず", "作業を", "続けた。"], 1],
          ["Dù thất bại không bỏ.", ["失敗した", "にもかかわらず", "諦め", "なかった。"], 1],
          ["Dù thiếu chuẩn bị thành công.", ["準備不足", "にもかかわらず", "発表は", "成功した。"], 1],
          ["Dù cao tuổi vẫn hoạt động.", ["高齢", "にもかかわらず", "彼は", "現役だ。"], 1],
          ["Dù không khỏe vẫn đi làm.", ["体調不良", "にもかかわらず", "出勤", "した。"], 1],
          ["Dù nỗ lực không có kết quả.", ["努力した", "にもかかわらず", "結果は", "出なかった。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l14-g02",
      {
        meaning: "Tuy… nhưng… / dù nói vậy… (nhượng bộ, thường viết)",
        structures: ["普通形 ＋ ものの", "〜とはいうものの"],
        explanation:
          "Thừa nhận A nhưng kết quả/thực tế là B không như mong đợi; とはいうものの nhấn 'dù nói thế'.",
        usage: "Văn viết, tự sự: biết là khó nhưng…; nói là nghỉ nhưng…",
        cautions: [
          "ものの hơi trang trọng; ít dùng nói chuyện thân mật.",
          "とはいうものの thường đứng đầu mệnh đề sau khi đã nêu ý trước.",
        ],
        contrast: "ものの／とはいうものの ≈ tuy… nhưng. Gần けれど; trang trọng hơn のに.",
        examples: [
          ex(
            "挑戦したものの思うような結果は出なかった。",
            "ちょうせんしたもののおもうようなけっかはでなかった。",
            "Tuy đã thử thách nhưng kết quả không như mong muốn.",
            [
              ["挑戦", "ちょうせん"],
              ["したものの"],
              ["思", "おも"],
              ["うような"],
              ["結果", "けっか"],
              ["は"],
              ["出", "で"],
              ["なかった。"],
            ],
          ),
          ex(
            "説明を受けたもののまだ理解できない。",
            "せつめいをうけたもののまだりかいできない。",
            "Tuy đã được giải thích nhưng vẫn chưa hiểu.",
            [
              ["説明", "せつめい"],
              ["を"],
              ["受", "う"],
              ["けたものの"],
              ["まだ"],
              ["理解", "りかい"],
              ["できない。"],
            ],
          ),
          ex(
            "安いとはいうものの品質は確かだ。",
            "やすいとはいうもののひんしつはたしかだ。",
            "Dù nói là rẻ nhưng chất lượng chắc chắn.",
            [
              ["安", "やす"],
              ["いとはいうものの"],
              ["品質", "ひんしつ"],
              ["は"],
              ["確", "たし"],
              ["かだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ものの／〜とはいうものの",
        "Câu dùng ものの／とはいうものの: thừa nhận A nhưng thực tế là B.",
        [
          ["Tuy đã cố nhưng không đạt mục tiêu.", "頑張ったものの目標には届かなかった。"],
          ["Tuy mua máy mới nhưng hay hỏng.", "新しいパソコンを買ったもののすぐ故障した。"],
          ["Tuy nghe giải thích nhưng vẫn nghi.", "説明を聞いたものの疑問が残る。"],
          ["Dù nói đơn giản nhưng làm khó.", "簡単だとはいうものの実際は難しい。"],
          ["Tuy đã nghỉ nhưng vẫn mệt.", "休んだものの疲れが取れない。"],
          ["Tuy đăng ký nhưng chưa tham gia.", "申し込んだもののまだ参加していない。"],
          ["Dù nói nhỏ nhưng ảnh hưởng lớn.", "小さな問題だとはいうものの影響は大きい。"],
          ["Tuy đọc sách nhưng quên ngay.", "本を読んだもののすぐ忘れてしまう。"],
          ["Tuy luyện tập nhưng kỹ năng chưa lên.", "練習したものの上達が遅い。"],
          ["Dù nói là gần nhưng đi mất giờ.", "近いとはいうものの歩くと一時間かかる。"],
        ],
        [
          ["約束したものの都合が悪くなった。", "Tuy đã hứa nhưng lịch bị xấu."],
          ["調べたものの確証は得られなかった。", "Tuy đã tra cứu nhưng không có bằng chứng chắc."],
          ["開始したもののすぐに中断した。", "Tuy đã bắt đầu nhưng sớm bị gián đoạn."],
          ["便利だとはいうものの使い方が複雑だ。", "Dù nói tiện nhưng cách dùng phức tạp."],
          ["合格したものの安心できない。", "Tuy đã đậu nhưng chưa yên tâm."],
          ["節約したものの貯金は増えない。", "Tuy tiết kiệm nhưng tiền tiết kiệm không tăng."],
          ["助言したものの相手は聞かない。", "Tuy đã khuyên nhưng đối phương không nghe."],
          ["無料だとはいうものの別料金が必要だ。", "Dù nói miễn phí nhưng cần phí khác."],
          ["準備したものの雨で中止になった。", "Tuy đã chuẩn bị nhưng mưa nên hủy."],
          ["経験豊富だとはいうものの初めての分野だ。", "Dù nói giàu kinh nghiệm nhưng lĩnh vực mới."],
        ],
        [
          ["Tuy thử thách không như ý.", ["挑戦した", "ものの", "結果は", "出なかった。"], 1],
          ["Tuy giải thích vẫn chưa hiểu.", ["説明を", "受けたものの", "理解は", "できない。"], 1],
          ["Dù rẻ chất lượng chắc.", ["安いとは", "いうものの", "品質は", "確かだ。"], 1],
          ["Tuy cố không đạt mục tiêu.", ["頑張った", "ものの", "目標には", "届かない。"], 1],
          ["Dù đơn giản làm khó.", ["簡単だとは", "いうものの", "実際は", "難しい。"], 1],
          ["Tuy nghỉ vẫn mệt.", ["休んだ", "ものの", "疲れが", "残る。"], 1],
          ["Tuy hứa lịch xấu.", ["約束した", "ものの", "都合が", "悪い。"], 1],
          ["Dù tiện cách dùng phức tạp.", ["便利だとは", "いうものの", "使い方は", "複雑だ。"], 1],
          ["Tuy đậu chưa yên tâm.", ["合格した", "ものの", "安心は", "できない。"], 1],
          ["Tuy chuẩn bị mưa hủy.", ["準備した", "ものの", "雨で", "中止だ。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l14-g03",
      {
        meaning: "Tuy… nhưng… / dù là… vẫn… (nhượng bộ)",
        structures: ["Vます形／いA語幹／なA・N ＋ ながら（も）"],
        explanation:
          "Thừa nhận tình trạng A nhưng hành động/kết quả B trái hoặc ngoài dự kiến; ながらも nhấn nhượng bộ rõ hơn.",
        usage: "Biết sai mà vẫn làm; nhỏ tuổi mà…; nghèo mà…",
        cautions: [
          "Khác ながら 'vừa… vừa…' (đồng thời) — ngữ cảnh quyết định nghĩa.",
          "Với danh từ/なA thường: N／なA語幹＋ながら（も）.",
        ],
        contrast: "ながら（も） ≈ tuy… nhưng (nhượng bộ). Khác ながら đồng thời; gần つつも.",
        examples: [
          ex(
            "狭いながらも快適な部屋だ。",
            "せまいながらもかいてきなへやだ。",
            "Tuy hẹp nhưng là phòng dễ chịu.",
            [
              ["狭", "せま"],
              ["いながらも"],
              ["快適", "かいてき"],
              ["な"],
              ["部屋", "へや"],
              ["だ。"],
            ],
          ),
          ex(
            "彼は学生でありながら一流企業で働いている。",
            "かれはがくせいでありながらいちりゅうきぎょうではたらいている。",
            "Anh ấy dù là sinh viên vẫn làm ở công ty hàng đầu.",
            [
              ["彼", "かれ"],
              ["は"],
              ["学生", "がくせい"],
              ["でありながら"],
              ["一流", "いちりゅう"],
              ["企業", "きぎょう"],
              ["で"],
              ["働", "はたら"],
              ["いている。"],
            ],
          ),
          ex(
            "知っていながら教えてくれなかった。",
            "しっていながらおしえてくれなかった。",
            "Tuy biết nhưng không chịu nói cho tôi.",
            [
              ["知", "し"],
              ["っていながら"],
              ["教", "おし"],
              ["えてくれなかった。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ながら（も）",
        "Câu dùng ながら（も） nhượng bộ: tuy A nhưng B.",
        [
          ["Tuy nhỏ tuổi nhưng rất chín chắn.", "若いながらも彼はとても落ち着いている。"],
          ["Tuy nghèo nhưng sống vui.", "貧しいながらも楽しく暮らしている。"],
          ["Tuy bận vẫn trả lời thư.", "忙しいながらもメールを返信した。"],
          ["Tuy biết nguy hiểm vẫn đi.", "危険だと知りながらも出かけた。"],
          ["Tuy là người mới vẫn đề xuất ý hay.", "新人でありながら優れた提案をした。"],
          ["Tuy mệt vẫn hoàn thành báo cáo.", "疲れながらも報告書を仕上げた。"],
          ["Tuy xa nhưng đi làm mỗi ngày.", "遠いながらも毎日通勤している。"],
          ["Tuy thất bại vẫn mỉm cười.", "失敗しながらも笑顔を見せた。"],
          ["Tuy đơn giản nhưng hiệu quả.", "単純ながらも効果的な方法だ。"],
          ["Tuy không thích vẫn tham dự.", "気が進まないながらも出席した。"],
        ],
        [
          ["残念ながら今回は欠席します。", "Đáng tiếc là lần này tôi xin vắng."],
          ["狭いながらも工夫次第で快適だ。", "Tuy hẹp nhưng khéo bố trí vẫn dễ chịu."],
          ["疑いながらも契約書にサインした。", "Tuy nghi ngờ vẫn ký hợp đồng."],
          ["子供ながらよく気がつく。", "Dù còn trẻ đã rất tinh ý."],
          ["申し訳ないながらもお願いがある。", "Xin lỗi nhưng tôi có việc nhờ."],
          ["不便ながらもこの町が好きだ。", "Tuy bất tiện nhưng thích thị trấn này."],
          ["驚きながらも冷静に対応した。", "Tuy ngạc nhiên vẫn ứng phó bình tĩnh."],
          ["反対されながらも計画を進めた。", "Tuy bị phản đối vẫn tiến hành kế hoạch."],
          ["初心者ながらも大会に出た。", "Dù mới vẫn tham gia giải."],
          ["涙を流しながらも前を向いた。", "Tuy khóc vẫn hướng về phía trước."],
        ],
        [
          ["Tuy hẹp phòng dễ chịu.", ["狭い", "ながらも", "快適な", "部屋だ。"], 1],
          ["Dù sinh viên làm công ty lớn.", ["学生で", "ありながら", "一流で", "働く。"], 1],
          ["Tuy biết không nói.", ["知って", "いながら", "教えて", "くれない。"], 1],
          ["Tuy nghèo sống vui.", ["貧しい", "ながらも", "楽しく", "暮らす。"], 1],
          ["Tuy bận vẫn trả lời.", ["忙しい", "ながらも", "メールを", "返す。"], 1],
          ["Tuy mệt hoàn thành báo cáo.", ["疲れ", "ながらも", "報告書を", "仕上げた。"], 1],
          ["Tuy nghi vẫn ký.", ["疑い", "ながらも", "契約に", "サインした。"], 1],
          ["Dù trẻ rất tinh ý.", ["子供", "ながら", "よく", "気がつく。"], 1],
          ["Tuy bất tiện thích phố.", ["不便", "ながらも", "この町が", "好きだ。"], 1],
          ["Dù mới vẫn dự giải.", ["初心者", "ながらも", "大会に", "出た。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l14-g04",
      {
        meaning: "Dù… nhưng… / trong khi… (nhượng bộ văn viết)",
        structures: ["Vます形 ＋ つつ（も）"],
        explanation:
          "Nhượng bộ mang sắc văn viết: thừa nhận A nhưng vẫn B; gần ながらも nhưng trang trọng hơn.",
        usage: "Bài luận, báo cáo: biết rủi ro nhưng vẫn tiến hành; lo lắng nhưng quyết định.",
        cautions: [
          "Khác つつ tiến triển đồng thời ở bài khác (L2).",
          "Chủ yếu gắn động từ dạng ます; ít dùng hội thoại thân mật.",
        ],
        contrast: "つつ（も） ≈ dù… nhưng (viết). Gần ながらも; trang trọng hơn のに.",
        examples: [
          ex(
            "リスクを知りつつも挑戦することにした。",
            "りすくをしりつつもちょうせんすることにした。",
            "Dù biết rủi ro vẫn quyết định thử thách.",
            [
              ["リスクを"],
              ["知", "し"],
              ["りつつも"],
              ["挑戦", "ちょうせん"],
              ["することにした。"],
            ],
          ),
          ex(
            "迷いつつも最終的に賛成した。",
            "まよいつつもさいしゅうてきにさんせいした。",
            "Dù còn phân vân, cuối cùng vẫn tán thành.",
            [
              ["迷", "まよ"],
              ["いつつも"],
              ["最終的", "さいしゅうてき"],
              ["に"],
              ["賛成", "さんせい"],
              ["した。"],
            ],
          ),
          ex(
            "感謝しつつも辞退せざるを得なかった。",
            "かんしゃしつつもじたいせざるをえなかった。",
            "Dù biết ơn vẫn buộc phải từ chối.",
            [
              ["感謝", "かんしゃ"],
              ["しつつも"],
              ["辞退", "じたい"],
              ["せざるを得なかった。"],
            ],
          ),
        ],
      },
      packFrom(
        "Vます ＋ つつ（も）",
        "Câu dùng つつ（も） nhượng bộ văn viết: dù A nhưng B.",
        [
          ["Dù lo vẫn nộp đơn.", "心配しつつも出願した。"],
          ["Dù tiếc vẫn từ chức.", "惜しみつつも退職を決めた。"],
          ["Dù sợ vẫn lên sân khấu.", "恐れつつも舞台に立った。"],
          ["Dù nghi vẫn tin lời đó.", "疑いつつもその話を信じた。"],
          ["Dù phản đối trong lòng vẫn ký.", "反対しつつも書類にサインした。"],
          ["Dù mệt vẫn hoàn tất kiểm tra.", "疲れつつも点検を終えた。"],
          ["Dù xấu hổ vẫn xin lỗi.", "恥じつつも謝罪した。"],
          ["Dù do dự vẫn trả lời.", "躊躇いつつも返事をした。"],
          ["Dù hiểu rủi ro vẫn đầu tư.", "理解しつつも投資を続けた。"],
          ["Dù cảm ơn vẫn từ chối lời mời.", "感謝しつつも招待を断った。"],
        ],
        [
          ["危険を認識しつつも作業を続けた。", "Dù nhận thức nguy hiểm vẫn tiếp tục làm."],
          ["期待しつつも結果を待った。", "Dù kỳ vọng vẫn chờ kết quả."],
          ["反省しつつも次の課題に進んだ。", "Dù tự phản tỉnh vẫn sang bài tiếp."],
          ["不満を感じつつも指示に従った。", "Dù bất mãn vẫn tuân theo chỉ thị."],
          ["悲しみつつも笑顔を保った。", "Dù buồn vẫn giữ nụ cười."],
          ["迷いつつも進路を決めた。", "Dù phân vân vẫn chọn hướng đi."],
          ["驚きつつも冷静に記録した。", "Dù ngạc nhiên vẫn ghi chép bình tĩnh."],
          ["申し訳なく思いつつも断った。", "Dù thấy có lỗi vẫn từ chối."],
          ["楽しみつつも準備を進めた。", "Dù mong chờ vẫn tiến hành chuẩn bị."],
          ["理解しつつもルールは守れなかった。", "Dù hiểu vẫn không giữ được quy tắc."],
        ],
        [
          ["Dù biết rủi ro vẫn thử.", ["リスクを", "知りつつも", "挑戦する", "ことにした。"], 1],
          ["Dù phân vân vẫn tán thành.", ["迷い", "つつも", "最終的に", "賛成した。"], 1],
          ["Dù biết ơn phải từ chối.", ["感謝し", "つつも", "辞退せざるを", "得なかった。"], 1],
          ["Dù lo vẫn nộp đơn.", ["心配し", "つつも", "出願を", "した。"], 1],
          ["Dù sợ vẫn lên sân khấu.", ["恐れ", "つつも", "舞台に", "立った。"], 1],
          ["Dù nghi vẫn tin.", ["疑い", "つつも", "その話を", "信じた。"], 1],
          ["Dù nhận nguy vẫn làm.", ["危険を", "認識しつつも", "作業を", "続けた。"], 1],
          ["Dù bất mãn vẫn tuân.", ["不満を", "感じつつも", "指示に", "従った。"], 1],
          ["Dù phân vân chọn hướng.", ["迷い", "つつも", "進路を", "決めた。"], 1],
          ["Dù thấy lỗi vẫn từ chối.", ["申し訳なく", "思いつつも", "誘いを", "断った。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l14-g05",
      {
        meaning: "Nói là… nhưng… / dù gọi là… cũng chẳng… (hạ thấp kỳ vọng)",
        structures: ["普通形 ＋ といっても"],
        explanation:
          "Thừa nhận cách gọi/đánh giá A nhưng thực tế mức độ thấp hơn hoặc khác với tưởng tượng.",
        usage: "Giải thích lại: nói là chuyên gia nhưng mới bắt đầu; nói là gần nhưng mất một giờ.",
        cautions: [
          "Thường đi sau danh từ hoặc đánh giá: Nといっても…",
          "Khác からといって (chỉ vì… không có nghĩa…).",
        ],
        contrast: "といっても ≈ nói là… nhưng thực ra. Khác とはいえ; gần hạ thấp kỳ vọng.",
        examples: [
          ex(
            "専門家といってもまだ経験が浅い。",
            "せんもんかといってもまだけいけんがあさい。",
            "Nói là chuyên gia nhưng kinh nghiệm vẫn nông.",
            [
              ["専門家", "せんもんか"],
              ["といっても"],
              ["まだ"],
              ["経験", "けいけん"],
              ["が"],
              ["浅", "あさ"],
              ["い。"],
            ],
          ),
          ex(
            "休みといっても一日だけだ。",
            "やすみといってもいちにちだけだ。",
            "Nói là nghỉ nhưng chỉ có một ngày.",
            [
              ["休", "やす"],
              ["みといっても"],
              ["一日", "いちにち"],
              ["だけだ。"],
            ],
          ),
          ex(
            "失敗といっても大きな損害はない。",
            "しっぱいといってもおおきなそんがいはない。",
            "Nói là thất bại nhưng không thiệt hại lớn.",
            [
              ["失敗", "しっぱい"],
              ["といっても"],
              ["大", "おお"],
              ["きな"],
              ["損害", "そんがい"],
              ["はない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜といっても",
        "Câu dùng といっても: nói là A nhưng thực tế mức độ thấp/khác.",
        [
          ["Nói là xa nhưng đi bộ được.", "遠いといっても歩いて行ける距離だ。"],
          ["Nói là đông nhưng chờ không lâu.", "混んでいるといっても待ち時間は短い。"],
          ["Nói là khó nhưng có ví dụ.", "難しいといっても例がある。"],
          ["Nói là tăng nhưng chỉ một chút.", "増えたといっても少しだけだ。"],
          ["Nói là công ty lớn nhưng chi nhánh nhỏ.", "大企業といっても小さな支社だ。"],
          ["Nói là lỗi nhưng dễ sửa.", "ミスといっても簡単に直せる。"],
          ["Nói là mùa đông nhưng chưa lạnh lắm.", "冬といってもそれほど寒くない。"],
          ["Nói là thành công nhưng mới bước đầu.", "成功といってもまだ第一歩だ。"],
          ["Nói là quà nhưng chỉ tấm thiệp.", "プレゼントといってもカードだけだ。"],
          ["Nói là họp nhưng chỉ năm phút.", "会議といっても五分で終わる。"],
        ],
        [
          ["高いといっても予算内だ。", "Nói là đắt nhưng trong ngân sách."],
          ["遅いといっても一時間程度だ。", "Nói là muộn nhưng khoảng một giờ."],
          ["賛成といっても条件付きだ。", "Nói là tán thành nhưng có điều kiện."],
          ["休みといっても半日しかない。", "Nói là nghỉ nhưng chỉ nửa ngày."],
          ["問題といっても小さなことだ。", "Nói là vấn đề nhưng chuyện nhỏ."],
          ["雨といっても霧雨程度だ。", "Nói là mưa nhưng chỉ mưa phùn."],
          ["忙しいといっても残業はない。", "Nói là bận nhưng không tăng ca."],
          ["変更といっても日付だけだ。", "Nói là thay đổi nhưng chỉ ngày tháng."],
          ["反対といっても少数だ。", "Nói là phản đối nhưng là thiểu số."],
          ["遠いといっても電車で十分だ。", "Nói là xa nhưng tàu mười phút."],
        ],
        [
          ["Nói chuyên gia kinh nghiệm nông.", ["専門家と", "いっても", "経験は", "浅い。"], 1],
          ["Nói nghỉ chỉ một ngày.", ["休みと", "いっても", "一日", "だけだ。"], 1],
          ["Nói thất bại không thiệt lớn.", ["失敗と", "いっても", "損害は", "ない。"], 1],
          ["Nói xa vẫn đi bộ được.", ["遠いと", "いっても", "歩ける", "距離だ。"], 1],
          ["Nói tăng chỉ một chút.", ["増えたと", "いっても", "少し", "だけだ。"], 1],
          ["Nói lỗi dễ sửa.", ["ミスと", "いっても", "簡単に", "直せる。"], 1],
          ["Nói đông chờ không lâu.", ["混んでいると", "いっても", "待ちは", "短い。"], 1],
          ["Nói đắt trong ngân sách.", ["高いと", "いっても", "予算内", "だ。"], 1],
          ["Nói họp năm phút xong.", ["会議と", "いっても", "五分で", "終わる。"], 1],
          ["Nói xa tàu mười phút.", ["遠いと", "いっても", "電車で", "十分だ。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l14-g06",
      {
        meaning: "Chỉ vì… không có nghĩa là… / không phải cứ… là…",
        structures: ["普通形 ＋ からといって"],
        explanation:
          "Phủ định suy luận: chỉ vì có A không đồng nghĩa được phép/được kết luận B; hay đi với phủ định hoặc わけではない.",
        usage: "Khuyên can: chỉ vì trẻ không có nghĩa được lười; chỉ vì đỗ không có nghĩa hết học.",
        cautions: [
          "Thường kết hợp わけではない／とは限らない／〜ない.",
          "Khác といっても (hạ thấp mức độ của chính A).",
        ],
        contrast: "からといって ≈ chỉ vì… không có nghĩa…. Khác といっても; gần だからといって.",
        examples: [
          ex(
            "高いからといって品質が良いとは限らない。",
            "たかいからといってひんしつがよいとはかぎらない。",
            "Chỉ vì đắt không có nghĩa chất lượng chắc tốt.",
            [
              ["高", "たか"],
              ["いからといって"],
              ["品質", "ひんしつ"],
              ["が"],
              ["良", "よ"],
              ["いとは"],
              ["限", "かぎ"],
              ["らない。"],
            ],
          ),
          ex(
            "忙しいからといって連絡を怠ってはいけない。",
            "いそがしいからといってれんらくをおこたってはいけない。",
            "Chỉ vì bận không được lơ là liên lạc.",
            [
              ["忙", "いそが"],
              ["しいからといって"],
              ["連絡", "れんらく"],
              ["を"],
              ["怠", "おこた"],
              ["ってはいけない。"],
            ],
          ),
          ex(
            "若いうちだからといって無理をしてはいけない。",
            "わかいうちだからといってむりをしてはいけない。",
            "Chỉ vì còn trẻ không được ép sức quá mức.",
            [
              ["若", "わか"],
              ["いうちだからといって"],
              ["無理", "むり"],
              ["をしてはいけない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜からといって",
        "Câu dùng からといって: chỉ vì A không có nghĩa / không được B.",
        [
          ["Chỉ vì rẻ không có nghĩa kém.", "安いからといって粗悪とは限らない。"],
          ["Chỉ vì đậu không có nghĩa hết học.", "合格したからといって勉強をやめてはいけない。"],
          ["Chỉ vì quen không được cẩu thả.", "慣れているからといって油断してはいけない。"],
          ["Chỉ vì xa không có nghĩa không đi được.", "遠いからといって行けないわけではない。"],
          ["Chỉ vì thất bại không được bỏ cuộc.", "失敗したからといって諦めてはいけない。"],
          ["Chỉ vì mưa không có nghĩa hủy hết.", "雨だからといって全て中止とは限らない。"],
          ["Chỉ vì là sếp không được hách dịch.", "上司だからといって横柄であってはいけない。"],
          ["Chỉ vì có tiền không có nghĩa hạnh phúc.", "お金があるからといって幸せとは限らない。"],
          ["Chỉ vì mệt không được bỏ qua an toàn.", "疲れたからといって安全を疎かにしてはいけない。"],
          ["Chỉ vì lần đầu không có nghĩa được từ bỏ.", "初めてだからといって포기してはいけない。"],
        ],
        [
          ["好きだからといって食べ過ぎてはいけない。", "Chỉ vì thích không được ăn quá nhiều."],
          ["暇だからといって無駄に過ごしてはいけない。", "Chỉ vì rảnh không được phí thời gian."],
          ["有名だからといって信頼できるとは限らない。", "Chỉ vì nổi tiếng không chắc đáng tin."],
          ["安いからといって買いすぎてはいけない。", "Chỉ vì rẻ không được mua quá nhiều."],
          ["怒ったからといって暴言を吐いてはいけない。", "Chỉ vì giận không được nói tục."],
          ["便利だからといって依存しすぎてはいけない。", "Chỉ vì tiện không được phụ thuộc quá."],
          ["若いからといって無理は禁物だ。", "Chỉ vì trẻ, ép sức là điều cấm."],
          ["経験があるからといって慢心してはいけない。", "Chỉ vì có kinh nghiệm không được kiêu."],
          ["無料だからといって品質が低いとは限らない。", "Chỉ vì miễn phí không chắc chất lượng thấp."],
          ["忙しいからといって健康を犠牲にしてはいけない。", "Chỉ vì bận không được hy sinh sức khỏe."],
        ],
        [
          ["Chỉ vì đắt không chắc tốt.", ["高いから", "といって", "品質が", "良いとは限らない。"], 1],
          ["Chỉ vì bận không lơ liên lạc.", ["忙しいから", "といって", "連絡を", "怠るな。"], 1],
          ["Chỉ vì trẻ không ép sức.", ["若いから", "といって", "無理を", "するな。"], 1],
          ["Chỉ vì rẻ không chắc kém.", ["安いから", "といって", "粗悪とは", "限らない。"], 1],
          ["Chỉ vì đậu không bỏ học.", ["合格したから", "といって", "勉強を", "やめるな。"], 1],
          ["Chỉ vì thất bại không bỏ.", ["失敗したから", "といって", "諦めては", "いけない。"], 1],
          ["Chỉ vì thích không ăn quá.", ["好きだから", "といって", "食べ過ぎて", "はいけない。"], 1],
          ["Chỉ vì nổi tiếng không chắc tin.", ["有名だから", "といって", "信頼できるとは", "限らない。"], 1],
          ["Chỉ vì rảnh không phí thì giờ.", ["暇だから", "といって", "無駄に", "過ごすな。"], 1],
          ["Chỉ vì bận không bỏ sức khỏe.", ["忙しいから", "といって", "健康を", "犠牲にするな。"], 1],
        ],
      ),
    ),
  ];
}
