import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L06-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 7, BATCH);

export function lesson07Patterns(byId) {
  return [
    P(
      byId,
      "l07-g01",
      {
        meaning: "Về / liên quan đến…",
        structures: ["N ＋ に関して", "N ＋ に関する ＋ N"],
        explanation:
          "Nêu chủ đề hoặc lĩnh vực đang nói đến; sắc thái trang trọng hơn について.",
        usage: "Báo cáo, họp, văn viết: về vấn đề…",
        cautions: [
          "に関する修飾 N (問題に関する資料).",
          "Hội thoại thân mật thường dùng について.",
        ],
        contrast: "に関して ≈ về… (trang trọng). Gần について; khác をめぐって (tranh cãi xoay quanh).",
        examples: [
          ex(
            "この問題に関して意見を聞かせてください。",
            "このもんだいにかんしていけんをきかせてください。",
            "Về vấn đề này, hãy cho tôi nghe ý kiến.",
            [
              ["この"],
              ["問題", "もんだい"],
              ["に"],
              ["関", "かん"],
              ["して"],
              ["意見", "いけん"],
              ["を"],
              ["聞", "き"],
              ["かせてください。"],
            ],
          ),
          ex(
            "環境に関する記事を書いた。",
            "かんきょうにかんするきじをかいた。",
            "Tôi đã viết bài liên quan đến môi trường.",
            [
              ["環境", "かんきょう"],
              ["に"],
              ["関", "かん"],
              ["する"],
              ["記事", "きじ"],
              ["を"],
              ["書", "か"],
              ["いた。"],
            ],
          ),
          ex(
            "契約内容に関して確認が必要だ。",
            "けいやくないようにかんしてかくにんがひつようだ。",
            "Cần xác nhận về nội dung hợp đồng.",
            [
              ["契約", "けいやく"],
              ["内容", "ないよう"],
              ["に"],
              ["関", "かん"],
              ["して"],
              ["確認", "かくにん"],
              ["が"],
              ["必要", "ひつよう"],
              ["だ。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ に関して／に関する",
        "Câu dùng に関して／に関する để nói về / liên quan đến chủ đề.",
        [
          ["Về kế hoạch này cần thảo luận thêm.", "この計画に関してさらに議論が必要だ。"],
          ["Tôi muốn hỏi về lịch trình.", "日程に関して質問したい。"],
          ["Đã có báo cáo về tai nạn.", "事故に関する報告が出た。"],
          ["Về ngân sách chưa quyết định.", "予算に関してまだ決まっていない。"],
          ["Đây là tài liệu liên quan đến luật mới.", "これは新法に関する資料だ。"],
          ["Về chất lượng sản phẩm có khiếu nại.", "製品の品質に関して苦情がある。"],
          ["Họ họp về chính sách tuyển dụng.", "採用方針に関して会議を開いた。"],
          ["Về sức khỏe của anh ấy tôi không biết.", "彼の健康に関しては知らない。"],
          ["Cần điều tra về nguyên nhân.", "原因に関して調査が必要だ。"],
          ["Bài viết liên quan đến giáo dục được đọc nhiều.", "教育に関する記事がよく読まれている。"],
        ],
        [
          ["安全に関して注意を呼びかける。", "Kêu gọi chú ý về an toàn."],
          ["料金に関する説明を読んでください。", "Hãy đọc phần giải thích về phí."],
          ["この件に関しては後日連絡します。", "Về việc này sẽ liên lạc sau."],
          ["歴史に関する本を借りた。", "Tôi mượn sách liên quan đến lịch sử."],
          ["規則に関して疑問がある。", "Tôi có thắc mắc về quy định."],
          ["天候に関する情報を確認した。", "Đã kiểm tra thông tin về thời tiết."],
          ["プライバシーに関して厳しいルールがある。", "Có quy tắc nghiêm về quyền riêng tư."],
          ["貿易に関する交渉が続いている。", "Đàm phán liên quan đến thương mại đang tiếp diễn."],
          ["彼の経歴に関しては詳しくない。", "Về lý lịch anh ấy tôi không rõ lắm."],
          ["技術に関して専門家に相談した。", "Đã hỏi chuyên gia về kỹ thuật."],
        ],
        [
          ["Về vấn đề này hãy cho ý kiến.", ["問題に", "関して", "意見を", "ください。"], 1],
          ["Cần xác nhận về hợp đồng.", ["契約に", "関して", "確認が", "要る。"], 1],
          ["Viết bài về môi trường.", ["環境に", "関する", "記事を", "書いた。"], 1],
          ["Hỏi về lịch trình.", ["日程に", "関して", "質問が", "ある。"], 1],
          ["Báo cáo về tai nạn.", ["事故に", "関する", "報告が", "出た。"], 1],
          ["Chưa quyết về ngân sách.", ["予算に", "関して", "未定", "だ。"], 1],
          ["Khiếu nại về chất lượng.", ["品質に", "関して", "苦情が", "来た。"], 1],
          ["Họp về tuyển dụng.", ["採用に", "関して", "会議を", "開く。"], 1],
          ["Điều tra về nguyên nhân.", ["原因に", "関して", "調査を", "行う。"], 1],
          ["Đọc giải thích về phí.", ["料金に", "関する", "説明を", "読む。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l07-g02",
      {
        meaning: "Xoay quanh / xung quanh (thường tranh luận, xung đột)",
        structures: ["N ＋ をめぐって", "N ＋ をめぐる ＋ N"],
        explanation:
          "Nêu trung tâm của tranh cãi, đàm phán, quan tâm; thường có nhiều bên liên quan.",
        usage: "Tin tức, phân tích: tranh luận xoay quanh…",
        cautions: [
          "Khác について ở chỗ nhấn 'xoay quanh một điểm nóng'.",
          "をめぐる修飾 N (遺産をめぐる争い).",
        ],
        contrast: "をめぐって ≈ xoay quanh. Khác に関して (trung lập về chủ đề).",
        examples: [
          ex(
            "相続をめぐって家族が争っている。",
            "そうぞくをめぐってかぞくがあらそっている。",
            "Gia đình đang tranh chấp xoay quanh thừa kế.",
            [
              ["相続", "そうぞく"],
              ["を"],
              ["めぐって"],
              ["家族", "かぞく"],
              ["が"],
              ["争", "あらそ"],
              ["っている。"],
            ],
          ),
          ex(
            "新制度をめぐる議論が続いている。",
            "しんせいどをめぐるぎろんがつづいている。",
            "Cuộc thảo luận xoay quanh chế độ mới vẫn tiếp diễn.",
            [
              ["新", "しん"],
              ["制度", "せいど"],
              ["を"],
              ["めぐる"],
              ["議論", "ぎろん"],
              ["が"],
              ["続", "つづ"],
              ["いている。"],
            ],
          ),
          ex(
            "土地の境界をめぐって隣人と対立した。",
            "とちのきょうかいをめぐってりんじんとたいりつした。",
            "Đối đầu với hàng xóm xoay quanh ranh giới đất.",
            [
              ["土地", "とち"],
              ["の"],
              ["境界", "きょうかい"],
              ["を"],
              ["めぐって"],
              ["隣人", "りんじん"],
              ["と"],
              ["対立", "たいりつ"],
              ["した。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ をめぐって／をめぐる",
        "Câu dùng をめぐって để nói tranh luận/xung đột xoay quanh một điểm.",
        [
          ["Họ tranh luận xoay quanh ngân sách.", "予算をめぐって議論している。"],
          ["Có xung đột xoay quanh quyền lợi.", "権利をめぐって対立が起きている。"],
          ["Tin tức xoay quanh vụ bê bối.", "その不祥事をめぐる報道が多い。"],
          ["Hai nước đàm phán xoay quanh biên giới.", "国境をめぐって両国が交渉している。"],
          ["Gia đình cãi nhau xoay quanh nhà cửa.", "家屋をめぐって親族がもめている。"],
          ["Có tranh chấp xoay quanh bản quyền.", "著作権をめぐる争いがある。"],
          ["Ứng viên tranh luận xoay quanh thuế.", "税金をめぐって候補者が討論した。"],
          ["Công ty kiện nhau xoay quanh bằng sáng chế.", "特許をめぐって企業が争っている。"],
          ["Cư dân phản đối xoay quanh dự án xây dựng.", "建設計画をめぐって住民が反対している。"],
          ["Báo chí đưa tin xoay quanh kết quả bầu cử.", "選挙結果をめぐる報道が続いている。"],
        ],
        [
          ["遺産をめぐって兄弟が対立した。", "Anh em đối đầu xoay quanh di sản."],
          ["人事をめぐる噂が広がっている。", "Tin đồn xoay quanh nhân sự đang lan."],
          ["方針をめぐって意見が分かれた。", "Ý kiến chia rẽ xoay quanh phương châm."],
          ["契約条件をめぐって交渉が難航した。", "Đàm phán xoay quanh điều kiện hợp đồng gặp khó."],
          ["真実をめぐる論争が続いた。", "Tranh luận xoay quanh sự thật kéo dài."],
          ["優勝をめぐって両チームが競った。", "Hai đội tranh tài xoay quanh chức vô địch."],
          ["責任の所在をめぐって議論になった。", "Thảo luận xoay quanh trách nhiệm thuộc về ai."],
          ["開発計画をめぐる抗議が行われた。", "Có cuộc phản đối xoay quanh kế hoạch phát triển."],
          ["株価をめぐって投資家がざわついた。", "Nhà đầu tư xôn xao xoay quanh giá cổ phiếu."],
          ["ルール改正をめぐって賛否が分かれた。", "Tán thành/phản đối chia rẽ xoay quanh sửa quy tắc."],
        ],
        [
          ["Tranh luận xoay quanh ngân sách.", ["予算を", "めぐって", "議論が", "続く。"], 1],
          ["Xung đột xoay quanh quyền lợi.", ["権利を", "めぐって", "対立が", "起きた。"], 1],
          ["Tin xoay quanh bê bối.", ["不祥事を", "めぐる", "報道が", "多い。"], 1],
          ["Đàm phán xoay quanh biên giới.", ["国境を", "めぐって", "交渉が", "進む。"], 1],
          ["Cãi nhau xoay quanh nhà.", ["家屋を", "めぐって", "親族が", "もめる。"], 1],
          ["Tranh chấp xoay quanh bản quyền.", ["著作権を", "めぐる", "争いが", "ある。"], 1],
          ["Kiện xoay quanh bằng sáng chế.", ["特許を", "めぐって", "企業が", "争う。"], 1],
          ["Phản đối xoay quanh dự án.", ["計画を", "めぐって", "住民が", "反対する。"], 1],
          ["Anh em đối đầu xoay quanh di sản.", ["遺産を", "めぐって", "兄弟が", "対立した。"], 1],
          ["Ý kiến chia rẽ xoay quanh phương châm.", ["方針を", "めぐって", "意見が", "分かれた。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l07-g03",
      {
        meaning: "Về mặt… / trong lĩnh vực… thì (không ai bằng)",
        structures: ["N ＋ にかけては", "N ＋ にかけても"],
        explanation:
          "Nhấn mạnh lĩnh vực sở trường: về mặt A thì (anh ấy) xuất sắc; にかけても nhấn dù lĩnh vực nào.",
        usage: "Khen ngợi năng lực, so sánh chuyên môn.",
        cautions: [
          "Không nhầm với から～にかけて (khoảng thời gian/không gian).",
          "Thường theo sau đánh giá tích cực.",
        ],
        contrast: "にかけては ≈ về mặt… thì. Khác に関して (chỉ nêu chủ đề).",
        examples: [
          ex(
            "料理にかけては彼女に勝てない。",
            "りょうりにかけてはかのじょにかてない。",
            "Về nấu ăn thì không thắng được cô ấy.",
            [
              ["料理", "りょうり"],
              ["にかけては"],
              ["彼女", "かのじょ"],
              ["に"],
              ["勝", "か"],
              ["てない。"],
            ],
          ),
          ex(
            "記憶力にかけては彼が一番だ。",
            "きおくりょくにかけてはかれがいちばんだ。",
            "Về trí nhớ thì anh ấy số một.",
            [
              ["記憶力", "きおくりょく"],
              ["にかけては"],
              ["彼", "かれ"],
              ["が"],
              ["一番", "いちばん"],
              ["だ。"],
            ],
          ),
          ex(
            "誠実さにかけても彼は信頼できる。",
            "せいじつさにかけてもかれはしんらいできる。",
            "Về sự chân thành thì anh ấy cũng đáng tin.",
            [
              ["誠実", "せいじつ"],
              ["さにかけても"],
              ["彼", "かれ"],
              ["は"],
              ["信頼", "しんらい"],
              ["できる。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ にかけては／にかけても",
        "Câu dùng にかけては để nói về mặt / trong lĩnh vực thì (xuất sắc).",
        [
          ["Về tiếng Anh thì không ai bằng anh ấy.", "英語にかけては彼の右に出る者はいない。"],
          ["Về tốc độ thì đội này mạnh nhất.", "スピードにかけてはこのチームが最強だ。"],
          ["Về nấu ăn tôi thua chị.", "料理にかけては姉にはかなわない。"],
          ["Về tính cẩn thận thì cô ấy số một.", "丁寧さにかけては彼女が一番だ。"],
          ["Về kiến thức lịch sử thì thầy ấy giỏi.", "歴史の知識にかけては先生が詳しい。"],
          ["Về dịch vụ khách hàng cửa hàng này nổi tiếng.", "接客にかけてはこの店が有名だ。"],
          ["Về sức bền thì anh ấy không thua ai.", "持久力にかけては彼は負けない。"],
          ["Về thiết kế thì công ty đó hàng đầu.", "デザインにかけてはあの会社がトップだ。"],
          ["Về sự đúng giờ thì đội này đáng tin.", "時間厳守にかけてはこの班は信頼できる。"],
          ["Về khiếu hài hước thì bạn ấy giỏi.", "ユーモアにかけては彼が上手だ。"],
        ],
        [
          ["交渉にかけては部長が得意だ。", "Về đàm phán thì trưởng phòng giỏi."],
          ["忍耐にかけては彼女は誰にも負けない。", "Về kiên nhẫn thì cô ấy không thua ai."],
          ["味にかけては母の料理が一番だ。", "Về vị thì món mẹ nấu số một."],
          ["正確さにかけては機械の方が上だ。", "Về độ chính xác thì máy tốt hơn."],
          ["創造性にかけては学生たちがすごい。", "Về sáng tạo thì sinh viên thật ấn tượng."],
          ["体力にかけても彼は若い頃と変わらない。", "Về thể lực thì anh ấy vẫn như thời trẻ."],
          ["礼儀にかけてはこの学校が厳しい。", "Về lễ nghi thì trường này nghiêm."],
          ["効率にかけては新しい方法が優れている。", "Về hiệu quả thì phương pháp mới vượt trội."],
          ["歌唱力にかけては彼女が群を抜いている。", "Về khả năng hát thì cô ấy vượt trội."],
          ["分析力にかけては彼は社内一だ。", "Về phân tích thì anh ấy nhất công ty."],
        ],
        [
          ["Về nấu ăn không thắng cô ấy.", ["料理に", "かけては", "彼女に", "勝てない。"], 1],
          ["Về trí nhớ anh ấy số một.", ["記憶力に", "かけては", "彼が", "一番だ。"], 1],
          ["Về tiếng Anh không ai bằng.", ["英語に", "かけては", "彼が", "最強だ。"], 1],
          ["Về tốc độ đội này mạnh.", ["速度に", "かけては", "この班が", "上だ。"], 1],
          ["Về sự cẩn thận cô ấy nhất.", ["丁寧さに", "かけては", "彼女が", "第一だ。"], 1],
          ["Về tiếp khách quán này nổi tiếng.", ["接客に", "かけては", "この店が", "有名だ。"], 1],
          ["Về sức bền anh ấy không thua.", ["持久力に", "かけては", "彼は", "負けない。"], 1],
          ["Về thiết kế công ty đó top.", ["デザインに", "かけては", "あの社が", "トップだ。"], 1],
          ["Về đàm phán trưởng phòng giỏi.", ["交渉に", "かけては", "部長が", "得意だ。"], 1],
          ["Về vị món mẹ số một.", ["味に", "かけては", "母の料理が", "一番だ。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l07-g04",
      {
        meaning: "Đối với… / đối lại…",
        structures: ["N ＋ に対して", "N ＋ に対する ＋ N"],
        explanation:
          "Nêu đối tượng nhận hành động/thái độ, hoặc đối chiếu hai bên.",
        usage: "Thái độ với người/việc; so sánh A thì… còn B thì…",
        cautions: [
          "に対する修飾 N (会社に対する不満).",
          "Có thể mang nghĩa 'trái lại' khi đối chiếu.",
        ],
        contrast: "に対して ≈ đối với / đối lại. Khác について (về chủ đề) và にこたえて (đáp ứng).",
        examples: [
          ex(
            "彼は顧客に対して丁寧だ。",
            "かれはこきゃくにたいしてていねいだ。",
            "Anh ấy lịch sự đối với khách hàng.",
            [
              ["彼", "かれ"],
              ["は"],
              ["顧客", "こきゃく"],
              ["に"],
              ["対", "たい"],
              ["して"],
              ["丁寧", "ていねい"],
              ["だ。"],
            ],
          ),
          ex(
            "質問に対する答えを準備した。",
            "しつもんにたいするこたえをじゅんびした。",
            "Đã chuẩn bị câu trả lời cho câu hỏi.",
            [
              ["質問", "しつもん"],
              ["に"],
              ["対", "たい"],
              ["する"],
              ["答", "こた"],
              ["えを"],
              ["準備", "じゅんび"],
              ["した。"],
            ],
          ),
          ex(
            "都市部に対して地方は人口が減っている。",
            "としぶにたいしてちほうはじんこうがへっている。",
            "Đối lại khu đô thị, địa phương dân số đang giảm.",
            [
              ["都市部", "としぶ"],
              ["に"],
              ["対", "たい"],
              ["して"],
              ["地方", "ちほう"],
              ["は"],
              ["人口", "じんこう"],
              ["が"],
              ["減", "へ"],
              ["っている。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ に対して／に対する",
        "Câu dùng に対して để nói đối với đối tượng hoặc đối chiếu.",
        [
          ["Anh ấy nghiêm khắc đối với học sinh.", "彼は生徒に対して厳しい。"],
          ["Công ty có trách nhiệm đối với xã hội.", "企業は社会に対して責任がある。"],
          ["Tôi biết ơn đối với sự giúp đỡ của bạn.", "あなたの援助に対して感謝している。"],
          ["Đối với phê bình anh ấy bình tĩnh.", "批判に対して彼は冷静だ。"],
          ["Đây là biện pháp đối với rủi ro.", "これはリスクに対する対策だ。"],
          ["Đối lại năm ngoái, năm nay bán chạy.", "去年に対して今年はよく売れている。"],
          ["Cô ấy dịu dàng đối với trẻ nhỏ.", "彼女は子供に対して優しい。"],
          ["Đã trả lời đối với khiếu nại.", "苦情に対して返答した。"],
          ["Đối với đề xuất này ý kiến chia rẽ.", "この提案に対して意見が分かれた。"],
          ["Thái độ đối với môi trường đang thay đổi.", "環境に対する意識が変わってきている。"],
        ],
        [
          ["上司に対して意見を述べた。", "Trình bày ý kiến đối với cấp trên."],
          ["暴力に対する罰則が強化された。", "Hình phạt đối với bạo lực được siết chặt."],
          ["期待に対して結果が伴わなかった。", "Đối với kỳ vọng, kết quả không theo kịp."],
          ["外国人に対して親切な町だ。", "Là thị trấn thân thiện đối với người nước ngoài."],
          ["値上げに対して客が反発した。", "Khách phản ứng đối với việc tăng giá."],
          ["彼の態度に対して不満がある。", "Tôi bất mãn đối với thái độ của anh ấy."],
          ["質問に対してすぐに答えた。", "Trả lời ngay đối với câu hỏi."],
          ["A案に対してB案の方が現実的だ。", "Đối lại phương án A, B thực tế hơn."],
          ["自然災害に対する備えが必要だ。", "Cần chuẩn bị đối với thiên tai."],
          ["観客に対して感謝の言葉を述べた。", "Nói lời cảm ơn đối với khán giả."],
        ],
        [
          ["Lịch sự đối với khách.", ["顧客に", "対して", "丁寧に", "接する。"], 1],
          ["Chuẩn bị trả lời cho câu hỏi.", ["質問に", "対する", "答えを", "用意した。"], 1],
          ["Nghiêm đối với học sinh.", ["生徒に", "対して", "厳しく", "指導する。"], 1],
          ["Biết ơn đối với giúp đỡ.", ["援助に", "対して", "感謝を", "伝える。"], 1],
          ["Biện pháp đối với rủi ro.", ["リスクに", "対する", "対策を", "取る。"], 1],
          ["Dịu dàng đối với trẻ.", ["子供に", "対して", "優しく", "話す。"], 1],
          ["Trả lời khiếu nại.", ["苦情に", "対して", "返答を", "した。"], 1],
          ["Ý kiến chia rẽ về đề xuất.", ["提案に", "対して", "賛否が", "分かれた。"], 1],
          ["Phản ứng đối với tăng giá.", ["値上げに", "対して", "客が", "反発した。"], 1],
          ["Nói cảm ơn đối với khán giả.", ["観客に", "対して", "礼を", "述べた。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l07-g05",
      {
        meaning: "Đáp ứng / đáp lại (mong đợi, yêu cầu, tiếng gọi…)",
        structures: ["N ＋ にこたえて", "N ＋ にこたえ"],
        explanation:
          "Hành động nhằm đáp ứng kỳ vọng, nhu cầu, yêu cầu của đối tượng.",
        usage: "Thông báo, quảng cáo, bài viết trang trọng.",
        cautions: [
          "Thường đi với 期待／要望／ニーズ／声など.",
          "Không dùng cho 'trả lời câu hỏi' thông thường (dùng 答える).",
        ],
        contrast: "にこたえて ≈ đáp ứng. Khác に対して (đối với) và 答える (trả lời).",
        examples: [
          ex(
            "消費者の要望にこたえて新製品を出した。",
            "しょうひしゃのようぼうにこたえてしんせいひんをだした。",
            "Đáp ứng nguyện vọng người tiêu dùng, đã ra sản phẩm mới.",
            [
              ["消費者", "しょうひしゃ"],
              ["の"],
              ["要望", "ようぼう"],
              ["にこたえて"],
              ["新製品", "しんせいひん"],
              ["を"],
              ["出", "だ"],
              ["した。"],
            ],
          ),
          ex(
            "ファンの声にこたえて再放送が決まった。",
            "ふぁんのこえにこたえてさいほうそうがきまった。",
            "Đáp lại tiếng nói người hâm mộ, đã quyết định phát lại.",
            [
              ["ファンの"],
              ["声", "こえ"],
              ["にこたえて"],
              ["再放送", "さいほうそう"],
              ["が"],
              ["決", "き"],
              ["まった。"],
            ],
          ),
          ex(
            "期待にこたえて彼は好成績を残した。",
            "きたいにこたえてかれはこうせいせきをのこした。",
            "Đáp lại kỳ vọng, anh ấy đạt thành tích tốt.",
            [
              ["期待", "きたい"],
              ["にこたえて"],
              ["彼", "かれ"],
              ["は"],
              ["好成績", "こうせいせき"],
              ["を"],
              ["残", "のこ"],
              ["した。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ にこたえて",
        "Câu dùng にこたえて để nói đáp ứng / đáp lại kỳ vọng hoặc yêu cầu.",
        [
          ["Đáp ứng nhu cầu thị trường đã mở rộng sản xuất.", "市場のニーズにこたえて生産を拡大した。"],
          ["Đáp lại yêu cầu của cư dân đã mở thêm xe buýt.", "住民の要求にこたえてバスを増便した。"],
          ["Đáp ứng kỳ vọng của fan cô ấy hát lại.", "ファンの期待にこたえて彼女はアンコールした。"],
          ["Đáp lại tiếng gọi cứu trợ đã gửi hàng.", "救援の呼びかけにこたえて物資を送った。"],
          ["Đáp ứng mong muốn khách đã kéo dài giờ mở cửa.", "客の希望にこたえて営業時間を延ばした。"],
          ["Đáp lại kỳ vọng giáo viên anh ấy đậu kỳ thi.", "先生の期待にこたえて彼は試験に合格した。"],
          ["Đáp ứng nhu cầu học viên mở thêm lớp tối.", "受講者のニーズにこたえて夜間講座を開いた。"],
          ["Đáp lại yêu cầu công chúng công bố dữ liệu.", "世論の要求にこたえてデータを公開した。"],
          ["Đáp ứng nguyện vọng nhân viên cải thiện phúc lợi.", "社員の要望にこたえて福利厚生を改善した。"],
          ["Đáp lại kỳ vọng cổ đông tăng cổ tức.", "株主の期待にこたえて配当を増やした。"],
        ],
        [
          ["顧客の声にこたえて価格を見直した。", "Đáp lại tiếng nói khách hàng đã xem lại giá."],
          ["時代の要請にこたえて制度を変えた。", "Đáp ứng yêu cầu thời đại đã đổi chế độ."],
          ["読者の要望にこたえて続編を書いた。", "Đáp ứng nguyện vọng độc giả đã viết phần tiếp."],
          ["選手たちは声援にこたえて奮闘した。", "Các vận động viên đáp lại cổ vũ và cố gắng."],
          ["地域の期待にこたえて病院が開業した。", "Đáp ứng kỳ vọng địa phương bệnh viện đã khai trương."],
          ["子供たちの願いにこたえて公園を造った。", "Đáp lại ước nguyện của trẻ đã làm công viên."],
          ["利用者の意見にこたえてアプリを更新した。", "Đáp ứng ý kiến người dùng đã cập nhật app."],
          ["国際社会の要請にこたえて協力した。", "Đáp ứng yêu cầu cộng đồng quốc tế đã hợp tác."],
          ["観客のアンコールにこたえて再演した。", "Đáp lại encore của khán giả đã diễn lại."],
          ["現場のニーズにこたえて人員を増やした。", "Đáp ứng nhu cầu hiện trường đã tăng nhân sự."],
        ],
        [
          ["Đáp ứng nguyện vọng ra sản phẩm mới.", ["要望に", "こたえて", "新製品を", "出した。"], 1],
          ["Đáp lại tiếng nói fan phát lại.", ["声に", "こたえて", "再放送が", "決まった。"], 1],
          ["Đáp lại kỳ vọng đạt thành tích.", ["期待に", "こたえて", "好成績を", "残した。"], 1],
          ["Đáp ứng nhu cầu mở rộng sản xuất.", ["ニーズに", "こたえて", "生産を", "拡大した。"], 1],
          ["Đáp lại yêu cầu tăng chuyến xe.", ["要求に", "こたえて", "増便を", "決めた。"], 1],
          ["Đáp ứng mong muốn kéo dài giờ.", ["希望に", "こたえて", "時間を", "延ばした。"], 1],
          ["Đáp lại kỳ vọng thầy đậu thi.", ["期待に", "こたえて", "合格を", "果たした。"], 1],
          ["Đáp ứng nguyện vọng cải thiện phúc lợi.", ["要望に", "こたえて", "待遇を", "改善した。"], 1],
          ["Đáp lại ý kiến cập nhật app.", ["意見に", "こたえて", "アプリを", "更新した。"], 1],
          ["Đáp ứng nhu cầu tăng nhân sự.", ["ニーズに", "こたえて", "人員を", "増やした。"], 1],
        ],
      ),
    ),
  ];
}
