import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L11-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 13, BATCH);

export function lesson13Patterns(byId) {
  return [
    P(
      byId,
      "l13-g01",
      {
        meaning: "… nghĩa là… / … chính là… (định nghĩa, giải thích)",
        structures: ["N ＋ とは", "〜とは〜ことだ／〜ものだ"],
        explanation:
          "Đưa ra định nghĩa hoặc giải thích bản chất của từ/khái niệm; hay gặp trong sách giáo khoa và bài giảng.",
        usage: "Giải thích thuật ngữ, nêu ý nghĩa: AとはBだ.",
        cautions: [
          "Khác というのは khi kể chuyện / dẫn lời nói thường ngày.",
          "Không dùng とは để chỉ liên tưởng chủ đề (dùng といえば／というと).",
        ],
        contrast: "とは ≈ định nghĩa. Khác といえば (nhắc đến thì liên tưởng) và というのは (giải thích mềm).",
        examples: [
          ex(
            "Longevityとは長生きすることだ。",
            "ろんじぇびてぃーとはながいきすることだ。",
            "Longevity nghĩa là sống lâu.",
            [
              ["Longevityとは"],
              ["長生", "ながい"],
              ["きすることだ。"],
            ],
          ),
          ex(
            "ボランティアとは無報酬で社会に貢献することだ。",
            "ぼらんてぃあとはむほうしゅうでしゃかいにこうけんすることだ。",
            "Tình nguyện nghĩa là đóng góp cho xã hội không thù lao.",
            [
              ["ボランティアとは"],
              ["無報酬", "むほうしゅう"],
              ["で"],
              ["社会", "しゃかい"],
              ["に"],
              ["貢献", "こうけん"],
              ["することだ。"],
            ],
          ),
          ex(
            "この記号とは何を意味するのか。",
            "このきごうとはなにをいみするのか。",
            "Ký hiệu này nghĩa là gì vậy?",
            [
              ["この"],
              ["記号", "きごう"],
              ["とは"],
              ["何", "なに"],
              ["を"],
              ["意味", "いみ"],
              ["するのか。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ とは",
        "Câu dùng とは để định nghĩa hoặc giải thích khái niệm.",
        [
          ["GDP nghĩa là tổng sản phẩm quốc nội.", "GDPとは国内総生産のことだ。"],
          ["Thư viện nghĩa là nơi cho mượn sách.", "図書館とは本を借りる場所だ。"],
          ["Passport nghĩa là hộ chiếu.", "パスポートとは旅券のことだ。"],
          ["Copyright nghĩa là bản quyền.", "著作権とは作品を保護する権利だ。"],
          ["Recycling nghĩa là tái chế.", "リサイクルとは資源を再利用することだ。"],
          ["Internship nghĩa là thực tập.", "インターンシップとは実務を学ぶことだ。"],
          ["Deadline nghĩa là hạn chót.", "締め切りとは提出の最終期限だ。"],
          ["Democracy nghĩa là dân chủ.", "民主主義とは国民が政治に参加する仕組みだ。"],
          ["Inflation nghĩa là lạm phát.", "インフレとは物価が上がることだ。"],
          ["Mentor nghĩa là người hướng dẫn.", "メンターとは助言してくれる先輩だ。"],
        ],
        [
          ["AIとは人工知能のことだ。", "AI nghĩa là trí tuệ nhân tạo."],
          ["方言とは地域特有の言葉だ。", "Phương ngữ nghĩa là lời nói riêng của vùng."],
          ["予算とは使えるお金の計画だ。", "Ngân sách nghĩa là kế hoạch tiền được dùng."],
          ["履歴書とは職歴を書く書類だ。", "Sơ yếu lý lịch nghĩa là giấy ghi lịch sử nghề."],
          ["残業とは定時後に働くことだ。", "Tăng ca nghĩa là làm việc sau giờ quy định."],
          ["条約とは国同士の約束だ。", "Hiệp ước nghĩa là lời hứa giữa các nước."],
          ["栄養とは体に必要な成分だ。", "Dinh dưỡng nghĩa là thành phần cơ thể cần."],
          ["選挙とは代表を選ぶ制度だ。", "Bầu cử nghĩa là chế độ chọn đại diện."],
          ["習慣とは繰り返し行う行動だ。", "Thói quen nghĩa là hành động lặp lại."],
          ["偏見とは根拠のない思い込みだ。", "Định kiến nghĩa là thành kiến thiếu căn cứ."],
        ],
        [
          ["GDP nghĩa là tổng sản phẩm.", ["GDPとは", "国内の", "総生産の", "ことだ。"], 0],
          ["Thư viện là nơi mượn sách.", ["図書館とは", "本を", "借りる", "場所だ。"], 0],
          ["AI nghĩa là trí tuệ nhân tạo.", ["AIとは", "人工", "知能の", "ことだ。"], 0],
          ["Deadline là hạn nộp cuối.", ["締め切りとは", "提出の", "最終", "期限だ。"], 0],
          ["Recycling là tái sử dụng.", ["リサイクルとは", "資源を", "再利用する", "ことだ。"], 0],
          ["Ngân sách là kế hoạch tiền.", ["予算とは", "使える", "お金の", "計画だ。"], 0],
          ["Tăng ca là làm sau giờ.", ["残業とは", "定時後に", "働く", "ことだ。"], 0],
          ["Bầu cử là chọn đại diện.", ["選挙とは", "代表を", "選ぶ", "制度だ。"], 0],
          ["Thói quen là hành động lặp.", ["習慣とは", "繰り返し", "行う", "行動だ。"], 0],
          ["Định kiến là thành kiến.", ["偏見とは", "根拠のない", "思い込み", "だ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l13-g02",
      {
        meaning: "Nói đến… thì… / nhắc đến… liền nghĩ đến…",
        structures: ["N／普通形 ＋ といえば"],
        explanation:
          "Đưa chủ đề rồi liên tưởng đến điều tiêu biểu, hoặc nêu ý kiến khi phải chọn.",
        usage: "Nhắc chủ đề: nói đến mùa hè thì…; cũng dùng khi chọn đáp án: nếu phải nói thì…",
        cautions: [
          "partial-match: bài TNĐG cũng nhắc といったら — vẫn học riêng といえば.",
          "Khác とは (định nghĩa) và となると (khi đụng đến thì…).",
        ],
        contrast: "といえば ≈ nhắc đến thì liên tưởng. Gần というと; khác といったら (cảm thán mạnh).",
        examples: [
          ex(
            "夏といえば海と花火だ。",
            "なつといえばうみとはなびだ。",
            "Nói đến mùa hè thì biển và pháo hoa.",
            [
              ["夏", "なつ"],
              ["といえば"],
              ["海", "うみ"],
              ["と"],
              ["花火", "はなび"],
              ["だ。"],
            ],
          ),
          ex(
            "日本の料理といえば寿司が思い浮かぶ。",
            "にほんのりょうりといえばすしがおもいうかぶ。",
            "Nói đến món Nhật thì nghĩ đến sushi.",
            [
              ["日本", "にほん"],
              ["の"],
              ["料理", "りょうり"],
              ["といえば"],
              ["寿司", "すし"],
              ["が"],
              ["思", "おも"],
              ["い"],
              ["浮", "う"],
              ["かぶ。"],
            ],
          ),
          ex(
            "私の趣味といえば読書です。",
            "わたしのしゅみといえばどくしょです。",
            "Sở thích của tôi, nói thì là đọc sách.",
            [
              ["私", "わたし"],
              ["の"],
              ["趣味", "しゅみ"],
              ["といえば"],
              ["読書", "どくしょ"],
              ["です。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ といえば",
        "Câu dùng といえば: nhắc chủ đề rồi liên tưởng điều tiêu biểu.",
        [
          ["Nói đến Kyoto thì đền chùa.", "京都といえばお寺だ。"],
          ["Nói đến mùa đông thì tuyết.", "冬といえば雪だ。"],
          ["Nói đến Osaka thì takoyaki.", "大阪といえばたこ焼きだ。"],
          ["Nói đến kỳ nghỉ thì du lịch.", "休暇といえば旅行だ。"],
          ["Nói đến sáng thì cà phê.", "朝といえばコーヒーだ。"],
          ["Nói đến thể thao thì bóng đá.", "スポーツといえばサッカーだ。"],
          ["Nói đến quà Nhật thì mochi.", "日本のお土産といえば餅だ。"],
          ["Nói đến kỳ thi thì ôn tập.", "試験といえば復習だ。"],
          ["Nói đến cuối tuần thì nghỉ ngơi.", "週末といえば休息だ。"],
          ["Nói đến mùa xuân thì hoa anh đào.", "春といえば桜だ。"],
        ],
        [
          ["秋といえば紅葉が美しい。", "Nói đến mùa thu thì lá đỏ đẹp."],
          ["東京といえば電車が便利だ。", "Nói đến Tokyo thì tàu điện tiện."],
          ["子供の頃といえば外で遊んだ。", "Nhắc tuổi nhỏ thì chơi ngoài trời."],
          ["健康といえば睡眠が大切だ。", "Nói đến sức khỏe thì ngủ quan trọng."],
          ["夏祭りといえば浴衣を着る。", "Nói đến lễ hội hè thì mặc yukata."],
          ["誕生日といえばケーキだ。", "Nói đến sinh nhật thì bánh kem."],
          ["雨の日といえば家で本を読む。", "Nói đến ngày mưa thì đọc sách ở nhà."],
          ["仕事のストレスといえば残業だ。", "Nói đến stress công việc thì tăng ca."],
          ["旅行といえば計画が楽しい。", "Nói đến du lịch thì lập kế hoạch vui."],
          ["勉強といえば辞書が必要だ。", "Nói đến học thì cần từ điển."],
        ],
        [
          ["Nói hè thì biển pháo hoa.", ["夏と", "いえば", "海が", "好きだ。"], 1],
          ["Nói Kyoto thì đền.", ["京都と", "いえば", "お寺が", "有名だ。"], 1],
          ["Nói đông thì tuyết.", ["冬と", "いえば", "雪が", "降る。"], 1],
          ["Nói thu thì lá đỏ.", ["秋と", "いえば", "紅葉が", "美しい。"], 1],
          ["Nói xuân thì anh đào.", ["春と", "いえば", "桜が", "咲く。"], 1],
          ["Nói sinh nhật thì bánh.", ["誕生日と", "いえば", "ケーキを", "食べる。"], 1],
          ["Nói cuối tuần thì nghỉ.", ["週末と", "いえば", "休息が", "必要だ。"], 1],
          ["Nói thể thao thì bóng đá.", ["スポーツと", "いえば", "サッカーが", "人気だ。"], 1],
          ["Nói Tokyo thì tàu tiện.", ["東京と", "いえば", "電車が", "便利だ。"], 1],
          ["Nói sức khỏe thì ngủ.", ["健康と", "いえば", "睡眠が", "大切だ。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l13-g03",
      {
        meaning: "Nói đến… / nhắc đến… thì… (cụm liên tưởng chủ đề)",
        structures: [
          "N／普通形 ＋ というと",
          "N／普通形 ＋ といえば",
          "N／普通形 ＋ といったら",
        ],
        explanation:
          "Cùng nêu chủ đề rồi dẫn liên tưởng; というと hơi khách quan, といえば phổ biến, といったら có thể nhấn cảm xúc.",
        usage: "Mở chủ đề hội thoại hoặc bài viết: nhắc A thì nghĩ B.",
        cautions: [
          "Ba dạng gần nghĩa; chọn theo sắc thái, không đổi lung tung trong cùng câu.",
          "といったら còn dùng cảm thán (l13-g05) — phân biệt ngữ cảnh.",
        ],
        contrast: "というと／といえば／といったら ≈ nói đến thì…. Khác とは (định nghĩa).",
        examples: [
          ex(
            "旅行というと海外を想像する人が多い。",
            "りょこうというとかいがいをそうぞうするひとがおおい。",
            "Nói đến du lịch, nhiều người tưởng tượng nước ngoài.",
            [
              ["旅行", "りょこう"],
              ["というと"],
              ["海外", "かいがい"],
              ["を"],
              ["想像", "そうぞう"],
              ["する"],
              ["人", "ひと"],
              ["が"],
              ["多", "おお"],
              ["い。"],
            ],
          ),
          ex(
            "休憩といえばコーヒーが欠かせない。",
            "きゅうけいといえばコーヒーがかかせない。",
            "Nói đến nghỉ giải lao thì cà phê không thể thiếu.",
            [
              ["休憩", "きゅうけい"],
              ["といえば"],
              ["コーヒーが"],
              ["欠", "か"],
              ["かせない。"],
            ],
          ),
          ex(
            "彼の笑顔といったら忘れられない。",
            "かれのえがおといったらわすれられない。",
            "Nụ cười anh ấy thì không thể quên.",
            [
              ["彼", "かれ"],
              ["の"],
              ["笑顔", "えがお"],
              ["といったら"],
              ["忘", "わす"],
              ["れられない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜というと／といえば／といったら",
        "Câu nêu chủ đề bằng というと・といえば・といったら rồi liên tưởng.",
        [
          ["Nói đến kỳ nghỉ hè thì biển.", "夏休みというと海だ。"],
          ["Nói đến bữa sáng thì bánh mì.", "朝食といえばパンだ。"],
          ["Nói đến thành công thì nỗ lực.", "成功といったら努力だ。"],
          ["Nói đến mưa thì ô.", "雨というと傘が必要だ。"],
          ["Nói đến văn phòng thì máy tính.", "オフィスといえばパソコンだ。"],
          ["Nói đến đêm khuya thì yên tĩnh.", "深夜といったら静かだ。"],
          ["Nói đến trường thì bạn bè.", "学校というと友達だ。"],
          ["Nói đến mùa thu hoạch thì gạo.", "収穫といえば米だ。"],
          ["Nói đến lễ hội thì trống.", "祭りといったら太鼓だ。"],
          ["Nói đến thư viện thì im lặng.", "図書館というと静かな場所だ。"],
        ],
        [
          ["休日というと家族と過ごす。", "Nói đến ngày nghỉ thì ở với gia đình."],
          ["運動といえばジョギングが好きだ。", "Nói đến vận động thì thích chạy bộ."],
          ["彼の料理といったら本格的だ。", "Món anh ấy nấu thì rất đúng điệu."],
          ["冬というとこたつが恋しい。", "Nói đến mùa đông thì nhớ kotatsu."],
          ["通勤といえば満員電車だ。", "Nói đến đi làm thì tàu chật cứng."],
          ["失敗といったら学びの機会だ。", "Nói đến thất bại thì là cơ hội học."],
          ["春というと花粉症に注意だ。", "Nói đến xuân thì chú ý dị ứng phấn hoa."],
          ["会議といえば資料の準備だ。", "Nói đến họp thì chuẩn bị tài liệu."],
          ["彼の優しさといったら有名だ。", "Sự tử tế của anh ấy thì nổi tiếng."],
          ["旅行というと計画が大切だ。", "Nói đến du lịch thì kế hoạch quan trọng."],
        ],
        [
          ["Nói du lịch thì nghĩ nước ngoài.", ["旅行と", "いうと", "海外を", "想像する。"], 1],
          ["Nói nghỉ thì cà phê.", ["休憩と", "いえば", "コーヒーが", "欲しい。"], 1],
          ["Nụ cười anh khó quên.", ["笑顔と", "いったら", "忘れられない", "ものだ。"], 1],
          ["Nói hè thì biển.", ["夏休みと", "いうと", "海が", "浮かぶ。"], 1],
          ["Nói sáng thì bánh mì.", ["朝食と", "いえば", "パンが", "定番だ。"], 1],
          ["Nói mưa thì cần ô.", ["雨と", "いうと", "傘が", "必要だ。"], 1],
          ["Nói đi làm thì tàu đông.", ["通勤と", "いえば", "満員電車が", "思い浮かぶ。"], 1],
          ["Nói họp thì chuẩn bị giấy.", ["会議と", "いえば", "資料の", "準備だ。"], 1],
          ["Nói đông thì nhớ kotatsu.", ["冬と", "いうと", "こたつが", "恋しい。"], 1],
          ["Nói thất bại thì học được.", ["失敗と", "いったら", "学びの", "機会だ。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l13-g04",
      {
        meaning: "Cứ đụng đến… / khi nói đến lĩnh vực… thì…",
        structures: ["N ＋ （のこと）となると", "普通形 ＋ となると"],
        explanation:
          "Khi chủ đề chuyển sang lĩnh vực/việc cụ thể, thái độ hoặc tình hình thay đổi rõ; thường nhấn điểm yếu/điểm mạnh đặc biệt.",
        usage: "Nhấn: bình thường thì được, nhưng cứ đụng đến A thì…",
        cautions: [
          "Khác となると giả định điều kiện ở bài khác (L15).",
          "のこととなると nhấn 'việc về…' rõ hơn một chút.",
        ],
        contrast: "（のこと）となると ≈ cứ đụng đến… thì. Khác といえば (liên tưởng nhẹ).",
        examples: [
          ex(
            "彼は普段おとなしいが、仕事のこととなると厳しい。",
            "かれはふだんおとなしいが、しごとのこととなるときびしい。",
            "Anh ấy thường hiền, nhưng đụng đến việc làm thì nghiêm.",
            [
              ["彼", "かれ"],
              ["は"],
              ["普段", "ふだん"],
              ["おとなしいが、"],
              ["仕事", "しごと"],
              ["のこととなると"],
              ["厳", "きび"],
              ["しい。"],
            ],
          ),
          ex(
            "お金のこととなると慎重になる。",
            "おかねのこととなるとしんちょうになる。",
            "Cứ đụng đến tiền thì trở nên thận trọng.",
            [
              ["お金", "おかね"],
              ["のこととなると"],
              ["慎重", "しんちょう"],
              ["になる。"],
            ],
          ),
          ex(
            "試験となると急に本気を出す。",
            "しけんとなるときゅうにほんきをだす。",
            "Cứ đến kỳ thi thì đột nhiên nghiêm túc.",
            [
              ["試験", "しけん"],
              ["となると"],
              ["急", "きゅう"],
              ["に"],
              ["本気", "ほんき"],
              ["を"],
              ["出", "だ"],
              ["す。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ （のこと）となると",
        "Câu dùng （のこと）となると: cứ đụng đến lĩnh vực đó thì thái độ đổi.",
        [
          ["Đụng đến toán thì cậu ấy giỏi.", "数学のこととなると彼は得意だ。"],
          ["Đụng đến sức khỏe thì lo ngay.", "健康のこととなると心配になる。"],
          ["Đụng đến thời hạn thì căng thẳng.", "締め切りとなると緊張する。"],
          ["Đụng đến con thì bà ấy mềm mỏng.", "子供のこととなると彼女は優しい。"],
          ["Đụng đến tiền nhà thì tính toán kỹ.", "家賃のこととなると慎重に考える。"],
          ["Đụng đến thuyết trình thì run.", "発表となると声が震える。"],
          ["Đụng đến ăn thì anh ấy kén.", "食事のこととなると彼は厳しい。"],
          ["Đụng đến quy tắc thì không nhượng.", "規則となると妥協しない。"],
          ["Đụng đến tiếng Anh thì tự tin.", "英語のこととなると自信がある。"],
          ["Đụng đến đêm khuya thì mệt.", "深夜となると集中力が落ちる。"],
        ],
        [
          ["趣味のこととなると話が長い。", "Đụng đến sở thích thì nói dài."],
          ["安全のこととなると妥協できない。", "Đụng đến an toàn thì không thỏa hiệp."],
          ["試合となると急に強くなる。", "Cứ đến trận đấu thì đột nhiên mạnh."],
          ["将来のこととなると悩みが増える。", "Đụng đến tương lai thì lo nhiều hơn."],
          ["料理のこととなると時間がかかる。", "Đụng đến nấu ăn thì tốn thời gian."],
          ["契約となると書類が増える。", "Cứ đến hợp đồng thì giấy tờ tăng."],
          ["家族のこととなると優先する。", "Đụng đến gia đình thì ưu tiên."],
          ["品質のこととなると妥協しない。", "Đụng đến chất lượng thì không nhượng."],
          ["通勤となると電車が混む。", "Cứ đến giờ đi làm thì tàu đông."],
          ["責任のこととなると態度が変わる。", "Đụng đến trách nhiệm thì thái độ đổi."],
        ],
        [
          ["Đụng việc làm thì nghiêm.", ["仕事の", "こととなると", "態度が", "厳しい。"], 1],
          ["Đụng tiền thì thận trọng.", ["お金の", "こととなると", "慎重に", "なる。"], 1],
          ["Đến thi thì nghiêm túc.", ["試験と", "なると", "本気を", "出す。"], 1],
          ["Đụng toán thì giỏi.", ["数学の", "こととなると", "彼は", "得意だ。"], 1],
          ["Đụng sức khỏe thì lo.", ["健康の", "こととなると", "心配が", "増える。"], 1],
          ["Đến thuyết trình thì run.", ["発表と", "なると", "声が", "震える。"], 1],
          ["Đụng sở thích thì nói dài.", ["趣味の", "こととなると", "話が", "長い。"], 1],
          ["Đụng an toàn không thỏa hiệp.", ["安全の", "こととなると", "妥協は", "できない。"], 1],
          ["Đụng gia đình thì ưu tiên.", ["家族の", "こととなると", "最優先に", "する。"], 1],
          ["Đụng trách nhiệm thái độ đổi.", ["責任の", "こととなると", "態度が", "変わる。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l13-g05",
      {
        meaning: "Nói đến… thì… (nhấn mạnh / cảm thán mức độ)",
        structures: ["N／普通形 ＋ といったら"],
        explanation:
          "Nhắc chủ đề rồi nhấn mức độ mạnh, thường kèm cảm thán: đẹp quá, tệ quá, không tả nổi…",
        usage: "Khen/chê mạnh: nói đến A thì thật sự…; cũng dùng liên tưởng như といえば.",
        cautions: [
          "partial-match: chia sẻ bài TNĐG với といえば — vẫn viết đủ nội dung riêng.",
          "Hay đi với ない／すごい／ひどい…; tránh dùng như định nghĩa とは.",
        ],
        contrast: "といったら ≈ nhấn cảm xúc khi nhắc chủ đề. Gần といえば; mạnh hơn というと.",
        examples: [
          ex(
            "この景色の美しさといったらない。",
            "このけしきのうつくしさといったらない。",
            "Đẹp của cảnh này thì không tả nổi.",
            [
              ["この"],
              ["景色", "けしき"],
              ["の"],
              ["美", "うつく"],
              ["しさといったらない。"],
            ],
          ),
          ex(
            "昨日の混雑といったらひどかった。",
            "きのうのこんざつといったらひどかった。",
            "Đông đúc hôm qua thì thật kinh khủng.",
            [
              ["昨日", "きのう"],
              ["の"],
              ["混雑", "こんざつ"],
              ["といったら"],
              ["ひどかった。"],
            ],
          ),
          ex(
            "彼女の努力といったら尊敬するしかない。",
            "かのじょのどりょくといったらそんけいするしかない。",
            "Nỗ lực của cô ấy thì chỉ còn biết kính phục.",
            [
              ["彼女", "かのじょ"],
              ["の"],
              ["努力", "どりょく"],
              ["といったら"],
              ["尊敬", "そんけい"],
              ["するしかない。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ といったら",
        "Câu dùng といったら để nhấn mức độ hoặc cảm thán khi nhắc chủ đề.",
        [
          ["Nóng hôm nay thì không tả nổi.", "今日の暑さといったらない。"],
          ["Vui của buổi tiệc thì tuyệt.", "パーティーの楽しさといったら最高だ。"],
          ["Ồn của công trường thì kinh.", "工事の騒音といったらひどい。"],
          ["Ngọt của bánh thì bất ngờ.", "このケーキの甘さといったら驚くほどだ。"],
          ["Lạnh đêm qua thì khủng khiếp.", "昨夜の寒さといったらひどかった。"],
          ["Đông của ga thì không tin nổi.", "駅の混雑といったら信じられない。"],
          ["Khó của bài thi thì quá sức.", "試験の難しさといったら大変だ。"],
          ["Đẹp của hoa anh đào thì tuyệt.", "桜の美しさといったら素晴らしい。"],
          ["Chậm của mạng thì bực.", "通信の遅さといったらいらいらする。"],
          ["Tốt của dịch vụ thì đáng khen.", "接客の良さといったら感心する。"],
        ],
        [
          ["彼の優しさといったら有名だ。", "Sự tử tế của anh ấy thì nổi tiếng."],
          ["この店の安さといったら驚きだ。", "Rẻ của quán này thì đáng kinh ngạc."],
          ["渋滞のひどさといったら困る。", "Tắc đường tệ thế thì khổ."],
          ["娘の成長といったら早いものだ。", "Con gái lớn nhanh thì thật nhanh."],
          ["夜景のきれいさといったらない。", "Đẹp của cảnh đêm thì không tả nổi."],
          ["彼の遅刻といったら日常茶飯事だ。", "Đi muộn của anh ấy thì chuyện thường ngày."],
          ["この香りの強さといったら独特だ。", "Mạnh của mùi này thì độc đáo."],
          ["夏休みの短さといったら残念だ。", "Ngắn của nghỉ hè thì đáng tiếc."],
          ["彼の記憶力といったらすごい。", "Trí nhớ của anh ấy thì tuyệt."],
          ["朝の混雑といったら避けたい。", "Đông buổi sáng thì muốn tránh."],
        ],
        [
          ["Cảnh đẹp không tả nổi.", ["景色の", "美しさと", "いったら", "ない。"], 2],
          ["Đông hôm qua thật tệ.", ["昨日の", "混雑と", "いったら", "ひどい。"], 2],
          ["Nỗ lực cô đáng kính.", ["努力と", "いったら", "尊敬する", "しかない。"], 1],
          ["Nóng hôm nay không tả.", ["今日の", "暑さと", "いったら", "ない。"], 2],
          ["Ồn công trường kinh.", ["工事の", "騒音と", "いったら", "ひどい。"], 2],
          ["Ga đông không tin nổi.", ["駅の", "混雑と", "いったら", "信じられない。"], 2],
          ["Hoa anh đào đẹp tuyệt.", ["桜の", "美しさと", "いったら", "素晴らしい。"], 2],
          ["Mạng chậm thì bực.", ["通信の", "遅さと", "いったら", "いらいらする。"], 2],
          ["Quán rẻ đáng ngạc nhiên.", ["店の", "安さと", "いったら", "驚きだ。"], 2],
          ["Trí nhớ anh thì siêu.", ["記憶力と", "いったら", "本当に", "すごい。"], 1],
        ],
      ),
    ),
  ];
}
