import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L11-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 11, BATCH);

export function lesson11Patterns(byId) {
  return [
    P(
      byId,
      "l11-g01",
      {
        meaning: "Bất kể… / không phân biệt…",
        structures: ["N ＋ を問わず"],
        explanation:
          "Không phân biệt loại/đối tượng; điều kiện áp dụng cho mọi trường hợp nêu ra.",
        usage: "Thông báo, quy định: bất kể tuổi tác, ngày đêm, nội ngoại…",
        cautions: [
          "Thường dùng với cặp đối lập hoặc phạm vi rộng (年齢・性別, 昼夜…).",
          "Trang trọng hơn でも／でも; không dùng tùy tiện trong hội thoại thân mật.",
        ],
        contrast: "を問わず ≈ bất kể. Gần にかかわらず; khác はともかく (tạm gác A).",
        examples: [
          ex(
            "年齢を問わず参加できる。",
            "ねんれいをとわずさんかできる。",
            "Bất kể tuổi tác đều có thể tham gia.",
            [
              ["年齢", "ねんれい"],
              ["を"],
              ["問", "と"],
              ["わず"],
              ["参加", "さんか"],
              ["できる。"],
            ],
          ),
          ex(
            "昼夜を問わず電話がかかってくる。",
            "ちゅうやをとわずでんわがかかってくる。",
            "Điện thoại gọi đến bất kể ngày đêm.",
            [
              ["昼夜", "ちゅうや"],
              ["を"],
              ["問", "と"],
              ["わず"],
              ["電話", "でんわ"],
              ["がかかってくる。"],
            ],
          ),
          ex(
            "経験を問わず募集している。",
            "けいけんをとわずぼしゅうしている。",
            "Đang tuyển bất kể kinh nghiệm.",
            [
              ["経験", "けいけん"],
              ["を"],
              ["問", "と"],
              ["わず"],
              ["募集", "ぼしゅう"],
              ["している。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜を問わず",
        "Câu dùng を問わず: bất kể phạm vi nêu ra, điều kiện vẫn áp dụng.",
        [
          ["Bất kể giới tính đều được ứng tuyển.", "性別を問わず応募できる。"],
          ["Bất kể quốc tịch đều được vào cửa.", "国籍を問わず入場できる。"],
          ["Bất kể ngày thường hay cuối tuần cửa hàng mở.", "平日・休日を問わず店が開いている。"],
          ["Bất kể nghề nghiệp đều được tham dự.", "職業を問わず出席できる。"],
          ["Bất kể thời tiết trận đấu vẫn diễn ra.", "天候を問わず試合は行われる。"],
          ["Bất kể trình độ đều được học thử.", "レベルを問わず体験できる。"],
          ["Bất kể mùa vụ đều có hàng.", "季節を問わず商品がある。"],
          ["Bất kể quy mô công ty đều nhận hỗ trợ.", "規模を問わず支援を受けられる。"],
          ["Bất kể phương tiện đều phải trả phí.", "交通手段を問わず料金がかかる。"],
          ["Bất kể lý do đều phải nộp báo cáo.", "理由を問わず報告書が必要だ。"],
        ],
        [
          ["学歴を問わず挑戦してほしい。", "Muốn mọi người thử sức bất kể học vấn."],
          ["場所を問わず連絡が取れる。", "Liên lạc được bất kể nơi đâu."],
          ["分野を問わず専門家が集まった。", "Chuyên gia tụ họp bất kể lĩnh vực."],
          ["時間を問わず相談に乗る。", "Sẵn sàng tư vấn bất kể giờ giấc."],
          ["立場を問わず意見を言うべきだ。", "Nên nêu ý kiến bất kể lập trường."],
          ["形式を問わず提出してよい。", "Nộp được bất kể hình thức."],
          ["言語を問わず資料を用意した。", "Đã chuẩn bị tài liệu bất kể ngôn ngữ."],
          ["距離を問わず配達する。", "Giao hàng bất kể khoảng cách."],
          ["予算を問わず見積もりを出す。", "Đưa báo giá bất kể ngân sách."],
          ["条件を問わず検討する。", "Xem xét bất kể điều kiện."],
        ],
        [
          ["Bất kể tuổi đều tham gia được.", ["年齢を", "問わず", "参加が", "可能だ。"], 1],
          ["Gọi đến bất kể ngày đêm.", ["昼夜を", "問わず", "電話が", "来る。"], 1],
          ["Tuyển bất kể kinh nghiệm.", ["経験を", "問わず", "募集を", "行う。"], 1],
          ["Ứng tuyển bất kể giới tính.", ["性別を", "問わず", "応募が", "できる。"], 1],
          ["Vào cửa bất kể quốc tịch.", ["国籍を", "問わず", "入場が", "認められる。"], 1],
          ["Mở cửa bất kể ngày thường hay nghỉ.", ["平日休日を", "問わず", "営業を", "続ける。"], 1],
          ["Thi đấu bất kể thời tiết.", ["天候を", "問わず", "試合が", "実施される。"], 1],
          ["Học thử bất kể trình độ.", ["レベルを", "問わず", "体験が", "できる。"], 1],
          ["Thử sức bất kể học vấn.", ["学歴を", "問わず", "挑戦して", "ほしい。"], 1],
          ["Tư vấn bất kể giờ.", ["時間を", "問わず", "相談に", "乗る。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l11-g02",
      {
        meaning: "Không liên quan đến… / bất chấp…",
        structures: [
          "N／Vる・ない／いA／なA語幹 ＋ にかかわりなく",
          "N／Vる・ない／いA／なA語幹 ＋ にかかわらず",
        ],
        explanation:
          "Kết quả/hành động không bị ảnh hưởng bởi điều kiện nêu trước; bất chấp A vẫn B.",
        usage: "Quy định, lập luận: dù mưa hay nắng, dù đồng ý hay không…",
        cautions: [
          "にかかわらず phổ biến hơn trong văn viết; にかかわりなく cùng nghĩa.",
          "Sau danh từ đôi khi có の (天候のいかんにかかわらず).",
        ],
        contrast: "にかかわらず ≈ bất chấp. Gần を問わず; khác もかまわず (không quan tâm đến…).",
        examples: [
          ex(
            "天候にかかわらず出発する。",
            "てんこうにかかわらずしゅっぱつする。",
            "Dù thời tiết thế nào cũng khởi hành.",
            [
              ["天候", "てんこう"],
              ["にかかわらず"],
              ["出発", "しゅっぱつ"],
              ["する。"],
            ],
          ),
          ex(
            "費用にかかわりなく必要な調査をする。",
            "ひようにかかわりなくひつようなちょうさをする。",
            "Bất chấp chi phí vẫn làm khảo sát cần thiết.",
            [
              ["費用", "ひよう"],
              ["にかかわりなく"],
              ["必要", "ひつよう"],
              ["な"],
              ["調査", "ちょうさ"],
              ["をする。"],
            ],
          ),
          ex(
            "賛成するしないにかかわらず決める。",
            "さんせいするしないにかかわらずきめる。",
            "Dù tán thành hay không vẫn quyết định.",
            [
              ["賛成", "さんせい"],
              ["するしない"],
              ["にかかわらず"],
              ["決", "き"],
              ["める。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜にかかわりなく・〜にかかわらず",
        "Câu dùng にかかわらず／にかかわりなく: kết quả không phụ thuộc điều kiện trước.",
        [
          ["Bất chấp tuổi vẫn được dự thi.", "年齢にかかわらず受験できる。"],
          ["Bất chấp kết quả vẫn tiếp tục luyện.", "結果にかかわりなく練習を続ける。"],
          ["Dù mưa hay nắng sự kiện vẫn tổ chức.", "雨天晴天にかかわらず行事を行う。"],
          ["Bất chấp ý kiến vẫn tiến hành.", "意見にかかわらず進める。"],
          ["Dù có hay không có kinh nghiệm đều được.", "経験の有無にかかわらず応募できる。"],
          ["Bất chấp khoảng cách vẫn giao hàng.", "距離にかかわりなく配送する。"],
          ["Dù đồng ý hay phản đối phải tuân thủ.", "賛成反対にかかわらず規則に従う。"],
          ["Bất chấp tình trạng sức khỏe phải nghỉ.", "体調にかかわらず休むべきだ。"],
          ["Dù thành công hay thất bại hãy báo cáo.", "成否にかかわらず報告せよ。"],
          ["Bất chấp ngân sách vẫn ưu tiên an toàn.", "予算にかかわりなく安全を優先する。"],
        ],
        [
          ["成績にかかわらず努力は認められる。", "Nỗ lực được công nhận bất chấp điểm số."],
          ["性別にかかわりなく平等に扱う。", "Đối xử bình đẳng bất chấp giới tính."],
          ["来るか来ないかにかかわらず席を用意する。", "Chuẩn bị chỗ dù đến hay không."],
          ["天候のいかんにかかわらず実施する。", "Tổ chức bất chấp tình hình thời tiết."],
          ["好き嫌いにかかわらず野菜を食べなさい。", "Hãy ăn rau bất chấp thích hay ghét."],
          ["国籍にかかわらず権利がある。", "Có quyền bất chấp quốc tịch."],
          ["時間にかかわりなく対応する。", "Ứng phó bất chấp thời gian."],
          ["勝敗にかかわらず握手する。", "Bắt tay bất chấp thắng thua."],
          ["費用の多少にかかわらず申請できる。", "Xin được bất chấp chi phí nhiều ít."],
          ["状況にかかわらず冷静でいろ。", "Hãy bình tĩnh bất chấp tình huống."],
        ],
        [
          ["Khởi hành bất chấp thời tiết.", ["天候に", "かかわらず", "出発を", "決めた。"], 1],
          ["Khảo sát bất chấp chi phí.", ["費用に", "かかわりなく", "調査を", "行う。"], 1],
          ["Quyết định dù tán thành hay không.", ["賛否に", "かかわらず", "決定を", "下す。"], 1],
          ["Dự thi bất chấp tuổi.", ["年齢に", "かかわらず", "受験が", "できる。"], 1],
          ["Luyện tiếp bất chấp kết quả.", ["結果に", "かかわりなく", "練習を", "続ける。"], 1],
          ["Tiến hành bất chấp ý kiến.", ["意見に", "かかわらず", "作業を", "進める。"], 1],
          ["Giao hàng bất chấp khoảng cách.", ["距離に", "かかわりなく", "配送を", "行う。"], 1],
          ["Báo cáo dù thành hay bại.", ["成否に", "かかわらず", "報告が", "必要だ。"], 1],
          ["Đối xử bình đẳng bất chấp giới tính.", ["性別に", "かかわりなく", "平等に", "扱う。"], 1],
          ["Bắt tay bất chấp thắng thua.", ["勝敗に", "かかわらず", "握手を", "する。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l11-g03",
      {
        meaning: "Không quan tâm đến… / mặc kệ…",
        structures: ["N ＋ もかまわず", "V／いA ＋ のもかまわず"],
        explanation:
          "Bỏ qua sự bất tiện/ý kiến xung quanh mà vẫn làm; nhấn mạnh thái độ không e ngại.",
        usage: "Miêu tả hành động bất chấp sự chú ý, mệt mỏi, mưa…",
        cautions: [
          "Thường mang sắc thái chủ quan: mặc kệ A vẫn làm B.",
          "Khác を問わず (phạm vi quy định); もかまわず thiên về hành vi cá nhân.",
        ],
        contrast: "もかまわず ≈ mặc kệ. Khác にかかわらず (điều kiện khách quan).",
        examples: [
          ex(
            "人目もかまわず泣いた。",
            "ひとめもかまわずないた。",
            "Khóc mặc kệ ánh mắt người quanh.",
            [
              ["人目", "ひとめ"],
              ["もかまわず"],
              ["泣", "な"],
              ["いた。"],
            ],
          ),
          ex(
            "雨もかまわず走り続けた。",
            "あめもかまわずはしりつづけた。",
            "Tiếp tục chạy mặc kệ mưa.",
            [
              ["雨", "あめ"],
              ["もかまわず"],
              ["走", "はし"],
              ["り続けた。"],
            ],
          ),
          ex(
            "疲れているのもかまわず残業した。",
            "つかれているのもかまわずざんぎょうした。",
            "Làm thêm mặc dù đang mệt.",
            [
              ["疲", "つか"],
              ["れているのもかまわず"],
              ["残業", "ざんぎょう"],
              ["した。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜もかまわず",
        "Câu dùng もかまわず: mặc kệ trở ngại/ý kiến mà vẫn hành động.",
        [
          ["Nói to mặc kệ xung quanh.", "周囲もかまわず大声で話した。"],
          ["Ngồi xuống mặc kệ bẩn.", "汚れもかまわず座った。"],
          ["Giúp đỡ mặc kệ bị chỉ trích.", "批判もかまわず助けた。"],
          ["Đi tiếp mặc kệ đau chân.", "足の痛みもかまわず歩いた。"],
          ["Hát mặc kệ xấu hổ.", "恥ずかしさもかまわず歌った。"],
          ["Làm việc mặc kệ sốt.", "熱もかまわず働いた。"],
          ["Cười mặc kệ nghi thức.", "形式もかまわず笑った。"],
          ["Vào nhà mặc kệ giày bẩn.", "靴の泥もかまわず入った。"],
          ["Hỏi mặc kệ đang bận.", "忙しさもかまわず質問した。"],
          ["Gửi thư mặc kệ khuya.", "夜更けもかまわずメールを送った。"],
        ],
        [
          ["視線もかまわず抱きしめた。", "Ôm chặt mặc kệ ánh nhìn."],
          ["危険もかまわず飛び込んだ。", "Nhảy vào mặc kệ nguy hiểm."],
          ["迷惑もかまわず頼んだ。", "Nhờ vả mặc kệ gây phiền."],
          ["服装もかまわず出席した。", "Tham dự mặc kệ trang phục."],
          ["時間もかまわず議論した。", "Thảo luận mặc kệ thời gian."],
          ["体調もかまわず練習した。", "Luyện tập mặc kệ sức khỏe."],
          ["規則もかまわず行動した。", "Hành động mặc kệ quy tắc."],
          ["騒音もかまわず眠った。", "Ngủ được mặc kệ tiếng ồn."],
          ["反対もかまわず決断した。", "Quyết định mặc kệ phản đối."],
          ["年齢もかまわず挑戦した。", "Thử thách mặc kệ tuổi tác."],
        ],
        [
          ["Khóc mặc kệ ánh mắt người.", ["人目も", "かまわず", "涙を", "流した。"], 1],
          ["Chạy tiếp mặc kệ mưa.", ["雨も", "かまわず", "走行を", "続けた。"], 1],
          ["Làm thêm mặc dù mệt.", ["疲れも", "かまわず", "残業を", "した。"], 1],
          ["Nói to mặc kệ xung quanh.", ["周囲も", "かまわず", "大声で", "話した。"], 1],
          ["Ngồi mặc kệ bẩn.", ["汚れも", "かまわず", "地面に", "座った。"], 1],
          ["Giúp mặc kệ chỉ trích.", ["批判も", "かまわず", "援助を", "した。"], 1],
          ["Hát mặc kệ xấu hổ.", ["恥ずかしさも", "かまわず", "歌声を", "上げた。"], 1],
          ["Làm việc mặc kệ sốt.", ["熱も", "かまわず", "仕事を", "続けた。"], 1],
          ["Nhảy vào mặc kệ nguy hiểm.", ["危険も", "かまわず", "中へ", "飛び込んだ。"], 1],
          ["Quyết định mặc kệ phản đối.", ["反対も", "かまわず", "決断を", "下した。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l11-g04",
      {
        meaning: "Tạm gác… sang một bên / … thì chưa nói",
        structures: ["N ＋ はともかく（として）"],
        explanation:
          "Đặt A sang một bên (không bàn/không ưu tiên) rồi nhấn mạnh B quan trọng hơn.",
        usage: "Đàm phán, đánh giá: về giá thì chưa nói, chất lượng…; ngoại hình thì thôi, tính cách…",
        cautions: [
          "はともかく（として） không phủ nhận A, chỉ tạm không bàn.",
          "Khác はさておき (cũng tạm gác nhưng đôi khi chuyển chủ đề nhẹ hơn).",
        ],
        contrast: "はともかく ≈ tạm gác A. Gần はさておき; khác を問わず (bất kể).",
        examples: [
          ex(
            "値段はともかく品質がいい。",
            "ねだんはともかくひんしつがいい。",
            "Giá thì chưa nói, chất lượng tốt.",
            [
              ["値段", "ねだん"],
              ["はともかく"],
              ["品質", "ひんしつ"],
              ["がいい。"],
            ],
          ),
          ex(
            "見た目はともかくとして中身が大事だ。",
            "みためはともかくとしてなかみがだいじだ。",
            "Ngoại hình thì thôi, nội dung mới quan trọng.",
            [
              ["見", "み"],
              ["た目はともかくとして"],
              ["中身", "なかみ"],
              ["が"],
              ["大事", "だいじ"],
              ["だ。"],
            ],
          ),
          ex(
            "勝敗はともかく全力を出せ。",
            "しょうはいはともかくぜんりょくをだせ。",
            "Thắng thua thì chưa nói, hãy hết sức.",
            [
              ["勝敗", "しょうはい"],
              ["はともかく"],
              ["全力", "ぜんりょく"],
              ["を"],
              ["出", "だ"],
              ["せ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜はともかく（として）",
        "Câu dùng はともかく（として）: tạm gác A rồi nhấn B.",
        [
          ["Kỹ năng thì chưa nói, thái độ tốt.", "技術はともかく態度がよい。"],
          ["Tốc độ thì thôi, an toàn quan trọng.", "速さはともかくとして安全が大事だ。"],
          ["Điểm số thì chưa nói, hãy cố gắng.", "点数はともかく努力してほしい。"],
          ["Hình thức thì thôi, nội dung phải rõ.", "形式はともかく内容を明確にせよ。"],
          ["Giá thuê thì chưa nói, vị trí thuận tiện.", "家賃はともかく立地が便利だ。"],
          ["Kinh nghiệm thì thôi, nhiệt huyết có.", "経験はともかくとして熱意がある。"],
          ["Ngoại ngữ thì chưa nói, giao tiếp ổn.", "語学はともかくコミュニケーションはできる。"],
          ["Thời gian thì thôi, chất lượng ưu tiên.", "時間はともかく品質を優先する。"],
          ["Danh tiếng thì chưa nói, thực lực đáng tin.", "名声はともかく実力が確かだ。"],
          ["Sở thích thì thôi, nhiệm vụ phải xong.", "好みはともかくとして仕事を終えよ。"],
        ],
        [
          ["趣味はともかく健康第一だ。", "Sở thích thì chưa nói, sức khỏe trước hết."],
          ["結果はともかく挑戦した意味がある。", "Kết quả thì thôi, việc thử đã có ý nghĩa."],
          ["デザインはともかく使いやすい。", "Thiết kế thì chưa nói, dễ dùng."],
          ["給料はともかくとしてやりがいがある。", "Lương thì thôi, có động lực."],
          ["年齢はともかく能力で判断する。", "Tuổi thì chưa nói, đánh giá theo năng lực."],
          ["過去はともかく今後を考えよう。", "Quá khứ thì thôi, hãy nghĩ tương lai."],
          ["見た目はともかく味が抜群だ。", "Ngoại hình thì chưa nói, vị xuất sắc."],
          ["費用はともかく必要なら買う。", "Chi phí thì thôi, cần thì mua."],
          ["評判はともかく自分で確かめたい。", "Dư luận thì chưa nói, muốn tự kiểm."],
          ["勝敗はともかく楽しもう。", "Thắng thua thì thôi, hãy vui."],
        ],
        [
          ["Giá thì chưa nói chất lượng tốt.", ["値段は", "ともかく", "品質が", "高い。"], 1],
          ["Ngoại hình thì thôi nội dung quan trọng.", ["見た目は", "ともかくとして", "中身を", "見よ。"], 1],
          ["Thắng thua thì chưa nói hãy hết sức.", ["勝敗は", "ともかく", "全力で", "戦え。"], 1],
          ["Kỹ năng thì chưa nói thái độ tốt.", ["技術は", "ともかく", "態度が", "よい。"], 1],
          ["Tốc độ thì thôi an toàn quan trọng.", ["速さは", "ともかくとして", "安全が", "大事だ。"], 1],
          ["Điểm thì chưa nói hãy cố.", ["点数は", "ともかく", "努力が", "必要だ。"], 1],
          ["Hình thức thì thôi nội dung phải rõ.", ["形式は", "ともかく", "内容を", "明確に。"], 1],
          ["Kinh nghiệm thì thôi có nhiệt huyết.", ["経験は", "ともかくとして", "熱意が", "ある。"], 1],
          ["Thiết kế thì chưa nói dễ dùng.", ["デザインは", "ともかく", "操作が", "簡単だ。"], 1],
          ["Quá khứ thì thôi nghĩ tương lai.", ["過去は", "ともかく", "今後を", "考えよう。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l11-g05",
      {
        meaning: "Gác… sang một bên / nói gì thì nói…",
        structures: ["N ＋ はさておき"],
        explanation:
          "Tạm gác chủ đề A rồi chuyển sang B; thường dùng để chuyển mạch hoặc ưu tiên vấn đề khác.",
        usage: "Hội thoại/viết: chuyện đó tạm gác, trước hết…; đùa thì thôi, vấn đề chính…",
        cautions: [
          "Thường đứng đầu câu hoặc mệnh đề để chuyển chủ đề.",
          "Gần はともかく nhưng はさておき thiên về 'tạm để đó, nói việc khác'.",
        ],
        contrast: "はさておき ≈ tạm gác rồi chuyển. Gần はともかく; khác もかまわず.",
        examples: [
          ex(
            "冗談はさておき本題に入ろう。",
            "じょうだんはさておきほんだいにはいろう。",
            "Đùa thì thôi, vào vấn đề chính.",
            [
              ["冗談", "じょうだん"],
              ["はさておき"],
              ["本題", "ほんだい"],
              ["に入ろう。"],
            ],
          ),
          ex(
            "勝敗はさておき楽しめた。",
            "しょうはいはさておきたのしめた。",
            "Thắng thua tạm gác, đã vui được.",
            [
              ["勝敗", "しょうはい"],
              ["はさておき"],
              ["楽", "たの"],
              ["しめた。"],
            ],
          ),
          ex(
            "費用はさておき日程を決めたい。",
            "ひようはさておきにっていをきめたい。",
            "Chi phí tạm gác, muốn chốt lịch.",
            [
              ["費用", "ひよう"],
              ["はさておき"],
              ["日程", "にってい"],
              ["を"],
              ["決", "き"],
              ["めたい。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜はさておき",
        "Câu dùng はさておき: tạm gác A rồi chuyển/ưu tiên B.",
        [
          ["Chi tiết tạm gác, hãy nói kết luận.", "詳細はさておき結論を話そう。"],
          ["Quá khứ tạm gác, nhìn về phía trước.", "過去はさておき前を向こう。"],
          ["Giá tạm gác, hãy thử dùng.", "値段はさておき使ってみよう。"],
          ["Danh tiếng tạm gác, xem sản phẩm.", "評判はさておき製品を見よう。"],
          ["Cảm xúc tạm gác, hãy quyết định.", "感情はさておき決断しよう。"],
          ["Hình thức tạm gác, nội dung trước.", "形式はさておき内容を先に。"],
          ["Lời đồn tạm gác, xác nhận sự thật.", "噂はさておき事実を確認せよ。"],
          ["Sở thích tạm gác, nhiệm vụ đã đến hạn.", "好みはさておき締切が近い。"],
          ["Ngoại hình tạm gác, sức khỏe quan trọng.", "外見はさておき健康が大事だ。"],
          ["Tranh luận tạm gác, cần dữ liệu.", "議論はさておきデータが必要だ。"],
        ],
        [
          ["挨拶はさておき要件を伝えたい。", "Chào hỏi tạm gác, muốn nói việc cần."],
          ["趣味はさておき仕事の話をしよう。", "Sở thích tạm gác, nói chuyện công việc."],
          ["天候はさておき準備を整えよ。", "Thời tiết tạm gác, hãy chuẩn bị."],
          ["年齢はさておき実力を見たい。", "Tuổi tạm gác, muốn xem thực lực."],
          ["文句はさておき手伝ってくれ。", "Phàn nàn tạm gác, hãy giúp đi."],
          ["理論はさておき実践が先だ。", "Lý thuyết tạm gác, thực hành trước."],
          ["私事はさておき会議を始めよう。", "Chuyện riêng tạm gác, bắt đầu họp."],
          ["得失はさておき挑戦する価値がある。", "Được mất tạm gác, đáng thử."],
          ["見た目はさておき機能が優れている。", "Ngoại hình tạm gác, chức năng vượt trội."],
          ["雑談はさておき提案を聞こう。", "Tán gẫu tạm gác, hãy nghe đề xuất."],
        ],
        [
          ["Đùa thì thôi vào vấn đề chính.", ["冗談は", "さておき", "本題を", "話そう。"], 1],
          ["Thắng thua tạm gác đã vui.", ["勝敗は", "さておき", "楽しさが", "残った。"], 1],
          ["Chi phí tạm gác muốn chốt lịch.", ["費用は", "さておき", "日程から", "決めよう。"], 1],
          ["Chi tiết tạm gác nói kết luận.", ["詳細は", "さておき", "結論を", "話そう。"], 1],
          ["Quá khứ tạm gác nhìn phía trước.", ["過去は", "さておき", "前方を", "向こう。"], 1],
          ["Giá tạm gác hãy thử dùng.", ["値段は", "さておき", "使用を", "試そう。"], 1],
          ["Cảm xúc tạm gác hãy quyết.", ["感情は", "さておき", "決断を", "しよう。"], 1],
          ["Lời đồn tạm gác xác nhận sự thật.", ["噂は", "さておき", "事実を", "確認せよ。"], 1],
          ["Chào hỏi tạm gác nói việc cần.", ["挨拶は", "さておき", "用件を", "伝えたい。"], 1],
          ["Tán gẫu tạm gác nghe đề xuất.", ["雑談は", "さておき", "提案を", "聞こう。"], 1],
        ],
      ),
    ),
  ];
}
