import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L21-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 22, BATCH);

export function lesson22Patterns(byId) {
  return [
    P(
      byId,
      "l22-g01",
      {
        meaning: "Hình như… / trông có vẻ… (suy đoán từ dấu hiệu)",
        structures: [
          "普通形 ＋ とみえる／と見える",
          "普通形 ＋ とみえて",
        ],
        explanation:
          "とみえる／と見えて suy đoán dựa trên vẻ bề ngoài hoặc tình huống quan sát được: có vẻ như A.",
        usage: "Nhận xét từ dấu hiệu: mệt; bận; vừa khóc; sắp mưa…",
        cautions: [
          "とみえて nối tiếp: vì có vẻ A nên B.",
          "Khác ようだ／みたいだ khẩu ngữ hơn; とみえる hơi khách quan/văn viết.",
        ],
        contrast:
          "とみえる ≈ có vẻ như…. Gần ようだ nhưng nhấn suy đoán từ vẻ ngoài quan sát.",
        examples: [
          ex(
            "彼は疲れているとみえる。",
            "かれはつかれているとみえる。",
            "Anh ấy trông có vẻ mệt.",
            [
              ["彼", "かれ"],
              ["は"],
              ["疲", "つか"],
              ["れているとみえる。"],
            ],
          ),
          ex(
            "雨が降るとみえて傘を持っている。",
            "あめがふるとみえてかさをもっている。",
            "Có vẻ sắp mưa nên đang cầm ô.",
            [
              ["雨", "あめ"],
              ["が"],
              ["降", "ふ"],
              ["るとみえて"],
              ["傘", "かさ"],
              ["を"],
              ["持", "も"],
              ["っている。"],
            ],
          ),
          ex(
            "会議は長引いたとみえる。",
            "かいぎはながびいたとみえる。",
            "Cuộc họp hình như đã kéo dài.",
            [
              ["会議", "かいぎ"],
              ["は"],
              ["長", "なが"],
              ["引", "び"],
              ["いたとみえる。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜とみえる",
        "Câu とみえる／と見えて: suy đoán từ dấu hiệu — có vẻ như….",
        [
          ["Cô ấy có vẻ đang vội.", "彼女は急いでいるとみえる。"],
          ["Có vẻ lạnh nên mặc áo dày.", "寒いとみえて厚着をしている。"],
          ["Anh ấy hình như vừa khóc.", "彼は泣いていたとみえる。"],
          ["Có vẻ bận nên không trả lời.", "忙しいとみえて返事がない。"],
          ["Cửa hàng hình như đã đóng.", "店は閉店したとみえる。"],
          ["Có vẻ đói nên ăn nhanh.", "空腹だとみえて急いで食べている。"],
          ["Họ hình như đã hòa giải.", "二人は仲直りしたとみえる。"],
          ["Có vẻ sốt nên da đỏ.", "熱があるとみえて顔が赤い。"],
          ["Máy hình như bị hỏng.", "機械は故障したとみえる。"],
          ["Có vẻ mưa to nên đường ướt.", "大雨だったとみえて道が濡れている。"],
        ],
        [
          ["彼は失望しているとみえる。", "Anh ấy trông có vẻ thất vọng."],
          ["風邪だとみえて咳をしている。", "Có vẻ cảm nên đang ho."],
          ["試験は難しかったとみえる。", "Kỳ thi hình như đã khó."],
          ["怒っているとみえて黙り込んだ。", "Có vẻ giận nên im thin thít."],
          ["旅先から戻ったとみえる。", "Hình như vừa về từ chuyến đi."],
          ["足りないとみえて補充を頼んだ。", "Có vẻ thiếu nên nhờ bổ sung."],
          ["成功したとみえて喜んでいる。", "Hình như thành công nên đang vui."],
          ["迷っているとみえて立ち止まった。", "Có vẻ do dự nên dừng bước."],
          ["約束を忘れたとみえる。", "Hình như đã quên lời hứa."],
          ["疲弊したとみえて休んでいる。", "Có vẻ kiệt sức nên đang nghỉ."],
        ],
        [
          ["Cô ấy đang vội vàng.", ["彼女は急いでいると", "みえる様子", "だ", "。"], 0],
          ["Lạnh nên mặc áo dày.", ["寒いとみえて", "コートを", "着込んでいる", "。"], 0],
          ["Anh ấy vừa khóc xong.", ["彼は泣いていたと", "みえる痕が", "ある", "。"], 0],
          ["Bận nên không trả lời.", ["忙しいとみえて", "連絡が", "途絶えた", "。"], 0],
          ["Cửa hàng đã đóng cửa.", ["店は閉店したと", "みえる看板が", "出ている", "。"], 0],
          ["Đói nên ăn rất nhanh.", ["空腹だとみえて", "一気に", "平らげた", "。"], 0],
          ["Hai người đã hòa giải.", ["二人は仲直りしたと", "みえる笑顔を", "見せた", "。"], 0],
          ["Sốt nên mặt đỏ bừng.", ["熱があるとみえて", "頬が", "赤くなっている", "。"], 0],
          ["Máy móc đã bị hỏng.", ["機械は故障したと", "みえる音が", "する", "。"], 0],
          ["Mưa to nên đường ướt.", ["大雨だったとみえて", "路面が", "濡れている", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l22-g02",
      {
        meaning: "Có thể (xảy ra điều xấu)… / e rằng sẽ…",
        structures: ["Vます ＋ かねない"],
        explanation:
          "かねない cảnh báo khả năng điều không mong muốn xảy ra: rất có thể A (xấu).",
        usage: "Cảnh báo rủi ro: quên; gây hiểu nhầm; dẫn đến tai nạn…",
        cautions: [
          "Chỉ dùng cho khả năng tiêu cực; không dùng cho kết quả tốt.",
          "Đối lập かねる (khó/không thể làm — lịch sự).",
        ],
        contrast:
          "かねない ≈ e rằng sẽ (xấu)…. Khác かもしれない (trung tính) và đối lập かねる.",
        examples: [
          ex(
            "このままでは失敗しかねない。",
            "このままではしっぱいしかねない。",
            "Cứ thế này e rằng sẽ thất bại.",
            [
              ["このままでは"],
              ["失敗", "しっぱい"],
              ["しかねない。"],
            ],
          ),
          ex(
            "誤解を招きかねない表現だ。",
            "ごかいをまねきかねないひょうげんだ。",
            "Cách nói có thể gây hiểu nhầm.",
            [
              ["誤解", "ごかい"],
              ["を"],
              ["招", "まね"],
              ["きかねない"],
              ["表現", "ひょうげん"],
              ["だ。"],
            ],
          ),
          ex(
            "彼は秘密を漏らしかねない。",
            "かれはひみつをもらしかねない。",
            "Anh ấy có thể lộ bí mật.",
            [
              ["彼", "かれ"],
              ["は"],
              ["秘密", "ひみつ"],
              ["を"],
              ["漏", "も"],
              ["らしかねない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜かねない",
        "Câu Vます＋かねない: có nguy cơ / e rằng sẽ (điều xấu).",
        [
          ["E rằng sẽ đến muộn.", "遅刻しかねない。"],
          ["Có thể gây thương tích.", "けがをさせかねない。"],
          ["E rằng quên mang theo.", "忘れかねないので確認する。"],
          ["Có thể dẫn đến tranh cãi.", "論争を招きかねない。"],
          ["E rằng mất khách hàng.", "顧客を失いかねない。"],
          ["Có thể phá vỡ quan hệ.", "関係を壊しかねない発言だ。"],
          ["E rằng cháy nếu bất cẩn.", "不注意だと火事になりかねない。"],
          ["Có thể bị phạt nặng.", "高額の罰金を科されかねない。"],
          ["E rằng kế hoạch đổ bể.", "計画が頓挫しかねない。"],
          ["Có thể làm mất uy tín.", "信用を失いかねない行為だ。"],
        ],
        [
          ["事故を起こしかねない運転だ。", "Cách lái có thể gây tai nạn."],
          ["約束を破りかねない態度だ。", "Thái độ e rằng sẽ thất hứa."],
          ["情報漏洩を招きかねない。", "Có thể dẫn đến lộ thông tin."],
          ["体調を崩しかねない働き方だ。", "Cách làm việc e rằng hại sức khỏe."],
          ["対立が深刻化しかねない。", "Đối lập có thể trở nên nghiêm trọng."],
          ["誤解されかねない言い方だ。", "Cách nói dễ bị hiểu nhầm."],
          ["予算オーバーになりかねない。", "E rằng vượt ngân sách."],
          ["信頼を損ないかねない。", "Có thể làm tổn hại lòng tin."],
          ["遅刻の常習になりかねない。", "E rằng thành thói quen muộn giờ."],
          ["大きな損失を招きかねない。", "Có thể gây tổn thất lớn."],
        ],
        [
          ["E sẽ đến giờ muộn.", ["このペースでは", "遅刻しかねないと", "思う", "。"], 0],
          ["Chơi bất cẩn dễ gây thương.", ["不用意だと", "けがをさせかねない", "遊びだ", "。"], 0],
          ["E quên mang theo đồ.", ["大事な書類を", "忘れかねないので", "確認する", "。"], 0],
          ["Có thể gây tranh cãi.", ["その提案は", "論争を招きかねないと", "危惧する", "。"], 0],
          ["E mất khách hàng.", ["対応を誤ると", "顧客を失いかねない", "状況だ", "。"], 0],
          ["Có thể phá quan hệ.", ["不用意な一言が", "関係を壊しかねない", "発言だ", "。"], 0],
          ["Bất cẩn dễ cháy.", ["火の取り扱いを誤ると", "火事になりかねない", "危険が", "ある。"], 0],
          ["Vi phạm dễ bị phạt nặng.", ["規則違反だと", "罰金を科されかねない", "行為だ", "。"], 0],
          ["E kế hoạch đổ vỡ.", ["資金不足で", "計画が頓挫しかねない", "恐れが", "ある。"], 0],
          ["Có thể mất uy tín.", ["その行為は", "信用を失いかねない", "結果を", "招く。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l22-g03",
      {
        meaning: "Có nguy cơ… / e rằng sẽ… (lo ngại)",
        structures: [
          "Nの ＋ おそれがある",
          "Vる ＋ おそれがある",
        ],
        explanation:
          "おそれがある nêu lo ngại khả năng xấu xảy ra — thường văn viết, tin tức, cảnh báo chính thức.",
        usage: "Cảnh báo thiên tai, sức khỏe, an ninh, rủi ro pháp lý…",
        cautions: [
          "Thường dùng kanji 恐れがある trong văn bản trang trọng.",
          "Khác かねない (khẩu ngữ/đánh giá cá nhân hơn); おそれがある khách quan hơn.",
        ],
        contrast:
          "おそれがある ≈ có nguy cơ…. Gần かねない nhưng thiên văn phong tin tức/chính thức.",
        examples: [
          ex(
            "大雨による洪水のおそれがある。",
            "おおあめによるこうずいのおそれがある。",
            "Có nguy cơ lũ do mưa lớn.",
            [
              ["大雨", "おおあめ"],
              ["による"],
              ["洪水", "こうずい"],
              ["のおそれがある。"],
            ],
          ),
          ex(
            "感染が拡大するおそれがある。",
            "かんせんがかくだいするおそれがある。",
            "Có nguy cơ lây nhiễm lan rộng.",
            [
              ["感染", "かんせん"],
              ["が"],
              ["拡大", "かくだい"],
              ["するおそれがある。"],
            ],
          ),
          ex(
            "データ消失のおそれがある。",
            "データしょうしつのおそれがある。",
            "Có nguy cơ mất dữ liệu.",
            [
              ["データ"],
              ["消失", "しょうしつ"],
              ["のおそれがある。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜おそれがある",
        "Câu おそれがある: có nguy cơ / e rằng (điều xấu) sẽ xảy ra.",
        [
          ["Có nguy cơ động đất xảy ra.", "地震が発生するおそれがある。"],
          ["E rằng giá sẽ tăng mạnh.", "価格が高騰するおそれがある。"],
          ["Có nguy cơ tắc đường dài.", "長時間の渋滞のおそれがある。"],
          ["E rằng thuốc có tác dụng phụ.", "副作用が出るおそれがある。"],
          ["Có nguy cơ hệ thống sập.", "システムが停止するおそれがある。"],
          ["E rằng chất lượng giảm.", "品質が低下するおそれがある。"],
          ["Có nguy cơ cháy rừng.", "山火事のおそれがある。"],
          ["E rằng bị lộ thông tin cá nhân.", "個人情報が漏れるおそれがある。"],
          ["Có nguy cơ thiếu nhân lực.", "人手不足のおそれがある。"],
          ["E rằng hợp đồng bị hủy.", "契約が破棄されるおそれがある。"],
        ],
        [
          ["台風が接近するおそれがある。", "Có nguy cơ bão tiến gần."],
          ["健康を害するおそれがある。", "E rằng hại sức khỏe."],
          ["誤作動のおそれがある。", "Có nguy cơ hoạt động sai."],
          ["環境が汚染されるおそれがある。", "E rằng môi trường bị ô nhiễm."],
          ["倒産のおそれがある企業だ。", "Doanh nghiệp có nguy cơ phá sản."],
          ["二次被害が発生するおそれがある。", "Có nguy cơ thiệt hại thứ cấp."],
          ["供給が滞るおそれがある。", "E rằng nguồn cung bị trì trệ."],
          ["法的な争いのおそれがある。", "Có nguy cơ tranh chấp pháp lý."],
          ["記録が改ざんされるおそれがある。", "E rằng hồ sơ bị chỉnh sửa sai."],
          ["交通麻痺のおそれがある。", "Có nguy cơ giao thông tê liệt."],
        ],
        [
          ["Có nguy cơ động đất.", ["地震が発生する", "おそれがあると", "発表された", "。"], 0],
          ["E giá sẽ tăng mạnh.", ["価格が高騰する", "おそれがあるため", "注意する", "。"], 0],
          ["Có nguy cơ tắc đường.", ["長時間の渋滞の", "おそれがある区間", "だ", "。"], 0],
          ["E thuốc có tác dụng phụ.", ["副作用が出る", "おそれがある薬", "だ", "。"], 0],
          ["Hệ thống có thể dừng đột ngột.", ["システムが停止する", "おそれがあるので", "点検する", "。"], 0],
          ["E chất lượng giảm sút.", ["品質が低下する", "おそれがある製品", "だ", "。"], 0],
          ["Cảnh báo nguy cơ cháy rừng.", ["山火事の", "おそれがあると", "警告された", "。"], 0],
          ["E lộ thông tin cá nhân.", ["個人情報が漏れる", "おそれがあるため", "対策を", "取る。"], 0],
          ["Có nguy cơ thiếu người.", ["人手不足の", "おそれがある部署", "だ", "。"], 0],
          ["E hợp đồng bị hủy.", ["契約が破棄される", "おそれがある案件", "だ", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l22-g04",
      {
        meaning: "Sẽ không… / quyết không…; chẳng phải là… hay sao?",
        structures: [
          "Vる／Vまい形 ＋ まい",
          "普通形 ＋ ではあるまいか",
        ],
        explanation:
          "まい: phủ định ý chí/suy đoán (sẽ không / quyết không). ではあるまいか: nghi vấn nhẹ khẳng định — chẳng phải A hay sao?",
        usage: "Quyết tâm không làm; suy đoán phủ định; khẳng định gián tiếp lịch sự.",
        cautions: [
          "Động từ nhóm I: 書く→書くまい; nhóm II: 食べる→食べまい; する→するまい／すまい; 来る→こまい.",
          "ではあるまいか gần nghĩa ではないだろうか.",
        ],
        contrast:
          "まい ≈ sẽ/quyết không…. ではあるまいか ≈ chẳng phải… sao? Khác ないだろう trung tính hơn.",
        examples: [
          ex(
            "二度と行くまいと決意した。",
            "にどといくまいとけついした。",
            "Quyết không bao giờ đi nữa.",
            [
              ["二度", "にど"],
              ["と"],
              ["行", "い"],
              ["くまいと"],
              ["決意", "けつい"],
              ["した。"],
            ],
          ),
          ex(
            "彼は真実を知るまい。",
            "かれはしんじつをしるまい。",
            "Anh ấy sẽ chẳng biết sự thật.",
            [
              ["彼", "かれ"],
              ["は"],
              ["真実", "しんじつ"],
              ["を"],
              ["知", "し"],
              ["るまい。"],
            ],
          ),
          ex(
            "これは詐欺ではあるまいか。",
            "これはさぎではあるまいか。",
            "Chẳng phải đây là lừa đảo hay sao?",
            [
              ["これは"],
              ["詐欺", "さぎ"],
              ["ではあるまいか。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜まい／ではあるまいか",
        "Câu まい: quyết/sẽ không…. ではあるまいか: chẳng phải… sao?",
        [
          ["Quyết không nói với ai.", "誰にも言うまい。"],
          ["Chẳng phải anh ấy đang lo sao?", "彼は心配しているのではあるまいか。"],
          ["Sẽ không bao giờ quên.", "決して忘れまい。"],
          ["Chẳng phải giá quá cao sao?", "値段が高すぎるのではあるまいか。"],
          ["Quyết không phụ lòng tin.", "信頼を裏切るまい。"],
          ["Chẳng phải đây là cơ hội sao?", "これは好機ではあるまいか。"],
          ["Sẽ không lặp lại lỗi đó.", "同じ過ちを繰り返すまい。"],
          ["Chẳng phải kế hoạch rủi ro sao?", "計画は危険ではあるまいか。"],
          ["Quyết không bỏ cuộc giữa chừng.", "途中で諦めるまい。"],
          ["Chẳng phải kết quả sai sao?", "結果が誤っているのではあるまいか。"],
        ],
        [
          ["二度と頼むまい。", "Quyết không nhờ nữa."],
          ["彼は気づくまい。", "Anh ấy sẽ chẳng nhận ra."],
          ["これは過労ではあるまいか。", "Chẳng phải đây là kiệt sức vì làm việc sao?"],
          ["秘密を漏らすまいと誓った。", "Thề sẽ không lộ bí mật."],
          ["状況は深刻ではあるまいか。", "Chẳng phải tình hình nghiêm trọng sao?"],
          ["二度と嘘はつくまい。", "Quyết không nói dối nữa."],
          ["彼には分かるまい。", "Anh ấy sẽ chẳng hiểu nổi."],
          ["これは警告ではあるまいか。", "Chẳng phải đây là cảnh báo sao?"],
          ["後悔するようなことはするまい。", "Sẽ không làm điều dễ hối hận."],
          ["提案は時期尚早ではあるまいか。", "Chẳng phải đề xuất còn quá sớm sao?"],
        ],
        [
          ["Quyết không kể với ai.", ["誰にも", "言うまいと", "心に決めた", "。"], 0],
          ["Anh ấy đang lo lắng chăng?", ["彼は心配しているのでは", "あるまいかと", "思う", "。"], 0],
          ["Sẽ không quên được.", ["この教訓は", "決して忘れまいと", "誓う", "。"], 0],
          ["Giá chẳng quá cao sao?", ["値段が高すぎるのでは", "あるまいかと", "疑う", "。"], 0],
          ["Quyết không phụ niềm tin.", ["周囲の信頼を", "裏切るまいと", "努める", "。"], 0],
          ["Đây chẳng phải cơ hội sao?", ["今こそ好機では", "あるまいかと", "判断する", "。"], 0],
          ["Không lặp lại lỗi cũ.", ["同じ過ちを", "繰り返すまいと", "反省した", "。"], 0],
          ["Kế hoạch rủi ro chăng?", ["その計画は危険では", "あるまいかと", "危惧する", "。"], 0],
          ["Quyết không bỏ cuộc.", ["どんな困難でも", "諦めるまいと", "踏ん張る", "。"], 0],
          ["Kết quả sai chăng?", ["計算結果が誤っているのでは", "あるまいかと", "確認する", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l22-g05",
      {
        meaning: "Chắc chắn là… / không sai nữa là…",
        structures: [
          "普通形 ＋ に違いない",
          "普通形 ＋ に相違ない",
        ],
        explanation:
          "に違いない／に相違ない khẳng định mạnh suy đoán: chắc chắn A, không còn nghi ngờ.",
        usage: "Kết luận từ bằng chứng: chắc là thủ phạm; chắc đã đến nơi…",
        cautions: [
          "に相違ない trang trọng/văn viết hơn に違いない.",
          "Là suy đoán chắc chắn, không phải sự thật đã xác nhận 100%.",
        ],
        contrast:
          "に違いない ≈ chắc chắn…. Gần はずだ nhưng nhấn niềm tin mạnh của người nói hơn.",
        examples: [
          ex(
            "彼が犯人に違いない。",
            "かれがはんにんにちがいない。",
            "Chắc chắn anh ấy là thủ phạm.",
            [
              ["彼", "かれ"],
              ["が"],
              ["犯人", "はんにん"],
              ["に"],
              ["違", "ちが"],
              ["いない。"],
            ],
          ),
          ex(
            "これは本物に相違ない。",
            "これはほんものにそういない。",
            "Đây chắc chắn là đồ thật.",
            [
              ["これは"],
              ["本物", "ほんもの"],
              ["に"],
              ["相違", "そうい"],
              ["ない。"],
            ],
          ),
          ex(
            "彼女はもう着いているに違いない。",
            "かのじょはもうついているにちがいない。",
            "Cô ấy chắc đã đến nơi rồi.",
            [
              ["彼女", "かのじょ"],
              ["は"],
              ["もう"],
              ["着", "つ"],
              ["いているに"],
              ["違", "ちが"],
              ["いない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜に違いない／に相違ない",
        "Câu に違いない／に相違ない: chắc chắn là… (suy đoán mạnh).",
        [
          ["Chắc chắn anh ấy nói dối.", "彼は嘘をついているに違いない。"],
          ["Đây chắc chắn là lỗi hệ thống.", "これはシステム障害に相違ない。"],
          ["Cô ấy chắc đang giận.", "彼女は怒っているに違いない。"],
          ["Chắc chắn mưa sẽ đến.", "まもなく雨になるに違いない。"],
          ["Đây chắc là chữ ký giả.", "これは偽造の署名に相違ない。"],
          ["Anh ấy chắc đã quên hẹn.", "彼は約束を忘れたに違いない。"],
          ["Chắc chắn còn chỗ trống.", "空席が残っているに違いない。"],
          ["Đây chắc chắn là tin đồn.", "これは噂に相違ない。"],
          ["Cậu bé chắc đang đói.", "子供は空腹に違いない。"],
          ["Chắc chắn có lý do sâu xa.", "裏に事情があるに相違ない。"],
        ],
        [
          ["犯人は内部の者に違いない。", "Thủ phạm chắc chắn là người trong cuộc."],
          ["この判断は誤りに相違ない。", "Phán đoán này chắc chắn sai."],
          ["彼はすでに帰宅したに違いない。", "Anh ấy chắc đã về nhà rồi."],
          ["原因は配線に相違ない。", "Nguyên nhân chắc chắn là dây điện."],
          ["彼女は合格するに違いない。", "Cô ấy chắc chắn sẽ đỗ."],
          ["これは誤報に相違ない。", "Đây chắc chắn là tin sai."],
          ["彼の話は事実に違いない。", "Lời anh ấy chắc chắn là sự thật."],
          ["結果は明白に相違ない。", "Kết quả chắc chắn đã rõ ràng."],
          ["荷物は届いているに違いない。", "Hành lý chắc đã tới rồi."],
          ["意図は明らかであるに相違ない。", "Ý đồ chắc chắn đã rõ."],
        ],
        [
          ["Anh ấy đang nói dối chắc.", ["彼は嘘をついているに", "違いないと", "思う", "。"], 0],
          ["Đây là lỗi hệ thống chắc.", ["これはシステム障害に", "相違ないと", "判断する", "。"], 0],
          ["Cô ấy đang giận chắc.", ["彼女は怒っているに", "違いない様子", "だ", "。"], 0],
          ["Sắp mưa chắc chắn rồi.", ["まもなく雨になるに", "違いない空模様", "だ", "。"], 0],
          ["Chữ ký giả chắc chắn.", ["これは偽造の署名に", "相違ないと", "見られる", "。"], 0],
          ["Anh quên hẹn chắc rồi.", ["彼は約束を忘れたに", "違いないと", "気づいた", "。"], 0],
          ["Còn chỗ trống chắc chắn.", ["空席が残っているに", "違いない会場", "だ", "。"], 0],
          ["Đây là tin đồn chắc.", ["これは単なる噂に", "相違ないと", "思う", "。"], 0],
          ["Đứa trẻ đang đói chắc.", ["子供は空腹に", "違いない様子で", "泣いている", "。"], 0],
          ["Có lý do sâu xa chắc.", ["裏に事情があるに", "相違ないと", "推測する", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l22-g06",
      {
        meaning: "Chắc chắn / nhất định là… (đương nhiên)",
        structures: [
          "普通形 ＋ にきまっている",
          "普通形 ＋ に決まっている",
        ],
        explanation:
          "にきまっている khẳng định đầy tự tin/đương nhiên: A thì chắc chắn/nhất định vậy rồi.",
        usage: "Nhận định chắc nịch, đôi khi hơi chủ quan/khẩu ngữ hơn に違いない.",
        cautions: [
          "に決まっている là cách viết kanji phổ biến của にきまっている.",
          "Thiên khẩu ngữ/cảm xúc; văn bản trang trọng ưu tiên に違いない／はずだ.",
        ],
        contrast:
          "にきまっている ≈ nhất định là…. Gần に違いない nhưng chủ quan/khẩu ngữ hơn.",
        examples: [
          ex(
            "勝つにきまっている。",
            "かつにきまっている。",
            "Nhất định sẽ thắng.",
            [
              ["勝", "か"],
              ["つにきまっている。"],
            ],
          ),
          ex(
            "彼の言うことは嘘に決まっている。",
            "かれのいうことはうそにきまっている。",
            "Lời anh ấy nhất định là nói dối.",
            [
              ["彼", "かれ"],
              ["の"],
              ["言", "い"],
              ["うことは"],
              ["嘘", "うそ"],
              ["に"],
              ["決", "き"],
              ["まっている。"],
            ],
          ),
          ex(
            "そんな計画は失敗にきまっている。",
            "そんなけいかくはしっぱいにきまっている。",
            "Kế hoạch kiểu đó nhất định thất bại.",
            [
              ["そんな"],
              ["計画", "けいかく"],
              ["は"],
              ["失敗", "しっぱい"],
              ["にきまっている。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜にきまっている",
        "Câu にきまっている／に決まっている: nhất định / chắc chắn là….",
        [
          ["Nhất định anh ấy sẽ đến muộn.", "彼は遅れるにきまっている。"],
          ["Giá đó nhất định đắt.", "その値段は高いに決まっている。"],
          ["Nhất định sẽ có hàng đợi.", "行列ができるにきまっている。"],
          ["Câu trả lời nhất định sai.", "その答えは間違っているに決まっている。"],
          ["Nhất định trời sẽ nắng.", "晴れるにきまっている。"],
          ["Anh ấy nhất định từ chối.", "彼は断るに決まっている。"],
          ["Nhất định hết vé sớm.", "すぐに売り切れるにきまっている。"],
          ["Tin đó nhất định giả.", "その話は嘘に決まっている。"],
          ["Nhất định cô ấy vui.", "彼女は喜ぶにきまっている。"],
          ["Kết quả nhất định rõ ràng.", "結果は明白に決まっている。"],
        ],
        [
          ["彼が優勝するにきまっている。", "Anh ấy nhất định đoạt chức vô địch."],
          ["この店は混むに決まっている。", "Quán này nhất định đông."],
          ["試験は難しいにきまっている。", "Kỳ thi nhất định khó."],
          ["言い訳は通用しないに決まっている。", "Lời bao biện nhất định không ăn thua."],
          ["値段が上がるにきまっている。", "Giá nhất định sẽ tăng."],
          ["彼の提案は通るに決まっている。", "Đề xuất của anh ấy nhất định được duyệt."],
          ["今夜は眠れないにきまっている。", "Đêm nay nhất định không ngủ được."],
          ["その映画は面白いに決まっている。", "Phim đó nhất định hay."],
          ["文句が出るにきまっている。", "Nhất định sẽ có phàn nàn."],
          ["彼は賛成するに決まっている。", "Anh ấy nhất định đồng ý."],
        ],
        [
          ["Anh ấy sẽ đến muộn chắc.", ["彼は遅れるに", "きまっていると", "思う", "。"], 0],
          ["Giá đó đắt là chắc.", ["その値段は高いに", "決まっていると", "誰もが", "思う。"], 0],
          ["Nhất định có hàng đợi.", ["行列ができるに", "きまっている時間帯", "だ", "。"], 0],
          ["Đáp án sai là chắc.", ["その答えは間違っているに", "決まっていると", "断言できる", "。"], 0],
          ["Trời nắng là chắc rồi.", ["今日は晴れるに", "きまっている空", "だ", "。"], 0],
          ["Anh ấy từ chối chắc.", ["彼は断るに", "決まっていると", "予想する", "。"], 0],
          ["Vé hết sớm là chắc.", ["チケットはすぐに売り切れるに", "きまっていると", "分かる", "。"], 0],
          ["Tin đó giả là chắc.", ["その話は嘘に", "決まっていると", "見破る", "。"], 0],
          ["Cô ấy vui là chắc.", ["彼女は喜ぶに", "きまっている反応", "だ", "。"], 0],
          ["Kết quả rõ là chắc.", ["結果は明白に", "決まっている案件", "だ", "。"], 0],
        ],
      ),
    ),
  ];
}
