import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L06-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 9, BATCH);

export function lesson09Patterns(byId) {
  return [
    P(
      byId,
      "l09-g01",
      {
        meaning: "Càng… càng… / theo đà… thì…",
        structures: ["Vる／N ＋ につれて", "Vる／N ＋ にしたがって／にしたがい"],
        explanation:
          "A thay đổi thì B cũng thay đổi theo tỷ lệ/đồng thời; にしたがって còn mang nghĩa 'theo (chỉ thị)'.",
        usage: "Mô tả xu hướng thay đổi theo thời gian hoặc mức độ.",
        cautions: [
          "Hai vế thường cùng chiều thay đổi.",
          "にしたがって có thêm nghĩa tuân theo lệnh/quy tắc.",
        ],
        contrast: "につれて／にしたがって ≈ càng… càng. Gần に伴って; khác に応じて (tùy theo).",
        examples: [
          ex(
            "山を上るにつれて景色が変わった。",
            "やまをのぼるにつれてけしきがかわった。",
            "Càng lên núi cảnh càng đổi.",
            [
              ["山", "やま"],
              ["を"],
              ["上", "のぼ"],
              ["る"],
              ["につれて"],
              ["景色", "けしき"],
              ["が"],
              ["変", "か"],
              ["わった。"],
            ],
          ),
          ex(
            "経済成長にしたがって生活が豊かになった。",
            "けいざいせいちょうにしたがってせいかつがゆたかになった。",
            "Theo đà tăng trưởng kinh tế, đời sống giàu hơn.",
            [
              ["経済", "けいざい"],
              ["成長", "せいちょう"],
              ["にしたがって"],
              ["生活", "せいかつ"],
              ["が"],
              ["豊", "ゆた"],
              ["かになった。"],
            ],
          ),
          ex(
            "指示にしたがって作業してください。",
            "しじにしたがってさぎょうしてください。",
            "Hãy làm việc theo chỉ thị.",
            [
              ["指示", "しじ"],
              ["にしたがって"],
              ["作業", "さぎょう"],
              ["してください。"],
            ],
          ),
        ],
      },
      packFrom(
        "V／N ＋ につれて／にしたがって",
        "Câu dùng につれて／にしたがって: càng A càng B, hoặc theo chỉ thị.",
        [
          ["Càng lớn tuổi sức khỏe càng yếu.", "年を取るにつれて体力が衰える。"],
          ["Càng về tối đường càng vắng.", "夜になるにつれて道が静かになる。"],
          ["Theo đà học, từ vựng tăng.", "勉強するにしたがって語彙が増える。"],
          ["Càng lên cao không khí càng lạnh.", "高くなるにつれて気温が下がる。"],
          ["Theo chỉ dẫn của hướng dẫn viên đi.", "案内にしたがって進んでください。"],
          ["Càng luyện tập kỹ năng càng lên.", "練習するにつれて上達する。"],
          ["Theo đà đô thị hóa dân số tăng.", "都市化にしたがって人口が増えた。"],
          ["Càng đọc sách hiểu biết càng rộng.", "本を読むにつれて知識が広がる。"],
          ["Theo quy tắc an toàn thao tác.", "ルールにしたがって操作する。"],
          ["Càng gần kỳ thi càng lo.", "試験が近づくにつれて不安になる。"],
        ],
        [
          ["季節が進むにつれて花が咲く。", "Theo mùa tiến triển hoa nở."],
          ["経験を積むにしたがって判断が速くなる。", "Càng tích lũy kinh nghiệm phán đoán càng nhanh."],
          ["時間がたつにつれて痛みが引いた。", "Càng để thời gian đau càng giảm."],
          ["マニュアルにしたがって組み立てる。", "Lắp ráp theo sổ tay."],
          ["収入が増えるにつれて支出も増える。", "Thu nhập tăng thì chi tiêu cũng tăng."],
          ["技術が進歩するにしたがって生活が便利になる。", "Công nghệ tiến bộ thì đời sống tiện hơn."],
          ["暗くなるにつれて街灯がつく。", "Trời tối dần thì đèn đường bật."],
          ["指示にしたがって避難した。", "Sơ tán theo chỉ thị."],
          ["慣れるにつれて緊張が解けた。", "Càng quen thì hết căng thẳng."],
          ["需要が高まるにしたがって価格が上がった。", "Nhu cầu tăng thì giá tăng."],
        ],
        [
          ["Càng lên núi cảnh càng đổi.", ["上る", "につれて", "景色が", "変わる。"], 1],
          ["Theo tăng trưởng đời sống giàu.", ["成長に", "したがって", "生活が", "豊かだ。"], 1],
          ["Làm theo chỉ thị.", ["指示に", "したがって", "作業を", "する。"], 1],
          ["Càng lớn sức khỏe yếu.", ["年を取る", "につれて", "体力が", "落ちる。"], 1],
          ["Càng tối đường càng vắng.", ["夜に", "なるにつれ", "道が", "静かだ。"], 1],
          ["Càng luyện càng tiến bộ.", ["練習する", "につれて", "上達が", "早い。"], 1],
          ["Theo quy tắc thao tác.", ["規則に", "したがって", "操作を", "行う。"], 1],
          ["Càng gần thi càng lo.", ["近づく", "につれて", "不安が", "増す。"], 1],
          ["Thu tăng chi cũng tăng.", ["増える", "につれて", "支出も", "増える。"], 1],
          ["Sơ tán theo chỉ thị.", ["指示に", "したがって", "避難を", "した。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l09-g02",
      {
        meaning: "Cùng với… / đồng thời với…",
        structures: [
          "N／Vる ＋ に伴って／に伴い／に伴う",
          "N／Vる ＋ とともに",
        ],
        explanation:
          "A xảy ra thì B đi kèm; とともに còn nghĩa 'cùng với người/việc'.",
        usage: "Tin tức, phân tích thay đổi xã hội; hợp tác cùng ai đó.",
        cautions: [
          "に伴う修飾 N (開発に伴う問題).",
          "とともに rộng nghĩa hơn (cùng làm với ai).",
        ],
        contrast: "に伴って／とともに ≈ cùng với. Gần につれて; とともに thêm 'cùng người'.",
        examples: [
          ex(
            "人口増加に伴って交通が混雑した。",
            "じんこうぞうかにともなってこうつうがこんざつした。",
            "Cùng với tăng dân số, giao thông tắc.",
            [
              ["人口", "じんこう"],
              ["増加", "ぞうか"],
              ["に"],
              ["伴", "ともな"],
              ["って"],
              ["交通", "こうつう"],
              ["が"],
              ["混雑", "こんざつ"],
              ["した。"],
            ],
          ),
          ex(
            "家族とともに田舎へ引っ越した。",
            "かぞくとともにいなかへひっこした。",
            "Chuyển về quê cùng gia đình.",
            [
              ["家族", "かぞく"],
              ["とともに"],
              ["田舎", "いなか"],
              ["へ"],
              ["引", "ひ"],
              ["っ越した。"],
            ],
          ),
          ex(
            "時代とともに価値観が変わる。",
            "じだいとともにかちかんがかわる。",
            "Cùng với thời đại, giá trị quan thay đổi.",
            [
              ["時代", "じだい"],
              ["とともに"],
              ["価値観", "かちかん"],
              ["が"],
              ["変", "か"],
              ["わる。"],
            ],
          ),
        ],
      },
      packFrom(
        "N／V ＋ に伴って／とともに",
        "Câu dùng に伴って／とともに: cùng với A thì B, hoặc cùng với ai đó.",
        [
          ["Cùng với phát triển kinh tế ô nhiễm tăng.", "経済発展に伴って公害が増えた。"],
          ["Cùng với tuổi già bệnh tăng.", "老化に伴って病気が増える。"],
          ["Tôi học cùng bạn.", "友人とともに勉強する。"],
          ["Cùng với mở cửa cửa hàng đông hơn.", "開店に伴って客が増えた。"],
          ["Cùng với cải cách quy tắc thay đổi.", "改革とともにルールが変わった。"],
          ["Cùng với đô thị hóa nông thôn trống.", "都市化に伴って過疎が進んだ。"],
          ["Làm việc cùng đồng nghiệp.", "同僚とともに働く。"],
          ["Cùng với tăng nhiệt độ tiêu thụ điện tăng.", "気温上昇に伴って電力消費が増える。"],
          ["Cùng với toàn cầu hóa cạnh tranh gay gắt.", "グローバル化とともに競争が激しくなった。"],
          ["Cùng với kết hôn chuyển nhà.", "結婚とともに住まいを変えた。"],
        ],
        [
          ["開発に伴う環境問題が指摘された。", "Vấn đề môi trường đi kèm phát triển bị chỉ ra."],
          ["地震に伴って津波の心配がある。", "Cùng với động đất có lo sóng thần."],
          ["先生とともに研究を発表した。", "Công bố nghiên cứu cùng thầy."],
          ["円安に伴って輸入コストが上がった。", "Cùng với yên yếu chi phí nhập tăng."],
          ["成長とともに責任も増える。", "Cùng với trưởng thành trách nhiệm cũng tăng."],
          ["閉店に伴い従業員を配置転換した。", "Cùng với đóng cửa đã điều chuyển nhân viên."],
          ["彼とともにプロジェクトを進める。", "Tiến hành dự án cùng anh ấy."],
          ["制度変更に伴って手続きが増えた。", "Cùng với đổi chế độ thủ tục tăng."],
          ["夜が更けるとともに寒くなった。", "Cùng với đêm khuya trời lạnh hơn."],
          ["留学とともに視野が広がった。", "Cùng với du học tầm nhìn mở rộng."],
        ],
        [
          ["Cùng tăng dân số giao thông tắc.", ["増加に", "伴って", "交通が", "混む。"], 1],
          ["Chuyển nhà cùng gia đình.", ["家族と", "ともに", "田舎へ", "移った。"], 1],
          ["Giá trị đổi cùng thời đại.", ["時代と", "ともに", "価値観が", "変わる。"], 1],
          ["Ô nhiễm tăng cùng phát triển.", ["発展に", "伴って", "公害が", "増えた。"], 1],
          ["Học cùng bạn.", ["友人と", "ともに", "勉強を", "する。"], 1],
          ["Khách tăng cùng mở cửa.", ["開店に", "伴って", "客が", "増えた。"], 1],
          ["Quy tắc đổi cùng cải cách.", ["改革と", "ともに", "規則が", "変わった。"], 1],
          ["Làm cùng đồng nghiệp.", ["同僚と", "ともに", "仕事を", "進める。"], 1],
          ["Chi phí tăng cùng yên yếu.", ["円安に", "伴って", "コストが", "上がった。"], 1],
          ["Tầm nhìn mở cùng du học.", ["留学と", "ともに", "視野が", "広がった。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l09-g03",
      {
        meaning: "Tùy thuộc vào… / do… quyết định",
        structures: ["N ＋ 次第だ", "N ＋ 次第で", "N ＋ 次第です"],
        explanation:
          "Kết quả phụ thuộc vào N; 次第で nêu 'tùy theo N thì…'. Đây là nghĩa 'depends on', khác 次第 'ngay khi' ở bài 3.",
        usage: "Nhấn yếu tố quyết định kết quả.",
        cautions: [
          "Không nhầm với Vます＋次第 (ngay khi) của Lesson 3.",
          "次第だ thường kết thúc câu: ～は君次第だ.",
        ],
        contrast: "次第だ ≈ tùy thuộc. Khác に応じて (đáp ứng tương ứng) và Lesson 3 次第.",
        examples: [
          ex(
            "成功するかどうかは努力次第だ。",
            "せいこうするかどうかはどりょくしだいだ。",
            "Thành công hay không là tùy ở nỗ lực.",
            [
              ["成功", "せいこう"],
              ["するかどうかは"],
              ["努力", "どりょく"],
              ["次第", "しだい"],
              ["だ。"],
            ],
          ),
          ex(
            "天気次第で予定を変える。",
            "てんきしだいでよていをかえる。",
            "Tùy thời tiết mà đổi lịch.",
            [
              ["天気", "てんき"],
              ["次第", "しだい"],
              ["で"],
              ["予定", "よてい"],
              ["を"],
              ["変", "か"],
              ["える。"],
            ],
          ),
          ex(
            "採用は面接の結果次第です。",
            "さいようはめんせつのけっかしだいです。",
            "Tuyển dụng tùy kết quả phỏng vấn.",
            [
              ["採用", "さいよう"],
              ["は"],
              ["面接", "めんせつ"],
              ["の"],
              ["結果", "けっか"],
              ["次第", "しだい"],
              ["です。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ 次第だ／次第で",
        "Câu dùng 次第だ／次第で: kết quả tùy thuộc vào N (không phải 'ngay khi').",
        [
          ["Đậu hay không tùy ở cách học của bạn.", "合格できるかは君の勉強次第だ。"],
          ["Tùy ngân sách mà chọn khách sạn.", "予算次第でホテルを選ぶ。"],
          ["Giá cả tùy cung cầu.", "価格は需給次第だ。"],
          ["Tùy tình hình mà hủy sự kiện.", "状況次第でイベントを中止する。"],
          ["Thăng tiến tùy thành tích.", "昇進は実績次第だ。"],
          ["Tùy sức khỏe mà tham gia marathon.", "体調次第でマラソンに出る。"],
          ["Chất lượng tùy nguyên liệu.", "品質は材料次第だ。"],
          ["Tùy số lượng mà giảm giá.", "数量次第で割引する。"],
          ["Kế hoạch tùy phê duyệt của giám đốc.", "計画は社長の承認次第だ。"],
          ["Tùy giao thông mà đến muộn.", "交通次第で遅れることもある。"],
        ],
        [
          ["勝敗は運次第だと言われる。", "Người ta nói thắng thua tùy vận may."],
          ["返事次第で次の予定を決める。", "Tùy câu trả lời mà quyết lịch tiếp."],
          ["味は火加減次第で変わる。", "Vị thay đổi tùy độ lửa."],
          ["契約は条件次第で結べる。", "Hợp đồng có thể ký tùy điều kiện."],
          ["売上は宣伝次第で伸びる。", "Doanh số tăng tùy quảng cáo."],
          ["安全性は管理次第だ。", "An toàn tùy ở quản lý."],
          ["行き先は気分次第で決める。", "Đích đến quyết tùy tâm trạng."],
          ["評価は提出物の完成度次第です。", "Đánh giá tùy độ hoàn thiện bài nộp."],
          ["参加は本人の意思次第だ。", "Tham gia tùy ý bản thân."],
          ["納期は工場の都合次第で延びる。", "Hạn giao có thể trễ tùy nhà máy."],
        ],
        [
          ["Thành công tùy nỗ lực.", ["努力", "次第だ", "と言って", "もいい。"], 1],
          ["Đổi lịch tùy thời tiết.", ["天気", "次第で", "予定を", "変える。"], 1],
          ["Tuyển dụng tùy phỏng vấn.", ["結果", "次第で", "採用が", "決まる。"], 1],
          ["Chọn khách sạn tùy ngân sách.", ["予算", "次第で", "宿を", "選ぶ。"], 1],
          ["Hủy sự kiện tùy tình hình.", ["状況", "次第で", "中止も", "ある。"], 1],
          ["Anh ấy nói thăng tiến là tùy thành tích.", ["実績", "次第だ", "と彼は", "言う。"], 1],
          ["Giảm giá tùy số lượng.", ["数量", "次第で", "割引が", "付く。"], 1],
          ["Vị đổi tùy độ lửa.", ["火加減", "次第で", "味が", "変わる。"], 1],
          ["Doanh số tùy quảng cáo.", ["宣伝", "次第で", "売上は", "伸びる。"], 1],
          ["Tham gia tùy ý muốn.", ["意思", "次第だ", "と説明を", "した。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l09-g04",
      {
        meaning: "Tùy theo / tương ứng với…",
        structures: ["N ＋ に応じて", "N ＋ に応じ"],
        explanation:
          "Thay đổi cách xử lý cho phù hợp với mức độ, nhu cầu, tình huống của A.",
        usage: "Phí tùy theo, hỗ trợ tương ứng với…",
        cautions: [
          "Nhấn 'đáp ứng tương ứng', không chỉ 'càng… càng'.",
          "に応じ thường dạng viết.",
        ],
        contrast: "に応じて ≈ tùy theo / tương ứng. Khác 次第だ (phụ thuộc) và につれて (tỷ lệ thay đổi).",
        examples: [
          ex(
            "能力に応じて仕事を割り当てる。",
            "のうりょくにおうじてしごとをわりあてる。",
            "Phân công việc tùy theo năng lực.",
            [
              ["能力", "のうりょく"],
              ["に"],
              ["応", "おう"],
              ["じて"],
              ["仕事", "しごと"],
              ["を"],
              ["割", "わ"],
              ["り当てる。"],
            ],
          ),
          ex(
            "予算に応じた計画を立てる。",
            "よさんにおうじたけいかくをたてる。",
            "Lập kế hoạch tương ứng với ngân sách.",
            [
              ["予算", "よさん"],
              ["に"],
              ["応", "おう"],
              ["じた"],
              ["計画", "けいかく"],
              ["を"],
              ["立", "た"],
              ["てる。"],
            ],
          ),
          ex(
            "必要に応じて資料を追加する。",
            "ひつようにおうじてしりょうをついかする。",
            "Bổ sung tài liệu tùy theo nhu cầu.",
            [
              ["必要", "ひつよう"],
              ["に"],
              ["応", "おう"],
              ["じて"],
              ["資料", "しりょう"],
              ["を"],
              ["追加", "ついか"],
              ["する。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ に応じて／に応じ",
        "Câu dùng に応じて: xử lý tương ứng / tùy theo mức độ hoặc nhu cầu.",
        [
          ["Tính phí tùy theo thời gian sử dụng.", "利用時間に応じて料金を計算する。"],
          ["Hỗ trợ tùy theo thu nhập.", "収入に応じて支援する。"],
          ["Chọn quà tùy theo tuổi.", "年齢に応じて贈り物を選ぶ。"],
          ["Điều chỉnh độ khó tùy theo trình độ.", "レベルに応じて難易度を調整する。"],
          ["Thưởng tùy theo đóng góp.", "貢献度に応じて報酬を出す。"],
          ["Thay đổi lịch tùy theo yêu cầu khách.", "客の要望に応じて日程を変える。"],
          ["Cấp thuốc tùy theo triệu chứng.", "症状に応じて薬を出す。"],
          ["Tăng nhân sự tùy theo khối lượng việc.", "業務量に応じて人員を増やす。"],
          ["Giảm giá tùy theo số lượng mua.", "購入数に応じて割引する。"],
          ["Thiết kế tùy theo mục đích sử dụng.", "用途に応じて設計を変える。"],
        ],
        [
          ["状況に応じて柔軟に対応する。", "Ứng xử linh hoạt tùy theo tình hình."],
          ["実力に応じたクラス分けをする。", "Xếp lớp tương ứng với thực lực."],
          ["需要に応じて生産量を調整する。", "Điều chỉnh sản lượng tùy theo nhu cầu."],
          ["季節に応じたメニューを出す。", "Đưa thực đơn theo mùa."],
          ["規模に応じて設備を整える。", "Chuẩn bị thiết bị tùy theo quy mô."],
          ["経験に応じて指導方法を変える。", "Đổi cách hướng dẫn tùy theo kinh nghiệm."],
          ["リスクに応じた保険に入る。", "Mua bảo hiểm tương ứng với rủi ro."],
          ["成績に応じて奨学金を支給する。", "Cấp học bổng tùy theo thành tích."],
          ["天候に応じて服装を選ぶ。", "Chọn trang phục tùy theo thời tiết."],
          ["目的に応じて道具を使い分ける。", "Dùng dụng cụ khác nhau tùy mục đích."],
        ],
        [
          ["Phân việc tùy năng lực.", ["能力に", "応じて", "仕事を", "分ける。"], 1],
          ["Kế hoạch tương ứng ngân sách.", ["予算に", "応じた", "計画を", "立てる。"], 1],
          ["Bổ sung tùy nhu cầu.", ["必要に", "応じて", "資料を", "追加する。"], 1],
          ["Tính phí tùy thời gian.", ["時間に", "応じて", "料金を", "決める。"], 1],
          ["Hỗ trợ tùy thu nhập.", ["収入に", "応じて", "支援を", "行う。"], 1],
          ["Điều chỉnh độ khó tùy trình độ.", ["レベルに", "応じて", "難易度を", "変える。"], 1],
          ["Thưởng tùy đóng góp.", ["貢献に", "応じて", "報酬を", "出す。"], 1],
          ["Thuốc tùy triệu chứng.", ["症状に", "応じて", "薬を", "処方する。"], 1],
          ["Ứng xử tùy tình hình.", ["状況に", "応じて", "対応を", "変える。"], 1],
          ["Xếp lớp theo thực lực.", ["実力に", "応じた", "クラスに", "分ける。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l09-g05",
      {
        meaning: "Mỗi khi… / hễ… là…",
        structures: ["Vる／N ＋ につけて", "Vる／N ＋ につけ"],
        explanation:
          "Mỗi lần gặp A thì cảm xúc/hành động B xuất hiện; thường gắn kỷ niệm, xúc cảm.",
        usage: "Nhớ người, xúc động mỗi khi nhìn/nghe…",
        cautions: [
          "Thường đi với cảm xúc (思い出す、残念に思う).",
          "～につけ～につけ liệt kê 'dù A hay B'.",
        ],
        contrast: "につけて ≈ mỗi khi. Khác たびに (trung lập hơn) và につれて (tỷ lệ thay đổi).",
        examples: [
          ex(
            "この写真を見るにつけ故郷を思い出す。",
            "このしゃしんをみるにつけこきょうをおもいだす。",
            "Mỗi khi nhìn ảnh này lại nhớ quê.",
            [
              ["この"],
              ["写真", "しゃしん"],
              ["を"],
              ["見", "み"],
              ["る"],
              ["につけ"],
              ["故郷", "こきょう"],
              ["を"],
              ["思", "おも"],
              ["い出す。"],
            ],
          ),
          ex(
            "彼の話を聞くにつけ感心する。",
            "かれのはなしをきくにつけかんしんする。",
            "Mỗi khi nghe chuyện anh ấy lại khâm phục.",
            [
              ["彼", "かれ"],
              ["の"],
              ["話", "はなし"],
              ["を"],
              ["聞", "き"],
              ["く"],
              ["につけ"],
              ["感心", "かんしん"],
              ["する。"],
            ],
          ),
          ex(
            "雨の日につけ体調が悪くなる。",
            "あめのひにつけたいちょうがわるくなる。",
            "Hễ ngày mưa là sức khỏe kém đi.",
            [
              ["雨", "あめ"],
              ["の"],
              ["日", "ひ"],
              ["につけ"],
              ["体調", "たいちょう"],
              ["が"],
              ["悪", "わる"],
              ["くなる。"],
            ],
          ),
        ],
      },
      packFrom(
        "V／N ＋ につけて／につけ",
        "Câu dùng につけて／につけ: mỗi khi A thì cảm xúc/phản ứng B.",
        [
          ["Mỗi khi nghe bài hát này lại nhớ bạn.", "この歌を聞くにつけ友人を思い出す。"],
          ["Mỗi khi đọc thư của mẹ lại thấy ấm áp.", "母の手紙を読むにつけ心が温まる。"],
          ["Hễ thất bại là anh ấy lại cố gắng.", "失敗するにつけ彼はまた努力する。"],
          ["Mỗi khi nhìn biển lại thấy bình yên.", "海を見るにつけ気持ちが落ち着く。"],
          ["Hễ nghe tin đó là lo.", "その知らせを聞くにつけ心配になる。"],
          ["Mỗi khi về quê lại nhớ tuổi thơ.", "故郷に帰るにつけ子供の頃を思い出す。"],
          ["Hễ gặp khó là cô ấy bình tĩnh ứng phó.", "困難につけ彼女は冷静に対応する。"],
          ["Mỗi khi ngửi mùi này lại nhớ nhà.", "この匂いにつけ家を思い出す。"],
          ["Hễ xem tin thời tiết là kiểm tra lịch ngoài trời.", "天気予報を見るにつけ外出予定を確認する。"],
          ["Mỗi khi cầm món quà lại cảm ơn.", "贈り物を手にするにつけ感謝の気持ちが湧く。"],
        ],
        [
          ["彼の笑顔を見るにつけ元気が出る。", "Mỗi khi thấy anh ấy cười lại thấy khỏe."],
          ["古い日記を読むにつけ当時を思い出す。", "Mỗi khi đọc nhật ký cũ lại nhớ thời ấy."],
          ["ニュースを見るにつけ世の中の厳しさを感じる。", "Mỗi khi xem tin tức lại thấy đời khắc nghiệt."],
          ["この道を通るにつけ事故のことを思い出す。", "Mỗi khi đi đường này lại nhớ vụ tai nạn."],
          ["成功するにつけ周囲の支えに気づく。", "Mỗi khi thành công lại nhận ra sự nâng đỡ quanh mình."],
          ["冬になるにつけ関節が痛む。", "Hễ vào đông là khớp đau."],
          ["彼の手紙を読むにつけ安心する。", "Mỗi khi đọc thư anh ấy lại yên tâm."],
          ["失敗につけ学びがあると感じる。", "Hễ thất bại là cảm thấy có điều để học."],
          ["この曲を口ずさむにつけ学生時代が蘇る。", "Mỗi khi ngân nga bài này lại sống lại thời sinh viên."],
          ["雨につけ気分が沈みがちだ。", "Hễ mưa là tâm trạng dễ trầm."],
        ],
        [
          ["Mỗi khi nhìn ảnh nhớ quê.", ["写真を", "見るにつけ", "故郷を", "思い出す。"], 1],
          ["Mỗi khi nghe chuyện khâm phục.", ["話を", "聞くにつけ", "感心が", "湧く。"], 1],
          ["Hễ ngày mưa sức khỏe kém.", ["雨の日に", "つけ", "体調が", "悪い。"], 1],
          ["Mỗi khi nghe bài nhớ bạn.", ["歌を", "聞くにつけ", "友人を", "思い出す。"], 1],
          ["Mỗi khi nhìn biển bình yên.", ["海を", "見るにつけ", "心が", "落ち着く。"], 1],
          ["Hễ nghe tin lại lo.", ["知らせを", "聞くにつけ", "心配に", "なる。"], 1],
          ["Mỗi khi về quê nhớ tuổi thơ.", ["帰るに", "つけ", "昔を", "思い出す。"], 1],
          ["Mỗi khi ngửi mùi nhớ nhà.", ["匂いに", "つけ", "家を", "思い出す。"], 1],
          ["Mỗi khi thấy cười thấy khỏe.", ["笑顔を", "見るにつけ", "元気が", "出る。"], 1],
          ["Hễ vào đông khớp đau.", ["冬に", "なるにつけ", "関節が", "痛む。"], 1],
        ],
      ),
    ),
  ];
}
