import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L21-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 24, BATCH);

export function lesson24Patterns(byId) {
  return [
    P(
      byId,
      "l24-g01",
      {
        meaning: "Hãy cùng… đi / sao không cùng… nhỉ (kêu gọi hành động chung)",
        structures: [
          "V意志形 ＋ ではないか／じゃないか",
          "V（よ）う ＋ ではないか",
        ],
        explanation:
          "（よ）うではないか／じゃないか kêu gọi cùng làm: đề xuất mạnh mang sắc ‘cùng nhau quyết tâm’ hơn 〜ましょう.",
        usage: "Hội họp, bài phát biểu, khuyến khích nhóm: hãy cùng cố gắng; cùng bắt đầu thôi.",
        cautions: [
          "ではないか trang trọng hơn; じゃないか khẩu ngữ.",
          "Khác 〜ようか (do dự/đề xuất nhẹ); ở đây nhấn kêu gọi tập thể.",
        ],
        contrast:
          "（よ）うではないか ≈ hãy cùng…. Khác ことだ (khuyên cá nhân) và べきだ (nghĩa vụ lẽ phải).",
        examples: [
          ex(
            "力を合わせて解決しようではないか。",
            "ちからをあわせてかいけつしようではないか。",
            "Hãy cùng chung sức giải quyết thôi.",
            [
              ["力", "ちから"],
              ["を"],
              ["合", "あ"],
              ["わせて"],
              ["解決", "かいけつ"],
              ["しようではないか。"],
            ],
          ),
          ex(
            "新しい企画に挑戦しようじゃないか。",
            "あたらしいきかくにちょうせんしようじゃないか。",
            "Hãy thử thách dự án mới thôi.",
            [
              ["新", "あたら"],
              ["しい"],
              ["企画", "きかく"],
              ["に"],
              ["挑戦", "ちょうせん"],
              ["しようじゃないか。"],
            ],
          ),
          ex(
            "今夜はゆっくり休もうではないか。",
            "こんやはゆっくりやすもうではないか。",
            "Đêm nay hãy nghỉ ngơi thoải mái thôi.",
            [
              ["今夜", "こんや"],
              ["はゆっくり"],
              ["休", "やす"],
              ["もうではないか。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜（よ）うではないか",
        "Câu kêu gọi chung: V（よ）う＋ではないか／じゃないか — hãy cùng…",
        [
          ["Hãy cùng ôn thi chăm chỉ thôi.", "一緒に試験勉強を頑張ろうではないか。"],
          ["Hãy bắt đầu họp thôi.", "会議を始めようじゃないか。"],
          ["Hãy cùng bảo vệ môi trường thôi.", "環境を守ろうではないか。"],
          ["Hãy thử lại lần nữa thôi.", "もう一度やり直そうじゃないか。"],
          ["Hãy cùng chia sẻ ý kiến thôi.", "意見を出し合おうではないか。"],
          ["Hãy đi bộ đến ga thôi.", "駅まで歩いて行こうじゃないか。"],
          ["Hãy cùng chào đón khách thôi.", "来客を迎えようではないか。"],
          ["Hãy tiết kiệm điện thôi.", "電気を節約しようじゃないか。"],
          ["Hãy cùng hoàn thành báo cáo thôi.", "報告書を仕上げようではないか。"],
          ["Hãy nghỉ giải lao một chút thôi.", "少し休憩しようじゃないか。"],
        ],
        [
          ["真相を明らかにしようではないか。", "Hãy cùng làm rõ sự thật thôi."],
          ["地域のためにボランティアしようじゃないか。", "Hãy tình nguyện vì địa phương thôi."],
          ["無駄な争いはやめようではないか。", "Hãy thôi tranh cãi vô ích thôi."],
          ["新しいルールを守ろうじゃないか。", "Hãy cùng tuân thủ quy tắc mới thôi."],
          ["今日中に結論を出そうではないか。", "Hãy đưa ra kết luận trong hôm nay thôi."],
          ["お互いを尊重しようじゃないか。", "Hãy tôn trọng lẫn nhau thôi."],
          ["計画を見直そうではないか。", "Hãy xem lại kế hoạch thôi."],
          ["笑顔で挨拶しようじゃないか。", "Hãy chào nhau bằng nụ cười thôi."],
          ["力を合わせて勝ち残ろうではないか。", "Hãy chung sức để ở lại vòng trong thôi."],
          ["まずは現状を把握しようじゃないか。", "Trước hết hãy nắm tình hình hiện tại thôi."],
        ],
        [
          ["Cùng chung sức giải quyết thôi.", ["力を合わせて", "解決しよう", "ではないか", "。"], 0],
          ["Thử thách dự án mới thôi.", ["新しい企画に", "挑戦しよう", "じゃないか", "。"], 0],
          ["Đêm nay nghỉ thoải mái thôi.", ["今夜はゆっくり", "休もう", "ではないか", "。"], 0],
          ["Cùng ôn thi chăm chỉ thôi.", ["一緒に試験勉強を", "頑張ろう", "ではないか", "。"], 0],
          ["Bắt đầu cuộc họp thôi.", ["会議を", "始めよう", "じゃないか", "。"], 0],
          ["Cùng bảo vệ môi trường thôi.", ["環境を", "守ろう", "ではないか", "。"], 0],
          ["Thử lại lần nữa thôi.", ["もう一度", "やり直そう", "じゃないか", "。"], 0],
          ["Làm rõ sự thật thôi.", ["真相を", "明らかにしよう", "ではないか", "。"], 0],
          ["Thôi tranh cãi vô ích.", ["無駄な争いは", "やめよう", "ではないか", "。"], 0],
          ["Nắm tình hình trước đã.", ["まずは現状を", "把握しよう", "じゃないか", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l24-g02",
      {
        meaning: "Nên… / điều cần làm là… (lời khuyên cụ thể)",
        structures: ["Vる ＋ ことだ", "Vない ＋ ことだ"],
        explanation:
          "ことだ đưa lời khuyên thực tế: điều nên làm (hoặc không nên làm) trong tình huống đó là A — mang sắc ‘cách hay nhất lúc này’.",
        usage: "Khuyên bạn bè/đồng nghiệp: muốn khỏe thì nên ngủ sớm; đừng lo thừa thì nên hỏi.",
        cautions: [
          "Khác ことだ định nghĩa (〜とは〜ことだ ở bài khác); ở đây là lời khuyên.",
          "Thường dùng với người ngang/dưới hoặc tự nhủ; với cấp trên có thể quá thẳng.",
        ],
        contrast:
          "ことだ ≈ nên/điều cần làm là…. Khác べきだ (lẽ phải) và ものだ (chuẩn mực xã hội).",
        examples: [
          ex(
            "風邪のときは暖かくして寝ることだ。",
            "かぜのときはあたたかくしてねることだ。",
            "Khi cảm thì nên đắp ấm mà ngủ.",
            [
              ["風邪", "かぜ"],
              ["のときは"],
              ["暖", "あたた"],
              ["かくして"],
              ["寝", "ね"],
              ["ることだ。"],
            ],
          ),
          ex(
            "分からないことはすぐ質問することだ。",
            "わからないことはすぐしつもんすることだ。",
            "Điều không hiểu thì nên hỏi ngay.",
            [
              ["分", "わ"],
              ["からないことはすぐ"],
              ["質問", "しつもん"],
              ["することだ。"],
            ],
          ),
          ex(
            "焦らずに一歩ずつ進むことだ。",
            "あせらずにいっぽずつすすむことだ。",
            "Đừng vội — nên tiến từng bước một.",
            [
              ["焦", "あせ"],
              ["らずに"],
              ["一歩", "いっぽ"],
              ["ずつ"],
              ["進", "すす"],
              ["むことだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ことだ",
        "Câu khuyên thực tế: Vる／Vない＋ことだ — nên / đừng…",
        [
          ["Muốn giỏi thì nên luyện mỗi ngày.", "上達したければ毎日練習することだ。"],
          ["Mệt thì nên nghỉ sớm hôm nay.", "疲れたら今日は早く休むことだ。"],
          ["Trước họp nên đọc tài liệu.", "会議の前に資料を読むことだ。"],
          ["Đừng đoán mò — nên kiểm tra số liệu.", "勘に頼らずデータを確認することだ。"],
          ["Muốn giảm cân thì nên đi bộ.", "痩せたければ歩くことだ。"],
          ["Khi căng thẳng nên hít thở sâu.", "緊張したら深呼吸することだ。"],
          ["Đừng trì hoãn — nên làm ngay việc quan trọng.", "先延ばしせず重要任務から着手することだ。"],
          ["Muốn được tin thì nên giữ lời hứa.", "信頼されたければ約束を守ることだ。"],
          ["Khi lạc đường nên hỏi người địa phương.", "道に迷ったら地元の人に尋ねることだ。"],
          ["Đừng so sánh — nên tập trung vào mình.", "他人と比べず自分の課題に集中することだ。"],
        ],
        [
          ["体調管理を怠らないことだ。", "Đừng sao nhãng việc quản lý sức khỏe."],
          ["困ったときは一人で抱え込まないことだ。", "Khi khó đừng ôm một mình."],
          ["発言の前に要点を整理することだ。", "Trước khi phát biểu nên sắp xếp ý chính."],
          ["ミスしたらすぐに謝ることだ。", "Lỡ sai thì nên xin lỗi ngay."],
          ["節約したければ無駄遣いをやめることだ。", "Muốn tiết kiệm thì nên thôi tiêu xài lãng phí."],
          ["良い人間関係を築きたければ挨拶を欠かさないことだ。", "Muốn quan hệ tốt thì đừng bỏ chào hỏi."],
          ["安全のためにはヘルメットを着用することだ。", "Vì an toàn nên đội mũ bảo hiểm."],
          ["成果を出すには優先順位をつけることだ。", "Muốn ra kết quả thì nên đặt thứ tự ưu tiên."],
          ["眠れないときはカフェインを控えることだ。", "Khó ngủ thì nên hạn chế caffeine."],
          ["誤解を避けるにはメールで確認することだ。", "Muốn tránh hiểu nhầm thì nên xác nhận bằng mail."],
        ],
        [
          ["Cảm thì nên đắp ấm ngủ.", ["風邪のときは暖かくして", "寝る", "こと", "だ。"], 0],
          ["Không hiểu thì hỏi ngay.", ["分からないことはすぐ", "質問する", "こと", "だ。"], 0],
          ["Đừng vội, tiến từng bước.", ["焦らずに一歩ずつ", "進む", "こと", "だ。"], 0],
          ["Muốn giỏi luyện mỗi ngày.", ["上達したければ毎日", "練習する", "こと", "だ。"], 0],
          ["Mệt thì nghỉ sớm hôm nay.", ["疲れたら今日は早く", "休む", "こと", "だ。"], 0],
          ["Trước họp đọc tài liệu.", ["会議の前に資料を", "読む", "こと", "だ。"], 0],
          ["Căng thẳng thì hít sâu.", ["緊張したら", "深呼吸する", "こと", "だ。"], 0],
          ["Lỡ sai thì xin lỗi ngay.", ["ミスしたらすぐに", "謝る", "こと", "だ。"], 0],
          ["An toàn thì đội mũ.", ["安全のためにはヘルメットを", "着用する", "こと", "だ。"], 0],
          ["Khó ngủ hạn chế caffeine.", ["眠れないときはカフェインを", "控える", "こと", "だ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l24-g03",
      {
        meaning: "Nên… / không nên… (theo lẽ thường, đạo lý xã hội)",
        structures: [
          "Vる ＋ ものだ",
          "Vない ＋ ものだ",
          "Vる ＋ ものではない／もんじゃない",
        ],
        explanation:
          "ものだ／ものではない khuyên theo chuẩn mực xã hội hoặc lẽ thường: người ta vốn nên A; không nên làm B. Khác ものだ cảm thán/bản chất ở bài 23.",
        usage: "Dạy bảo, nhắc nhở phép tắc: trẻ em nên chào; không nên cười nhạo người khác.",
        cautions: [
          "ものではない／もんじゃない phủ định mạnh ‘không nên’ theo đạo lý.",
          "Giọng có thể giáo huấn; cẩn thận đối tượng nghe.",
        ],
        contrast:
          "ものだ（khuyên）≈ nên theo lẽ thường. Khác ものだ bài 23 (cảm thán) và ことだ (khuyên tình huống cụ thể).",
        examples: [
          ex(
            "目上の人には丁寧に話すものだ。",
            "めうえのひとにはていねいにはなすものだ。",
            "Với người trên thì nên nói lịch sự.",
            [
              ["目上", "めうえ"],
              ["の"],
              ["人", "ひと"],
              ["には"],
              ["丁寧", "ていねい"],
              ["に"],
              ["話", "はな"],
              ["すものだ。"],
            ],
          ),
          ex(
            "他人の失敗を笑うつもりはないものだ。",
            "たにんのしっぱいをわらいつもりはないものだ。",
            "Lẽ ra không nên có ý cười thất bại người khác.",
            [
              ["他人", "たにん"],
              ["の"],
              ["失敗", "しっぱい"],
              ["を"],
              ["笑", "わら"],
              ["うつもりはないものだ。"],
            ],
          ),
          ex(
            "借りたものは返すべきで、無断で使うものではない。",
            "かりたものはかえすべきで、むだんでつかうものではない。",
            "Đồ mượn phải trả — không nên tự ý dùng.",
            [
              ["借", "か"],
              ["りたものは"],
              ["返", "かえ"],
              ["すべきで、"],
              ["無断", "むだん"],
              ["で"],
              ["使", "つか"],
              ["うものではない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ものだ／〜ものではない",
        "Câu khuyên đạo lý: Vる＋ものだ／ものではない — nên / không nên…",
        [
          ["Trẻ em nên chào người lớn.", "子供は大人に挨拶するものだ。"],
          ["Không nên nói xấu sau lưng.", "陰で人の悪口を言うものではない。"],
          ["Đến đúng giờ là lẽ thường.", "約束の時間には来るものだ。"],
          ["Không nên mở thư của người khác.", "他人の手紙を開けるものではない。"],
          ["Được giúp thì nên cảm ơn.", "助けてもらったらお礼を言うものだ。"],
          ["Không nên bỏ rác bừa bãi.", "ゴミをポイ捨てするものではない。"],
          ["Trong thư viện nên giữ im lặng.", "図書館では静かにするものだ。"],
          ["Không nên cười khi tang lễ.", "葬式で笑うものではない。"],
          ["Có lỗi thì nên thành thật thừa nhận.", "間違えたら素直に認めるものだ。"],
          ["Không nên tự ý lấy đồ chung.", "共用の物を勝手に持ち出すものではない。"],
        ],
        [
          ["困っている人を見捨てるものではない。", "Không nên bỏ mặc người đang khó."],
          ["食事の前には手を洗うものだ。", "Trước bữa ăn nên rửa tay."],
          ["他人の秘密をばらすものではない。", "Không nên tiết lộ bí mật người khác."],
          ["公共交通では優先席を譲るものだ。", "Trên phương tiện công cộng nên nhường ghế ưu tiên."],
          ["嘘をついて逃れようとするものではない。", "Không nên nói dối để thoát thân."],
          ["感謝の気持ちは言葉で伝えるものだ。", "Lòng biết ơn nên bày tỏ bằng lời."],
          ["公共の場で大声で騒ぐものではない。", "Không nên om sòm nơi công cộng."],
          ["借りたお金はきちんと返すものだ。", "Tiền mượn nên trả đúng đắn."],
          ["相手の話を最後まで遮るものではない。", "Không nên cắt ngang lời người khác đến cuối."],
          ["ルールは守って遊ぶものだ。", "Chơi thì nên tuân thủ luật."],
        ],
        [
          ["Với người trên nói lịch sự.", ["目上の人には丁寧に", "話す", "もの", "だ。"], 0],
          ["Đồ mượn không tự ý dùng.", ["無断で使う", "ものでは", "ない", "。"], 0],
          ["Trẻ nên chào người lớn.", ["子供は大人に", "挨拶する", "もの", "だ。"], 0],
          ["Không nói xấu sau lưng.", ["陰で人の悪口を", "言うものでは", "ない", "。"], 0],
          ["Đến đúng giờ hẹn.", ["約束の時間には", "来る", "もの", "だ。"], 0],
          ["Không mở thư người khác.", ["他人の手紙を", "開けるものでは", "ない", "。"], 0],
          ["Được giúp thì cảm ơn.", ["助けてもらったらお礼を", "言う", "もの", "だ。"], 0],
          ["Không bỏ mặc người khó.", ["困っている人を", "見捨てるものでは", "ない", "。"], 0],
          ["Trước ăn nên rửa tay.", ["食事の前には手を", "洗う", "もの", "だ。"], 0],
          ["Tiền mượn nên trả đúng.", ["借りたお金はきちんと", "返す", "もの", "だ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l24-g04",
      {
        meaning: "Không cần… / chẳng việc gì phải…",
        structures: [
          "Vる ＋ ことはない",
          "Vない ＋ ことはない（別義：không phải là không…）",
        ],
        explanation:
          "Vる＋ことはない trấn an hoặc khuyên: không cần làm A / chẳng việc gì phải A. (Lưu ý: Vない＋ことはない mang nghĩa khác — ‘không phải là không…’.)",
        usage: "An ủi, giảm áp lực: không cần lo; chẳng việc gì phải xin lỗi nhiều.",
        cautions: [
          "Ở bài này trọng tâm nghĩa ‘không cần’ với Vる＋ことはない.",
          "Khác に越したことはない (tốt nhất nếu…) ở bài 23.",
        ],
        contrast:
          "ことはない ≈ không cần…. Khác べきではない (không nên — đạo đức) và ものではない (không nên — chuẩn mực).",
        examples: [
          ex(
            "小さなミスくらい気にすることはない。",
            "ちいさなみすくらいきにすることはない。",
            "Lỗi nhỏ thôi — chẳng việc gì phải để tâm.",
            [
              ["小", "ちい"],
              ["さなミスくらい"],
              ["気", "き"],
              ["にすることはない。"],
            ],
          ),
          ex(
            "全部一人でやることはない。",
            "ぜんぶひとりでやることはない。",
            "Không cần làm hết một mình.",
            [
              ["全部", "ぜんぶ"],
              ["一人", "ひとり"],
              ["でやることはない。"],
            ],
          ),
          ex(
            "そんなに慌てることはない。",
            "そんなにあわてることはない。",
            "Không cần phải cuống lên như thế.",
            [
              ["そんなに"],
              ["慌", "あわ"],
              ["てることはない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ことはない",
        "Câu trấn an/khuyên: Vる＋ことはない — không cần / chẳng việc gì phải…",
        [
          ["Không cần xin lỗi nhiều lần.", "何度も謝ることはない。"],
          ["Chẳng việc gì phải xấu hổ.", "恥ずかしがることはない。"],
          ["Không cần mang quá nhiều đồ.", "荷物を抱えすぎることはない。"],
          ["Chẳng việc gì phải so sánh với người khác.", "他人と比べることはない。"],
          ["Không cần trả lời ngay lập tức.", "すぐに返事することはない。"],
          ["Chẳng việc gì phải thức trắng vì việc đó.", "その件で徹夜することはない。"],
          ["Không cần nói lớn như vậy.", "そんなに大きな声を出すことはない。"],
          ["Chẳng việc gì phải từ chối cứng.", "きっぱり断ることはない。"],
          ["Không cần mua cái đắt nhất.", "一番高いものを選ぶことはない。"],
          ["Chẳng việc gì phải giấu chuyện nhỏ.", "些細なことを隠すことはない。"],
        ],
        [
          ["心配しすぎることはない。", "Không cần lo quá mức."],
          ["一人で抱え込むことはない。", "Chẳng việc gì phải ôm một mình."],
          ["完璧を目指しすぎることはない。", "Không cần cầu toàn quá."],
          ["今更後悔することはない。", "Giờ này chẳng việc gì phải hối hận."],
          ["わざわざ出向くことはない。", "Không cần phải đích thân đến."],
          ["細かい点まで気にすることはない。", "Không cần để ý đến từng chi tiết nhỏ."],
          ["無理に笑うことはない。", "Chẳng việc gì phải cười gượng."],
          ["全部覚えようとすることはない。", "Không cần cố nhớ hết."],
          ["そんなに急ぐことはない。", "Không cần vội đến thế."],
          ["遠慮しすぎることはない。", "Chẳng việc gì phải khách khí quá."],
        ],
        [
          ["Lỗi nhỏ chẳng cần để tâm.", ["小さなミスくらい", "気にする", "ことは", "ない。"], 0],
          ["Không cần làm hết một mình.", ["全部一人で", "やる", "ことは", "ない。"], 0],
          ["Không cần cuống như thế.", ["そんなに", "慌てる", "ことは", "ない。"], 0],
          ["Không cần xin lỗi nhiều.", ["何度も", "謝る", "ことは", "ない。"], 0],
          ["Chẳng việc gì xấu hổ.", ["恥ずかしがる", "ことは", "ない", "。"], 0],
          ["Không cần so với người.", ["他人と", "比べる", "ことは", "ない。"], 0],
          ["Không lo quá mức.", ["心配しすぎる", "ことは", "ない", "。"], 0],
          ["Không ôm một mình.", ["一人で抱え込む", "ことは", "ない", "。"], 0],
          ["Không cần đích thân đến.", ["わざわざ", "出向く", "ことは", "ない。"], 0],
          ["Không cần vội đến thế.", ["そんなに", "急ぐ", "ことは", "ない。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l24-g05",
      {
        meaning: "Sẽ không… / quyết không…; liệu có… hay không…",
        structures: [
          "Vる／Vます ＋ まい",
          "V（よ）うか ＋ Vまい か",
          "V（よ）うかVまいか",
        ],
        explanation:
          "まい phủ định ý chí hoặc suy đoán mạnh: quyết/sẽ không A. （よ）うか〜まいか diễn tả do dự giữa làm hay không làm.",
        usage: "Quyết tâm: sẽ không lặp lại. Do dự: liệu có nói hay không nói.",
        cautions: [
          "Khác まい／ではあるまいか ở bài 22 (suy đoán ‘chẳng phải… sao?’); bài này nhấn ý chí và lưỡng lự.",
          "する→するまい／すまい; くる→こまい; nhóm II: 食べまい.",
        ],
        contrast:
          "まい ≈ quyết/sẽ không. （よ）うかまいか ≈ liệu có… hay không. Khác ないだろう (suy đoán trung tính).",
        examples: [
          ex(
            "二度と同じ失敗はすまい。",
            "にどとおなじしっぱいはすまい。",
            "Sẽ không phạm cùng một lỗi nữa.",
            [
              ["二度", "にど"],
              ["と"],
              ["同", "おな"],
              ["じ"],
              ["失敗", "しっぱい"],
              ["はすまい。"],
            ],
          ),
          ex(
            "行くか行くまいか迷っている。",
            "いくかいくまいかまよっている。",
            "Đang phân vân liệu có đi hay không.",
            [
              ["行", "い"],
              ["くか"],
              ["行", "い"],
              ["くまいか"],
              ["迷", "まよ"],
              ["っている。"],
            ],
          ),
          ex(
            "言うか言うまいか今夜決める。",
            "いうかいうまいかこんやけっていする。",
            "Đêm nay sẽ quyết nói hay không nói.",
            [
              ["言", "い"],
              ["うか"],
              ["言", "い"],
              ["うまいか"],
              ["今夜", "こんや"],
              ["決", "けっ"],
              ["める。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜まい／〜（よ）うか〜まいか",
        "Câu ý chí/do dự: 〜まい — quyết không…; （よ）うかまいか — liệu có… hay không.",
        [
          ["Quyết không bỏ cuộc giữa chừng.", "途中で諦めるまい。"],
          ["Liệu có nhận lời hay không đang phân vân.", "引き受けるか引き受けるまいか迷う。"],
          ["Sẽ không lộ bí mật cho ai.", "秘密を誰にも漏らすまい。"],
          ["Liệu có mua hay không vẫn chưa quyết.", "買うか買うまいか決められない。"],
          ["Quyết không phụ lòng mọi người.", "皆の期待を裏切るまい。"],
          ["Liệu có chuyển việc hay không đang nghĩ.", "転職するか転職すまいか考え中だ。"],
          ["Sẽ không quên ơn lần này.", "この恩は忘れまい。"],
          ["Liệu có gửi mail hay không do dự.", "メールを送ろうか送るまいか迷った。"],
          ["Quyết không nói dối nữa.", "もう嘘はつくまい。"],
          ["Liệu có tham gia hay không chưa rõ.", "参加しようかするまいか分からない。"],
        ],
        [
          ["二度と遅刻はすまい。", "Sẽ không đến muộn nữa."],
          ["告白しようかするまいか昨夜悩んだ。", "Đêm qua khổ sở liệu có tỏ tình hay không."],
          ["彼にはもう頼むまい。", "Sẽ không nhờ anh ấy nữa."],
          ["残るか残るまいか家族と相談する。", "Ở lại hay không sẽ bàn với gia đình."],
          ["同じ過ちを繰り返すまいと誓った。", "Thề sẽ không lặp lại lỗi cũ."],
          ["発表するか発表すまいか直前まで迷った。", "Đến phút chót vẫn phân vân công bố hay không."],
          ["二度と文句は言うまい。", "Sẽ không phàn nàn nữa."],
          ["行くか行くまいか朝までに決める。", "Đi hay không sẽ quyết trước sáng."],
          ["弱い自分に負けるまい。", "Sẽ không thua cái tôi yếu đuối."],
          ["断るか断るまいか一晩考える。", "Từ chối hay không nghĩ cả đêm."],
        ],
        [
          ["Không phạm cùng lỗi nữa.", ["二度と同じ失敗は", "す", "まい", "。"], 0],
          ["Phân vân đi hay không.", ["行くか行くまいか", "迷って", "いる", "。"], 0],
          ["Đêm nay quyết nói hay không.", ["言うか言うまいか", "今夜", "決める", "。"], 0],
          ["Quyết không bỏ cuộc.", ["途中で", "諦める", "まい", "。"], 0],
          ["Không lộ bí mật.", ["秘密を誰にも", "漏らす", "まい", "。"], 0],
          ["Mua hay không chưa quyết.", ["買うか買うまいか", "決められ", "ない", "。"], 0],
          ["Không đến muộn nữa.", ["二度と遅刻は", "す", "まい", "。"], 0],
          ["Không nhờ anh ấy nữa.", ["彼にはもう", "頼む", "まい", "。"], 0],
          ["Không thua cái tôi yếu.", ["弱い自分に", "負ける", "まい", "。"], 0],
          ["Đi hay không quyết sáng.", ["行くか行くまいか", "朝までに", "決める", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l24-g06",
      {
        meaning: "Làm gì có… / tuyệt đối không… (phủ định mạnh, phản kháng)",
        structures: [
          "普通形 ＋ ものか／もんか",
          "Vる ＋ ものか",
          "いAい ＋ ものか",
        ],
        explanation:
          "ものか／もんか phủ định cảm xúc mạnh: làm gì có chuyện đó; tuyệt đối không làm/không thừa nhận — thường phản kháng hoặc tự nhủ quyết liệt.",
        usage: "Từ chối quyết liệt: làm gì có chịu thua; tuyệt đối không xin lỗi kẻ đó.",
        cautions: [
          "もんか khẩu ngữ hơn ものか; giọng mạnh, dễ tỏ ra thô.",
          "Khác ものではない (khuyên ‘không nên’); ものか là ‘tuyệt đối không / làm gì có’.",
        ],
        contrast:
          "ものか ≈ làm gì có / tuyệt đối không. Khác ことはない (không cần) và まい (quyết không — ý chí).",
        examples: [
          ex(
            "あんな理不尽な要求に応じるものか。",
            "あんなりふじんなようきゅうにおうじるものか。",
            "Làm gì có chuyện đáp ứng yêu cầu vô lý đó.",
            [
              ["あんな"],
              ["理不尽", "りふじん"],
              ["な"],
              ["要求", "ようきゅう"],
              ["に"],
              ["応", "おう"],
              ["じるものか。"],
            ],
          ),
          ex(
            "二度と彼に頼むもんか。",
            "にどとかれにたのむもんか。",
            "Tuyệt đối không nhờ anh ấy nữa.",
            [
              ["二度", "にど"],
              ["と"],
              ["彼", "かれ"],
              ["に"],
              ["頼", "たの"],
              ["むもんか。"],
            ],
          ),
          ex(
            "こんな成績で満足できるものか。",
            "こんなせいせきでまんぞくできるものか。",
            "Làm gì có thỏa mãn với thành tích thế này.",
            [
              ["こんな"],
              ["成績", "せいせき"],
              ["で"],
              ["満足", "まんぞく"],
              ["できるものか。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ものか",
        "Câu phủ định mạnh: 普通形＋ものか／もんか — làm gì có / tuyệt đối không…",
        [
          ["Làm gì có chịu thua dễ vậy.", "こんなことで負けるものか。"],
          ["Tuyệt đối không tin lời đó.", "そんな話を信じるもんか。"],
          ["Làm gì có bỏ cuộc giữa chừng.", "途中で諦めるものか。"],
          ["Tuyệt đối không đi cùng hắn.", "あいつと同行するもんか。"],
          ["Làm gì có quên ơn sâu đó.", "あの恩を忘れるものか。"],
          ["Tuyệt đối không lặp lại lỗi cũ.", "同じミスを繰り返すもんか。"],
          ["Làm gì có sợ lời dị nghị.", "陰口など怖がるものか。"],
          ["Tuyệt đối không bán rẻ nguyên tắc.", "信念を安売りするもんか。"],
          ["Làm gì có vui với lời khen giả.", "社交辞令で喜べるものか。"],
          ["Tuyệt đối không để lộ bí mật.", "秘密を漏らすもんか。"],
        ],
        [
          ["誰がそんな条件を飲むものか。", "Ai mà chấp nhận điều kiện kiểu đó."],
          ["こんな安月給で働くもんか。", "Tuyệt đối không làm với lương thấp thế."],
          ["負けてたまるものか。", "Làm gì có chịu thua."],
          ["もう二度と謝るもんか。", "Tuyệt đối không xin lỗi nữa."],
          ["こんな説明で納得できるものか。", "Làm gì có thuyết phục được với giải thích thế này."],
          ["弱い者いじめをするものか。", "Tuyệt đối không bắt nạt kẻ yếu."],
          ["約束を破って逃げるもんか。", "Làm gì có bỏ chạy sau khi phá hứa."],
          ["こんな難問にひるむものか。", "Tuyệt đối không nao núng trước bài khó thế."],
          ["彼の言いなりになるもんか。", "Làm gì có nghe theo anh ấy hết."],
          ["現状に甘んじるものか。", "Tuyệt đối không cam chịu hiện trạng."],
        ],
        [
          ["Đáp ứng yêu cầu vô lý ư?", ["あんな理不尽な要求に", "応じる", "もの", "か。"], 0],
          ["Không nhờ anh ấy nữa.", ["二度と彼に", "頼む", "もん", "か。"], 0],
          ["Thỏa mãn thành tích này ư?", ["こんな成績で", "満足できる", "もの", "か。"], 0],
          ["Chịu thua dễ vậy ư?", ["こんなことで", "負ける", "もの", "か。"], 0],
          ["Tin lời đó sao được.", ["そんな話を", "信じる", "もん", "か。"], 0],
          ["Bỏ cuộc giữa chừng ư?", ["途中で", "諦める", "もの", "か。"], 0],
          ["Không quên ơn đó.", ["あの恩を", "忘れる", "もの", "か。"], 0],
          ["Ai chấp nhận điều kiện đó.", ["誰がそんな条件を", "飲む", "もの", "か。"], 0],
          ["Chịu thua sao được.", ["負けて", "たまる", "もの", "か。"], 0],
          ["Không cam chịu hiện trạng.", ["現状に", "甘んじる", "もの", "か。"], 0],
        ],
      ),
    ),
  ];
}
