import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L16-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 16, BATCH);

export function lesson16Patterns(byId) {
  return [
    P(
      byId,
      "l16-g01",
      {
        meaning: "Do… / nhờ… / tùy theo… / bằng…",
        structures: [
          "N ＋ によって／により",
          "N ＋ による ＋ N",
        ],
        explanation:
          "によって・により diễn đạt nguyên nhân, phương tiện, hoặc 'tùy theo'; による修飾 danh từ (〜による影響).",
        usage: "Nêu lý do/cách thức trang trọng; cũng dùng 'tùy người/tùy trường hợp'.",
        cautions: [
          "により thiên văn viết hơn によって.",
          "による luôn đứng trước danh từ; không kết câu như によってだ.",
        ],
        contrast:
          "によって ≈ do/nhờ/tùy. Khác おかげで (ơn) và せいで (tại) về sắc thái.",
        examples: [
          ex(
            "地震によって橋が壊れた。",
            "じしんによってはしがこわれた。",
            "Do động đất, cầu bị hỏng.",
            [
              ["地震", "じしん"],
              ["によって"],
              ["橋", "はし"],
              ["が"],
              ["壊", "こわ"],
              ["れた。"],
            ],
          ),
          ex(
            "人によって考え方が違う。",
            "ひとによってかんがえかたがちがう。",
            "Tùy người mà cách nghĩ khác nhau.",
            [
              ["人", "ひと"],
              ["によって"],
              ["考え方", "かんがえかた"],
              ["が"],
              ["違", "ちが"],
              ["う。"],
            ],
          ),
          ex(
            "ネットによる情報収集が増えた。",
            "ねっとによるじょうほうしゅうしゅうがふえた。",
            "Thu thập thông tin bằng mạng tăng lên.",
            [
              ["ネットによる"],
              ["情報", "じょうほう"],
              ["収集", "しゅうしゅう"],
              ["が"],
              ["増", "ふ"],
              ["えた。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜によって／により／による",
        "Câu nguyên nhân·phương tiện·tùy theo: によって／により／による.",
        [
          ["Do bão, tàu bị hủy.", "台風によって電車が運休した。"],
          ["Tùy mùa mà giá thay đổi.", "季節によって値段が変わる。"],
          ["Nhờ nỗ lực, anh ấy đậu.", "努力により彼は合格した。"],
          ["Ảnh hưởng do cháy rừng rất lớn.", "山火事による被害は大きい。"],
          ["Tùy quốc gia mà luật khác.", "国によって法律が異なる。"],
          ["Do tai nạn giao thông đường tắc.", "事故によって道路が渋滞した。"],
          ["Bằng thí nghiệm xác nhận được giả thuyết.", "実験により仮説が確認された。"],
          ["Tùy cách nói mà ấn tượng đổi.", "言い方によって印象が変わる。"],
          ["Thiệt hại do mưa lớn lan rộng.", "大雨による損害が広がった。"],
          ["Do chính sách mới quy tắc đổi.", "新制度によって規則が変わった。"],
        ],
        [
          ["火災によって建物が全焼した。", "Do cháy, tòa nhà cháy sạch."],
          ["方法によって結果が大きく違う。", "Tùy phương pháp kết quả khác nhiều."],
          ["調査により事実が明らかになった。", "Nhờ điều tra sự thật lộ rõ."],
          ["ウイルスによる感染が拡大した。", "Lây nhiễm do virus lan rộng."],
          ["年齢によって料金が分かれる。", "Tùy tuổi phí khác nhau."],
          ["騒音によって眠れなかった。", "Do tiếng ồn không ngủ được."],
          ["話し合いにより解決した。", "Nhờ bàn bạc đã giải quyết."],
          ["地域による差が大きい。", "Chênh lệch theo vùng lớn."],
          ["技術によって作業が楽になった。", "Nhờ kỹ thuật việc dễ hơn."],
          ["天候により予定が延期された。", "Do thời tiết lịch bị hoãn."],
        ],
        [
          ["Do động đất cầu hỏng.", ["地震によって", "橋が", "壊れた", "そうだ。"], 0],
          ["Tùy người cách nghĩ khác.", ["人によって", "考え方が", "違う", "ものだ。"], 0],
          ["Thu thập bằng mạng tăng.", ["ネットによる", "情報収集が", "増えた", "らしい。"], 0],
          ["Do bão tàu hủy.", ["台風によって", "電車が", "運休した", "ようだ。"], 0],
          ["Tùy mùa giá đổi.", ["季節によって", "値段が", "変わる", "ことがある。"], 0],
          ["Nhờ nỗ lực đậu.", ["努力により", "彼は", "合格した", "らしい。"], 0],
          ["Thiệt hại cháy rừng lớn.", ["山火事による", "被害は", "大きい", "だろう。"], 0],
          ["Tùy nước luật khác.", ["国によって", "法律が", "異なる", "はずだ。"], 0],
          ["Do tai nạn đường tắc.", ["事故によって", "道路が", "渋滞した", "ようだ。"], 0],
          ["Bằng thí nghiệm xác nhận.", ["実験により", "仮説が", "確認された", "そうだ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l16-g02",
      {
        meaning: "Vì… mà… (lý do chủ quan, biện hộ nhẹ)",
        structures: [
          "普通形 ＋ ものだから／もので",
          "普通形 ＋ もの（終助詞的）",
        ],
        explanation:
          "ものだから・もので nêu lý do cá nhân, thường giải thích/biện hộ; もの ở cuối câu nhấn mạnh lý do kiểu trẻ con/thân mật.",
        usage: "Xin lỗi, giải thích vì sao mình làm vậy; hội thoại hàng ngày.",
        cautions: [
          "Không dùng cho lý do khách quan trang trọng (dùng ため／ので).",
          "ものだから thường trước kết quả; もの kết thúc câu giải thích.",
        ],
        contrast:
          "ものだから ≈ vì (biện hộ). Khác から／ので (trung lập hơn).",
        examples: [
          ex(
            "道が混んでいたものだから遅刻した。",
            "みちがこんでいたものだからちこくした。",
            "Vì đường tắc nên tôi đến muộn.",
            [
              ["道", "みち"],
              ["が"],
              ["混", "こ"],
              ["んでいたものだから"],
              ["遅刻", "ちこく"],
              ["した。"],
            ],
          ),
          ex(
            "初めてなもので緊張しています。",
            "はじめてなものできんちょうしています。",
            "Vì lần đầu nên đang căng thẳng.",
            [
              ["初", "はじ"],
              ["めてなもので"],
              ["緊張", "きんちょう"],
              ["しています。"],
            ],
          ),
          ex(
            "知らなかったんだもの。",
            "しらなかったんだもの。",
            "Tại mình không biết mà.",
            [
              ["知", "し"],
              ["らなかったんだもの。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ものだから／もので／もの",
        "Câu lý do chủ quan: ものだから／もので／もの.",
        [
          ["Vì mưa to nên taxi về.", "雨が強かったものだからタクシーで帰った。"],
          ["Vì mệt nên về sớm.", "疲れていたもので早退した。"],
          ["Tại quên mất mà.", "忘れていたんだもの。"],
          ["Vì đông quá nên xếp hàng lâu.", "混雑していたものだから長く並んだ。"],
          ["Vì lần đầu gặp nên ngại.", "初対面なもので少し遠慮した。"],
          ["Vì điện thoại hết pin nên không gọi.", "電池が切れていたものだから電話できなかった。"],
          ["Vì say xe nên không ăn.", "乗り物酔いしたもんで何も食べなかった。"],
          ["Tại sợ hỏng nên không đụng.", "壊しそうで怖かったんだもの。"],
          ["Vì hết chỗ nên đứng.", "席がなかったものだから立っていた。"],
          ["Vì tối rồi nên về trước.", "もう遅いもので先に帰ります。"],
        ],
        [
          ["急用が入ったものだから欠席した。", "Vì có việc gấp nên vắng."],
          ["慣れていないもんで時間がかかった。", "Vì chưa quen nên mất thời gian."],
          ["仕方ないんだもの。", "Tại chẳng còn cách nào mà."],
          ["風邪気味なものだから安静にしている。", "Vì hơi cảm nên đang nghỉ."],
          ["初めての経験なもので戸惑った。", "Vì trải nghiệm lần đầu nên bối rối."],
          ["連絡が遅れたものだから誤解された。", "Vì liên lạc chậm nên bị hiểu nhầm."],
          ["眠かったもんで聞き逃した。", "Vì buồn ngủ nên nghe sót."],
          ["知らなかったんだもの、責めないで。", "Tại không biết mà, đừng trách."],
          ["道に迷ったものだから遅れた。", "Vì lạc đường nên muộn."],
          ["子どもが熱を出したもんで休んだ。", "Vì con sốt nên nghỉ."],
        ],
        [
          ["Vì đường tắc đến muộn.", ["混んでいたものだから", "遅刻", "して", "しまった。"], 0],
          ["Vì lần đầu đang căng.", ["初めてなもので", "緊張", "して", "いる。"], 0],
          ["Tại không biết mà.", ["知らなかったんだ", "もの", "だ", "よ。"], 0],
          ["Vì mưa to về taxi.", ["雨が強かったものだから", "タクシーで", "帰った", "らしい。"], 0],
          ["Vì mệt về sớm.", ["疲れていたもので", "早退", "した", "そうだ。"], 0],
          ["Vì đông xếp hàng lâu.", ["混雑していたものだから", "長く", "並んだ", "ようだ。"], 0],
          ["Vì hết pin không gọi.", ["電池切れだったものだから", "電話でき", "なかった", "そうだ。"], 0],
          ["Vì hết chỗ phải đứng.", ["席がなかったものだから", "立って", "いた", "らしい。"], 0],
          ["Vì tối về trước.", ["もう遅いもので", "先に", "帰り", "ます。"], 0],
          ["Vì việc gấp nên vắng.", ["急用が入ったものだから", "欠席", "した", "らしい。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l16-g03",
      {
        meaning: "Nhờ… (tốt) / tại… (xấu)",
        structures: [
          "Nの／普通形 ＋ おかげだ／おかげで",
          "Nの／普通形 ＋ せいだ／せいで",
        ],
        explanation:
          "おかげだ・おかげで nhấn mạnh kết quả tốt nhờ ai/cái gì; せいだ・せいで đổ lỗi kết quả xấu.",
        usage: "Cảm ơn, khen; hoặc trách móc nguyên nhân xấu.",
        cautions: [
          "おかげで đôi khi dùng mỉa (kết quả xấu) — ngữ cảnh quyết định.",
          "せいで hầu như chỉ kết quả tiêu cực; tránh dùng khi cảm ơn.",
        ],
        contrast:
          "おかげ ≈ nhờ (tích cực). せい ≈ tại (tiêu cực). Khác によって (trung lập hơn).",
        examples: [
          ex(
            "先生のおかげで合格できた。",
            "せんせいのおかげでごうかくできた。",
            "Nhờ thầy cô mà đậu được.",
            [
              ["先生", "せんせい"],
              ["のおかげで"],
              ["合格", "ごうかく"],
              ["できた。"],
            ],
          ),
          ex(
            "雨のせいで試合が中止になった。",
            "あめのせいでしあいがちゅうしになった。",
            "Tại mưa nên trận đấu bị hủy.",
            [
              ["雨", "あめ"],
              ["のせいで"],
              ["試合", "しあい"],
              ["が"],
              ["中止", "ちゅうし"],
              ["になった。"],
            ],
          ),
          ex(
            "成功したのは仲間のおかげだ。",
            "せいこうしたのはなかまのおかげだ。",
            "Thành công là nhờ đồng đội.",
            [
              ["成功", "せいこう"],
              ["したのは"],
              ["仲間", "なかま"],
              ["のおかげだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜おかげだ／せいだ",
        "Câu nhờ (tốt) hoặc tại (xấu): おかげ／せい.",
        [
          ["Nhờ lời khuyên mà quyết định được.", "助言のおかげで決断できた。"],
          ["Tại ùn tắc nên họp muộn.", "渋滞のせいで会議に遅れた。"],
          ["Nhờ luyện tập điểm tăng.", "練習のおかげで点数が上がった。"],
          ["Tại mất ngủ nên tập trung kém.", "不眠のせいで集中できない。"],
          ["Nhờ hỗ trợ dự án xong đúng hạn.", "支援のおかげで期限内に終わった。"],
          ["Tại ồn ào không nghe rõ.", "騒音のせいでよく聞こえない。"],
          ["Nhờ thuốc cảm đỡ hơn.", "薬のおかげで風邪が治りかけた。"],
          ["Tại bất cẩn làm hỏng máy.", "不注意のせいで機械を壊した。"],
          ["Thắng là nhờ cả đội.", "勝てたのはチームのおかげだ。"],
          ["Trễ là tại xe buýt.", "遅れたのはバスのせいだ。"],
        ],
        [
          ["家族のおかげで頑張れた。", "Nhờ gia đình mà cố gắng được."],
          ["事故のせいで道が塞がった。", "Tại tai nạn đường bị chặn."],
          ["先輩のおかげで仕事が早く終わった。", "Nhờ senpai việc xong sớm."],
          ["風邪のせいで声が出ない。", "Tại cảm không ra tiếng."],
          ["協力のおかげで目標を達成した。", "Nhờ hợp tác đạt mục tiêu."],
          ["油断のせいでミスした。", "Tại chủ quan nên sai."],
          ["晴れたのは風のおかげだ。", "Trời quang là nhờ gió."],
          ["失敗したのは準備不足のせいだ。", "Thất bại là tại thiếu chuẩn bị."],
          ["辞書のおかげで意味が分かった。", "Nhờ từ điển hiểu nghĩa."],
          ["遅刻したのは目覚ましのせいだ。", "Muộn là tại đồng hồ báo thức."],
        ],
        [
          ["Nhờ thầy cô đậu được.", ["先生のおかげで", "合格", "できた", "そうだ。"], 0],
          ["Tại mưa trận hủy.", ["雨のせいで", "試合が", "中止に", "なった。"], 0],
          ["Thành công nhờ đồng đội.", ["成功したのは", "仲間の", "おかげ", "だ。"], 2],
          ["Nhờ lời khuyên quyết được.", ["助言のおかげで", "決断", "できた", "らしい。"], 0],
          ["Tại ùn tắc họp muộn.", ["渋滞のせいで", "会議に", "遅れた", "ようだ。"], 0],
          ["Luyện tập giúp điểm tăng.", ["練習のおかげで", "点数が", "上がった", "そうだ。"], 0],
          ["Mất ngủ khiến kém tập trung.", ["不眠のせいで", "集中でき", "ない", "らしい。"], 0],
          ["Hỗ trợ giúp xong đúng hạn.", ["支援のおかげで", "期限内に", "終わった", "そうだ。"], 0],
          ["Thắng nhờ công cả đội.", ["勝てたのは", "チームの", "おかげ", "だ。"], 2],
          ["Muộn là do xe buýt.", ["遅れたのは", "バスの", "せい", "だ。"], 2],
        ],
      ),
    ),

    P(
      byId,
      "l16-g04",
      {
        meaning: "Vì quá… / vì mức độ… quá mức nên…",
        structures: [
          "Vる／いAい／Nの ＋ あまり（に）",
          "あまりの ＋ N ＋ に",
        ],
        explanation:
          "あまり diễn đạt vì mức độ cảm xúc/trạng thái quá cao nên có kết quả (thường ngoài ý muốn); あまりのNに nhấn mạnh 'vì mức N quá…'.",
        usage: "Giải thích hành động/kết quả do cảm xúc hoặc tình huống quá mức.",
        cautions: [
          "Thường kết quả tiêu cực hoặc không kiểm soát được.",
          "あまりの〜に bắt buộc có danh từ sau あまりの.",
        ],
        contrast:
          "あまり ≈ vì quá…. Khác すぎて (quá mức thuần túy) về sắc thái lý do cảm xúc.",
        examples: [
          ex(
            "喜びのあまり泣いてしまった。",
            "よろこびのあまりないてしまった。",
            "Vì vui quá nên khóc mất.",
            [
              ["喜", "よろこ"],
              ["びのあまり"],
              ["泣", "な"],
              ["いてしまった。"],
            ],
          ),
          ex(
            "驚きのあまり声も出なかった。",
            "おどろきのあまりこえもでなかった。",
            "Vì ngạc nhiên quá đến mức không ra tiếng.",
            [
              ["驚", "おどろ"],
              ["きのあまり"],
              ["声", "こえ"],
              ["も"],
              ["出", "で"],
              ["なかった。"],
            ],
          ),
          ex(
            "あまりの暑さに倒れた。",
            "あまりのあつさにたおれた。",
            "Vì nóng quá mức nên ngã.",
            [
              ["あまりの"],
              ["暑", "あつ"],
              ["さに"],
              ["倒", "たお"],
              ["れた。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜あまり／あまりの〜に",
        "Câu vì quá mức: あまり／あまりのNに.",
        [
          ["Vì lo quá không ngủ được.", "心配のあまり眠れなかった。"],
          ["Vì tức quá nói lớn.", "怒りのあまり大声を出した。"],
          ["Vì vui quá ôm lấy bạn.", "嬉しさのあまり友人を抱きしめた。"],
          ["Vì thất vọng quá im lặng.", "失望のあまり黙り込んだ。"],
          ["Vì mệt quá ngồi phệt xuống.", "疲労のあまり座り込んだ。"],
          ["Vì nóng quá mức mất nước.", "あまりの暑さに脱水した。"],
          ["Vì đông quá mức lối vào tắc.", "あまりの混雑に入口が塞がった。"],
          ["Vì sợ quá chân cứng.", "恐怖のあまり足が動かなかった。"],
          ["Vì cảm động quá chảy nước mắt.", "感動のあまり涙が出た。"],
          ["Vì ồn quá mức đau đầu.", "あまりの騒音に頭が痛くなった。"],
        ],
        [
          ["緊張のあまり手が震えた。", "Vì căng thẳng quá tay run."],
          ["悲しみのあまり食欲がない。", "Vì buồn quá không muốn ăn."],
          ["喜びのあまり飛び上がった。", "Vì vui quá nhảy dựng."],
          ["驚きのあまり立ち尽くした。", "Vì ngạc nhiên quá đứng sững."],
          ["忙しさのあまり食事を抜いた。", "Vì bận quá bỏ bữa."],
          ["あまりの寒さに震えた。", "Vì lạnh quá mức mà run."],
          ["あまりの高さに足がすくんだ。", "Vì cao quá mức chân mềm."],
          ["期待のあまり眠れなかった。", "Vì kỳ vọng quá không ngủ được."],
          ["悔しさのあまり拳を握った。", "Vì tức quá nắm chặt tay."],
          ["あまりの安さに驚いた。", "Vì rẻ quá mức mà ngạc nhiên."],
        ],
        [
          ["Vì vui quá khóc mất.", ["喜びのあまり", "泣いて", "しまった", "らしい。"], 0],
          ["Vì ngạc nhiên không ra tiếng.", ["驚きのあまり", "声も", "出なかった", "そうだ。"], 0],
          ["Vì nóng quá mức ngã.", ["あまりの暑さに", "倒れて", "しまった", "ようだ。"], 0],
          ["Vì lo quá không ngủ.", ["心配のあまり", "眠れ", "なかった", "らしい。"], 0],
          ["Tức quá nên nói lớn.", ["怒りのあまり", "大声を", "出した", "そうだ。"], 0],
          ["Thất vọng quá nên im lặng.", ["失望のあまり", "黙り", "込んだ", "ようだ。"], 0],
          ["Đông quá mức nên lối tắc.", ["あまりの混雑に", "入口が", "塞がった", "そうだ。"], 0],
          ["Sợ quá nên chân cứng.", ["恐怖のあまり", "足が", "動かなかった", "らしい。"], 0],
          ["Cảm động quá nên khóc.", ["感動のあまり", "涙が", "出た", "そうだ。"], 0],
          ["Ồn quá mức nên đau đầu.", ["あまりの騒音に", "頭が", "痛くなった", "ようだ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l16-g05",
      {
        meaning: "Do… / vì… (thông báo trang trọng, biển báo)",
        structures: ["N ＋ につき"],
        explanation:
          "つき nêu lý do ngắn gọn trên biển báo, thông báo công cộng: vì lý do X nên…",
        usage: "Thông báo cửa hàng, công ty, giao thông: tạm đóng, thay đổi lịch…",
        cautions: [
          "Chủ yếu văn viết/thông báo; ít dùng hội thoại thân mật.",
          "Thường sau danh từ; không kết hợp tự do như ので.",
        ],
        contrast:
          "につき ≈ vì (thông báo). Khác ため／ので (hội thoại/viết linh hoạt hơn).",
        examples: [
          ex(
            "工事中につき通行止めです。",
            "こうじちゅうにつきつうこうどめです。",
            "Do đang thi công nên cấm đi lại.",
            [
              ["工事", "こうじ"],
              ["中", "ちゅう"],
              ["につき"],
              ["通行", "つうこう"],
              ["止", "ど"],
              ["めです。"],
            ],
          ),
          ex(
            "本日定休日につき休業します。",
            "ほんじつていきゅうびにつききゅうぎょうします。",
            "Do hôm nay nghỉ định kỳ nên tạm đóng cửa.",
            [
              ["本日", "ほんじつ"],
              ["定休日", "ていきゅうび"],
              ["につき"],
              ["休業", "きゅうぎょう"],
              ["します。"],
            ],
          ),
          ex(
            "諸事情につき中止といたします。",
            "しょじじょうにつきちゅうしといたします。",
            "Do nhiều lý do nên quyết định hủy.",
            [
              ["諸事情", "しょじじょう"],
              ["につき"],
              ["中止", "ちゅうし"],
              ["といたします。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜につき",
        "Câu lý do thông báo: Nにつき.",
        [
          ["Do bảo trì nên tạm dừng dịch vụ.", "メンテナンスにつきサービスを停止します。"],
          ["Do hết hàng nên không bán.", "売切れにつき販売できません。"],
          ["Do mưa lớn nên hủy sự kiện.", "大雨につきイベントは中止です。"],
          ["Do họp nên phòng bận.", "会議につきこの部屋は使用中です。"],
          ["Do kiểm tra nên thang máy dừng.", "点検につきエレベーターは停止中です。"],
          ["Do sửa chữa nên lối đi đổi.", "改修につき通路を変更します。"],
          ["Do hết chỗ nên hết nhận đặt.", "満席につき予約受付を終了します。"],
          ["Do nghỉ lễ nên đóng cửa.", "祝日につき本日は休業です。"],
          ["Do sự cố hệ thống nên chậm trễ.", "システム障害につき遅延が発生しています。"],
          ["Do đang chuẩn bị nên xin chờ.", "準備中につき少々お待ちください。"],
        ],
        [
          ["改装中につきしばらくお休みします。", "Do đang cải tạo nên tạm nghỉ."],
          ["悪天候につき運休します。", "Do thời tiết xấu nên tạm dừng chạy."],
          ["社内事情につき採用を見送ります。", "Do tình hình công ty nên hoãn tuyển."],
          ["停電につき営業を中断します。", "Do mất điện nên tạm ngừng bán."],
          ["混雑につき入場を制限します。", "Do đông nên hạn chế vào."],
          ["故障につき修理中です。", "Do hỏng nên đang sửa."],
          ["年末年始につき営業時間が変わります。", "Do cuối/đầu năm giờ bán đổi."],
          ["雨天につき屋内で実施します。", "Do mưa nên tổ chức trong nhà."],
          ["在庫僅少につきお一人様一点まで。", "Do tồn kho ít, mỗi người một món."],
          ["清掃につき一時ご利用いただけません。", "Do dọn vệ sinh nên tạm thời không dùng được."],
        ],
        [
          ["Do thi công cấm đi lại.", ["工事中につき", "通行止めに", "なって", "います。"], 0],
          ["Do nghỉ định kỳ đóng cửa.", ["定休日につき", "休業", "いたし", "ます。"], 0],
          ["Do nhiều lý do hủy.", ["諸事情につき", "中止と", "させて", "いただきます。"], 0],
          ["Do bảo trì dừng dịch vụ.", ["メンテナンスにつき", "サービスを", "停止", "します。"], 0],
          ["Do hết hàng không bán.", ["売切れにつき", "販売は", "でき", "ません。"], 0],
          ["Do mưa lớn hủy sự kiện.", ["大雨につき", "イベントは", "中止と", "します。"], 0],
          ["Do họp phòng đang dùng.", ["会議につき", "この部屋は", "使用中", "です。"], 0],
          ["Do kiểm tra thang máy dừng.", ["点検につき", "エレベーターは", "停止中", "です。"], 0],
          ["Do hết chỗ hết nhận đặt.", ["満席につき", "予約受付を", "終了", "します。"], 0],
          ["Do đang chuẩn bị xin chờ.", ["準備中につき", "少々お待ち", "ください", "ませ。"], 0],
        ],
      ),
    ),
  ];
}
