import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L21-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 25, BATCH);

export function lesson25Patterns(byId) {
  return [
    P(
      byId,
      "l25-g01",
      {
        meaning: "Không chịu nổi / không sao ngăn được (cảm xúc mạnh)",
        structures: [
          "Vて ＋ しかたがない／しょうがない／たまらない",
          "いAくて ＋ しかたがない／しょうがない／たまらない",
          "なAで ＋ しかたがない／しょうがない／たまらない",
        ],
        explanation:
          "Diễn tả cảm xúc/mong muốn mạnh đến mức không kiểm soát được. てたまらない thiên cảm xúc chủ quan; て仕方がない／しょうがない cũng dùng cho khó chịu, buồn chán.",
        usage: "Nói cảm xúc mạnh: vui, buồn, muốn, ngứa, ồn… không chịu nổi.",
        cautions: [
          "Thường gắn cảm xúc/trạng thái của bản thân người nói.",
          "しょうがない khẩu ngữ hơn 仕方がない; cả ba gần nghĩa nhưng sắc thái hơi khác.",
        ],
        contrast:
          "てたまらない／て仕方がない ≈ không chịu nổi. Khác てならない (thường cảm xúc tự nhiên, văn viết hơn).",
        examples: [
          ex(
            "合格が嬉しくてたまらない。",
            "ごうかくがうれしくてたまらない。",
            "Đỗ rồi vui không chịu nổi.",
            [
              ["合格", "ごうかく"],
              ["が"],
              ["嬉", "うれ"],
              ["しくてたまらない。"],
            ],
          ),
          ex(
            "隣の騒音がうるさくて仕方がない。",
            "となりのそうおんがうるさくてしかたがない。",
            "Tiếng ồn nhà bên ồn không chịu nổi.",
            [
              ["隣", "となり"],
              ["の"],
              ["騒音", "そうおん"],
              ["がうるさくて"],
              ["仕方", "しかた"],
              ["がない。"],
            ],
          ),
          ex(
            "新しい映画が見たくてしょうがない。",
            "あたらしいえいががみたくてしょうがない。",
            "Muốn xem phim mới không chịu nổi.",
            [
              ["新", "あたら"],
              ["しい"],
              ["映画", "えいが"],
              ["が"],
              ["見", "み"],
              ["たくてしょうがない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜てしかたがない／しょうがない／たまらない",
        "Câu cảm xúc mạnh: 〜てたまらない／仕方がない／しょうがない.",
        [
          ["Nóng không chịu nổi.", "暑くてたまらない。"],
          ["Muốn gặp bạn không chịu nổi.", "友人に会いたくてしょうがない。"],
          ["Ngứa không chịu nổi.", "かゆくて仕方がない。"],
          ["Buồn ngủ không chịu nổi.", "眠くてたまらない。"],
          ["Lo lắng không chịu nổi.", "不安で仕方がない。"],
          ["Muốn ăn bánh ngọt quá.", "甘いものが食べたくてしょうがない。"],
          ["Cáu tiết không chịu nổi.", "腹が立ってたまらない。"],
          ["Nhớ nhà không chịu nổi.", "故郷が恋しくて仕方がない。"],
          ["Tò mò không chịu nổi.", "中身が気になってしょうがない。"],
          ["Vui vì được khen không chịu nổi.", "褒められて嬉しくてたまらない。"],
        ],
        [
          ["寒くてたまらないので暖房を入れた。", "Lạnh không chịu nổi nên bật sưởi."],
          ["彼の成功が羨ましくて仕方がない。", "Ghen tị thành công của anh ấy không chịu nổi."],
          ["休みが待ち遠しくてしょうがない。", "Mong ngày nghỉ không chịu nổi."],
          ["この曲を聴くと悲しくてたまらない。", "Nghe bài này buồn không chịu nổi."],
          ["喉が渇いて仕方がない。", "Khát không chịu nổi."],
          ["新しいスマホが欲しくてしょうがない。", "Muốn điện thoại mới không chịu nổi."],
          ["虫刺されがかゆくてたまらない。", "Muỗi đốt ngứa không chịu nổi."],
          ["会議が長くて退屈で仕方がない。", "Họp dài chán không chịu nổi."],
          ["合格発表が気になってしょうがない。", "Tò mò kết quả thi không chịu nổi."],
          ["孫の顔が見たくてたまらない。", "Muốn thấy mặt cháu không chịu nổi."],
        ],
        [
          ["Nóng quá chịu không nổi.", ["今日は暑くて", "たまら", "ない", "。"], 0],
          ["Muốn gặp bạn quá đi.", ["友人に会いたくて", "しょうが", "ない", "。"], 0],
          ["Ngứa quá chịu không nổi.", ["傷口がかゆくて", "仕方が", "ない", "。"], 0],
          ["Buồn ngủ quá.", ["昨夜は眠くて", "たまら", "なかった", "。"], 0],
          ["Lo quá chịu không nổi.", ["結果が不安で", "仕方が", "ない", "。"], 0],
          ["Thèm đồ ngọt quá.", ["デザートが食べたくて", "しょうが", "ない", "。"], 0],
          ["Cáu quá chịu không nổi.", ["不正に腹が立って", "たまら", "ない", "。"], 0],
          ["Nhớ quê quá.", ["故郷が恋しくて", "仕方が", "ない", "。"], 0],
          ["Tò mò nội dung quá.", ["箱の中が気になって", "しょうが", "ない", "。"], 0],
          ["Được khen vui quá.", ["先生に褒められて", "嬉しくてたまら", "ない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l25-g02",
      {
        meaning: "Không chịu nổi / cứ… mãi không thôi (cảm xúc tự nhiên)",
        structures: [
          "Vて ＋ ならない",
          "いAくて ＋ ならない",
          "なAで ＋ ならない",
        ],
        explanation:
          "てならない diễn tả cảm xúc/nghĩ ngợi dâng lên tự nhiên, khó kiềm chế — thường lo, hối, tò mò, xúc động. Thiên văn viết/trang trọng hơn てたまらない.",
        usage: "Viết luận, nhật ký, kể cảm xúc: lo mãi, hối mãi, xúc động không thôi.",
        cautions: [
          "Thường với cảm xúc tự phát (心配・後悔・気になる・感動), ít dùng cho cảm giác thể chất như ngứa/nóng.",
          "Không nhầm với ならない nghĩa 'không được phép / không thành'.",
        ],
        contrast:
          "てならない ≈ cảm xúc tự nhiên không thôi. Gần てたまらない nhưng formal hơn, ít dùng cảm giác cơ thể.",
        examples: [
          ex(
            "息子の将来が心配でならない。",
            "むすこのしょうらいがしんぱいでならない。",
            "Lo tương lai con trai không thôi.",
            [
              ["息子", "むすこ"],
              ["の"],
              ["将来", "しょうらい"],
              ["が"],
              ["心配", "しんぱい"],
              ["でならない。"],
            ],
          ),
          ex(
            "あの時の失敗が悔やまれてならない。",
            "あのときのしっぱいがくやまれてならない。",
            "Cứ hối mãi về thất bại lúc đó.",
            [
              ["あの"],
              ["時", "とき"],
              ["の"],
              ["失敗", "しっぱい"],
              ["が"],
              ["悔や", "くや"],
              ["まれてならない。"],
            ],
          ),
          ex(
            "彼の安否が気になってならない。",
            "かれのあんぴがきになってならない。",
            "Cứ băn khoăn mãi về an nguy của anh ấy.",
            [
              ["彼", "かれ"],
              ["の"],
              ["安否", "あんぴ"],
              ["が"],
              ["気", "き"],
              ["になってならない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜てならない",
        "Câu cảm xúc tự nhiên: 〜てならない — cứ… không thôi.",
        [
          ["Cứ lo mãi về sức khỏe mẹ.", "母の健康が心配でならない。"],
          ["Cứ nhớ mãi lời cô ấy.", "彼女の言葉が思い出されてならない。"],
          ["Cứ xúc động mãi trước cảnh đó.", "その光景に感動してならない。"],
          ["Cứ nghi mãi lời giải thích.", "説明に疑問を感じてならない。"],
          ["Cứ tò mò mãi về kết quả.", "試験の結果が気になってならない。"],
          ["Cứ buồn mãi vì chia tay.", "別れが悲しくてならない。"],
          ["Cứ tiếc mãi cơ hội đã mất.", "逃した機会が惜しまれてならない。"],
          ["Cứ khó chịu mãi với thái độ đó.", "あの態度が腹立たしくてならない。"],
          ["Cứ xúc động mãi khi nghe tin.", "知らせを聞いて胸が熱くてならない。"],
          ["Cứ day dứt mãi vì đã im lặng.", "黙っていたことが悔やまれてならない。"],
        ],
        [
          ["友人の安否が気になってならない。", "Cứ băn khoăn mãi an nguy bạn."],
          ["幼い日々が懐かしくてならない。", "Cứ nhớ thương mãi ngày thơ ấu."],
          ["不公平さが許せなくてならない。", "Cứ không chấp nhận nổi sự bất công."],
          ["彼の成功が誇らしくてならない。", "Cứ tự hào mãi về thành công của anh ấy."],
          ["真相が知りたくてならない。", "Cứ muốn biết sự thật không thôi."],
          ["患者の容体が心配でならない。", "Cứ lo mãi tình trạng bệnh nhân."],
          ["昔の写真を見ると寂しくてならない。", "Nhìn ảnh cũ cứ buồn không thôi."],
          ["自分の発言が後悔されてならない。", "Cứ hối mãi lời mình đã nói."],
          ["被災地の様子が気になってならない。", "Cứ băn khoăn mãi tình hình vùng thiên tai."],
          ["あのメロディーが頭から離れなくてならない。", "Giai điệu đó cứ không rời khỏi đầu."],
        ],
        [
          ["Lo tương lai con không thôi.", ["息子の将来が", "とても心配で", "ならない", "。"], 0],
          ["Hối mãi thất bại hôm đó.", ["あの失敗が", "悔やまれて", "ならない", "。"], 0],
          ["Băn khoăn an nguy anh ấy.", ["彼の安否が", "大変気になって", "ならない", "。"], 0],
          ["Lo sức khỏe mẹ không thôi.", ["母の体調が", "心配で", "ならない", "。"], 0],
          ["Nhớ mãi câu cô ấy nói.", ["彼女の一言が", "思い出されて", "ならない", "。"], 0],
          ["Xúc động mãi trước cảnh ấy.", ["その場面に", "感動して", "ならない", "。"], 0],
          ["Tò mò điểm thi không thôi.", ["合否が", "気になって", "ならない", "。"], 0],
          ["Buồn mãi vì phải chia tay.", ["別れが", "悲しくて", "ならない", "。"], 0],
          ["Tiếc mãi cơ hội đã bỏ.", ["逃したチャンスが", "惜しまれて", "ならない", "。"], 0],
          ["Day dứt vì đã im lặng.", ["沈黙したことが", "悔やまれて", "ならない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l25-g03",
      {
        meaning: "Không thể không… / không nhịn được phải…",
        structures: [
          "Vない ＋ ではいられない",
          "Vず ＋ にはいられない",
        ],
        explanation:
          "ないではいられない／ずにはいられない: cảm xúc/ý thức thôi thúc khiến không thể đứng yên không làm — cười, khóc, giúp, nói…",
        usage: "Kể phản ứng không nhịn được: nghe chuyện buồn thì khóc; thấy khổ thì giúp.",
        cautions: [
          "ずにはいられない gắn Vず (không phải ない); する → せずにはいられない.",
          "Khác nghĩa bắt buộc xã hội của ないわけにはいかない / ざるを得ない.",
        ],
        contrast:
          "ずにはいられない ≈ không nhịn được phải làm. Khác ざるを得ない (bất đắc dĩ vì hoàn cảnh).",
        examples: [
          ex(
            "その話を聞いて笑わずにはいられない。",
            "そのはなしをきいてわらわずにはいられない。",
            "Nghe chuyện đó không nhịn được cười.",
            [
              ["その"],
              ["話", "はなし"],
              ["を"],
              ["聞", "き"],
              ["いて"],
              ["笑", "わら"],
              ["わずにはいられない。"],
            ],
          ),
          ex(
            "困っている人を見ると助けずにはいられない。",
            "こまっているひとをみるとたすけずにはいられない。",
            "Thấy người khó khăn thì không thể không giúp.",
            [
              ["困", "こま"],
              ["っている"],
              ["人", "ひと"],
              ["を"],
              ["見", "み"],
              ["ると"],
              ["助", "たす"],
              ["けずにはいられない。"],
            ],
          ),
          ex(
            "美味しい匂いがして買わないではいられない。",
            "おいしいにおいがしてかわないではいられない。",
            "Mùi ngon khiến không thể không mua.",
            [
              ["美味", "おい"],
              ["しい"],
              ["匂", "にお"],
              ["いがして"],
              ["買", "か"],
              ["わないではいられない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ないではいられない／ずにはいられない",
        "Câu thôi thúc: không thể không… / không nhịn được phải…",
        [
          ["Nghe tin buồn không nhịn được khóc.", "悲しい知らせに泣かずにはいられない。"],
          ["Thấy bất công không thể không nói.", "不正を見ると言わずにはいられない。"],
          ["Nghe nhạc hay không nhịn được hát theo.", "名曲を聴くと口ずさまずにはいられない。"],
          ["Nhìn ảnh cũ không thể không nhớ.", "昔の写真を見ると懐かしまずにはいられない。"],
          ["Thấy trẻ lạc không thể không hỏi.", "迷子を見つけると声をかけずにはいられない。"],
          ["Đọc tin đó không nhịn được tức.", "その記事を読むと怒らずにはいられない。"],
          ["Ngửi mùi cà phê không thể không uống.", "コーヒーの香りに誘われて飲まずにはいられない。"],
          ["Thấy lỗi không thể không sửa.", "誤りを見つけると直さずにはいられない。"],
          ["Nghe lời cảm ơn không nhịn được xúc động.", "お礼の言葉に感動せずにはいられない。"],
          ["Nhìn cảnh đẹp không thể không chụp.", "美しい景色を見ると撮らずにはいられない。"],
        ],
        [
          ["彼の冗談には笑わないではいられない。", "Nghe trò đùa anh ấy không nhịn được cười."],
          ["弱者を放っておけずにはいられない。", "Không thể bỏ mặc người yếu."],
          ["真相を知ると伝えないではいられない。", "Biết sự thật thì không thể không nói."],
          ["猫を見ると触らずにはいられない。", "Thấy mèo thì không nhịn được chạm."],
          ["名作を読むと考え込まずにはいられない。", "Đọc kiệt tác thì không thể không suy nghĩ."],
          ["空腹だと買わないではいられない。", "Đói thì không thể không mua."],
          ["不備を見つけると指摘せずにはいられない。", "Thấy thiếu sót thì không thể không chỉ ra."],
          ["旧友の消息を聞くと連絡せずにはいられない。", "Nghe tin bạn cũ thì không thể không liên lạc."],
          ["この味を知るとまた食べずにはいられない。", "Biết vị này rồi thì không thể không ăn lại."],
          ["正義のために立ち上がらずにはいられない。", "Vì công lý không thể không đứng lên."],
        ],
        [
          ["Nghe chuyện đó phải cười.", ["その話には", "笑わずには", "いられない", "。"], 0],
          ["Thấy khổ thì phải giúp.", ["困っている人を", "助けずには", "いられない", "。"], 0],
          ["Mùi ngon khiến phải mua.", ["香りに誘われて", "買わないでは", "いられない", "。"], 0],
          ["Tin buồn khiến phải khóc.", ["悲しい報せに", "泣かずには", "いられない", "。"], 0],
          ["Bất công khiến phải nói.", ["不正を見て", "言わずには", "いられない", "。"], 0],
          ["Ảnh cũ khiến phải nhớ.", ["昔の写真に", "懐かしまずには", "いられない", "。"], 0],
          ["Tin đó khiến phải giận.", ["記事を読んで", "怒らずには", "いられない", "。"], 0],
          ["Thấy lỗi thì phải sửa.", ["ミスを見つけて", "直さずには", "いられない", "。"], 0],
          ["Cảnh đẹp khiến phải chụp.", ["絶景を前に", "撮らずには", "いられない", "。"], 0],
          ["Được cảm ơn thì xúc động.", ["お礼の言葉に", "感動せずには", "いられない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l25-g04",
      {
        meaning: "Không thể không… / đành phải… (nghĩa vụ xã hội)",
        structures: ["Vない ＋ わけにはいかない", "Vない ＋ わけにいかない"],
        explanation:
          "ないわけに（は）いかない: vì lý do xã hội, bổn phận, lời hứa… nên không thể chọn không làm — đành phải làm.",
        usage: "Từ chối lời mời khó; phải đi họp; phải chăm sóc người thân.",
        cautions: [
          "Nhấn nghĩa vụ/hoàn cảnh xã hội hơn là thôi thúc cảm xúc.",
          "わけにはいかない phổ biến hơn; わけにいかない cũng gặp.",
        ],
        contrast:
          "ないわけにはいかない ≈ không thể không (vì bổn phận). Khác ずにはいられない (không nhịn được) và ざるを得ない (bất đắc dĩ khách quan).",
        examples: [
          ex(
            "上司に頼まれたので断らないわけにはいかない。",
            "じょうしにたのまれたのでことわらないわけにはいかない。",
            "Sếp nhờ nên không thể từ chối.",
            [
              ["上司", "じょうし"],
              ["に"],
              ["頼", "たの"],
              ["まれたので"],
              ["断", "ことわ"],
              ["らないわけにはいかない。"],
            ],
          ),
          ex(
            "約束した以上、行かないわけにはいかない。",
            "やくそくしたいじょう、いかないわけにはいかない。",
            "Đã hứa thì không thể không đi.",
            [
              ["約束", "やくそく"],
              ["した"],
              ["以上", "いじょう"],
              ["、"],
              ["行", "い"],
              ["かないわけにはいかない。"],
            ],
          ),
          ex(
            "親の世話をしないわけにはいかない。",
            "おやのせわをしないわけにはいかない。",
            "Không thể không chăm sóc bố mẹ.",
            [
              ["親", "おや"],
              ["の"],
              ["世話", "せわ"],
              ["をしないわけにはいかない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ないわけに（は）いかない",
        "Câu bổn phận: không thể không… / đành phải…",
        [
          ["Đã nhận việc thì không thể bỏ.", "引き受けた以上、やらないわけにはいかない。"],
          ["Bạn nhờ thì không thể không giúp.", "友人に頼まれて手伝わないわけにはいかない。"],
          ["Là thành viên thì không thể vắng.", "メンバーとして欠席しないわけにはいかない。"],
          ["Đã hẹn bác sĩ thì không thể trễ.", "予約したから遅れないわけにはいかない。"],
          ["Có lỗi thì không thể không xin lỗi.", "自分のミスなので謝らないわけにはいかない。"],
          ["Là trưởng nhóm thì không thể im.", "リーダーとして黙っていないわけにはいかない。"],
          ["Khách đến thì không thể không tiếp.", "客が来たので応対しないわけにはいかない。"],
          ["Luật quy định thì không thể bỏ qua.", "規則なので守らないわけにはいかない。"],
          ["Đã vay thì không thể không trả.", "借りたお金は返さないわけにはいかない。"],
          ["Thầy nhờ thì không thể từ chối.", "先生の頼みを断らないわけにはいかない。"],
        ],
        [
          ["家族の大事な日に行かないわけにはいかない。", "Ngày quan trọng của gia đình không thể không đi."],
          ["証拠がある以上、認めないわけにはいかない。", "Đã có bằng chứng thì không thể không thừa nhận."],
          ["同僚が忙しいので代わらないわけにはいかない。", "Đồng nghiệp bận nên không thể không làm thay."],
          ["招待された以上、出席しないわけにはいかない。", "Đã được mời thì không thể không dự."],
          ["約束の品は渡さないわけにはいかない。", "Đồ đã hứa không thể không giao."],
          ["被害者に説明しないわけにはいかない。", "Không thể không giải thích với nạn nhân."],
          ["税金は払わないわけにはいかない。", "Thuế không thể không nộp."],
          ["子どもの世話をしないわけにはいかない。", "Không thể không chăm sóc con."],
          ["締め切り前に提出しないわけにはいかない。", "Trước hạn không thể không nộp."],
          ["恩がある人を無視しないわけにはいかない。", "Người có ơn không thể bỏ mặc."],
        ],
        [
          ["Sếp nhờ nên khó từ chối.", ["上司の依頼を", "断らないわけには", "いかない", "。"], 0],
          ["Đã hứa thì phải đi.", ["約束したから", "行かないわけには", "いかない", "。"], 0],
          ["Phải chăm sóc bố mẹ.", ["親の面倒を", "見ないわけには", "いかない", "。"], 0],
          ["Nhận việc rồi phải làm.", ["引き受けた仕事は", "やらないわけには", "いかない", "。"], 0],
          ["Bạn nhờ thì phải giúp.", ["友人の頼みを", "断れないわけには", "いかない", "。"], 0],
          ["Thành viên thì khó vắng.", ["部員として", "欠かさないわけには", "いかない", "。"], 0],
          ["Có lỗi thì phải xin lỗi.", ["過失がある以上", "謝らないわけには", "いかない", "。"], 0],
          ["Khách tới thì phải tiếp.", ["来客には", "対応しないわけには", "いかない", "。"], 0],
          ["Vay rồi thì phải trả.", ["借金は", "返さないわけには", "いかない", "。"], 0],
          ["Được mời thì phải dự.", ["招かれた以上", "出席しないわけには", "いかない", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l25-g05",
      {
        meaning: "Đành phải… / không còn cách nào khác ngoài…",
        structures: ["Vない語幹 ＋ ざるを得ない", "する → せざるを得ない"],
        explanation:
          "ざるを得ない: vì hoàn cảnh khách quan/áp lực thực tế, không còn lựa chọn nào khác ngoài việc phải làm — sắc thái bất đắc dĩ, hơi trang trọng.",
        usage: "Tin tức, báo cáo, văn viết: buộc phải hủy, buộc phải thừa nhận, buộc phải thay đổi.",
        cautions: [
          "Dùng thân Vない bỏ ない + ざるを得ない; する đặc biệt thành せざるを得ない.",
          "Thiên bất đắc dĩ khách quan; khác cảm xúc ずにはいられない.",
        ],
        contrast:
          "ざるを得ない ≈ đành phải (không còn cách). Gần ないわけにはいかない nhưng nhấn hoàn cảnh bất khả kháng hơn bổn phận.",
        examples: [
          ex(
            "予算不足で計画を変更せざるを得ない。",
            "よさんぶそくでけいかくをへんこうせざるをえない。",
            "Thiếu ngân sách nên đành phải đổi kế hoạch.",
            [
              ["予算", "よさん"],
              ["不足", "ぶそく"],
              ["で"],
              ["計画", "けいかく"],
              ["を"],
              ["変更", "へんこう"],
              ["せざるを"],
              ["得", "え"],
              ["ない。"],
            ],
          ),
          ex(
            "証拠がない以上、認めざるを得ない。",
            "しょうこがないいじょう、みとめざるをえない。",
            "Không có bằng chứng thì đành phải thừa nhận.",
            [
              ["証拠", "しょうこ"],
              ["がない"],
              ["以上", "いじょう"],
              ["、"],
              ["認", "みと"],
              ["めざるを"],
              ["得", "え"],
              ["ない。"],
            ],
          ),
          ex(
            "体調不良で欠席せざるを得なかった。",
            "たいちょうふりょうでけっせきせざるをえなかった。",
            "Sức khỏe kém nên đành phải vắng mặt.",
            [
              ["体調", "たいちょう"],
              ["不良", "ふりょう"],
              ["で"],
              ["欠席", "けっせき"],
              ["せざるを"],
              ["得", "え"],
              ["なかった。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ざるを得ない",
        "Câu bất đắc dĩ: 〜ざるを得ない — đành phải…",
        [
          ["Mưa to nên đành hủy sự kiện.", "大雨でイベントを中止せざるを得ない。"],
          ["Hết hàng nên đành từ chối đơn.", "在庫切れで注文を断らざるを得ない。"],
          ["Lỗi hệ thống nên đành tạm dừng.", "障害のためサービスを停止せざるを得ない。"],
          ["Thiếu người nên đành tăng ca.", "人手不足で残業せざるを得ない。"],
          ["Giá tăng nên đành tăng giá bán.", "原価高騰で値上げせざるを得ない。"],
          ["Không còn chỗ nên đành chờ chuyến sau.", "満席で次便を待たざるを得ない。"],
          ["Bị phát hiện nên đành thú nhận.", "発覚した以上、告白せざるを得ない。"],
          ["Thời hạn gấp nên đành rút ngắn.", "期限が迫り短縮せざるを得ない。"],
          ["Phản đối nhiều nên đành rút lại.", "反対が多く撤回せざるを得ない。"],
          ["Bệnh nặng nên đành nhập viện.", "症状が重く入院せざるを得ない。"],
        ],
        [
          ["交通渋滞で遅刻せざるを得なかった。", "Kẹt xe nên đành phải đến muộn."],
          ["資金難で事業を縮小せざるを得ない。", "Thiếu vốn nên đành thu hẹp kinh doanh."],
          ["規則違反で処分せざるを得ない。", "Vi phạm quy định nên đành phải xử lý."],
          ["天候不良で離陸を延期せざるを得ない。", "Thời tiết xấu nên đành hoãn cất cánh."],
          ["データ不足で結論を保留せざるを得ない。", "Thiếu dữ liệu nên đành giữ nguyên kết luận."],
          ["契約上、支払わざるを得ない。", "Theo hợp đồng đành phải thanh toán."],
          ["世論の圧力で方針を変えざるを得ない。", "Áp lực dư luận nên đành đổi phương châm."],
          ["故障した車を修理せざるを得なかった。", "Xe hỏng nên đành phải sửa."],
          ["事実を前に認めざるを得ない。", "Trước sự thật đành phải thừa nhận."],
          ["安全のため立ち退かざるを得ない。", "Vì an toàn đành phải sơ tán."],
        ],
        [
          ["Thiếu ngân sách đành đổi kế hoạch.", ["予算不足で", "予定を変更せざるを", "得ない", "。"], 0],
          ["Không chứng cứ đành thừa nhận.", ["証拠がなく", "認めざるを", "得ない", "。"], 0],
          ["Ốm nên đành vắng mặt.", ["体調を崩し", "欠席せざるを", "得なかった", "。"], 0],
          ["Mưa lớn đành hủy sự kiện.", ["豪雨のため", "中止せざるを", "得ない", "。"], 0],
          ["Hết hàng đành từ chối.", ["在庫がなく", "断らざるを", "得ない", "。"], 0],
          ["Lỗi máy đành tạm dừng.", ["障害発生で", "停止せざるを", "得ない", "。"], 0],
          ["Thiếu người đành tăng ca.", ["人手不足で", "残業せざるを", "得ない", "。"], 0],
          ["Kẹt xe đành đến muộn.", ["渋滞で", "遅刻せざるを", "得なかった", "。"], 0],
          ["Thiếu vốn đành thu hẹp.", ["資金難で", "縮小せざるを", "得ない", "。"], 0],
          ["Vì an toàn đành sơ tán.", ["安全のため", "避難せざるを", "得ない", "。"], 0],
        ],
      ),
    ),
  ];
}
