import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L06-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 8, BATCH);

export function lesson08Patterns(byId) {
  return [
    P(
      byId,
      "l08-g01",
      {
        meaning: "Dựa trên… (làm chất liệu / nguồn gốc sáng tạo)",
        structures: ["N ＋ をもとに（して）"],
        explanation:
          "Lấy A làm nguyên liệu, dữ liệu gốc để tạo ra B (phim, bài báo, kế hoạch…).",
        usage: "Giới thiệu tác phẩm, báo cáo: dựa trên…",
        cautions: [
          "Nhấn 'nguồn chất liệu' hơn là căn cứ pháp lý cứng.",
          "Khác に基づいて (căn cứ quy tắc/dữ liệu chính thức).",
        ],
        contrast: "をもとに ≈ dựa trên chất liệu. Khác に基づいて (căn cứ chuẩn).",
        examples: [
          ex(
            "実話をもとに映画を作った。",
            "じつわをもとにえいがをつくった。",
            "Dựa trên chuyện thật đã làm phim.",
            [
              ["実話", "じつわ"],
              ["をもとに"],
              ["映画", "えいが"],
              ["を"],
              ["作", "つく"],
              ["った。"],
            ],
          ),
          ex(
            "アンケート結果をもとに改善策を考えた。",
            "あんけーとけっかをもとにかいぜんさくをかんがえた。",
            "Dựa trên kết quả khảo sát đã nghĩ biện pháp cải thiện.",
            [
              ["アンケート"],
              ["結果", "けっか"],
              ["をもとに"],
              ["改善策", "かいぜんさく"],
              ["を"],
              ["考", "かんが"],
              ["えた。"],
            ],
          ),
          ex(
            "この小説は日記をもとにしている。",
            "このしょうせつはにっきをもとにしている。",
            "Tiểu thuyết này dựa trên nhật ký.",
            [
              ["この"],
              ["小説", "しょうせつ"],
              ["は"],
              ["日記", "にっき"],
              ["をもとにしている。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ をもとに（して）",
        "Câu dùng をもとに để nói dựa trên chất liệu/nguồn gốc để tạo ra điều gì.",
        [
          ["Dựa trên dữ liệu đã viết báo cáo.", "データをもとに報告書を書いた。"],
          ["Dựa trên trải nghiệm bản thân đã viết sách.", "自分の経験をもとに本を書いた。"],
          ["Dựa trên truyền thuyết địa phương làm kịch.", "地元の伝説をもとに芝居を作った。"],
          ["Dựa trên ảnh cũ phục dựng phố.", "古い写真をもとに街並みを復元した。"],
          ["Dựa trên ý kiến khách thiết kế sản phẩm.", "客の意見をもとに製品を設計した。"],
          ["Dựa trên bản thảo này hoàn thiện bài.", "この下書きをもとに原稿を仕上げた。"],
          ["Dựa trên thống kê dự đoán xu hướng.", "統計をもとに傾向を予測した。"],
          ["Dựa trên câu chuyện mẹ kể viết tiểu thuyết.", "母の話をもとに小説を書いた。"],
          ["Dựa trên nghiên cứu đề xuất chính sách.", "研究をもとに政策を提案した。"],
          ["Dựa trên mẫu thử cải tiến máy.", "試作品をもとに機械を改良した。"],
        ],
        [
          ["実話をもとにドラマが作られた。", "Phim truyền hình được làm dựa trên chuyện thật."],
          ["会議の記録をもとに議事録を作成した。", "Tạo biên bản dựa trên ghi chép họp."],
          ["面接の結果をもとに採用を決める。", "Quyết định tuyển dụng dựa trên kết quả phỏng vấn."],
          ["現場の声をもとにマニュアルを改訂した。", "Sửa sổ tay dựa trên tiếng nói hiện trường."],
          ["歴史資料をもとに展示を企画した。", "Lên kế hoạch triển lãm dựa trên tư liệu lịch sử."],
          ["失敗をもとに次の計画を立てた。", "Lập kế hoạch tiếp theo dựa trên thất bại."],
          ["地図をもとに避難ルートを確認した。", "Xác nhận đường sơ tán dựa trên bản đồ."],
          ["顧客データをもとに販促を行う。", "Làm khuyến mãi dựa trên dữ liệu khách."],
          ["昔話をもとに子供向けの絵本を出した。", "Xuất bản sách tranh thiếu nhi dựa trên chuyện cổ."],
          ["実験結果をもとに仮説を修正した。", "Sửa giả thuyết dựa trên kết quả thí nghiệm."],
        ],
        [
          ["Dựa trên chuyện thật làm phim.", ["実話を", "もとに", "映画を", "作った。"], 1],
          ["Dựa trên khảo sát nghĩ biện pháp.", ["結果を", "もとに", "対策を", "考えた。"], 1],
          ["Dựa trên nhật ký viết tiểu thuyết.", ["日記を", "もとに", "小説を", "書いた。"], 1],
          ["Dựa trên dữ liệu viết báo cáo.", ["データを", "もとに", "報告を", "まとめた。"], 1],
          ["Dựa trên trải nghiệm viết sách.", ["経験を", "もとに", "本を", "出版した。"], 1],
          ["Dựa trên ảnh phục dựng phố.", ["写真を", "もとに", "街を", "復元した。"], 1],
          ["Dựa trên ý kiến thiết kế.", ["意見を", "もとに", "製品を", "設計した。"], 1],
          ["Dựa trên thống kê dự đoán.", ["統計を", "もとに", "傾向を", "予測した。"], 1],
          ["Dựa trên nghiên cứu đề xuất.", ["研究を", "もとに", "政策を", "提案した。"], 1],
          ["Dựa trên mẫu thử cải tiến.", ["試作を", "もとに", "機械を", "改良した。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l08-g02",
      {
        meaning: "Dựa vào / căn cứ theo (quy tắc, dữ liệu, luật…)",
        structures: ["N ＋ に基づいて", "N ＋ に基づき", "N ＋ に基づく ＋ N"],
        explanation:
          "Lấy A làm căn cứ chính thức để phán đoán, hành động, xây dựng.",
        usage: "Luật, quy định, nghiên cứu, đánh giá.",
        cautions: [
          "に基づく修飾 N (事実に基づく報道).",
          "Mang sắc thái căn cứ cứng hơn をもとに.",
        ],
        contrast: "に基づいて ≈ căn cứ theo. Khác をもとに (chất liệu sáng tạo).",
        examples: [
          ex(
            "法律に基づいて処分を決める。",
            "ほうりつにもとづいてしょぶんをきめる。",
            "Quyết định xử lý dựa trên luật.",
            [
              ["法律", "ほうりつ"],
              ["に"],
              ["基", "もと"],
              ["づいて"],
              ["処分", "しょぶん"],
              ["を"],
              ["決", "き"],
              ["める。"],
            ],
          ),
          ex(
            "調査結果に基づく報告を提出した。",
            "ちょうさけっかにもとづくほうこくをていしゅつした。",
            "Đã nộp báo cáo dựa trên kết quả điều tra.",
            [
              ["調査", "ちょうさ"],
              ["結果", "けっか"],
              ["に"],
              ["基", "もと"],
              ["づく"],
              ["報告", "ほうこく"],
              ["を"],
              ["提出", "ていしゅつ"],
              ["した。"],
            ],
          ),
          ex(
            "事実に基づいて判断すべきだ。",
            "じじつにもとづいてはんだんすべきだ。",
            "Nên phán đoán dựa trên sự thật.",
            [
              ["事実", "じじつ"],
              ["に"],
              ["基", "もと"],
              ["づいて"],
              ["判断", "はんだん"],
              ["すべきだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ に基づいて／に基づく",
        "Câu dùng に基づいて để nói căn cứ theo luật, dữ liệu, sự thật…",
        [
          ["Quyết định dựa trên quy định công ty.", "社内規定に基づいて決定する。"],
          ["Chấm điểm dựa trên tiêu chí đã công bố.", "公表された基準に基づいて採点する。"],
          ["Xây dựng kế hoạch dựa trên số liệu mới.", "最新の数値に基づいて計画を立てる。"],
          ["Báo cáo dựa trên bằng chứng rõ ràng.", "明確な証拠に基づく報告だ。"],
          ["Xử lý dựa trên hợp đồng.", "契約に基づいて処理する。"],
          ["Đánh giá dựa trên thành tích năm nay.", "今年の実績に基づいて評価する。"],
          ["Sửa lỗi dựa trên phản hồi người dùng.", "利用者の指摘に基づいて修正した。"],
          ["Phán quyết dựa trên lời khai.", "証言に基づいて判決が下された。"],
          ["Thiết kế dựa trên tiêu chuẩn an toàn.", "安全基準に基づいて設計する。"],
          ["Tính thuế dựa trên luật hiện hành.", "現行法に基づいて税額を計算する。"],
        ],
        [
          ["科学的根拠に基づいて説明する。", "Giải thích dựa trên căn cứ khoa học."],
          ["ガイドラインに基づき運用を始めた。", "Bắt đầu vận hành dựa trên hướng dẫn."],
          ["過去の事例に基づく判断だ。", "Là phán đoán dựa trên ví dụ quá khứ."],
          ["憲法に基づいて権利が守られる。", "Quyền được bảo vệ dựa trên hiến pháp."],
          ["統計に基づいて政策を見直す。", "Xem lại chính sách dựa trên thống kê."],
          ["診断に基づいて治療方針を決めた。", "Quyết định hướng điều trị dựa trên chẩn đoán."],
          ["規約に基づき会員資格を取り消した。", "Hủy tư cách hội viên dựa trên điều khoản."],
          ["実験データに基づく結論を発表した。", "Công bố kết luận dựa trên dữ liệu thí nghiệm."],
          ["国際基準に基づいて検査する。", "Kiểm tra dựa trên tiêu chuẩn quốc tế."],
          ["合意に基づいて協力を続ける。", "Tiếp tục hợp tác dựa trên thỏa thuận."],
        ],
        [
          ["Quyết định xử lý dựa trên luật.", ["法律に", "基づいて", "処分を", "決める。"], 1],
          ["Báo cáo dựa trên điều tra.", ["結果に", "基づく", "報告を", "提出した。"], 1],
          ["Phán đoán dựa trên sự thật.", ["事実に", "基づいて", "判断す", "べきだ。"], 1],
          ["Quyết dựa trên quy định.", ["規定に", "基づいて", "決定を", "下す。"], 1],
          ["Chấm dựa trên tiêu chí.", ["基準に", "基づいて", "採点を", "行う。"], 1],
          ["Tiến hành xử lý căn cứ theo hợp đồng.", ["契約に", "基づいて", "処理を", "進める。"], 1],
          ["Đánh giá dựa trên thành tích.", ["実績に", "基づいて", "評価を", "する。"], 1],
          ["Thiết kế dựa trên an toàn.", ["基準に", "基づいて", "設計を", "行う。"], 1],
          ["Giải thích dựa trên khoa học.", ["根拠に", "基づいて", "説明を", "する。"], 1],
          ["Kiểm tra dựa trên chuẩn quốc tế.", ["基準に", "基づいて", "検査を", "実施する。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l08-g03",
      {
        meaning: "Theo / dọc theo (đường, kế hoạch, chính sách…)",
        structures: ["N ＋ に沿って", "N ＋ に沿い"],
        explanation:
          "Đi theo đường/vạch, hoặc hành động phù hợp với kế hoạch, ý muốn, chính sách.",
        usage: "Hướng dẫn đường đi; thực thi theo kế hoạch.",
        cautions: [
          "Nghĩa không gian (dọc sông) và nghĩa trừu tượng (theo chính sách) đều phổ biến.",
        ],
        contrast: "に沿って ≈ theo / dọc theo. Khác に基づいて (căn cứ) và のもとで (dưới…).",
        examples: [
          ex(
            "川に沿って歩くと駅に着く。",
            "かわにそってあるくとえきにつく。",
            "Đi dọc theo sông sẽ đến ga.",
            [
              ["川", "かわ"],
              ["に"],
              ["沿", "そ"],
              ["って"],
              ["歩", "ある"],
              ["くと"],
              ["駅", "えき"],
              ["に"],
              ["着", "つ"],
              ["く。"],
            ],
          ),
          ex(
            "計画に沿って作業を進める。",
            "けいかくにそってさぎょうをすすめる。",
            "Tiến hành công việc theo kế hoạch.",
            [
              ["計画", "けいかく"],
              ["に"],
              ["沿", "そ"],
              ["って"],
              ["作業", "さぎょう"],
              ["を"],
              ["進", "すす"],
              ["める。"],
            ],
          ),
          ex(
            "お客様の希望に沿った商品を用意した。",
            "おきゃくさまのきぼうにそったしょうひんをよういした。",
            "Đã chuẩn bị hàng phù hợp với mong muốn khách.",
            [
              ["お客様", "おきゃくさま"],
              ["の"],
              ["希望", "きぼう"],
              ["に"],
              ["沿", "そ"],
              ["った"],
              ["商品", "しょうひん"],
              ["を"],
              ["用意", "ようい"],
              ["した。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ に沿って／に沿い",
        "Câu dùng に沿って để nói đi dọc theo hoặc hành động theo kế hoạch/ý muốn.",
        [
          ["Đi dọc theo bờ biển rất đẹp.", "海岸に沿って歩くと景色が美しい。"],
          ["Tiến hành theo lịch đã định.", "予定に沿って進行する。"],
          ["Làm theo chính sách công ty.", "会社の方針に沿って行動する。"],
          ["Xây nhà theo thiết kế.", "設計図に沿って家を建てる。"],
          ["Điều chỉnh theo yêu cầu khách.", "客の要望に沿って調整した。"],
          ["Dạy theo giáo trình.", "カリキュラムに沿って教える。"],
          ["Đi dọc theo đường ray đến công viên.", "線路に沿って公園まで行く。"],
          ["Thực hiện theo hướng dẫn an toàn.", "安全指針に沿って実施する。"],
          ["Viết lại theo góp ý biên tập.", "編集方針に沿って書き直した。"],
          ["Phát triển theo chiến lược dài hạn.", "長期戦略に沿って開発する。"],
        ],
        [
          ["川に沿いに桜が並んでいる。", "Hoa anh đào xếp dọc theo sông."],
          ["マニュアルに沿って操作してください。", "Hãy thao tác theo sổ tay."],
          ["政府の方針に沿った改革だ。", "Là cải cách theo phương châm chính phủ."],
          ["海岸線に沿って道路が続いている。", "Đường tiếp nối dọc theo đường bờ biển."],
          ["計画に沿わない変更は認めない。", "Không chấp nhận thay đổi lệch kế hoạch."],
          ["利用規約に沿って対応する。", "Xử lý theo điều khoản sử dụng."],
          ["壁に沿って家具を配置した。", "Bố trí nội thất dọc theo tường."],
          ["教育方針に沿って授業を組み立てる。", "Dựng bài giảng theo phương châm giáo dục."],
          ["川沿いに新しい歩道ができた。", "Có vỉa hè mới dọc sông."],
          ["お客様の意向に沿う形で進めます。", "Tiến hành theo hướng phù hợp ý khách."],
        ],
        [
          ["Đi dọc sông đến ga.", ["川に", "沿って", "歩くと", "着く。"], 1],
          ["Tiến hành theo kế hoạch.", ["計画に", "沿って", "作業を", "進める。"], 1],
          ["Hàng phù hợp mong muốn khách.", ["希望に", "沿った", "商品を", "用意した。"], 1],
          ["Đi dọc biển ngắm cảnh.", ["海岸に", "沿って", "景色を", "楽しむ。"], 1],
          ["Hành động theo phương châm.", ["方針に", "沿って", "行動を", "取る。"], 1],
          ["Xây theo bản thiết kế.", ["設計に", "沿って", "家を", "建てる。"], 1],
          ["Tiến hành bài giảng theo chương trình.", ["課程に", "沿って", "授業を", "進める。"], 1],
          ["Thao tác theo sổ tay.", ["手順に", "沿って", "操作を", "行う。"], 1],
          ["Bố trí dọc theo tường.", ["壁に", "沿って", "家具を", "置く。"], 1],
          ["Phát triển theo chiến lược.", ["戦略に", "沿って", "開発を", "進める。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l08-g04",
      {
        meaning: "Dưới… / nhờ… (điều kiện, sự bảo hộ, ảnh hưởng)",
        structures: ["N ＋ のもとで", "N ＋ のもとに"],
        explanation:
          "もとで nhấn môi trường/điều kiện hành động; もとに nhấn 'nhờ vào / dưới sự…'.",
        usage: "Dưới sự hướng dẫn, dưới chế độ, nhờ sự hỗ trợ.",
        cautions: [
          "のもとで / のもとに gần nhau; chọn theo collocation quen thuộc.",
          "Khác をもとに (chất liệu sáng tạo).",
        ],
        contrast: "のもとで／もとに ≈ dưới / nhờ. Khác をもとに (dựa trên chất liệu).",
        examples: [
          ex(
            "先生の指導のもとで研究を続けた。",
            "せんせいのしどうのもとでけんきゅうをつづけた。",
            "Tiếp tục nghiên cứu dưới sự hướng dẫn của thầy.",
            [
              ["先生", "せんせい"],
              ["の"],
              ["指導", "しどう"],
              ["のもとで"],
              ["研究", "けんきゅう"],
              ["を"],
              ["続", "つづ"],
              ["けた。"],
            ],
          ),
          ex(
            "新しい制度のもとに運営が始まった。",
            "あたらしいせいどのもとにうんえいがはじまった。",
            "Vận hành bắt đầu dưới chế độ mới.",
            [
              ["新", "あたら"],
              ["しい"],
              ["制度", "せいど"],
              ["のもとに"],
              ["運営", "うんえい"],
              ["が"],
              ["始", "はじ"],
              ["まった。"],
            ],
          ),
          ex(
            "平和のもとで子供たちが育つ。",
            "へいわのもとでこどもたちがそだつ。",
            "Trẻ em lớn lên trong hòa bình.",
            [
              ["平和", "へいわ"],
              ["のもとで"],
              ["子供", "こども"],
              ["たちが"],
              ["育", "そだ"],
              ["つ。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ のもとで／のもとに",
        "Câu dùng のもとで／のもとに để nói dưới điều kiện/sự hướng dẫn hoặc nhờ vào.",
        [
          ["Làm việc dưới sự giám sát chặt.", "厳しい監督のもとで作業する。"],
          ["Dự án tiến triển dưới sự hợp tác quốc tế.", "国際協力のもとで事業が進む。"],
          ["Họ tập luyện dưới sự chỉ đạo của HLV.", "監督の指導のもとで練習している。"],
          ["Công bố dưới sự đồng ý của gia đình.", "家族の同意のもとに公表した。"],
          ["Sống dưới áp lực cạnh tranh.", "競争の圧力のもとで生きている。"],
          ["Thí nghiệm dưới điều kiện kiểm soát.", "管理された条件のもとで実験する。"],
          ["Tổ chức dưới sự bảo trợ của thành phố.", "市の後援のもとに開催する。"],
          ["Học dưới sự hỗ trợ của học bổng.", "奨学金の支援のもとで学んでいる。"],
          ["Ra quyết định dưới trách nhiệm của giám đốc.", "社長の責任のもとに決定する。"],
          ["Trẻ chơi dưới sự trông coi của phụ huynh.", "保護者の見守りのもとで遊ぶ。"],
        ],
        [
          ["民主的な環境のもとで議論が進んだ。", "Thảo luận tiến triển trong môi trường dân chủ."],
          ["専門家の助言のもとに方針を変えた。", "Đổi phương châm nhờ lời khuyên chuyên gia."],
          ["夜間照明のもとで工事が続いた。", "Thi công tiếp dưới ánh đèn ban đêm."],
          ["新しい規則のもとで運用を開始した。", "Bắt đầu vận hành dưới quy tắc mới."],
          ["医師の監督のもとでリハビリを行う。", "Phục hồi chức năng dưới sự giám sát bác sĩ."],
          ["契約条件のもとに取引を続ける。", "Tiếp tục giao dịch dưới điều kiện hợp đồng."],
          ["厳しい暑さのもとでも訓練を欠かさない。", "Dù dưới nắng gay gắt vẫn không bỏ tập."],
          ["国連の枠組みのもとに協力した。", "Hợp tác trong khuôn khổ Liên Hợp Quốc."],
          ["親の保護のもとで安心している。", "Yên tâm dưới sự bảo vệ của cha mẹ."],
          ["公正な審査のもとで受賞者が決まった。", "Người đoạt giải được chọn dưới thẩm định công bằng."],
        ],
        [
          ["Nghiên cứu dưới hướng dẫn thầy.", ["指導の", "もとで", "研究を", "続けた。"], 1],
          ["Vận hành dưới chế độ mới.", ["制度の", "もとに", "運営が", "始まった。"], 1],
          ["Trẻ lớn trong hòa bình.", ["平和の", "もとで", "子供が", "育つ。"], 1],
          ["Làm việc dưới giám sát chặt.", ["監督の", "もとで", "作業を", "行う。"], 1],
          ["Công bố nhờ đồng ý gia đình.", ["同意の", "もとに", "公表を", "した。"], 1],
          ["Tổ chức dưới bảo trợ thành phố.", ["後援の", "もとに", "開催を", "決めた。"], 1],
          ["Học nhờ hỗ trợ học bổng.", ["支援の", "もとで", "学業を", "続ける。"], 1],
          ["Quyết định dưới trách nhiệm giám đốc.", ["責任の", "もとに", "決定を", "下す。"], 1],
          ["Phục hồi dưới giám sát bác sĩ.", ["監督の", "もとで", "訓練を", "行う。"], 1],
          ["Thảo luận trong môi trường dân chủ.", ["環境の", "もとで", "議論が", "進む。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l08-g05",
      {
        meaning: "Dành cho… / hướng tới đối tượng…",
        structures: ["N ＋ 向けだ", "N ＋ 向けの ＋ N", "N ＋ 向け"],
        explanation:
          "Nêu đối tượng mục tiêu của sản phẩm, dịch vụ, nội dung.",
        usage: "Quảng cáo, mô tả sản phẩm: dành cho người mới, dành cho trẻ em…",
        cautions: [
          "Khác に向けて (hướng tới mục tiêu/thời điểm hành động).",
          "向けの thường đứng trước danh từ.",
        ],
        contrast: "向けだ ≈ dành cho. Khác に向けて (hướng tới mục tiêu hành động).",
        examples: [
          ex(
            "これは初心者向けの教科書だ。",
            "これはしょしんしゃむけのきょうかしょだ。",
            "Đây là giáo trình dành cho người mới.",
            [
              ["これは"],
              ["初心者", "しょしんしゃ"],
              ["向けの"],
              ["教科書", "きょうかしょ"],
              ["だ。"],
            ],
          ),
          ex(
            "外国人向けに説明を簡略化した。",
            "がいこくじんむけにせつめいをかんりゃくかした。",
            "Đã đơn giản hóa giải thích cho người nước ngoài.",
            [
              ["外国人", "がいこくじん"],
              ["向けに"],
              ["説明", "せつめい"],
              ["を"],
              ["簡略化", "かんりゃくか"],
              ["した。"],
            ],
          ),
          ex(
            "子供向け番組が増えている。",
            "こどもむけばんぐみがふえている。",
            "Chương trình dành cho trẻ em đang tăng.",
            [
              ["子供", "こども"],
              ["向け"],
              ["番組", "ばんぐみ"],
              ["が"],
              ["増", "ふ"],
              ["えている。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ 向けだ／向けの",
        "Câu dùng 向け để nói sản phẩm/nội dung dành cho đối tượng nào.",
        [
          ["Đây là app dành cho người cao tuổi.", "これは高齢者向けのアプリだ。"],
          ["Họ phát triển sản phẩm dành cho phụ nữ.", "女性向けの商品を開発した。"],
          ["Có tour dành cho gia đình.", "家族向けのツアーがある。"],
          ["Sách này dành cho kỳ thi N2.", "この本はN2受験者向けだ。"],
          ["Dịch vụ dành cho doanh nghiệp nhỏ.", "中小企業向けのサービスだ。"],
          ["Thiết kế giao diện dành cho điện thoại.", "スマホ向けに画面を設計した。"],
          ["Khóa học dành cho người đi làm.", "社会人向けの講座を開く。"],
          ["Thực đơn dành cho người ăn chay.", "菜食主義者向けのメニューもある。"],
          ["Quảng cáo dành cho thanh thiếu niên.", "若者向けに広告を出す。"],
          ["Phần mềm dành cho trường học.", "学校向けのソフトを導入した。"],
        ],
        [
          ["初心者向けに説明を丁寧にした。", "Giải thích kỹ vì dành cho người mới."],
          ["海外向けに英語版を用意した。", "Chuẩn bị bản tiếng Anh cho thị trường nước ngoài."],
          ["子供向けだから漢字に振り仮名がある。", "Vì dành cho trẻ nên chữ Hán có furigana."],
          ["ビジネス向けの機能が充実している。", "Chức năng dành cho doanh nghiệp khá đầy đủ."],
          ["観光客向けの案内所が増えた。", "Quầy hướng dẫn dành cho khách du lịch tăng."],
          ["受験生向けの模試を実施する。", "Tổ chức thi thử dành cho thí sinh."],
          ["高齢者向けに文字を大きくした。", "Phóng to chữ cho người cao tuổi."],
          ["学生向けの割引がある。", "Có giảm giá dành cho học sinh/sinh viên."],
          ["家庭向けに使い方を簡単にした。", "Đơn giản hóa cách dùng cho hộ gia đình."],
          ["専門家向けの詳細データを公開した。", "Công bố dữ liệu chi tiết dành cho chuyên gia."],
        ],
        [
          ["Giáo trình dành cho người mới.", ["初心者", "向けの", "教科書", "だ。"], 1],
          ["Giải thích cho người nước ngoài.", ["外国人", "向けに", "説明を", "簡略化した。"], 1],
          ["Chương trình dành cho trẻ.", ["子供", "向けの", "番組が", "増えた。"], 1],
          ["App dành cho người cao tuổi.", ["高齢者", "向けの", "アプリ", "だ。"], 1],
          ["Sản phẩm dành cho phụ nữ.", ["女性", "向けの", "商品を", "出す。"], 1],
          ["Tour dành cho gia đình.", ["家族", "向けの", "旅行が", "ある。"], 1],
          ["Khóa dành cho người đi làm.", ["社会人", "向けの", "講座を", "開く。"], 1],
          ["Quảng cáo cho thanh niên.", ["若者", "向けに", "広告を", "出す。"], 1],
          ["Giảm giá dành cho học sinh.", ["学生", "向けの", "割引が", "ある。"], 1],
          ["Phần mềm dành cho trường.", ["学校", "向けの", "ソフトを", "入れる。"], 1],
        ],
      ),
    ),
  ];
}
