import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L21-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 26, BATCH);

export function lesson26Patterns(byId) {
  return [
    P(
      byId,
      "l26-g01",
      {
        meaning: "Thật sự muốn… / ước gì… / mong người khác… (ước nguyện mạnh)",
        structures: [
          "Vます語幹 ＋ たいものだ",
          "Vて ＋ ほしいものだ",
        ],
        explanation:
          "たいものだ／てほしいものだ nhấn mong muốn sâu, ước nguyện hoặc hy vọng chân thành — mạnh hơn たい／てほしい thông thường, thường mang sắc thái cảm thán.",
        usage: "Bày tỏ ước muốn cá nhân hoặc mong người khác hành động: ước được…; mong ai đó… giúp.",
        cautions: [
          "たいものだ nói mong muốn của chính mình; てほしいものだ mong người khác làm.",
          "Không dùng như mệnh lệnh trực tiếp; mang tính ước nguyện/cảm thán hơn yêu cầu cụ thể.",
        ],
        contrast:
          "たいものだ ≈ thật muốn/ước gì. Khác たい (mong muốn thường) và てほしい (mong người khác, ít cảm thán hơn).",
        examples: [
          ex(
            "一度は海外で暮らしてみたいものだ。",
            "いちどはかいがいでくらしてみたいものだ。",
            "Ước được sống thử ở nước ngoài một lần.",
            [
              ["一度", "いちど"],
              ["は"],
              ["海外", "かいがい"],
              ["で"],
              ["暮", "く"],
              ["らしてみたいものだ。"],
            ],
          ),
          ex(
            "若い人にもっと本を読んでほしいものだ。",
            "わかいひとにもっとほんをよんでほしいものだ。",
            "Mong giới trẻ đọc sách nhiều hơn.",
            [
              ["若", "わか"],
              ["い"],
              ["人", "ひと"],
              ["にもっと"],
              ["本", "ほん"],
              ["を"],
              ["読", "よ"],
              ["んでほしいものだ。"],
            ],
          ),
          ex(
            "静かな場所でゆっくり休みたいものだ。",
            "しずかなばしょでゆっくりやすみたいものだ。",
            "Ước được nghỉ ngơi thong thả ở nơi yên tĩnh.",
            [
              ["静", "しず"],
              ["かな"],
              ["場所", "ばしょ"],
              ["でゆっくり"],
              ["休", "やす"],
              ["みたいものだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜たいものだ／てほしいものだ",
        "Câu ước nguyện: 〜たいものだ／てほしいものだ — thật muốn / mong…",
        [
          ["Ước được gặp lại thầy cũ.", "昔の先生にもう一度会いたいものだ。"],
          ["Mong mọi người giữ lời hứa.", "皆に約束を守ってほしいものだ。"],
          ["Ước được đi du lịch không lo nghĩ.", "何も気にせず旅行したいものだ。"],
          ["Mong con cái khỏe mạnh.", "子供には元気でいてほしいものだ。"],
          ["Ước được nghe ý kiến chân thành.", "率直な意見を聞きたいものだ。"],
          ["Mong sếp lắng nghe nhân viên.", "上司には部下の声を聞いてほしいものだ。"],
          ["Ước được sống gần thiên nhiên.", "自然の近くで暮らしたいものだ。"],
          ["Mong thế hệ sau quý trọng hòa bình.", "次の世代に平和を大切にしてほしいものだ。"],
          ["Ước được thử sức với nghề mới.", "新しい仕事に挑戦したいものだ。"],
          ["Mong khách du lịch tôn trọng văn hóa địa phương.", "観光客には現地の文化を尊重してほしいものだ。"],
        ],
        [
          ["一生に一度は富士山に登りたいものだ。", "Ước được leo Phú Sĩ một lần trong đời."],
          ["政治家には正直であってほしいものだ。", "Mong chính trị gia trung thực."],
          ["週末は家族と過ごしたいものだ。", "Ước được dành cuối tuần với gia đình."],
          ["若者には夢を追い続けてほしいものだ。", "Mong thanh niên tiếp tục theo đuổi ước mơ."],
          ["静かな朝にコーヒーを味わいたいものだ。", "Ước được thưởng thức cà phê vào buổi sáng yên tĩnh."],
          ["隣人にはもう少し静かにしてほしいものだ。", "Mong hàng xóm yên lặng hơn một chút."],
          ["定年後は趣味に打ち込みたいものだ。", "Ước sau nghỉ hưu được dồn sức vào sở thích."],
          ["生徒には自分の頭で考えてほしいものだ。", "Mong học sinh tự suy nghĩ bằng đầu mình."],
          ["いつか自分の店を持ちたいものだ。", "Ước có ngày mở được cửa hàng riêng."],
          ["社会には弱者に優しい制度であってほしいものだ。", "Mong xã hội có chế độ tử tế với người yếu."],
        ],
        [
          ["Ước sống thử ở nước ngoài.", ["海外で一度は", "暮らしてみたい", "もの", "だ。"], 0],
          ["Mong giới trẻ đọc nhiều hơn.", ["若い人にもっと", "本を読んでほしい", "もの", "だ。"], 0],
          ["Ước nghỉ nơi yên tĩnh.", ["静かな場所で", "休みたい", "もの", "だ。"], 0],
          ["Ước gặp lại thầy cũ.", ["昔の恩師に", "会いたい", "もの", "だ。"], 0],
          ["Mong mọi người giữ lời.", ["皆に約束を", "守ってほしい", "もの", "だ。"], 0],
          ["Ước nghe ý kiến thẳng.", ["率直な声を", "聞きたい", "もの", "だ。"], 0],
          ["Mong sếp nghe nhân viên.", ["上司に部下の声を", "聞いてほしい", "もの", "だ。"], 0],
          ["Ước sống gần thiên nhiên.", ["自然のそばで", "暮らしたい", "もの", "だ。"], 0],
          ["Ước leo Phú Sĩ một lần.", ["富士山に一度は", "登りたい", "もの", "だ。"], 0],
          ["Mong chính trị gia trung thực.", ["政治家には正直で", "あってほしい", "もの", "だ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l26-g02",
      {
        meaning: "Đã từng… (hoài niệm) / lẽ ra nên… (lý tưởng)",
        structures: [
          "Vた ＋ ものだ",
          "普通形 ＋ ものだ（理想・あるべき姿）",
        ],
        explanation:
          "ものだ ở bài này chủ yếu: (1) nhớ lại thói quen/cảnh cũ với cảm xúc (たものだ); (2) nêu lý tưởng/điều đáng có — ‘lẽ ra phải…’, mang sắc cảm thán nhẹ.",
        usage: "Kể kỷ niệm: hồi đó hay…; nêu chuẩn mực lý tưởng: vốn phải… / đáng lẽ…",
        cautions: [
          "Nghĩa hoài niệm thường đi với Vたものだ và ngữ cảnh quá khứ.",
          "Khác ものだ bài 23 (bản chất/lẽ thường chung) và nghĩa khuyên bảo ở bài khác — ở đây nhấn nhớ thương hoặc lý tưởng.",
        ],
        contrast:
          "ものだ (bài 26) ≈ hoài niệm / lý tưởng. Khác たいものだ (ước muốn mạnh) và ものだ bản chất chung (bài 23).",
        examples: [
          ex(
            "子供の頃は川で魚を捕ったものだ。",
            "こどものころはかわでさかなをとったものだ。",
            "Hồi nhỏ tôi từng bắt cá ở sông.",
            [
              ["子供", "こども"],
              ["の"],
              ["頃", "ころ"],
              ["は"],
              ["川", "かわ"],
              ["で"],
              ["魚", "さかな"],
              ["を"],
              ["捕", "と"],
              ["ったものだ。"],
            ],
          ),
          ex(
            "教師というものは生徒の模範となるものだ。",
            "きょうしというものはせいとのもはんとなるものだ。",
            "Người thầy lẽ ra phải là gương mẫu cho học sinh.",
            [
              ["教師", "きょうし"],
              ["というものは"],
              ["生徒", "せいと"],
              ["の"],
              ["模範", "もはん"],
              ["となるものだ。"],
            ],
          ),
          ex(
            "冬の夜は囲炉裏を囲んで話したものだ。",
            "ふゆのよるはいろりをかこんではなしたものだ。",
            "Đêm đông từng ngồi quanh bếp lửa trò chuyện.",
            [
              ["冬", "ふゆ"],
              ["の"],
              ["夜", "よる"],
              ["は"],
              ["囲炉裏", "いろり"],
              ["を"],
              ["囲", "かこ"],
              ["んで"],
              ["話", "はな"],
              ["したものだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ものだ（回想・理想）",
        "Câu hoài niệm/lý tưởng: たものだ／ものだ — từng… / lẽ ra nên…",
        [
          ["Hồi học từng đạp xe đến trường.", "学生時代は自転車で通学したものだ。"],
          ["Lãnh đạo lẽ ra phải chịu trách nhiệm.", "指導者は責任を取るものだ。"],
          ["Hồi bé từng nghe bà kể chuyện.", "幼い頃は祖母の昔話を聞いたものだ。"],
          ["Bạn bè lẽ ra phải giúp lúc khó.", "友人は困った時に支え合うものだ。"],
          ["Hồi đó từng chạy trên cánh đồng.", "あの頃は野原を駆け回ったものだ。"],
          ["Lời hứa lẽ ra phải được giữ.", "約束は必ず果たすものだ。"],
          ["Hồi trẻ từng viết nhật ký mỗi đêm.", "若い日々は毎晩日記を書いたものだ。"],
          ["Người lớn lẽ ra phải bảo vệ trẻ em.", "大人は子供を守るものだ。"],
          ["Hồi quê từng hái trái trên đồi.", "田舎では丘で果実を摘んだものだ。"],
          ["Công chức lẽ ra phải trung thực.", "公務員は公正であるものだ。"],
        ],
        [
          ["夏休みは海辺で泳いだものだ。", "Hè từng bơi ở bờ biển."],
          ["親は子の成長を見守るものだ。", "Cha mẹ lẽ ra phải dõi theo sự lớn lên của con."],
          ["祭りでは夜遅くまで踊ったものだ。", "Ngày hội từng nhảy múa đến khuya."],
          ["医者は命を最優先するものだ。", "Bác sĩ lẽ ra phải ưu tiên mạng sống trước hết."],
          ["雨の日は図書館で過ごしたものだ。", "Ngày mưa từng dành thời gian ở thư viện."],
          ["報道は事実に基づくものだ。", "Báo chí lẽ ra phải dựa trên sự thật."],
          ["祖父は庭の野菜を育てたものだ。", "Ông từng trồng rau trong vườn."],
          ["選手は最後まで諦めないものだ。", "Vận động viên lẽ ra không bỏ cuộc đến cùng."],
          ["正月は親戚が集まったものだ。", "Tết từng có họ hàng tụ họp."],
          ["教師は一人ひとりを大切にするものだ。", "Giáo viên lẽ ra phải trân trọng từng học sinh."],
        ],
        [
          ["Hồi nhỏ từng bắt cá sông.", ["子供の頃は川で", "魚を捕った", "もの", "だ。"], 0],
          ["Thầy lẽ ra là gương mẫu.", ["教師は生徒の", "模範となる", "もの", "だ。"], 0],
          ["Đêm đông từng ngồi quanh lửa.", ["冬の夜は囲炉裏を", "囲んで話した", "もの", "だ。"], 0],
          ["Hồi học từng đạp xe đi học.", ["学生時代は自転車で", "通学した", "もの", "だ。"], 0],
          ["Lãnh đạo lẽ ra chịu trách nhiệm.", ["指導者は責任を", "取る", "もの", "だ。"], 0],
          ["Hồi bé từng nghe bà kể.", ["幼い頃は祖母の", "話を聞いた", "もの", "だ。"], 0],
          ["Bạn lẽ ra giúp lúc khó.", ["友人は困った時に", "支え合う", "もの", "だ。"], 0],
          ["Hè từng bơi ngoài biển.", ["夏休みは海で", "泳いだ", "もの", "だ。"], 0],
          ["Cha mẹ lẽ ra dõi con lớn.", ["親は子の成長を", "見守る", "もの", "だ。"], 0],
          ["Ngày mưa từng ở thư viện.", ["雨の日は図書館で", "過ごした", "もの", "だ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l26-g03",
      {
        meaning: "Không lẽ không… sao? / liệu có cách nào… không?",
        structures: [
          "Vない ＋ ものか",
          "Vない ＋ ものだろうか",
        ],
        explanation:
          "ないもの（だろう）か bày tỏ mong muốn tìm cách làm được điều khó, hoặc nghi vấn cảm thán: không thể nào… sao? — thường mang hy vọng hoặc bất mãn nhẹ.",
        usage: "Ước tìm giải pháp: không lẽ không cứu được sao?; liệu không thể cải thiện sao?",
        cautions: [
          "ものか／ものだろうか ở đây gắn Vない; sắc thái khác ものか phủ định mạnh kiểu ‘đâu có…’.",
          "ものだろうか hơi mềm/văn viết hơn ものか.",
        ],
        contrast:
          "ないものか ≈ không lẽ không… được sao. Khác たいものだ (ước muốn trực tiếp) và だろうか nghi vấn thuần túy.",
        examples: [
          ex(
            "何とか彼を助けられないものだろうか。",
            "なんとかかれをたすけられないものだろうか。",
            "Không lẽ không có cách nào giúp anh ấy sao?",
            [
              ["何", "なん"],
              ["とか"],
              ["彼", "かれ"],
              ["を"],
              ["助", "たす"],
              ["けられないものだろうか。"],
            ],
          ),
          ex(
            "もう少し安くできないものか。",
            "もうすこしやすくできないものか。",
            "Không lẽ không thể rẻ hơn một chút sao?",
            [
              ["もう"],
              ["少", "すこ"],
              ["し"],
              ["安", "やす"],
              ["くできないものか。"],
            ],
          ),
          ex(
            "この問題を解決できないものだろうか。",
            "このもんだいをかいけつできないものだろうか。",
            "Liệu không thể giải quyết vấn đề này sao?",
            [
              ["この"],
              ["問題", "もんだい"],
              ["を"],
              ["解決", "かいけつ"],
              ["できないものだろうか。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ないもの（だろう）か",
        "Câu mong cách làm: 〜ないものか／ものだろうか — không lẽ không… sao?",
        [
          ["Không lẽ không thể hòa giải sao?", "何とか仲直りできないものか。"],
          ["Liệu không thể rút ngắn thời gian sao?", "もう少し時間を短縮できないものだろうか。"],
          ["Không lẽ không cứu được bệnh nhân sao?", "患者を救えないものだろうか。"],
          ["Không thể cải thiện dịch vụ sao?", "サービスを改善できないものか。"],
          ["Liệu không thể tránh xung đột sao?", "衝突を避けられないものだろうか。"],
          ["Không lẽ không thuyết phục được sao?", "彼を説得できないものか。"],
          ["Liệu không thể giảm chi phí sao?", "コストを抑えられないものだろうか。"],
          ["Không thể tìm lại tài liệu sao?", "書類を見つけられないものか。"],
          ["Liệu không thể đổi lịch sao?", "日程を変更できないものだろうか。"],
          ["Không lẽ không bảo vệ môi trường sao?", "環境を守れないものだろうか。"],
        ],
        [
          ["何とか間に合わせられないものか。", "Không lẽ không kịp giờ sao?"],
          ["被害を最小限にできないものだろうか。", "Liệu không thể giảm thiệt hại tối thiểu sao?"],
          ["もっと分かりやすく説明できないものか。", "Không thể giải thích dễ hiểu hơn sao?"],
          ["両者の意見をまとめられないものだろうか。", "Liệu không thể gom ý kiến hai bên sao?"],
          ["この機械を修理できないものか。", "Không lẽ không sửa được máy này sao?"],
          ["無駄を省けないものだろうか。", "Liệu không thể cắt bỏ lãng phí sao?"],
          ["子供たちに希望を与えられないものか。", "Không thể trao hy vọng cho trẻ em sao?"],
          ["交通事故を減らせないものだろうか。", "Liệu không thể giảm tai nạn giao thông sao?"],
          ["もっと早く知らせられないものか。", "Không lẽ không báo sớm hơn sao?"],
          ["公正な判断が下せないものだろうか。", "Liệu không thể đưa ra phán đoán công bằng sao?"],
        ],
        [
          ["Không lẽ không giúp được anh ấy?", ["何とか彼を", "助けられない", "ものだろう", "か。"], 0],
          ["Không thể rẻ hơn chút sao?", ["もう少し安く", "できない", "もの", "か。"], 0],
          ["Liệu không giải quyết được sao?", ["この問題を", "解決できない", "ものだろう", "か。"], 0],
          ["Không lẽ không hòa giải được?", ["仲直りできない", "もの", "か", "。"], 0],
          ["Liệu không rút ngắn được giờ?", ["時間を短縮できない", "ものだろう", "か", "。"], 0],
          ["Không cải thiện dịch vụ sao?", ["サービスを", "改善できない", "もの", "か。"], 0],
          ["Không thuyết phục được sao?", ["彼を説得できない", "もの", "か", "。"], 0],
          ["Liệu không giảm chi phí sao?", ["費用を抑えられない", "ものだろう", "か", "。"], 0],
          ["Không lẽ không kịp giờ sao?", ["間に合わせられない", "もの", "か", "。"], 0],
          ["Liệu không giảm thiệt hại sao?", ["被害を抑えられない", "ものだろう", "か", "。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l26-g04",
      {
        meaning: "Có điều gì đó… / mang cảm giác… (đánh giá cảm xúc)",
        structures: [
          "普通形 ＋ ものがある",
          "いAい ＋ ものがある",
          "なAな ＋ ものがある",
        ],
        explanation:
          "ものがある nêu cảm nhận chủ quan: trong sự việc/đối tượng có yếu tố khiến ta thấy cảm động, khó chịu, đáng nể… — đánh giá tinh tế hơn nhận xét phẳng.",
        usage: "Viết luận, nhận xét: có gì đó cảm động; có điểm đáng suy nghĩ; có vẻ khiên cưỡng.",
        cautions: [
          "Thường đi với tính từ/động từ mang sắc thái đánh giá (感心・不満・不可解…).",
          "Khác ものだ cảm thán chung; ものがある nhấn ‘có yếu tố/cảm giác ấy’.",
        ],
        contrast:
          "ものがある ≈ có điều gì đó khiến thấy…. Khác ものだ (hoài niệm/lý tưởng) và ことがある (có khi…).",
        examples: [
          ex(
            "彼の生き方には感心するものがある。",
            "かれのいきかたにはかんしんするものがある。",
            "Cách sống của anh ấy có điều gì đó đáng khâm phục.",
            [
              ["彼", "かれ"],
              ["の"],
              ["生", "い"],
              ["き"],
              ["方", "かた"],
              ["には"],
              ["感心", "かんしん"],
              ["するものがある。"],
            ],
          ),
          ex(
            "その説明には納得できないものがある。",
            "そのせつめいにはなっとくできないものがある。",
            "Lời giải thích đó có điều gì khiến khó chấp nhận.",
            [
              ["その"],
              ["説明", "せつめい"],
              ["には"],
              ["納得", "なっとく"],
              ["できないものがある。"],
            ],
          ),
          ex(
            "この小説には心を打つものがある。",
            "このしょうせつにはこころをうつものがある。",
            "Cuốn tiểu thuyết này có điều gì đụng đến lòng người.",
            [
              ["この"],
              ["小説", "しょうせつ"],
              ["には"],
              ["心", "こころ"],
              ["を"],
              ["打", "う"],
              ["つものがある。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ものがある",
        "Câu cảm nhận: 〜ものがある — có điều gì đó…",
        [
          ["Bài phát biểu có điều cảm động.", "彼のスピーチには感動するものがある。"],
          ["Kế hoạch có điểm đáng nghi.", "その計画には疑わしいものがある。"],
          ["Tranh có vẻ sâu sắc.", "この絵には深いものがある。"],
          ["Thái độ đó có điều khó chịu.", "あの態度には不快なものがある。"],
          ["Câu chuyện có sức thuyết phục.", "話には説得力のあるものがある。"],
          ["Quyết định có vẻ vội vàng.", "その決定には性急なものがある。"],
          ["Ánh mắt có điều day dứt.", "彼の目には悔しそうなものがある。"],
          ["Báo cáo có điểm thiếu sót.", "報告書には不十分なものがある。"],
          ["Giai điệu có vẻ nhớ thương.", "その旋律には懐かしいものがある。"],
          ["Chính sách có điều bất công.", "政策には不公平なものがある。"],
        ],
        [
          ["彼女の努力には見習うべきものがある。", "Nỗ lực của cô ấy có điều đáng học hỏi."],
          ["その意見には一理あるものがある。", "Ý kiến đó có phần hợp lý."],
          ["この写真には悲しいものがある。", "Bức ảnh này có vẻ buồn."],
          ["上司の言葉には配慮が足りないものがある。", "Lời sếp có điều thiếu tế nhị."],
          ["作品には独創性を感じるものがある。", "Tác phẩm có điều gì mang tính độc đáo."],
          ["説明には曖昧なものがある。", "Lời giải thích có vẻ mơ hồ."],
          ["彼の提案には魅力的なものがある。", "Đề xuất của anh ấy có sức hấp dẫn."],
          ["現状には改善すべきものがある。", "Hiện trạng còn chỗ cần cải thiện."],
          ["その光景には息をのむものがある。", "Cảnh đó có điều khiến nín thở."],
          ["批判には耳を傾けるべきものがある。", "Lời phê bình có điều đáng lắng nghe."],
        ],
        [
          ["Cách sống anh ấy đáng khâm phục.", ["彼の生き方には", "感心する", "ものが", "ある。"], 0],
          ["Giải thích khó chấp nhận.", ["その説明には", "納得できない", "ものが", "ある。"], 0],
          ["Tiểu thuyết đụng đến lòng.", ["この小説には", "心を打つ", "ものが", "ある。"], 0],
          ["Phát biểu có phần cảm động.", ["スピーチには", "感動する", "ものが", "ある。"], 0],
          ["Kế hoạch kia đáng nghi ngờ.", ["計画には", "疑わしい", "ものが", "ある。"], 0],
          ["Thái độ có vẻ khó chịu.", ["態度には", "不快な", "ものが", "ある。"], 0],
          ["Quyết định có vẻ vội.", ["決定には", "性急な", "ものが", "ある。"], 0],
          ["Nỗ lực cô ấy đáng học.", ["努力には", "見習うべき", "ものが", "ある。"], 0],
          ["Ý kiến có phần hợp lý.", ["意見には", "一理ある", "ものが", "ある。"], 0],
          ["Tác phẩm mang tính độc đáo.", ["作品には", "独創性を感じる", "ものが", "ある。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l26-g05",
      {
        meaning: "Thật là…! / quả là…! (cảm thán)",
        structures: [
          "いAい ＋ ことだ",
          "なAな ＋ ことだ",
          "普通形 ＋ ことだ",
        ],
        explanation:
          "ことだ cảm thán nhấn mạnh cảm xúc trước tính chất sự việc: thật đáng tiếc, thật đáng mừng, thật nguy hiểm… — khác nghĩa khuyên bảo ‘nên…’.",
        usage: "Than thở, khen/chê cảm xúc: thật đáng sợ; thật vui; thật tội nghiệp.",
        cautions: [
          "Ở bài này là nghĩa cảm thán, không phải lời khuyên ことだ (nên làm…).",
          "Thường đi với tính từ đánh giá (悲しい・嬉しい・恐ろしい・情けない…).",
        ],
        contrast:
          "ことだ (cảm thán) ≈ thật là…! Khác ことだ khuyên bảo và ことだろう／ことか (cường điệu mức độ).",
        examples: [
          ex(
            "家族と長く離れるとは寂しいことだ。",
            "かぞくとながくはなれるとはさびしいことだ。",
            "Xa gia đình lâu thật là buồn.",
            [
              ["家族", "かぞく"],
              ["と"],
              ["長", "なが"],
              ["く"],
              ["離", "はな"],
              ["れるとは"],
              ["寂", "さび"],
              ["しいことだ。"],
            ],
          ),
          ex(
            "努力が報われるとは嬉しいことだ。",
            "どりょくがむくわれるとはうれしいことだ。",
            "Nỗ lực được đền đáp thật là vui.",
            [
              ["努力", "どりょく"],
              ["が"],
              ["報", "むく"],
              ["われるとは"],
              ["嬉", "うれ"],
              ["しいことだ。"],
            ],
          ),
          ex(
            "夜道を一人で歩くとは危険なことだ。",
            "よみちをひとりであるくとはきけんなことだ。",
            "Đi một mình trên đường đêm thật nguy hiểm.",
            [
              ["夜道", "よみち"],
              ["を"],
              ["一人", "ひとり"],
              ["で"],
              ["歩", "ある"],
              ["くとは"],
              ["危険", "きけん"],
              ["なことだ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ことだ（感嘆）",
        "Câu cảm thán: 〜ことだ — thật là…!",
        [
          ["Thất bại lần nữa thật đáng tiếc.", "再び失敗するとは残念なことだ。"],
          ["Được gặp bạn cũ thật vui.", "旧友に会えるとは嬉しいことだ。"],
          ["Bỏ mặc người yếu thật tệ.", "弱者を放置するとは情けないことだ。"],
          ["Leo núi một mình thật liều.", "一人で山に登るとは大胆なことだ。"],
          ["Mất chìa khóa thật phiền.", "鍵をなくすとは困ったことだ。"],
          ["Được khen trước mọi người thật xấu hổ.", "皆の前で褒められるとは恥ずかしいことだ。"],
          ["Thiên tai đến bất ngờ thật khủng khiếp.", "災害が突然襲うとは恐ろしいことだ。"],
          ["Hoàn thành đúng hạn thật đáng khen.", "期限内に仕上げるとは立派なことだ。"],
          ["Quên lời hứa thật đáng trách.", "約束を忘れるとは申し訳ないことだ。"],
          ["Nhìn con lớn lên thật cảm động.", "子供の成長を見るとは感慨深いことだ。"],
        ],
        [
          ["長年の夢が叶うとは喜ばしいことだ。", "Giấc mơ nhiều năm thành hiện thực thật đáng mừng."],
          ["大切な書類を紛失するとは重大なことだ。", "Làm mất giấy tờ quan trọng thật nghiêm trọng."],
          ["見知らぬ土地で迷子になるとは不安なことだ。", "Lạc ở nơi lạ thật bất an."],
          ["誠実に生きるとは美しいことだ。", "Sống chân thành thật đẹp."],
          ["助けを求めずに我慢するとは辛いことだ。", "Nhịn không cầu cứu thật khổ."],
          ["突然の別れは悲しいことだ。", "Chia tay đột ngột thật buồn."],
          ["嘘をつき通すとは恥ずかしいことだ。", "Nói dối đến cùng thật xấu hổ."],
          ["困難に立ち向かうとは勇気あることだ。", "Đối mặt khó khăn thật dũng cảm."],
          ["小さな親切は尊いことだ。", "Sự tử tế nhỏ thật quý."],
          ["健康を損なうとは愚かなことだ。", "Làm hại sức khỏe thật dại dột."],
        ],
        [
          ["Xa gia đình lâu thật buồn.", ["長く離れるとは", "寂しい", "こと", "だ。"], 0],
          ["Được đền đáp thật vui.", ["努力が報われるとは", "嬉しい", "こと", "だ。"], 0],
          ["Đi đường đêm một mình nguy hiểm.", ["夜道を一人で歩くとは", "危険な", "こと", "だ。"], 0],
          ["Thất bại lại thật đáng tiếc.", ["再び失敗するとは", "残念な", "こと", "だ。"], 0],
          ["Gặp bạn cũ thật vui.", ["旧友に会えるとは", "嬉しい", "こと", "だ。"], 0],
          ["Bỏ mặc kẻ yếu thật đáng xấu hổ.", ["弱者を放置するとは", "情けない", "こと", "だ。"], 0],
          ["Thiên tai bất ngờ thật đáng sợ.", ["災害が襲うとは", "恐ろしい", "こと", "だ。"], 0],
          ["Giấc mơ thành hiện thực đáng mừng.", ["夢が叶うとは", "喜ばしい", "こと", "だ。"], 0],
          ["Làm mất giấy tờ thật nghiêm trọng.", ["書類を紛失するとは", "重大な", "こと", "だ。"], 0],
          ["Sống chân thành thật đẹp.", ["誠実に生きるとは", "美しい", "こと", "だ。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l26-g06",
      {
        meaning: "Biết bao… / biết chừng nào…! (cường điệu cảm thán)",
        structures: [
          "普通形 ＋ ことだろう",
          "普通形 ＋ ことか",
        ],
        explanation:
          "ことだろう／ことか cường điệu mức độ cảm xúc hoặc suy đoán cảm thán: biết bao vui, biết chừng nào vất vả — thường kèm どれほど・なんと・どれだけ.",
        usage: "Cảm thán mạnh hoặc đồng cảm: biết bao lo lắng; vất vả biết chừng nào.",
        cautions: [
          "ことか thường kết thúc cảm thán mạnh; ことだろう hơi suy đoán/đồng cảm hơn.",
          "Hay đi với どれほど／なんと／どんなに để nhấn mức độ.",
        ],
        contrast:
          "ことだろう／ことか ≈ biết bao…! Khác ことだ cảm thán ngắn và だろう nghi vấn thường.",
        examples: [
          ex(
            "家族はどれほど心配したことだろう。",
            "かぞくはどれほどしんぱいしたことだろう。",
            "Gia đình đã lo lắng biết bao.",
            [
              ["家族", "かぞく"],
              ["はどれほど"],
              ["心配", "しんぱい"],
              ["したことだろう。"],
            ],
          ),
          ex(
            "一人でどれだけ苦労したことか。",
            "ひとりでどれだけくろうしたことか。",
            "Một mình đã vất vả biết chừng nào.",
            [
              ["一人", "ひとり"],
              ["でどれだけ"],
              ["苦労", "くろう"],
              ["したことか。"],
            ],
          ),
          ex(
            "合格を知った時、なんとうれしかったことか。",
            "ごうかくをしったとき、なんとうれしかったことか。",
            "Khi biết mình đỗ, vui biết bao.",
            [
              ["合格", "ごうかく"],
              ["を"],
              ["知", "し"],
              ["った"],
              ["時", "とき"],
              ["、なんと"],
              ["うれしかったことか。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ことだろう／ことか",
        "Câu cường điệu: 〜ことだろう／ことか — biết bao…!",
        [
          ["Cha mẹ đã chờ đợi biết bao.", "両親はどれほど待っていたことだろう。"],
          ["Cô ấy đã khóc biết chừng nào.", "彼女はどれだけ泣いたことか。"],
          ["Anh ấy đã cố gắng biết bao.", "彼はどんなに努力したことだろう。"],
          ["Đội đã thất vọng biết chừng nào.", "チームはどれほど落胆したことか。"],
          ["Trẻ em đã sợ hãi biết bao.", "子供たちはなんと怖がったことだろう。"],
          ["Bệnh nhân đã chịu đựng biết chừng nào.", "患者はどれだけ耐えたことか。"],
          ["Bạn đã vui mừng biết bao.", "君はどんなに喜んだことだろう。"],
          ["Họ đã mất mát biết chừng nào.", "彼らはどれほど失ったことか。"],
          ["Cô giáo đã tự hào biết bao.", "先生はなんと誇らしかったことだろう。"],
          ["Chúng tôi đã hồi hộp biết chừng nào.", "私たちはどれだけ緊張したことか。"],
        ],
        [
          ["被災者はどれほど不安だったことだろう。", "Nạn nhân đã bất an biết bao."],
          ["息子の成功に親はなんとうれしかったことか。", "Cha mẹ vui vì con thành công biết chừng nào."],
          ["長い旅はどんなに疲れたことだろう。", "Chuyến đi dài đã mệt biết bao."],
          ["誤解を解くのにどれだけ時間がかかったことか。", "Gỡ hiểu lầm mất thời gian biết chừng nào."],
          ["初めての舞台はどれほど緊張したことだろう。", "Sân khấu lần đầu hồi hộp biết bao."],
          ["友人の優しさにどれだけ救われたことか。", "Được cứu nhờ lòng tốt bạn biết chừng nào."],
          ["別れの日はなんと悲しかったことだろう。", "Ngày chia tay buồn biết bao."],
          ["完成までどれほど苦労したことか。", "Đến lúc hoàn thành đã vất vả biết chừng nào."],
          ["知らせを聞いてどんなに驚いたことだろう。", "Nghe tin đã ngạc nhiên biết bao."],
          ["静かな夜はどれだけ心が落ち着いたことか。", "Đêm yên đã làm lòng dịu lại biết chừng nào."],
        ],
        [
          ["Gia đình lo lắng biết bao.", ["家族はどれほど", "心配した", "ことだろう", "。"], 0],
          ["Một mình vất vả biết chừng nào.", ["一人でどれだけ", "苦労した", "ことか", "。"], 0],
          ["Khi đỗ vui biết bao.", ["合格を知った時", "なんとうれしかった", "ことか", "。"], 0],
          ["Cha mẹ chờ biết bao.", ["両親はどれほど", "待っていた", "ことだろう", "。"], 0],
          ["Cô ấy khóc biết chừng nào.", ["彼女はどれだけ", "泣いた", "ことか", "。"], 0],
          ["Anh ấy cố biết bao.", ["彼はどんなに", "努力した", "ことだろう", "。"], 0],
          ["Đội thất vọng biết chừng nào.", ["チームはどれほど", "落胆した", "ことか", "。"], 0],
          ["Nạn nhân bất an biết bao.", ["被災者はどれほど", "不安だった", "ことだろう", "。"], 0],
          ["Chuyến đi dài mệt biết bao.", ["長い旅はどんなに", "疲れた", "ことだろう", "。"], 0],
          ["Ngày chia tay buồn biết bao.", ["別れの日はなんと", "悲しかった", "ことだろう", "。"], 0],
        ],
      ),
    ),
  ];
}
