import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L11-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 15, BATCH);

export function lesson15Patterns(byId) {
  return [
    P(
      byId,
      "l15-g01",
      {
        meaning: "Nếu giả sử… / nếu đến mức… thì…",
        structures: [
          "普通形 ＋ としたら／とすれば／とすると",
          "普通形 ＋ となったら／となれば／となると",
        ],
        explanation:
          "としたら・とすれば・とすると giả định giả sử; となったら・となれば・となると nhấn mạnh khi tình huống trở thành thực tế thì…",
        usage: "Giả định kết quả, lập kế hoạch, cảnh báo nếu xảy ra trường hợp đó.",
        cautions: [
          "としたら／とすれば gần nhau; とすると thường dẫn đến suy luận.",
          "となると／となれば mang sắc thái 'đến lúc đó thì…' mạnh hơn giả định thuần.",
        ],
        contrast:
          "としたら ≈ nếu giả sử. となると ≈ nếu đến mức đó. Khác ば／たら thông thường (ít 'giả sử' hơn).",
        examples: [
          ex(
            "明日雨だとしたら試合は中止だ。",
            "あしたあめだとしたらしあいはちゅうしだ。",
            "Nếu giả sử ngày mai mưa thì trận đấu hủy.",
            [
              ["明日", "あした"],
              ["雨", "あめ"],
              ["だとしたら"],
              ["試合", "しあい"],
              ["は"],
              ["中止", "ちゅうし"],
              ["だ。"],
            ],
          ),
          ex(
            "彼が来るとすれば午後になるだろう。",
            "かれがくるとすればごごになるだろう。",
            "Nếu anh ấy đến thì chắc phải chiều.",
            [
              ["彼", "かれ"],
              ["が"],
              ["来", "く"],
              ["るとすれば"],
              ["午後", "ごご"],
              ["になるだろう。"],
            ],
          ),
          ex(
            "海外勤務となると準備が大変だ。",
            "かいがいきんむとなるとじゅんびがたいへんだ。",
            "Nếu đến mức công tác nước ngoài thì chuẩn bị rất vất vả.",
            [
              ["海外", "かいがい"],
              ["勤務", "きんむ"],
              ["となると"],
              ["準備", "じゅんび"],
              ["が"],
              ["大変", "たいへん"],
              ["だ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜としたら／となると",
        "Câu giả định: としたら／とすれば／とすると hoặc となったら／となれば／となると.",
        [
          ["Nếu giả sử anh ấy vắng thì họp sẽ trễ.", "彼が欠席だとしたら会議は遅れる。"],
          ["Nếu giá tăng thì phải đổi kế hoạch.", "値段が上がるとすれば計画を変える。"],
          ["Nếu đúng là vậy thì vấn đề nghiêm trọng.", "それが事実だとすると問題は深刻だ。"],
          ["Nếu phải chuyển nhà thì phí rất lớn.", "引っ越しとなったら費用が大きい。"],
          ["Nếu thi đậu thì tôi sẽ báo ngay.", "合格となればすぐに連絡する。"],
          ["Nếu đến mức làm đêm thì sức khỏe lo.", "夜勤となると健康が心配だ。"],
          ["Nếu mưa to thì hủy picnic.", "大雨だとしたらピクニックは中止だ。"],
          ["Nếu cô ấy từ chối thì phải tìm người khác.", "彼女が断るとすれば別の人を探す。"],
          ["Nếu ngân sách cắt thì dự án dừng.", "予算が削られるとなると事業は止まる。"],
          ["Nếu phải đi công tác xa thì cần chuẩn bị sớm.", "遠方出張となれば早めに準備する。"],
        ],
        [
          ["明日休みだとしたら何をするつもりか。", "Nếu giả sử ngày mai nghỉ thì định làm gì?"],
          ["彼が賛成するとすれば条件があるはずだ。", "Nếu anh ấy tán thành thì chắc có điều kiện."],
          ["この数字が正しいとすると計算ミスだ。", "Nếu con số này đúng thì là lỗi tính."],
          ["解雇となったら生活設計を見直す。", "Nếu đến mức bị sa thải thì xem lại kế hoạch sống."],
          ["契約破棄となれば損害賠償が発生する。", "Nếu hủy hợp đồng thì phát sinh bồi thường."],
          ["一人暮らしとなると家賃が重い。", "Nếu đến mức sống một mình thì tiền thuê nặng."],
          ["雪が積もったとしたら電車は遅れる。", "Nếu giả sử tuyết dày thì tàu sẽ trễ."],
          ["上司が来るとすれば会議室を空ける。", "Nếu sếp đến thì để trống phòng họp."],
          ["値上げとなると客が減るだろう。", "Nếu tăng giá thì khách sẽ giảm."],
          ["転勤となれば家族と相談が必要だ。", "Nếu điều động thì cần bàn với gia đình."],
        ],
        [
          ["Nếu mưa trận đấu hủy.", ["雨だとしたら", "試合は", "中止に", "なる。"], 0],
          ["Nếu anh ấy đến chắc chiều.", ["彼が来るとすれば", "午後に", "なる", "だろう。"], 0],
          ["Công tác nước ngoài thì chuẩn bị vất.", ["海外勤務となると", "準備が", "大変", "だ。"], 0],
          ["Nếu vắng họp trễ.", ["欠席だとしたら", "会議が", "遅れる", "だろう。"], 0],
          ["Nếu giá tăng đổi kế hoạch.", ["上がるとすれば", "計画を", "変える", "必要がある。"], 0],
          ["Nếu cắt ngân sách dự án dừng.", ["予算削減となると", "事業は", "止まる", "だろう。"], 0],
          ["Nếu đậu báo ngay.", ["合格となれば", "すぐに", "連絡", "する。"], 0],
          ["Nếu chuyển nhà phí lớn.", ["引っ越しとなったら", "費用が", "大きい", "だろう。"], 0],
          ["Nếu làm đêm lo sức khỏe.", ["夜勤となると", "健康が", "心配", "だ。"], 0],
          ["Nếu từ chối tìm người khác.", ["断るとすれば", "別の人を", "探す", "しかない。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l15-g02",
      {
        meaning: "Nếu có thể… thì… (ước muốn khó thực hiện)",
        structures: ["Vる ＋ ものなら"],
        explanation:
          "Diễn đạt 'nếu (có thể) làm được thì…'; thường kèm ước muốn hoặc hành động khó.",
        usage: "Ước muốn mạnh, giả định khả năng hiếm: nếu được thì muốn…",
        cautions: [
          "Thường đi với động từ khả năng hoặc hành động khó thực hiện.",
          "Khác （よ）うものなら (nếu lỡ… thì hậu quả xấu).",
        ],
        contrast: "ものなら ≈ nếu có thể thì…. Không nhầm với うものなら (cảnh báo).",
        examples: [
          ex(
            "行けるものなら今すぐ行きたい。",
            "いけるものならいますぐいきたい。",
            "Nếu có thể đi thì muốn đi ngay.",
            [
              ["行", "い"],
              ["けるものなら"],
              ["今", "いま"],
              ["すぐ"],
              ["行", "い"],
              ["きたい。"],
            ],
          ),
          ex(
            "戻れるものなら学生時代に戻りたい。",
            "もどれるものならがくせいじだいにもどりたい。",
            "Nếu quay lại được thì muốn về thời sinh viên.",
            [
              ["戻", "もど"],
              ["れるものなら"],
              ["学生", "がくせい"],
              ["時代", "じだい"],
              ["に"],
              ["戻", "もど"],
              ["りたい。"],
            ],
          ),
          ex(
            "やり直せるものなら最初からやり直したい。",
            "やりなおせるものならさいしょからやりなおしたい。",
            "Nếu làm lại được thì muốn làm lại từ đầu.",
            [
              ["やり直", "やりなお"],
              ["せるものなら"],
              ["最初", "さいしょ"],
              ["から"],
              ["やり直", "やりなお"],
              ["したい。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ものなら",
        "Câu dùng ものなら: nếu có thể (làm) thì… (thường là ước muốn khó).",
        [
          ["Nếu gặp được thì muốn hỏi ý kiến.", "会えるものなら意見を聞きたい。"],
          ["Nếu sửa được thì muốn sửa ngay.", "直せるものなら今すぐ直したい。"],
          ["Nếu nghỉ được thì muốn nghỉ một tuần.", "休めるものなら一週間休みたい。"],
          ["Nếu nói được thì muốn nói hết.", "言えるものなら全部言いたい。"],
          ["Nếu về được thì muốn về quê.", "帰れるものなら故郷に帰りたい。"],
          ["Nếu đổi được thì muốn đổi công việc.", "変えられるものなら仕事を変えたい。"],
          ["Nếu bay được thì muốn bay đi nước ngoài.", "飛べるものなら海外へ飛びたい。"],
          ["Nếu quên được thì muốn quên chuyện đó.", "忘れられるものならあの事を忘れたい。"],
          ["Nếu giúp được thì muốn giúp anh ấy.", "助けられるものなら彼を助けたい。"],
          ["Nếu mua được thì muốn mua nhà.", "買えるものなら家を買いたい。"],
        ],
        [
          ["会えるものなら直接会って謝りたい。", "Nếu gặp được thì muốn gặp trực tiếp xin lỗi."],
          ["戻れるものなら十年前に戻りたい。", "Nếu quay lại được thì muốn về mười năm trước."],
          ["直せるものなら自分で直してみる。", "Nếu sửa được thì thử tự sửa."],
          ["休めるものなら今日は休みたい。", "Nếu nghỉ được thì hôm nay muốn nghỉ."],
          ["言えるものなら本音を言いたい。", "Nếu nói được thì muốn nói thật lòng."],
          ["変えられるものなら運命を変えたい。", "Nếu đổi được thì muốn đổi số phận."],
          ["帰れるものなら今夜帰りたい。", "Nếu về được thì muốn về tối nay."],
          ["忘れられるものなら失敗を忘れたい。", "Nếu quên được thì muốn quên thất bại."],
          ["助けられるものなら全力で助けたい。", "Nếu giúp được thì muốn giúp hết sức."],
          ["やり直せるものなら試験をやり直したい。", "Nếu làm lại được thì muốn thi lại."],
        ],
        [
          ["Nếu đi được muốn đi ngay.", ["行けるものなら", "今すぐ", "行き", "たい。"], 0],
          ["Nếu về thời sinh viên được.", ["戻れるものなら", "学生時代に", "戻り", "たい。"], 0],
          ["Nếu làm lại từ đầu được.", ["やり直せるものなら", "最初から", "やり直し", "たい。"], 0],
          ["Nếu gặp được muốn hỏi.", ["会えるものなら", "意見を", "聞き", "たい。"], 0],
          ["Nếu sửa được sửa ngay.", ["直せるものなら", "今すぐ", "直し", "たい。"], 0],
          ["Nếu nghỉ được một tuần.", ["休めるものなら", "一週間", "休み", "たい。"], 0],
          ["Nếu nói được nói hết.", ["言えるものなら", "全部", "言い", "たい。"], 0],
          ["Nếu về quê được.", ["帰れるものなら", "故郷に", "帰り", "たい。"], 0],
          ["Nếu đổi việc được.", ["変えられるものなら", "仕事を", "変え", "たい。"], 0],
          ["Nếu mua nhà được.", ["買えるものなら", "家を", "買い", "たい。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l15-g03",
      {
        meaning: "Nếu lỡ… thì… (hậu quả xấu)",
        structures: ["V（よ）う ＋ ものなら"],
        explanation:
          "Giả định 'nếu (lỡ) làm…' rồi dẫn đến kết quả tiêu cực, cảnh báo hoặc lo sợ.",
        usage: "Cảnh báo: nếu dám/lỡ làm A thì B (xấu) sẽ xảy ra.",
        cautions: [
          "Luôn dùng thể ý chí （よ）う, không dùng dạng khả năng như ものなら thường.",
          "Hậu quả thường tiêu cực hoặc nghiêm trọng.",
        ],
        contrast: "（よ）うものなら ≈ nếu lỡ…. Khác ものなら (ước muốn nếu có thể).",
        examples: [
          ex(
            "文句を言おうものならすぐ怒られる。",
            "もんくをいおうものならすぐおこられる。",
            "Nếu lỡ phàn nàn thì bị mắng ngay.",
            [
              ["文句", "もんく"],
              ["を"],
              ["言", "い"],
              ["おうものなら"],
              ["すぐ"],
              ["怒", "おこ"],
              ["られる。"],
            ],
          ),
          ex(
            "遅刻しようものなら減点される。",
            "ちこくしようものならげんてんされる。",
            "Nếu lỡ đến muộn thì bị trừ điểm.",
            [
              ["遅刻", "ちこく"],
              ["しようものなら"],
              ["減点", "げんてん"],
              ["される。"],
            ],
          ),
          ex(
            "彼に逆らおうものなら後が怖い。",
            "かれにさからおうものならあとがこわい。",
            "Nếu lỡ chống lại anh ấy thì về sau đáng sợ.",
            [
              ["彼", "かれ"],
              ["に"],
              ["逆", "さから"],
              ["らおうものなら"],
              ["後", "あと"],
              ["が"],
              ["怖", "こわ"],
              ["い。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜（よ）うものなら",
        "Câu dùng （よ）うものなら: nếu lỡ… thì hậu quả xấu.",
        [
          ["Nếu lỡ trễ hạn thì bị phạt nặng.", "期限に遅れようものなら厳しく罰せられる。"],
          ["Nếu lỡ nói dối thì mất lòng tin.", "嘘をつこうものなら信用を失う。"],
          ["Nếu lỡ bỏ họp thì bị nhắc nhở.", "会議を欠席しようものなら注意される。"],
          ["Nếu lỡ phản đối thì bầu không khí căng.", "反対しようものなら空気が険しくなる。"],
          ["Nếu lỡ quên khóa thì không vào được.", "鍵を忘れようものなら入れなくなる。"],
          ["Nếu lỡ làm ồn thì hàng xóm phàn nàn.", "騒ごうものなら近所から苦情が来る。"],
          ["Nếu lỡ từ chối thì quan hệ xấu đi.", "断ろうものなら関係が悪化する。"],
          ["Nếu lỡ tiết lộ thì bị kỷ luật.", "漏らそうものなら処分される。"],
          ["Nếu lỡ bỏ cuộc giữa chừng thì mất cơ hội.", "途中でやめようものなら機会を失う。"],
          ["Nếu lỡ cười nhạo thì bị ghét.", "笑おうものなら嫌われる。"],
        ],
        [
          ["口答えしようものなら余計に怒られる。", "Nếu lỡ cãi lại thì bị mắng thêm."],
          ["秘密を話そうものなら信頼を失う。", "Nếu lỡ nói bí mật thì mất niềm tin."],
          ["規則を破ろうものなら出場停止だ。", "Nếu lỡ phá luật thì bị cấm thi đấu."],
          ["上司に逆らおうものなら昇進はない。", "Nếu lỡ chống sếp thì không thăng chức."],
          ["約束を破ろうものなら二度と頼めない。", "Nếu lỡ thất hẹn thì không nhờ được nữa."],
          ["遅刻しようものなら開始できない。", "Nếu lỡ muộn thì không thể bắt đầu."],
          ["文句を言おうものなら場が凍る。", "Nếu lỡ phàn nàn thì không khí đóng băng."],
          ["サボろうものなら評価が下がる。", "Nếu lỡ lười thì điểm đánh giá giảm."],
          ["無視しようものなら問題が拡大する。", "Nếu lỡ bỏ qua thì vấn đề lan rộng."],
          ["嘘をつこうものならすぐばれる。", "Nếu lỡ nói dối thì lộ ngay."],
        ],
        [
          ["Nếu lỡ phàn nàn bị mắng.", ["言おうものなら", "すぐ", "怒ら", "れる。"], 0],
          ["Nếu lỡ muộn bị trừ điểm.", ["遅刻しようものなら", "減点", "され", "る。"], 0],
          ["Nếu lỡ chống lại đáng sợ.", ["逆らおうものなら", "後が", "怖い", "だろう。"], 0],
          ["Nếu lỡ trễ hạn bị phạt.", ["遅れようものなら", "厳しく", "罰せ", "られる。"], 0],
          ["Nếu lỡ nói dối mất tin.", ["嘘をつこうものなら", "信用を", "失う", "だろう。"], 0],
          ["Nếu lỡ bỏ họp bị nhắc.", ["欠席しようものなら", "注意", "され", "る。"], 0],
          ["Nếu lỡ quên khóa không vào.", ["忘れようものなら", "入れなく", "なる", "だろう。"], 0],
          ["Nếu lỡ làm ồn bị phàn nàn.", ["騒ごうものなら", "苦情が", "来る", "だろう。"], 0],
          ["Nếu lỡ tiết lộ bị kỷ luật.", ["漏らそうものなら", "処分", "され", "る。"], 0],
          ["Nếu lỡ cười nhạo bị ghét.", ["笑おうものなら", "嫌わ", "れる", "だろう。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l15-g04",
      {
        meaning: "Nếu không… thì không thể… / chưa… thì chưa…",
        structures: ["Vない ＋ ことには ＋ Vない／難しいなど"],
        explanation:
          "Thiếu điều kiện A thì không thể đạt B; nhấn mạnh A là điều kiện tiên quyết.",
        usage: "Nêu điều kiện bắt buộc: không có A thì không làm được B.",
        cautions: [
          "Vế sau thường phủ định hoặc ý 'khó/không thể'.",
          "Khác なければ (điều kiện chung); ないことには nhấn mạnh 'thiếu thì không xong'.",
        ],
        contrast: "ないことには ≈ nếu không… thì không thể…. Gần なければ…ない.",
        examples: [
          ex(
            "実物を見ないことには決められない。",
            "じつぶつをみないことにはきめられない。",
            "Nếu không xem hàng thật thì không quyết được.",
            [
              ["実物", "じつぶつ"],
              ["を"],
              ["見", "み"],
              ["ないことには"],
              ["決", "き"],
              ["められない。"],
            ],
          ),
          ex(
            "許可がないことには始められない。",
            "きょかがいないことにははじめられない。",
            "Nếu không có phép thì không thể bắt đầu.",
            [
              ["許可", "きょか"],
              ["が"],
              ["ないことには"],
              ["始", "はじ"],
              ["められない。"],
            ],
          ),
          ex(
            "データを確認しないことには報告できない。",
            "データをかくにんしないことにはほうこくできない。",
            "Nếu không kiểm tra dữ liệu thì không báo cáo được.",
            [
              ["データを"],
              ["確認", "かくにん"],
              ["しないことには"],
              ["報告", "ほうこく"],
              ["できない。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜ないことには",
        "Câu dùng ないことには: nếu không A thì không thể B.",
        [
          ["Nếu không thử thì không biết hợp không.", "試さないことには合うか分からない。"],
          ["Nếu không họp thì không quyết được.", "会議を開かないことには決められない。"],
          ["Nếu không có vốn thì không mở cửa hàng.", "資金がないことには店を開けない。"],
          ["Nếu không luyện thì không tiến bộ.", "練習しないことには上達しない。"],
          ["Nếu không đọc hợp đồng thì không ký.", "契約書を読まないことにはサインできない。"],
          ["Nếu không có bằng chứng thì không buộc tội.", "証拠がないことには告発できない。"],
          ["Nếu không sửa lỗi thì không xuất bản.", "誤りを直さないことには出版できない。"],
          ["Nếu không hỏi ý thì không tiến hành.", "意見を聞かないことには進められない。"],
          ["Nếu không nghỉ thì không hồi phục.", "休まないことには回復しない。"],
          ["Nếu không có chìa thì không mở cửa.", "鍵がないことにはドアが開かない。"],
        ],
        [
          ["説明を聞かないことには納得できない。", "Nếu không nghe giải thích thì không thuyết phục được."],
          ["実地を見ないことには判断が難しい。", "Nếu không xem thực địa thì khó phán đoán."],
          ["同意がないことには公開できない。", "Nếu không có đồng ý thì không công khai được."],
          ["準備を整えないことには出発できない。", "Nếu không chuẩn bị xong thì không xuất phát được."],
          ["確認しないことには発送できない。", "Nếu không xác nhận thì không gửi hàng được."],
          ["経験がないことには指導は無理だ。", "Nếu không có kinh nghiệm thì hướng dẫn là vô lý."],
          ["材料が揃わないことには作れない。", "Nếu nguyên liệu chưa đủ thì không làm được."],
          ["本人に会わないことには真相は分からない。", "Nếu không gặp chính người đó thì không rõ sự thật."],
          ["検査を受けないことには診断できない。", "Nếu không khám thì không chẩn đoán được."],
          ["予算が決まらないことには発注できない。", "Nếu ngân sách chưa chốt thì không đặt hàng được."],
        ],
        [
          ["Không xem hàng thật không quyết.", ["見ないことには", "決め", "られ", "ない。"], 0],
          ["Không có phép không bắt đầu.", ["許可がないことには", "始め", "られ", "ない。"], 0],
          ["Không kiểm tra không báo cáo.", ["確認しないことには", "報告", "でき", "ない。"], 0],
          ["Không thử không biết hợp.", ["試さないことには", "合うか", "分から", "ない。"], 0],
          ["Không họp không quyết.", ["開かないことには", "決め", "られ", "ない。"], 0],
          ["Không có vốn không mở tiệm.", ["資金がないことには", "店を", "開け", "ない。"], 0],
          ["Không luyện không tiến.", ["練習しないことには", "上達", "し", "ない。"], 0],
          ["Không đọc hợp đồng không ký.", ["読まないことには", "サイン", "でき", "ない。"], 0],
          ["Không nghỉ không hồi phục.", ["休まないことには", "回復", "し", "ない。"], 0],
          ["Không có chìa không mở cửa.", ["鍵がないことには", "ドアが", "開か", "ない。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l15-g05",
      {
        meaning: "Nếu thiếu… / nếu bỏ qua… thì không…",
        structures: ["N ＋ を抜きにしては ＋ 〜ない／難しいなど"],
        explanation:
          "Không thể bàn/không thể thành công nếu thiếu yếu tố then chốt đó.",
        usage: "Nhấn mạnh vai trò không thể thiếu của người/việc/điều kiện.",
        cautions: [
          "Vế sau thường phủ định hoặc ý 'khó khăn'.",
          "を抜きにして (không は) còn dùng theo nghĩa 'bỏ qua… mà nói'.",
        ],
        contrast: "を抜きにしては ≈ nếu thiếu… thì không…. Khác なしでは (thiếu… thì).",
        examples: [
          ex(
            "彼の協力を抜きにしては成功しない。",
            "かれのきょうりょくをぬきにしてはせいこうしない。",
            "Nếu thiếu sự hợp tác của anh ấy thì không thành công.",
            [
              ["彼", "かれ"],
              ["の"],
              ["協力", "きょうりょく"],
              ["を抜きにしては"],
              ["成功", "せいこう"],
              ["しない。"],
            ],
          ),
          ex(
            "資金を抜きにしては事業は語れない。",
            "しきんをぬきにしてはじぎょうはかたれない。",
            "Nếu thiếu vốn thì không thể bàn về dự án.",
            [
              ["資金", "しきん"],
              ["を抜きにしては"],
              ["事業", "じぎょう"],
              ["は"],
              ["語", "かた"],
              ["れない。"],
            ],
          ),
          ex(
            "経験を抜きにしてはこの仕事は無理だ。",
            "けいけんをぬきにしてはこのしごとはむりだ。",
            "Nếu thiếu kinh nghiệm thì công việc này là vô lý.",
            [
              ["経験", "けいけん"],
              ["を抜きにしては"],
              ["この"],
              ["仕事", "しごと"],
              ["は"],
              ["無理", "むり"],
              ["だ。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜を抜きにしては",
        "Câu dùng を抜きにしては: nếu thiếu A thì không thể B.",
        [
          ["Nếu thiếu cô ấy thì đội không thắng.", "彼女を抜きにしてはチームは勝てない。"],
          ["Nếu thiếu dữ liệu thì phân tích khó.", "データを抜きにしては分析が難しい。"],
          ["Nếu thiếu hỗ trợ gia đình thì không tiếp tục.", "家族の支援を抜きにしては続けられない。"],
          ["Nếu thiếu công nghệ thì không cạnh tranh.", "技術を抜きにしては競争できない。"],
          ["Nếu thiếu lòng tin thì quan hệ không bền.", "信頼を抜きにしては関係が続かない。"],
          ["Nếu thiếu thời gian thì không hoàn thiện.", "時間を抜きにしては完成しない。"],
          ["Nếu thiếu hướng dẫn thì người mới bối rối.", "指導を抜きにしては新人は困る。"],
          ["Nếu thiếu khách hàng thì cửa hàng không sống.", "客を抜きにしては店は成り立たない。"],
          ["Nếu thiếu quy tắc thì tổ chức rối.", "ルールを抜きにしては組織が乱れる。"],
          ["Nếu thiếu sức khỏe thì không làm được.", "健康を抜きにしては働けない。"],
        ],
        [
          ["彼の助言を抜きにしては決断できない。", "Nếu thiếu lời khuyên của anh ấy thì không quyết được."],
          ["宣伝を抜きにしては売れ行きが伸びない。", "Nếu thiếu quảng cáo thì doanh số không tăng."],
          ["努力を抜きにしては上達は望めない。", "Nếu thiếu nỗ lực thì không mong tiến bộ."],
          ["地元の協力を抜きにしては開催できない。", "Nếu thiếu hợp tác địa phương thì không tổ chức được."],
          ["基礎を抜きにしては応用は難しい。", "Nếu thiếu nền tảng thì ứng dụng khó."],
          ["睡眠を抜きにしては集中できない。", "Nếu thiếu ngủ thì không tập trung được."],
          ["法律を抜きにしては取引は進められない。", "Nếu thiếu luật thì giao dịch không tiến hành được."],
          ["文化を抜きにしては習慣は語れない。", "Nếu thiếu văn hóa thì không bàn được tập quán."],
          ["練習を抜きにしては本番は怖い。", "Nếu thiếu luyện tập thì buổi chính đáng sợ."],
          ["予算を抜きにしては計画は机上の空論だ。", "Nếu thiếu ngân sách thì kế hoạch chỉ là lý thuyết."],
        ],
        [
          ["Thiếu hợp tác anh ấy không thành.", ["協力を抜きにしては", "成功", "し", "ない。"], 0],
          ["Thiếu vốn không bàn dự án.", ["資金を抜きにしては", "事業は", "語れ", "ない。"], 0],
          ["Thiếu kinh nghiệm việc này vô lý.", ["経験を抜きにしては", "この仕事は", "無理", "だ。"], 0],
          ["Thiếu cô ấy đội không thắng.", ["彼女を抜きにしては", "チームは", "勝て", "ない。"], 0],
          ["Thiếu dữ liệu phân tích khó.", ["データを抜きにしては", "分析が", "難しい", "だろう。"], 0],
          ["Thiếu hỗ trợ gia đình không tiếp.", ["支援を抜きにしては", "続け", "られ", "ない。"], 0],
          ["Thiếu công nghệ không cạnh tranh.", ["技術を抜きにしては", "競争", "でき", "ない。"], 0],
          ["Thiếu lòng tin quan hệ không bền.", ["信頼を抜きにしては", "関係が", "続か", "ない。"], 0],
          ["Thiếu sức khỏe không làm được.", ["健康を抜きにしては", "働け", "ない", "だろう。"], 0],
          ["Thiếu khách hàng tiệm không sống.", ["客を抜きにしては", "店は", "成り立た", "ない。"], 0],
        ],
      ),
    ),

    P(
      byId,
      "l15-g06",
      {
        meaning: "Dù là… / cho dù… thì…",
        structures: [
          "普通形 ＋ としても",
          "N／普通形 ＋ にしても",
          "N／普通形 ＋ にしろ／にせよ",
        ],
        explanation:
          "Nhượng bộ: chấp nhận giả định A nhưng kết luận B vẫn đúng hoặc vẫn phải làm.",
        usage: "Lập luận: dù A (có xảy ra) thì vẫn B; cũng dùng liệt kê dù A hay B.",
        cautions: [
          "としても thường sau mệnh đề giả định; にしても／にしろ／にせよ linh hoạt hơn.",
          "にしろ／にせよ sắc thái văn viết hoặc mạnh hơn にしても.",
        ],
        contrast:
          "としても／にしても ≈ dù…. にしろ／にせよ ≈ dù… (viết). Khác たとえ〜ても.",
        examples: [
          ex(
            "失敗したとしても諦めない。",
            "しっぱいしたとしてもあきらめない。",
            "Dù thất bại cũng không bỏ cuộc.",
            [
              ["失敗", "しっぱい"],
              ["したとしても"],
              ["諦", "あきら"],
              ["めない。"],
            ],
          ),
          ex(
            "高いにしても品質が良ければ買う。",
            "たかいにしてもひんしつがよければかう。",
            "Dù đắt, nếu chất lượng tốt thì mua.",
            [
              ["高", "たか"],
              ["いにしても"],
              ["品質", "ひんしつ"],
              ["が"],
              ["良", "よ"],
              ["ければ"],
              ["買", "か"],
              ["う。"],
            ],
          ),
          ex(
            "勝つにしろ負けるにしろ礼を失うな。",
            "かつにしろまけるにしろれいをうしなうな。",
            "Dù thắng hay thua đừng mất lễ độ.",
            [
              ["勝", "か"],
              ["つにしろ"],
              ["負", "ま"],
              ["けるにしろ"],
              ["礼", "れい"],
              ["を"],
              ["失", "うしな"],
              ["うな。"],
            ],
          ),
        ],
      },
      packFrom(
        "〜としても／にしても／にしろ",
        "Câu nhượng bộ: としても／にしても／にしろ／にせよ — dù… thì…",
        [
          ["Dù mưa cũng sẽ đến đúng giờ.", "雨だとしても時間通りに来る。"],
          ["Dù bận cũng hãy trả lời tin nhắn.", "忙しいにしても返信はしてほしい。"],
          ["Dù đồng ý hay không hãy nêu lý do.", "賛成にしろ反対にしろ理由を述べよ。"],
          ["Dù rẻ cũng phải kiểm tra kỹ.", "安いにせよよく確認せよ。"],
          ["Dù thành công cũng đừng chủ quan.", "成功したとしても油断するな。"],
          ["Dù muộn cũng hơn không làm.", "遅くにしてもやらないよりましだ。"],
          ["Dù anh ấy hay cô ấy đều có trách nhiệm.", "彼にせよ彼女にせよ責任がある。"],
          ["Dù khó cũng phải nộp đúng hạn.", "難しいとしても期限は守る。"],
          ["Dù ít tiền cũng tiết kiệm được.", "少なくにしても節約はできる。"],
          ["Dù thắng hay thua hãy bắt tay.", "勝つにしろ負けるにしろ握手しよう。"],
        ],
        [
          ["不合格だったとしても挑戦は無駄じゃない。", "Dù không đậu, thử cũng không phí."],
          ["高いにしても長く使えるなら得だ。", "Dù đắt, nếu dùng lâu thì đáng."],
          ["行くにせよ残るにせよ早く決めろ。", "Dù đi hay ở hãy quyết sớm."],
          ["彼が来ないとしても予定は変えない。", "Dù anh ấy không đến vẫn không đổi lịch."],
          ["子どもにしてもルールは守らせる。", "Dù là trẻ cũng bắt tuân quy tắc."],
          ["安いとしても品質が悪ければ買わない。", "Dù rẻ nếu kém chất lượng thì không mua."],
          ["賛成にしても条件付きだ。", "Dù tán thành cũng có điều kiện."],
          ["負けたにせよ学べば前進だ。", "Dù thua, nếu học được thì vẫn tiến."],
          ["忙しいにしても連絡だけはくれ。", "Dù bận cũng chỉ cần liên lạc."],
          ["結果にせよ過程にせよ誠実であれ。", "Dù kết quả hay quá trình hãy thành thật."],
        ],
        [
          ["Dù thất bại không bỏ cuộc.", ["失敗したとしても", "諦め", "ない", "だろう。"], 0],
          ["Dù đắt chất lượng tốt thì mua.", ["高いにしても", "品質が良ければ", "買う", "つもりだ。"], 0],
          ["Dù thắng hay thua giữ lễ.", ["勝つにしろ", "負けるにしろ", "礼を", "失うな。"], 1],
          ["Dù mưa đến đúng giờ.", ["雨だとしても", "時間通りに", "来る", "つもりだ。"], 0],
          ["Dù bận hãy trả lời.", ["忙しいにしても", "返信は", "して", "ほしい。"], 0],
          ["Dù tán thành hay phản đối nêu lý do.", ["賛成にしろ", "反対にしろ", "理由を", "述べよ。"], 1],
          ["Dù thành công đừng chủ quan.", ["成功したとしても", "油断", "する", "な。"], 0],
          ["Dù khó nộp đúng hạn.", ["難しいとしても", "期限は", "守る", "べきだ。"], 0],
          ["Dù anh hay cô đều có trách nhiệm.", ["彼にせよ", "彼女にせよ", "責任が", "ある。"], 1],
          ["Dù thắng hay thua bắt tay.", ["勝つにしろ", "負けるにしろ", "握手", "しよう。"], 1],
        ],
      ),
    ),
  ];
}
