import { packFrom, makePattern, ex } from "./_util.mjs";

const BATCH = "N2-L06-BATCH";
const P = (byId, id, theory, pack) =>
  makePattern(byId(id), theory, pack, 6, BATCH);

export function lesson06Patterns(byId) {
  return [
    P(
      byId,
      "l06-g01",
      {
        meaning: "Không chỉ… mà còn…; không giới hạn ở…",
        structures: ["N ＋ に限らず", "Vる／いA ＋ に限らず"],
        explanation:
          "Nêu phạm vi không bị giới hạn ở một đối tượng; thường tiếp theo là phạm vi rộng hơn.",
        usage: "Viết/nói trang trọng vừa; nhấn 'không chỉ A mà còn B'.",
        cautions: ["Thường đi với N; tránh dùng khi chỉ muốn nói 'chỉ có A'."],
        contrast: "に限らず ≈ không chỉ. Khác に限り (chỉ…).",
        examples: [
          ex(
            "子供に限らず大人も楽しめる。",
            "こどもにかぎらずおとなもたのしめる。",
            "Không chỉ trẻ em mà người lớn cũng chơi được.",
            [
              ["子供", "こども"],
              ["に"],
              ["限", "かぎ"],
              ["らず"],
              ["大人", "おとな"],
              ["も"],
              ["楽", "たの"],
              ["しめる。"],
            ],
          ),
          ex(
            "週末に限らず平日も混んでいる。",
            "しゅうまつにかぎらずへいじつもこんでいる。",
            "Không chỉ cuối tuần mà ngày thường cũng đông.",
            [
              ["週末", "しゅうまつ"],
              ["に"],
              ["限", "かぎ"],
              ["らず"],
              ["平日", "へいじつ"],
              ["も"],
              ["混", "こ"],
              ["んでいる。"],
            ],
          ),
          ex(
            "国内に限らず海外でも人気だ。",
            "こくないにかぎらずかいがいでもにんきだ。",
            "Không chỉ trong nước mà cả nước ngoài cũng nổi tiếng.",
            [
              ["国内", "こくない"],
              ["に"],
              ["限", "かぎ"],
              ["らず"],
              ["海外", "かいがい"],
              ["でも"],
              ["人気", "にんき"],
              ["だ。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ に限らず",
        "Câu dùng に限らず để nói không chỉ giới hạn ở phạm vi đã nêu.",
        [
          ["Không chỉ học sinh mà giáo viên cũng tham gia.", "学生に限らず教師も参加する。"],
          ["Không chỉ mùa hè mà mùa đông cũng bán.", "夏に限らず冬も売っている。"],
          ["Không chỉ Tokyo mà các tỉnh cũng áp dụng.", "東京に限らず地方でも導入されている。"],
          ["Không chỉ người lớn mà trẻ em cũng hiểu.", "大人に限らず子どもにもわかる。"],
          ["Không chỉ tiếng Anh mà tiếng Trung cũng cần.", "英語に限らず中国語も必要だ。"],
          ["Không chỉ ngày nghỉ mà ngày thường cũng mở cửa.", "休日に限らず平日も開店している。"],
          ["Không chỉ thành viên mà khách cũng được vào.", "会員に限らず来客も入れる。"],
          ["Không chỉ sách mà tạp chí cũng có.", "本に限らず雑誌もある。"],
          ["Không chỉ nam mà nữ cũng ứng tuyển được.", "男性に限らず女性も応募できる。"],
          ["Không chỉ công ty này mà cả ngành đều khó.", "この会社に限らず業界全体が厳しい。"],
        ],
        [
          ["若者に限らず高齢者も利用する。", "Không chỉ thanh niên mà người cao tuổi cũng dùng."],
          ["雨の日に限らず晴れの日も混む。", "Không chỉ ngày mưa mà ngày nắng cũng đông."],
          ["日本語に限らず韓国語も勉強している。", "Không chỉ tiếng Nhật mà còn học tiếng Hàn."],
          ["都会に限らず田舎でもネットが使える。", "Không chỉ thành phố mà nông thôn cũng dùng được mạng."],
          ["平日に限らず土日も配達する。", "Không chỉ ngày thường mà cả T7 CN cũng giao."],
          ["初心者に限らず経験者も歓迎だ。", "Không chỉ người mới mà cả người có kinh nghiệm cũng chào đón."],
          ["昼間に限らず夜も営業している。", "Không chỉ ban ngày mà đêm cũng mở cửa."],
          ["国内旅行に限らず海外旅行も増えた。", "Không chỉ du lịch trong nước mà du lịch nước ngoài cũng tăng."],
          ["スポーツに限らず芸術も盛んだ。", "Không chỉ thể thao mà nghệ thuật cũng thịnh."],
          ["この店に限らず駅前はどこも高い。", "Không chỉ quán này mà trước ga đâu cũng đắt."],
        ],
        [
          ["Không chỉ trẻ em cũng đến.", ["子供に", "限らず", "大人も", "来る。"], 1],
          ["Không chỉ cuối tuần cũng bận.", ["週末に", "限らず", "平日も", "忙しい。"], 1],
          ["Không chỉ trong nước cũng bán chạy.", ["国内に", "限らず", "海外でも", "売れる。"], 1],
          ["Không chỉ học sinh cũng học.", ["学生に", "限らず", "社会人も", "学ぶ。"], 1],
          ["Không chỉ mùa hè tổ chức quanh năm.", ["夏に", "限らず", "通年で", "開催する。"], 1],
          ["Không chỉ tiếng Anh hỗ trợ đa ngôn ngữ.", ["英語に", "限らず", "多言語で", "対応する。"], 1],
          ["Không chỉ thành viên cũng tham gia được.", ["会員に", "限らず", "一般も", "参加可だ。"], 1],
          ["Không chỉ sách giấy cũng có bản điện tử.", ["書籍に", "限らず", "電子版も", "ある。"], 1],
          ["Không chỉ Tokyo triển khai toàn quốc.", ["東京に", "限らず", "全国で", "展開する。"], 1],
          ["Không chỉ người lớn gia đình cũng đông.", ["大人に", "限らず", "家族連れも", "多い。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l06-g02",
      {
        meaning: "Không chỉ… mà còn… (văn viết/trang trọng)",
        structures: ["N ＋ のみならず", "Vる／いA ＋ のみならず"],
        explanation: "Cách nói trang trọng hơn だけでなく; nêu A rồi mở rộng sang B.",
        usage: "Bài luận, tin tức, thuyết trình.",
        cautions: ["Mang sắc thái viết; hội thoại thân mật thường dùng だけでなく."],
        contrast: "のみならず ≈ だけでなく nhưng trang trọng hơn.",
        examples: [
          ex(
            "彼は英語のみならず中国語も話せる。",
            "かれはえいごのみならずちゅうごくごもはなせる。",
            "Anh ấy không chỉ nói được tiếng Anh mà cả tiếng Trung.",
            [
              ["彼", "かれ"],
              ["は"],
              ["英語", "えいご"],
              ["のみならず"],
              ["中国語", "ちゅうごくご"],
              ["も"],
              ["話", "はな"],
              ["せる。"],
            ],
          ),
          ex(
            "品質のみならず価格も重要だ。",
            "ひんしつのみならずかかくもじゅうようだ。",
            "Không chỉ chất lượng mà giá cũng quan trọng.",
            [
              ["品質", "ひんしつ"],
              ["のみならず"],
              ["価格", "かかく"],
              ["も"],
              ["重要", "じゅうよう"],
              ["だ。"],
            ],
          ),
          ex(
            "アジアのみならず欧州でも需要がある。",
            "あじあのみならずおうしゅうでもじゅようがある。",
            "Không chỉ châu Á mà châu Âu cũng có nhu cầu.",
            [
              ["アジア"],
              ["のみならず"],
              ["欧州", "おうしゅう"],
              ["でも"],
              ["需要", "じゅよう"],
              ["がある。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ のみならず",
        "Câu dùng のみならず (trang trọng) để nói không chỉ A mà còn B.",
        [
          ["Anh ấy không chỉ thông minh mà còn chăm chỉ.", "彼は賢いのみならず勤勉だ。"],
          ["Không chỉ tốc độ mà độ chính xác cũng cao.", "速度のみならず精度も高い。"],
          ["Không chỉ nội dung mà hình thức cũng đẹp.", "内容のみならず形式も美しい。"],
          ["Không chỉ Nhật Bản mà châu Á cũng quan tâm.", "日本のみならずアジア全体が関心を持っている。"],
          ["Không chỉ lý thuyết mà thực hành cũng cần.", "理論のみならず実践も必要だ。"],
          ["Không chỉ lời nói mà thái độ cũng lịch sự.", "言葉のみならず態度も丁寧だ。"],
          ["Không chỉ giá mà dịch vụ cũng tốt.", "価格のみならずサービスも良い。"],
          ["Không chỉ học lực mà thể lực cũng quan trọng.", "学力のみならず体力も大切だ。"],
          ["Không chỉ thành phố lớn mà địa phương cũng phát triển.", "大都市のみならず地方も発展している。"],
          ["Không chỉ xuất khẩu mà tiêu thụ nội địa cũng tăng.", "輸出のみならず国内消費も伸びた。"],
        ],
        [
          ["彼女は歌のみならずダンスも得意だ。", "Cô ấy không chỉ hát mà nhảy cũng giỏi."],
          ["安全のみならず環境にも配慮する。", "Không chỉ an toàn mà còn cân nhắc môi trường."],
          ["経験のみならず資格も求められている。", "Không chỉ kinh nghiệm mà cả bằng cấp cũng được yêu cầu."],
          ["昼間のみならず夜間も対応可能だ。", "Không chỉ ban ngày mà ban đêm cũng xử lý được."],
          ["紙の資料のみならずデータも提出する。", "Không chỉ tài liệu giấy mà cả dữ liệu cũng nộp."],
          ["国内のみならず海外拠点もある。", "Không chỉ trong nước mà còn có cơ sở nước ngoài."],
          ["性能のみならずデザインも優れている。", "Không chỉ hiệu năng mà thiết kế cũng xuất sắc."],
          ["教師のみならず保護者も協力した。", "Không chỉ giáo viên mà phụ huynh cũng hợp tác."],
          ["費用のみならず時間が問題だ。", "Không chỉ chi phí mà thời gian mới là vấn đề."],
          ["日本語のみならず文化も学んでいる。", "Không chỉ tiếng Nhật mà còn học văn hóa."],
        ],
        [
          ["Không chỉ tiếng Anh cũng nói tiếng Pháp.", ["英語", "のみならず", "仏語も", "話す。"], 1],
          ["Không chỉ chất lượng cũng xem lại giá.", ["品質", "のみならず", "価格も", "見直す。"], 1],
          ["Không chỉ châu Á được thế giới chú ý.", ["アジア", "のみならず", "世界で", "注目される。"], 1],
          ["Không chỉ lý thuyết cũng đưa ví dụ thực.", ["理論", "のみならず", "実例も", "示す。"], 1],
          ["Không chỉ giá bảo hành cũng quan trọng.", ["値段", "のみならず", "保証も", "重要だ。"], 1],
          ["Không chỉ nội dung cũng tinh chỉnh cấu trúc.", ["内容", "のみならず", "構成も", "工夫する。"], 1],
          ["Không chỉ Nhật cũng phát hành ở nước ngoài.", ["日本", "のみならず", "海外でも", "発売する。"], 1],
          ["Không chỉ tốc độ độ ổn định cũng cao.", ["速さ", "のみならず", "安定性も", "高い。"], 1],
          ["Không chỉ học lực cũng xem tính hợp tác.", ["学力", "のみならず", "協調性も", "見る。"], 1],
          ["Không chỉ xuất khẩu nhập khẩu cũng tăng.", ["輸出", "のみならず", "輸入も", "増えた。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l06-g03",
      {
        meaning: "Không chỉ… mà thậm chí… (nhấn mức độ mạnh hơn)",
        structures: ["N ＋ ばかりか", "Vる／いA ＋ ばかりか"],
        explanation:
          "Nêu A rồi đưa B ở mức độ cao hơn/bất ngờ hơn; thường theo sau も／さえ.",
        usage: "Phàn nàn, nhấn mạnh, kể chuyện.",
        cautions: ["B thường 'nặng' hơn A; không dùng khi hai vế ngang bằng đơn thuần."],
        contrast: "ばかりか nhấn leo thang; のみならず trung lập hơn.",
        examples: [
          ex(
            "彼は遅刻ばかりか欠席までした。",
            "かれはちこくばかりかけっせきまでした。",
            "Anh ấy không chỉ đến muộn mà còn vắng mặt.",
            [
              ["彼", "かれ"],
              ["は"],
              ["遅刻", "ちこく"],
              ["ばかりか"],
              ["欠席", "けっせき"],
              ["までした。"],
            ],
          ),
          ex(
            "狭いばかりか暗い部屋だ。",
            "せまいばかりかくらいへやだ。",
            "Không chỉ chật mà căn phòng còn tối.",
            [
              ["狭", "せま"],
              ["い"],
              ["ばかりか"],
              ["暗", "くら"],
              ["い"],
              ["部屋", "へや"],
              ["だ。"],
            ],
          ),
          ex(
            "謝らないばかりか逆ギレした。",
            "あやまらないばかりかぎゃくぎれした。",
            "Không chỉ không xin lỗi mà còn cáu ngược.",
            [["謝", "あやま"], ["らない"], ["ばかりか"], ["逆ギレ", "ぎゃくぎれ"], ["した。"]],
          ),
        ],
      },
      packFrom(
        "N／V ＋ ばかりか",
        "Câu dùng ばかりか để nói không chỉ A mà thậm chí B (mức độ mạnh hơn).",
        [
          ["Không chỉ đắt mà còn kém chất lượng.", "高いばかりか品質も悪い。"],
          ["Không chỉ đến muộn mà còn không xin lỗi.", "遅れるばかりか謝りもしない。"],
          ["Không chỉ ồn mà còn nóng.", "うるさいばかりか暑い。"],
          ["Không chỉ thất bại mà còn làm hỏng máy.", "失敗したばかりか機械を壊した。"],
          ["Không chỉ quên đồ mà còn quên lịch hẹn.", "荷物を忘れたばかりか約束も忘れた。"],
          ["Không chỉ không giúp mà còn cản trở.", "手伝わないばかりか邪魔までする。"],
          ["Không chỉ khó mà còn nguy hiểm.", "難しいばかりか危険だ。"],
          ["Không chỉ tăng giá mà còn giảm khẩu phần.", "値上げしたばかりか量も減らした。"],
          ["Không chỉ mưa mà còn có gió mạnh.", "雨ばかりか強風も吹いた。"],
          ["Không chỉ sai mà còn không chịu sửa.", "間違えたばかりか直そうともしない。"],
        ],
        [
          ["彼は文句を言うばかりか怒鳴った。", "Anh ấy không chỉ phàn nàn mà còn gắt gỏng."],
          ["狭いばかりか窓もない。", "Không chỉ chật mà còn không có cửa sổ."],
          ["説明がないばかりか案内も不親切だ。", "Không chỉ thiếu giải thích mà hướng dẫn cũng bất lịch sự."],
          ["約束を破ったばかりか嘘までついた。", "Không chỉ phá hẹn mà còn nói dối."],
          ["時間がないばかりか予算もない。", "Không chỉ thiếu thời gian mà còn không có ngân sách."],
          ["彼は助けないばかりか笑う。", "Anh ấy không chỉ không giúp mà còn cười."],
          ["道が混んでいるばかりか工事中だ。", "Không chỉ đường tắc mà còn đang thi công."],
          ["味が薄いばかりか冷めていた。", "Không chỉ nhạt mà còn nguội."],
          ["連絡がないばかりか電話にも出ない。", "Không chỉ không liên lạc mà còn không nghe máy."],
          ["遅刻したばかりか資料も忘れた。", "Không chỉ đến muộn mà còn quên tài liệu."],
        ],
        [
          ["Không chỉ đắt chất lượng cũng kém.", ["高い", "ばかりか", "品質も", "悪い。"], 1],
          ["Không chỉ muộn còn ngồi im.", ["遅刻した", "ばかりか", "無言で", "座った。"], 1],
          ["Không chỉ ồn rung cũng lớn.", ["うるさい", "ばかりか", "振動も", "大きい。"], 1],
          ["Không chỉ thất bại còn đổ lỗi.", ["失敗した", "ばかりか", "責任を", "転嫁した。"], 1],
          ["Không chỉ quên còn ngang nhiên.", ["忘れた", "ばかりか", "開き直って", "いた。"], 1],
          ["Không chỉ khó còn mất thời gian.", ["難しい", "ばかりか", "時間も", "かかる。"], 1],
          ["Không chỉ mưa còn có sấm.", ["雨", "ばかりか", "雷も", "鳴った。"], 1],
          ["Không chỉ sai còn che giấu.", ["誤り", "ばかりか", "隠蔽まで", "した。"], 1],
          ["Không chỉ chật còn có mùi.", ["狭い", "ばかりか", "臭いも", "する。"], 1],
          ["Không chỉ tăng giá dịch vụ cũng giảm.", ["値上げ", "ばかりか", "サービスも", "低下した。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l06-g04",
      {
        meaning: "Huống hồ / chưa nói đến…; không chỉ… mà…",
        structures: ["N ＋ はもとより"],
        explanation:
          "Nêu A là điều đương nhiên, rồi nhấn mạnh B cũng vậy hoặc thậm chí hơn.",
        usage: "Viết và nói trang trọng vừa; so sánh mức độ.",
        cautions: [
          "はもとより thường đi với N; sắc thái 'A thì đã rõ, B cũng…'.",
          "Khác はもちろん ở mức trang trọng hơn một chút.",
        ],
        contrast: "はもとより ≈ A đương nhiên rồi, B cũng. Gần はもちろん.",
        examples: [
          ex(
            "彼は英語はもとよりフランス語も話せる。",
            "かれはえいごはもとよりふらんすごもはなせる。",
            "Anh ấy tiếng Anh thì đã rõ, tiếng Pháp cũng nói được.",
            [
              ["彼", "かれ"],
              ["は"],
              ["英語", "えいご"],
              ["はもとより"],
              ["フランス語"],
              ["も"],
              ["話", "はな"],
              ["せる。"],
            ],
          ),
          ex(
            "休日はもとより平日も混雑する。",
            "きゅうじつはもとよりへいじつもこんざつする。",
            "Ngày nghỉ thì đã vậy, ngày thường cũng đông.",
            [
              ["休日", "きゅうじつ"],
              ["はもとより"],
              ["平日", "へいじつ"],
              ["も"],
              ["混雑", "こんざつ"],
              ["する。"],
            ],
          ),
          ex(
            "専門家はもとより一般の人も興味を持っている。",
            "せんもんかはもとよりいっぱんのひともきょうみをもっている。",
            "Chuyên gia thì đương nhiên, người thường cũng quan tâm.",
            [
              ["専門家", "せんもんか"],
              ["はもとより"],
              ["一般", "いっぱん"],
              ["の"],
              ["人", "ひと"],
              ["も"],
              ["興味", "きょうみ"],
              ["を"],
              ["持", "も"],
              ["っている。"],
            ],
          ),
        ],
      },
      packFrom(
        "N ＋ はもとより",
        "Câu dùng はもとより: A đương nhiên rồi, B cũng vậy / thậm chí hơn.",
        [
          ["Tiếng Nhật thì đã rõ, tiếng Anh anh ấy cũng giỏi.", "日本語はもとより英語も得意だ。"],
          ["Giá thì đã vậy, chất lượng cũng tốt.", "値段はもとより品質も良い。"],
          ["Người lớn thì đương nhiên, trẻ em cũng hiểu.", "大人はもとより子どもにもわかる。"],
          ["Tokyo thì đã rõ, cả tỉnh lẻ cũng phổ biến.", "東京はもとより地方でも人気だ。"],
          ["Ngày nghỉ thì đương nhiên, ngày thường cũng mở.", "休日はもとより平日も開いている。"],
          ["Thành viên thì đã vậy, khách cũng được giảm.", "会員はもとより来客も割引される。"],
          ["Lý thuyết thì đương nhiên, thực hành cũng cần.", "理論はもとより実践も必要だ。"],
          ["An toàn thì đã rõ, tiện lợi cũng quan trọng.", "安全はもとより利便性も大切だ。"],
          ["Xuất khẩu thì đương nhiên, nội địa cũng tăng.", "輸出はもとより国内販売も伸びた。"],
          ["Giáo viên thì đã vậy, học sinh cũng tham gia.", "教師はもとより生徒も参加した。"],
        ],
        [
          ["彼は漢字はもとよりひらがなも書けない。", "Anh ấy chữ Hán thì đã vậy, hiragana cũng không viết được."],
          ["費用はもとより時間が足りない。", "Chi phí thì đương nhiên, thời gian cũng thiếu."],
          ["初心者はもとより経験者も迷う。", "Người mới thì đã vậy, người có kinh nghiệm cũng phân vân."],
          ["雨の日はもとより晴れの日も滑る。", "Ngày mưa thì đương nhiên, ngày nắng cũng trơn."],
          ["国内はもとより海外でも評価が高い。", "Trong nước thì đã rõ, nước ngoài đánh giá cũng cao."],
          ["味はもとより見た目もきれいだ。", "Vị thì đương nhiên, vẻ ngoài cũng đẹp."],
          ["速度はもとより安定性も求められる。", "Tốc độ thì đã vậy, độ ổn định cũng được yêu cầu."],
          ["昼間はもとより夜間も警備がある。", "Ban ngày thì đương nhiên, ban đêm cũng có bảo vệ."],
          ["大企業はもとより中小企業も導入した。", "Doanh nghiệp lớn thì đã rõ, SME cũng triển khai."],
          ["親はもとより本人が一番悩んでいる。", "Cha mẹ thì đương nhiên, bản thân lo nhất."],
        ],
        [
          ["Tiếng Anh thì đã rõ cũng nói được tiếng Pháp.", ["英語は", "もとより", "仏語も", "話せる。"], 1],
          ["Ngày nghỉ thì đương nhiên ngày thường cũng đông.", ["休日は", "もとより", "平日も", "混む。"], 1],
          ["Chuyên gia thì đã vậy người thường cũng đến.", ["専門家は", "もとより", "一般も", "来る。"], 1],
          ["Giá thì đương nhiên chất lượng cũng tốt.", ["値段は", "もとより", "質も", "高い。"], 1],
          ["Tokyo thì đã rõ tỉnh lẻ cũng bán.", ["東京は", "もとより", "地方でも", "売れる。"], 1],
          ["Lý thuyết thì đương nhiên thực hành cũng cần.", ["理論は", "もとより", "実践も", "要る。"], 1],
          ["Thành viên thì đã vậy khách cũng vào.", ["会員は", "もとより", "来客も", "入れる。"], 1],
          ["An toàn thì đương nhiên tiện lợi cũng xem.", ["安全は", "もとより", "便利さも", "見る。"], 1],
          ["Xuất khẩu thì đã rõ nội địa cũng tăng.", ["輸出は", "もとより", "内需も", "伸びた。"], 1],
          ["Người lớn thì đương nhiên trẻ cũng thích.", ["大人は", "もとより", "子供も", "喜ぶ。"], 1],
        ],
      ),
    ),

    P(
      byId,
      "l06-g05",
      {
        meaning: "Hơn nữa / thêm vào đó… (cộng dồn)",
        structures: ["N／いA／なA／V ＋ 上（に）"],
        explanation:
          "Nêu A rồi thêm B cùng chiều (thường xấu hơn hoặc tốt hơn); sắc thái 'đã A lại còn B'.",
        usage: "Phàn nàn hoặc khen ngợi khi cộng dồn lý do.",
        cautions: [
          "Đây là 上に additive (bài 6), khác 上で (sau khi xem xét) ở bài 3.",
          "Thường hai vế cùng chiều tích cực hoặc tiêu cực.",
        ],
        contrast: "上に ≈ hơn nữa / đã vậy còn. Khác ばかりか (leo thang bất ngờ hơn).",
        examples: [
          ex(
            "彼は仕事ができる上に性格も良い。",
            "かれはしごとができるうえにせいかくもよい。",
            "Anh ấy làm việc giỏi, hơn nữa tính tình cũng tốt.",
            [
              ["彼", "かれ"],
              ["は"],
              ["仕事", "しごと"],
              ["ができる"],
              ["上", "うえ"],
              ["に"],
              ["性格", "せいかく"],
              ["も"],
              ["良", "よ"],
              ["い。"],
            ],
          ),
          ex(
            "道が混んでいる上に雨まで降ってきた。",
            "みちがこんでいるうえにあめまでふってきた。",
            "Đường đã tắc, hơn nữa còn mưa.",
            [
              ["道", "みち"],
              ["が"],
              ["混", "こ"],
              ["んでいる"],
              ["上", "うえ"],
              ["に"],
              ["雨", "あめ"],
              ["まで"],
              ["降", "ふ"],
              ["ってきた。"],
            ],
          ),
          ex(
            "給料が安い上に休みも少ない。",
            "きゅうりょうがやすいうえにやすみもすくない。",
            "Lương đã thấp, hơn nữa ngày nghỉ cũng ít.",
            [
              ["給料", "きゅうりょう"],
              ["が"],
              ["安", "やす"],
              ["い"],
              ["上", "うえ"],
              ["に"],
              ["休", "やす"],
              ["みも"],
              ["少", "すく"],
              ["ない。"],
            ],
          ),
        ],
      },
      packFrom(
        "N／A／V ＋ 上（に）",
        "Câu dùng 上に để cộng dồn: đã A lại còn B.",
        [
          ["Rẻ hơn nữa chất lượng còn tốt.", "安い上に品質も良い。"],
          ["Đẹp hơn nữa vị cũng ngon.", "見た目がきれいな上に味もいい。"],
          ["Bận hơn nữa còn bị ốm.", "忙しい上に病気までした。"],
          ["Xa hơn nữa còn khó đi.", "遠い上に道も悪い。"],
          ["Thông minh hơn nữa còn chăm.", "頭が良い上に努力家だ。"],
          ["Đắt hơn nữa dịch vụ kém.", "高い上にサービスが悪い。"],
          ["Ồn hơn nữa còn nóng.", "うるさい上に暑い。"],
          ["Khó hơn nữa còn mất thời gian.", "難しい上に時間がかかる。"],
          ["Anh ấy nhanh nhẹn hơn nữa còn lịch sự.", "彼は仕事が早い上に丁寧だ。"],
          ["Mưa hơn nữa còn có gió mạnh.", "雨の上に強風も吹いた。"],
        ],
        [
          ["狭い上に暗い。", "Chật hơn nữa còn tối."],
          ["彼は経験豊富な上に人望もある。", "Anh ấy kinh nghiệm dày hơn nữa còn được quý."],
          ["約束を破った上に連絡もしない。", "Phá hẹn hơn nữa còn không liên lạc."],
          ["この店は安い上に量も多い。", "Quán này rẻ hơn nữa khẩu phần còn nhiều."],
          ["説明が長い上に分かりにくい。", "Giải thích dài hơn nữa còn khó hiểu."],
          ["彼は遅刻した上に資料を忘れた。", "Anh ấy đến muộn hơn nữa còn quên tài liệu."],
          ["物価が上がった上に給料は変わらない。", "Giá tăng hơn nữa lương không đổi."],
          ["道に迷った上に電池がなくなった。", "Lạc đường hơn nữa pin hết."],
          ["彼女は美しい上に優しい。", "Cô ấy đẹp hơn nữa còn dịu dàng."],
          ["会議が長い上に結論が出ない。", "Họp dài hơn nữa không ra kết luận."],
        ],
        [
          ["Rẻ hơn nữa chất lượng tốt.", ["安い", "上に", "品質も", "良い。"], 1],
          ["Bận hơn nữa còn ốm.", ["忙しい", "上に", "病気にも", "なった。"], 1],
          ["Xa hơn nữa đường xấu.", ["遠い", "上に", "道も", "悪い。"], 1],
          ["Đắt hơn nữa phục vụ kém.", ["高い", "上に", "接客も", "悪い。"], 1],
          ["Ồn hơn nữa nhiệt độ phòng cũng cao.", ["うるさい", "上に", "室温も", "高い。"], 1],
          ["Khó hơn nữa mất giờ.", ["難しい", "上に", "時間も", "かかる。"], 1],
          ["Chật hơn nữa tối.", ["狭い", "上に", "照明も", "暗い。"], 1],
          ["Muộn hơn nữa quên tài liệu.", ["遅刻した", "上に", "資料も", "忘れた。"], 1],
          ["Đẹp hơn nữa vị ngon.", ["きれいな", "上に", "味も", "良い。"], 1],
          ["Mưa hơn nữa gió mạnh.", ["雨の", "上に", "風も", "強い。"], 1],
        ],
      ),
    ),
  ];
}
