import type { Note, Question } from "../shared/domain";
type Seed = Omit<Question, "id" | "source"> & {
  term: string;
  reading: string;
  meaning: string;
};
const q = (
  kind: string,
  level: string,
  type: Question["type"],
  term: string,
  reading: string,
  meaning: string,
  prompt: string,
  options: string[],
  answer: number,
  explanation: string,
): Seed => ({
  kind,
  level,
  type,
  term,
  reading,
  meaning,
  prompt,
  options,
  answer,
  explanation,
});
// Original starter material. Level labels are editorial estimates, not official vocabulary lists.
export const bank: Question[] = (
  [
    q(
      "kanji",
      "N5",
      "reading",
      "学校",
      "がっこう",
      "Trường học",
      "毎日、【学校】へ行きます。",
      ["がこう", "がっこう", "がっこ", "かっこう"],
      1,
      "学校 đọc là がっこう: có âm ngắt っ và trường âm こう. がこう thiếu âm ngắt; がっこ thiếu trường âm; かっこう sai âm đầu.",
    ),
    q(
      "kanji",
      "N5",
      "reading",
      "先生",
      "せんせい",
      "Giáo viên",
      "田中さんは日本語の【先生】です。",
      ["せんせ", "せいせん", "せんせい", "せんしょう"],
      2,
      "先生 trong câu này là せんせい. せんせ thiếu い; せいせん đảo vị trí âm; せんしょう không phải cách đọc của từ này.",
    ),
    q(
      "kanji",
      "N5",
      "orthography",
      "水",
      "みず",
      "Nước",
      "つめたい【みず】を飲みます。",
      ["木", "火", "水", "本"],
      2,
      "みず viết là 水 (nước). 木 là cây, 火 là lửa, 本 là sách/gốc; chúng không có nghĩa và cách đọc phù hợp trong câu.",
    ),
    q(
      "kanji",
      "N4",
      "reading",
      "病院",
      "びょういん",
      "Bệnh viện",
      "熱があるので、【病院】へ行きます。",
      ["びよういん", "びょういん", "びょいん", "ひょういん"],
      1,
      "病院 là びょういん, với ょ nhỏ và trường âm う. びよういん là cách đọc của 美容院 (tiệm làm tóc); びょいん thiếu trường âm; ひょういん sai âm hữu thanh.",
    ),
    q(
      "kanji",
      "N4",
      "orthography",
      "料理",
      "りょうり",
      "Món ăn; nấu ăn",
      "母は日本の【りょうり】を作ります。",
      ["料理", "科理", "料金", "料埋"],
      0,
      "料理 nghĩa là món ăn/nấu ăn. 料金 là phí, còn 科理 và 料埋 không phải cách viết của りょうり. Chú ý bộ của 理 và 料.",
    ),
    q(
      "kanji",
      "N3",
      "reading",
      "約束",
      "やくそく",
      "Lời hứa; cuộc hẹn",
      "友達との【約束】を忘れてしまいました。",
      ["やっそく", "やくそく", "やくぞく", "やくそっく"],
      1,
      "約束 đọc là やくそく. Không biến く thành âm ngắt, không hữu thanh hóa そ và không thêm っ trước く.",
    ),
    q(
      "kanji",
      "N3",
      "orthography",
      "経験",
      "けいけん",
      "Kinh nghiệm",
      "海外で働いた【けいけん】があります。",
      ["経険", "経験", "軽験", "軽険"],
      1,
      "経験 là kinh nghiệm. 経 dùng bộ 糸, 験 dùng bộ 馬. 険 là hiểm và 軽 là nhẹ, không thay thế được các chữ trong 経験.",
    ),
    q(
      "kanji",
      "N2",
      "reading",
      "印象",
      "いんしょう",
      "Ấn tượng",
      "初めて会ったときの【印象】をよく覚えています。",
      ["いんしょ", "いんぞう", "いんしょう", "いんそう"],
      2,
      "印象 là いんしょう. いんしょ thiếu trường âm う; いんぞう và いんそう nhầm cách đọc 象 trong từ này.",
    ),
    q(
      "kanji",
      "N2",
      "orthography",
      "貢献",
      "こうけん",
      "Đóng góp",
      "地域の発展に【こうけん】したいです。",
      ["貢献", "貢験", "項献", "項験"],
      0,
      "貢献 là đóng góp. 貢 không phải 項; 献 không phải 験. Các lựa chọn còn lại không viết đúng từ こうけん trong ngữ cảnh này.",
    ),
    q(
      "kanji",
      "N1",
      "reading",
      "著しい",
      "いちじるしい",
      "Rõ rệt; đáng kể",
      "この分野では技術の進歩が【著しい】。",
      ["いちじるしい", "いちじろしい", "あらわしい", "しるしい"],
      0,
      "著しい đọc là いちじるしい, nghĩa là rõ rệt/đáng kể. いちじろしい sai âm; あらわしい và しるしい không phải cách đọc của tính từ này.",
    ),
    q(
      "kanji",
      "N1",
      "reading",
      "措置",
      "そち",
      "Biện pháp xử lý",
      "事故の再発を防ぐため、適切な【措置】を講じた。",
      ["しょち", "そじ", "そち", "しょじ"],
      2,
      "措置 đọc là そち. しょち là cách đọc của 処置; そじ và しょじ không phải cách đọc của 措置.",
    ),
    q(
      "vocabulary",
      "N5",
      "context",
      "飲む",
      "のむ",
      "Uống",
      "毎朝、水を（　）ます。",
      ["食べ", "飲み", "見", "聞き"],
      1,
      "水を飲みます là uống nước. 食べます dùng cho ăn, 見ます là nhìn, 聞きます là nghe; không kết hợp với 水 theo nghĩa uống.",
    ),
    q(
      "vocabulary",
      "N5",
      "paraphrase",
      "大きい",
      "おおきい",
      "To; lớn",
      "このかばんは【大きい】です。意味が近い文はどれですか。",
      [
        "このかばんは小さくないです。",
        "このかばんは新しいです。",
        "このかばんは安いです。",
        "このかばんは軽いです。",
      ],
      0,
      "大きい là to/lớn, gần với 小さくない (không nhỏ) trong các lựa chọn. 新しい là mới, 安い là rẻ, 軽い là nhẹ.",
    ),
    q(
      "vocabulary",
      "N4",
      "context",
      "間に合う",
      "まにあう",
      "Kịp giờ",
      "急げば、九時の電車に（　）。",
      ["間に合います", "片づけます", "比べます", "拾います"],
      0,
      "電車に間に合う là kịp chuyến tàu. 片づける là dọn, 比べる là so sánh, 拾う là nhặt, không diễn đạt việc kịp giờ.",
    ),
    q(
      "vocabulary",
      "N4",
      "usage",
      "予約",
      "よやく",
      "Đặt trước",
      "【予約】の使い方として正しいものはどれですか。",
      [
        "昨日のことを予約しました。",
        "レストランの席を予約しました。",
        "窓を予約して開けました。",
        "駅まで予約で歩きました。",
      ],
      1,
      "予約 dùng cho việc đặt trước chỗ/dịch vụ: đặt bàn nhà hàng. Không dùng để nhớ việc hôm qua, mở cửa sổ hoặc diễn tả cách đi bộ.",
    ),
    q(
      "vocabulary",
      "N3",
      "context",
      "延期",
      "えんき",
      "Hoãn lại",
      "台風のため、運動会は来週に（　）されました。",
      ["延期", "出席", "到着", "成長"],
      0,
      "延期 là dời lịch sang sau. 出席 là tham dự, 到着 là đến nơi, 成長 là trưởng thành; không phù hợp với 来週に…されました trong câu.",
    ),
    q(
      "vocabulary",
      "N3",
      "paraphrase",
      "突然",
      "とつぜん",
      "Đột nhiên",
      "電車が【突然】止まりました。",
      ["ゆっくり", "急に", "いつも", "やっと"],
      1,
      "突然 gần nghĩa 急に: đột nhiên. ゆっくり là chậm rãi, いつも là luôn luôn, やっと là cuối cùng sau khó khăn.",
    ),
    q(
      "vocabulary",
      "N2",
      "formation",
      "再確認",
      "さいかくにん",
      "Xác nhận lại",
      "提出する前に、内容を（　）確認してください。",
      ["不", "無", "再", "非"],
      2,
      "再 đứng trước danh từ Hán Nhật để chỉ làm lại: 再確認. 不・無・非 mang sắc thái phủ định, không diễn đạt xác nhận thêm lần nữa.",
    ),
    q(
      "vocabulary",
      "N2",
      "usage",
      "促進",
      "そくしん",
      "Thúc đẩy",
      "【促進】の使い方として正しいものはどれですか。",
      [
        "窓を促進して閉めた。",
        "交流を促進する活動を行う。",
        "電車に促進して乗った。",
        "名前を紙に促進した。",
      ],
      1,
      "交流を促進する là thúc đẩy giao lưu. 促進 kết hợp với quá trình/hoạt động phát triển, không thay cho đóng cửa, lên tàu hoặc viết tên.",
    ),
    q(
      "vocabulary",
      "N1",
      "paraphrase",
      "おおむね",
      "おおむね",
      "Nhìn chung; phần lớn",
      "計画は【おおむね】順調に進んでいる。",
      ["全く", "ほぼ", "決して", "むしろ"],
      1,
      "おおむね gần nghĩa ほぼ, chỉ nhìn chung/hầu hết. 全く là hoàn toàn, 決して thường đi với phủ định, むしろ là đúng hơn/thà rằng.",
    ),
    q(
      "vocabulary",
      "N1",
      "context",
      "妥協",
      "だきょう",
      "Thỏa hiệp",
      "双方が少しずつ条件を譲り、（　）点を見いだした。",
      ["妥協", "模倣", "干渉", "浪費"],
      0,
      "妥協点 là điểm thỏa hiệp, phù hợp việc hai bên nhượng bộ. 模倣 là bắt chước, 干渉 là can thiệp, 浪費 là lãng phí.",
    ),
    q(
      "grammar",
      "N5",
      "grammar",
      "〜に行く",
      "〜にいく",
      "Đi đến nơi nào",
      "日曜日、図書館（　）行きます。",
      ["を", "に", "で", "が"],
      1,
      "に đánh dấu điểm đến với 行きます. を là tân ngữ/đường đi trong cấu trúc khác, で là nơi thực hiện hành động, が đánh dấu chủ ngữ.",
    ),
    q(
      "grammar",
      "N5",
      "order",
      "語順：これは〜です",
      "",
      "Trật tự câu giới thiệu",
      "これは ＿＿ ＿＿ ★ ＿＿ です。★に入るものはどれですか。",
      ["日本語", "の", "本", "私の"],
      1,
      "Thứ tự hoàn chỉnh: これは 私の 日本語 の 本 です。Bốn vị trí là 私の / 日本語 / の / 本; vị trí thứ ba ★ là の.",
    ),
    q(
      "grammar",
      "N5",
      "text",
      "それから",
      "",
      "Sau đó",
      "日曜日は公園へ行きました。（　）、家で映画を見ました。二つの出来事を順番に説明します。",
      ["それから", "でも", "だから", "しかし"],
      0,
      "それから nối các sự việc theo thứ tự. でも và しかし diễn đạt tương phản; だから diễn đạt kết quả, không phải mục đích nối trình tự đã nêu.",
    ),
    q(
      "grammar",
      "N4",
      "grammar",
      "〜たことがある",
      "",
      "Đã từng làm gì",
      "私は一度、日本へ行った（　）があります。",
      ["もの", "こと", "ため", "ところ"],
      1,
      "Vたことがある diễn tả trải nghiệm đã từng làm. もの・ため・ところ không thay được こと trong cấu trúc trải nghiệm này.",
    ),
    q(
      "grammar",
      "N4",
      "order",
      "〜たことがある",
      "",
      "Trật tự câu trải nghiệm",
      "私は ＿＿ ＿＿ ★ ＿＿ あります。★に入るものはどれですか。",
      ["こと", "が", "日本へ", "行った"],
      0,
      "Thứ tự: 私は 日本へ 行った こと が あります。★ là vị trí thứ ba, こと. Cụm 行ったことがある diễn đạt trải nghiệm.",
    ),
    q(
      "grammar",
      "N3",
      "grammar",
      "〜ようにする",
      "",
      "Cố gắng duy trì thói quen",
      "健康のため、毎日歩く（　）しています。",
      ["ように", "ような", "そうな", "ための"],
      0,
      "Vるようにしている diễn tả cố gắng duy trì thói quen. ような・そうな dùng để bổ nghĩa danh từ, còn ための cần danh từ theo sau; chúng không nối trực tiếp với しています trong câu này.",
    ),
    q(
      "grammar",
      "N3",
      "text",
      "それでも",
      "",
      "Dù vậy",
      "昨日はひどい雨でした。（　）、試合は予定どおり行われました。",
      ["そのため", "それでも", "つまり", "例えば"],
      1,
      "それでも biểu thị dù trời mưa to, trận đấu vẫn diễn ra. そのため là do đó; つまり là tức là; 例えば là ví dụ.",
    ),
    q(
      "grammar",
      "N2",
      "grammar",
      "〜にもかかわらず",
      "",
      "Mặc dù",
      "十分に注意した（　）、ミスをしてしまった。",
      ["にもかかわらず", "に応じて", "に先立って", "にわたって"],
      0,
      "Vたにもかかわらず: mặc dù đã cẩn thận vẫn mắc lỗi. に応じて = tùy theo, に先立って = trước khi, にわたって = trải suốt; không phù hợp cấu trúc và quan hệ nhượng bộ.",
    ),
    q(
      "grammar",
      "N2",
      "order",
      "〜とは限らない",
      "",
      "Không nhất thiết",
      "値段が ＿＿ ＿＿ ★ ＿＿ 。★に入るものはどれですか。",
      ["品質がいい", "高いからといって", "限らない", "とは"],
      3,
      "Thứ tự: 値段が 高いからといって 品質がいい とは 限らない。★ là とは. Nghĩa: giá cao không nhất thiết chất lượng tốt.",
    ),
    q(
      "grammar",
      "N1",
      "grammar",
      "〜を余儀なくされる",
      "",
      "Bị buộc phải",
      "大雪のため、計画の変更を（　）。",
      ["余儀なくされた", "ものとした", "かたくなった", "きらいがあった"],
      0,
      "Nを余儀なくされる: bị hoàn cảnh buộc phải làm. ものとする là quy định/coi là; hai dạng còn lại không phù hợp cấu trúc 変更を trong câu.",
    ),
    q(
      "grammar",
      "N1",
      "text",
      "とはいえ",
      "",
      "Tuy vậy",
      "新しい制度には多くの利点がある。（　）、導入に伴う負担を無視することはできない。",
      ["したがって", "とはいえ", "すなわち", "それゆえ"],
      1,
      "とはいえ thừa nhận ưu điểm nhưng đưa ra hạn chế. したがって và それゆえ diễn đạt kết quả, すなわち diễn giải tương đương; không phù hợp mạch nhượng bộ.",
    ),
  ] as Seed[]
).map((item, i) => ({
  ...item,
  id: `starter-${i + 1}`,
  source: "Nội dung khởi đầu tự biên soạn",
}));
export const starterDecks = [
  {
    id: "vocabulary",
    title: "Những từ đầu tiên",
    kind: "vocabulary",
    symbol: "初",
    description: "Từ vựng cơ bản, dùng trong giao tiếp hằng ngày.",
  },
  {
    id: "kanji",
    title: "Kanji trong đời sống",
    kind: "kanji",
    symbol: "生",
    description: "Học cách đọc và nhận diện chữ trong ngữ cảnh.",
  },
  {
    id: "grammar",
    title: "Ngữ pháp nền tảng",
    kind: "grammar",
    symbol: "文",
    description: "Mẫu câu ngắn, giải thích rõ, thực hành ngay.",
  },
];
export function starterNotes(kind: string, level: string): Note[] {
  return bank
    .filter((q) => q.kind === kind && q.level === level)
    .map((q) => ({
      term: (q as unknown as Seed).term,
      reading: (q as unknown as Seed).reading,
      meaning: (q as unknown as Seed).meaning,
      example: q.prompt,
      question: {
        type: q.type,
        prompt: q.prompt,
        options: q.options,
        answer: q.answer,
        explanation: q.explanation,
      },
    }));
}
